### ISSUE TITLE
Configuration vs ConfigurationName build parameter

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#2115] opened 2018-04-05 22:19 UTC
_From @groogiam on April 5, 2018 21:30_

There appears to be a discrepancy between specifying the configuration from msbuild from the command line between the old and new csproj formats.

The old csproj file allowed specifying the configuration using /p:configuration="Test"

e.g. `msbuild MySln.sln /p:configuration="Test"`

This would properly set the ConfigurationName parameter for pre build events.

Note: ConfigurationName is what visual macro dialog uses as well.
![image](https://user-images.githubusercontent.com/1992395/38392710-7c4f1c40-38f6-11e8-80d0-a9deeb63dbe0.png)

This however does not happen for the new csproj format. In order to fix this I have to specify another command line argument `/p:configurationName="Test"`.

It seems like the setting configuration from msbuild should set this variable correctly no matter which csproj format is used.

_Copied from original issue: dotnet/project-system#3452_

**Comment by nguerrera** [comment] 2018-04-16 21:55
I cannot reproduce this issue. @groogiam Can you supply more details on the steps that you have taken to see ConfigurationName not being set?

I'm not seeing how this would behave any differently for Sdk-based proejcts. ConfigurationName is set here for both:
https://github.com/Microsoft/msbuild/blob/7c1f7a8cd8f2b844046892036912db28a7ec4c37/src/Tasks/Microsoft.Common.CurrentVersion.targets#L136

``` C#
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="echo Pre-build $(ConfigurationName)" />
  </Target>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="echo Post-build $(ConfigurationName)" />
  </Target>

</Project>
```

```
C:\...>msbuild /nologo /v:m /p:Configuration=Release
  Pre-build Release
  cname -> C:\temp\cname\bin\Release\netcoreapp2.0\cname.dll
  Post-build Release

```

**Comment by groogiam** [comment] 2018-04-18 01:06
After some further investigation this turned out to be an issue in the solution configuration. Some of the x64 configurations had the wrong configuration targeted. You can close this, sorry for the trouble.

**Closed** 2018-04-18 01:17 UTC
