### ISSUE TITLE
Allow specifying path to local SDK in global.json

### ISSUE THREAD

**Issue by Mrxx99** [dotnet/sdk#33924] opened 2023-07-11 19:38 UTC
### Is your feature request related to a problem? Please describe.
We need a very specific version of .NET SDK (down to minor version), because we are building a plugin
and sometimes we get runtime exceptions when our SDK version is higher than the main application.
Also the specific version is set through a dependency clearing process.
That's why we use a global.json with the specific version specified.
The problem now is when e.g. Visual Studio is updated, the .NET SDK is also updated, but when you had e.g.
6.0.408 installed and Visual Studio update causes 6.0.410 to be installed, than 6.0.408 gets auto uninstalled and it can't even be installed anymore. So we lost the "correct" SDK version without an easy way to install it anymore. And this problem happens every few month when updating SDK versions.

### Describe the solution you'd like
Allowing specifying a path to a local downloaded dotnet binaries like this in global.json would solve this issue.
```json
{
  "sdk": {
    "path": "../.dotnet"
  }
}
```

### Additional context
Note, we know we could add a local dotnet folder to path for every project but that is explicitly something we don't want to do on a local developer PC (we are using this on build servers).

**Comment by vitek-karas** [comment] 2023-07-12 11:25
I'd say it's exactly the same as #8254 .

@richlander and I worked on a proposal for something close to this here: https://github.com/dotnet/designs/blob/main/accepted/2022/version-selection.md#local-dotnet

But so far there is no decision made what and when to actually implement. In our repos this is typically worked around by using scripts to start build/dotnet. These same scripts also download the SDK into the repo-local directory if it's not there already. But this has obvious limitations (doesn't work well with VS for example).

**Comment by marcpopMSFT** [comment] 2023-07-18 21:24
Resolving as a duplicate of 8254. As Vitek noted, this is a longstanding request and the design is still TBD.

**Closed by marcpopMSFT** 2023-07-18 21:24 UTC
Labels: untriaged, Area-CLI
