### ISSUE TITLE
Running dotnet build -f net46 builds and packages packages that contain all frameworks

### ISSUE THREAD

**Issue by livarcocc** [dotnet/sdk#825] opened 2017-02-07 01:42 UTC
> from @niemyjski at https://github.com/dotnet/cli/issues/5595

So I was running into tons of issues that have been fixed in the nightlies and just wanted to build and package only .net 46 framework targets so I ran the build with `-f net46`

https://github.com/exceptionless/Foundatio/blob/master/appveyor.yml#L23

But it appears that the nuget package were still built and completed as full framework and net standard targets.

https://www.nuget.org/packages/Foundatio/

I expected the netstandard build and packaging not to take place (I also haven't looked inside the nuget package yet to see what is in the net standard folder).

**Comment by piotrpMSFT** [comment] 2017-02-07 08:46
@niemyjski how is `pack` occurring?

**Comment by niemyjski** [comment] 2017-02-07 15:36
via the new package on build functionality

**Comment by srivatsn** [comment] 2017-02-07 21:01
@piotrpMSFT since you're looking at the implementation of dotnet build -f, can you look into this as well?

**Comment by piotrpMSFT** [comment] 2017-02-08 02:53
There are a number of issues looking at this particular problem. @rohit21agrawal can correct me if I've not gone deep enough, but I'm becoming fairly convinced that this is turning out to be an opportunity for enhancement in the NuGet Pack targets. Namely, those targets allow Property-drive packing on build, but only for full outer builds. 

Regardless, yes, I'll help drive this issue.

**Comment by rohit21agrawal** [comment] 2017-02-08 04:56
i dont see how this is even a bug.
msbuild doesn't remember properties that were passed to it via command line. the only properties that persist across multiple command invocations are the ones that are in the csproj. If someone builds and pack separately, they can't expect that pack would know about the command line arguments  that were passed to build. Neither does pack care about the build outputs on disk - pack calls msbuild directly to understand what outputs need to be packed , and msbuild evaluates these outputs based on the command line arguments given to pack or in the csproj.

from what i can think of right now, the solution here is to promote the ability of pack (and any dotnet command that is a msbuild target) to be able to accept arbitrary msbuild property using the ``` /p:key=value ``` syntax

**Comment by rohit21agrawal** [comment] 2017-02-08 04:58
the right solution here would be the one i gave out in the following comment  : https://github.com/dotnet/cli/issues/4609#issuecomment-278044829

```dotnet pack /p:TargetFrameworks=net46```

**Comment by piotrpMSFT** [comment] 2017-02-08 06:52
@rohit21agrawal I think the issue here is that @niemyjski is building packages via `<GeneratePackageOnBuild>True</GeneratePackageOnBuild>`. The target framework is being passed in to build and the same invocation is resulting in an invocation of Pack. The bug, then, is that Pack ignores the /p:TargetFramework when invoked as part of build via that property.

Am I missunderstanding?

**Comment by rohit21agrawal** [comment] 2017-02-08 15:26
Ok.. I just played a little with this :

If my project has ```TargetFrameworks=net46;netstandard1.4``` set along with ```GeneratePackageOnBuild = true```, and I run ```dotnet build -f net46 ``` this will actually not end up creating the package at all - because the only way in Pack targets that we differentiate an inner build from an outer build is using the condition : 
```<IsInnerBuild Condition="'$(TargetFramework)' != '' AND '$(TargetFrameworks)' != ''">true</IsInnerBuild>``` . As you can see ```dotnet build -f net46``` causes pack to think of outer build as inner build too, and therefore it doesn't execute at all.

If instead I run ```dotnet build /p:TargetFrameworks=net46``` ; then I get the results i expect, the build only builds for the net46 framework and pack only packs the net46 assemblies.

Maybe we need to modify the framework switch to pass in TargetFrameworks instead of TargetFramework?

**Comment by dsplaisted** [comment] 2017-02-08 16:49
From the original issue:

> I expected the netstandard build and packaging not to take place

That is the behavior @rohit21agrawal is seeing.  It sounds like @niemyjski saw the package being created even when he passed in `-f net46`.

**Comment by rohit21agrawal** [comment] 2017-02-08 16:51
no, the behavior I am seeing is that the Pack target isn't being called at all.

@niemyjski do you have the RC4 update installed? To confirm could you please tell me the file version of 
````"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\CoreCLR\NuGet.Build.Tasks.Pack.dll"```

**Comment by dsplaisted** [comment] 2017-02-08 17:00
> no, the behavior I am seeing is that the Pack target isn't being called at all.

Unless I'm misunderstanding, this is what @niemyjski was expecting to happen

**Comment by rohit21agrawal** [comment] 2017-02-08 17:03
what I think he meant to say was that out of the two builds for net46 and netstandard1.4 (that his project targets) , he only expected the net46 build to happen.
@niemyjski can clear this for us.

**Comment by niemyjski** [comment] 2017-02-08 18:34
In RC3 I was seeing the package being created with -f net46, in RC4 (latest update?) it's not created... Why does `-f net46` not create the package but `/p:TargetFrameworks=net46` create it? Aren't they the same thing?

Yes, I expect only the net46 target to build and package

**Comment by rohit21agrawal** [comment] 2017-02-08 18:37
@piotrpMSFT : do you think you can fix this on the CLI side?

**Comment by rohit21agrawal** [comment] 2017-02-08 18:38
@niemyjski see my comment https://github.com/dotnet/sdk/issues/825#issuecomment-278359578 for explanation

**Comment by piotrpMSFT** [comment] 2017-02-13 03:17
@rohit21agrawal let's chat tomorrow. We need to think through the behavior that we want and design for it. @niemyjski is explicitly _not_ doing an outer build, which has other desirable side-effects like running inner-build-only targets, and would like a package produced regardless. I also expect @niemyjski wants to be able to use VS in which case a CLI fix will not help at all.

**Comment by niemyjski** [comment] 2017-02-14 16:39
Yeah, I want to use VS :). I'm probably going to end up turning off package on build feature off and move it to a build step (builds shouldn't do that much work)

**Comment by piotrpMSFT** [comment] 2017-02-15 03:00
@niemyjski that's a good strategy. I chatted with @rohit21agrawal about this issue today and it turns out that your usage of `-f` worked because of an unintended behavior of the pack target. @rohit21agrawal will be creating a nuget/home issue to discuss the intended behavior and to understand why `-f` is interesting to `pack`

In general, pack is supposed to create a single package for the entire project, encompassing all frameworks. Why is building a framework-specific package interesting to your scenario? Several issues are generated by this approach, key amongst them that the package identity for your project will be used up by a single framework, rendering you unable to publish packages for other frameworks...

**Comment by niemyjski** [comment] 2017-02-15 16:09
The thing with doing that, it becomes a PITA because you can't just do `dotnet pack src` (to package all projects in a sub directory... If you are only building a specific target framework, then packaging nuget should only include that runtime, not doing so is kind of black magic and not the intent the developer had when he ran it (e.g., what assemblies are being used for the net standard target, why is that build running I explicitly told it not to).

I wanted to push only net46 for two reasons...

1) there was a sdk issue that was logged that was causing nuget package failures due to including the source.
2) Some nuget packages were pre release and I was releasing a stable package and it allows me todo it and it should error out.

**Comment by dsplaisted** [comment] 2017-05-15 23:40
Closing this in favor of the NuGet issue.

**Closed by dsplaisted** 2017-05-15 23:40 UTC
Labels: Bug
