### ISSUE TITLE
sdk 6.0.400 breaks WPF projects with source generators

### ISSUE THREAD

**Issue by narcis-ro** [dotnet/sdk#27173] opened 2022-08-15 17:33 UTC
Steps to reproduce
- Simply start new WPF template
- Add System.Text.Json nuget
- Try to use generator for a dummy class
```
 public class WeatherForecast
    {
        public DateTime Date { get; set; }
        public int TemperatureCelsius { get; set; }
        public string? Summary { get; set; }
    }

    [JsonSourceGenerationOptions(WriteIndented = true)]
    [JsonSerializable(typeof(WeatherForecast))]
    internal partial class SourceGenerationContext : JsonSerializerContext
    {
    }
```
- Build

Output
```
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.g.cs(10,6,10,60): error CS0579: Duplicate 'global::System.CodeDom.Compiler.GeneratedCodeAttribute' attribute
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.DateTime.g.cs(11,104,11,113): error CS0102: The type 'SourceGenerationContext' already contains a definition for '_DateTime'
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.DateTime.g.cs(12,102,12,110): error CS0102: The type 'SourceGenerationContext' already contains a definition for 'DateTime'
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.Int32.g.cs(11,101,11,107): error CS0102: The type 'SourceGenerationContext' already contains a definition for '_Int32'
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.Int32.g.cs(12,99,12,104): error CS0102: The type 'SourceGenerationContext' already contains a definition for 'Int32'
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.String.g.cs(11,102,11,109): error CS0102: The type 'SourceGenerationContext' already contains a definition for '_String'
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.String.g.cs(12,100,12,106): error CS0102: The type 'SourceGenerationContext' already contains a definition for 'String'
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.WeatherForecast.g.cs(11,112,11,128): error CS0102: The type 'SourceGenerationContext' already contains a definition for '_WeatherForecast'
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.WeatherForecast.g.cs(12,110,12,125): error CS0102: The type 'SourceGenerationContext' already contains a definition for 'WeatherForecast'
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.WeatherForecast.g.cs(43,91,43,114): error CS0111: Type 'SourceGenerationContext' already defines a member called 'WeatherForecastPropInit' with the same parameter types
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.WeatherForecast.g.cs(113,29,113,60): error CS0111: Type 'SourceGenerationContext' already defines a member called 'WeatherForecastSerializeHandler' with the same parameter types
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.g.cs(14,71,14,87): error CS0102: The type 'SourceGenerationContext' already contains a definition for 's_defaultOptions'
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.g.cs(23,65,23,81): error CS0102: The type 'SourceGenerationContext' already contains a definition for 's_defaultContext'
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.g.cs(24,63,24,70): error CS0102: The type 'SourceGenerationContext' already contains a definition for 'Default'
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.g.cs(26,76,26,102): error CS0102: The type 'SourceGenerationContext' already contains a definition for 'GeneratedSerializerOptions'
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.g.cs(28,16,28,39): error CS0111: Type 'SourceGenerationContext' already defines a member called 'SourceGenerationContext' with the same parameter types
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.g.cs(32,16,32,39): error CS0111: Type 'SourceGenerationContext' already defines a member called 'SourceGenerationContext' with the same parameter types
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.g.cs(36,71,36,104): error CS0111: Type 'SourceGenerationContext' already defines a member called 'GetRuntimeProvidedCustomConverter' with the same parameter types
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.GetJsonTypeInfo.g.cs(11,86,11,97): error CS0111: Type 'SourceGenerationContext' already defines a member called 'GetTypeInfo' with the same parameter types
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.PropertyNames.g.cs(12,74,12,87): error CS0102: The type 'SourceGenerationContext' already contains a definition for 'PropName_Date'
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.PropertyNames.g.cs(13,74,13,101): error CS0102: The type 'SourceGenerationContext' already contains a definition for 'PropName_TemperatureCelsius'
1>C:\WpfApp6\WpfApp6\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.PropertyNames.g.cs(14,74,14,90): error CS0102: The type 'SourceGenerationContext' already contains a definition for 'PropName_Summary'
```

Notes: 
- This happens for any source generator. Tried with others actually, system.text.json above is just an example.
- Does NOT happen with 6.0.300 sdk an below
- Happens the moment there is a *.xaml file in the project
- Check the emitted the generator files, and they are no generated twice.
- If you use 6.0.201 or 6.0.300 via global.json, same project builds, without any changes.

Csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
	<ItemGroup>
    <PackageReference Include="System.Text.Json" Version="6.0.5" />
  </ItemGroup>
</Project>

```

**Comment by baronfel** [comment] 2022-08-15 17:35
This is a dupe of a known WCF targets issue, more details can be found here: https://github.com/dotnet/sdk/issues/26557

**Closed by baronfel** 2022-08-15 17:35 UTC
Labels: untriaged, Area-NetSDK
