### ISSUE TITLE
Runtime Id does not follow generic naming convention in published arm64 releases

### ISSUE THREAD

**Issue by toolboc** [dotnet/sdk#2644] opened 2018-11-04 22:17 UTC
I am working on adding support for linux-arm64 to the [azure-pipelines-agent](https://github.com/Microsoft/azure-pipelines-agent/pull/1921).  

I noticed that the current arm32 release of the dotnet core SDK @ https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.403/dotnet-sdk-2.1.403-linux-arm.tar.gz uses a generic name "linux-arm" 
for the Runtime Id:
![image](https://user-images.githubusercontent.com/2018336/47970546-9236c780-e04c-11e8-81c7-d5966bf948b9.png)

However, the current arm64 release of the dotnet core SDK @ https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.403/dotnet-sdk-2.1.403-linux-arm64.tar.gz uses a platform specific name "ubuntu.18.04-arm64" instead of an expected generic name of "linux-arm64" for the Runtime Id:
![image](https://user-images.githubusercontent.com/2018336/47970485-9ca49180-e04b-11e8-88c2-5d0b09f34f0b.png)

Is this expected, or should both releases report a generic name for the Runtime Id?

**Comment by peterhuene** [comment] 2018-11-08 01:09
Hi @toolboc,

Thanks for reporting this.

`dotnet --info` uses two sources of information to show the `RID`:

* If the current platform RID is supported by the shared framework RID graph (contained in `Microsoft.NETCore.App.deps.json`), then it will display it.  For Ubuntu 18.04 (ARM64), the RID is in the graph so this is what is displayed.  However
* However, Raspbian isn't a supported RID in the graph, so `dotnet --info` falls back to the `.version` file in the .NET Core SDK's directory.  This contains the more generic `linux-arm`, which is what is being displayed.

As such, I'm closing this by design from the CLI.  If we want to support Raspbian in the RID graph, that would be a `dotnet/core-clr` / `dotnet/core-setup` issue I believe.

**Closed by peterhuene** 2018-11-08 01:09 UTC
