### ISSUE TITLE
Binding redirects are not generated automatically

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#1016] opened 2017-03-21 03:53 UTC
_From @davidmatson on March 21, 2017 3:31_

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net452</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="9.0.1" />
    <PackageReference Include="WindowsAzure.Storage" Version="7.2.1" />
  </ItemGroup>
</Project>
```

Expected:
Binding redirects are generated automatically.

Actual:
```
1>Consider app.config remapping of assembly "Newtonsoft.Json, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" from Version "6.0.0.0" [] to Version "9.0.0.0" [C:\Users\me\.nuget\packages\newtonsoft.json\9.0.1\lib\net45\Newtonsoft.Json.dll] to solve conflict and get rid of warning.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.
```

Somewhat ironically, the link mentioned in the error output:
http://go.microsoft.com/fwlink/?LinkId=294190

Says that binding redirects are generated automatically if the target framework is .NET 4.5.1 or higher. This project targets .NET 4.5.2, but the binding redirects are still not generated automatically.

Current workaround is to add the property explicitly:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net452</TargetFramework>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="9.0.1" />
    <PackageReference Include="WindowsAzure.Storage" Version="7.2.1" />
  </ItemGroup>
</Project>
```

_Copied from original issue: dotnet/roslyn-project-system#1809_

**Comment by dsplaisted** [comment] 2017-03-21 06:02
It looks like the issue here is that [this condition](https://github.com/dotnet/sdk/blob/952b5b7a25913ea181efffe5dd245b85b836e83b/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.BeforeCommon.targets#L46) needs to check for an output type of `WinExe` in addition to `Exe`:

```xml
  <PropertyGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework' and '$(OutputType)' == 'Exe'">
    <AutoGenerateBindingRedirects Condition="'$(AutoGenerateBindingRedirects)' == ''">true</AutoGenerateBindingRedirects>
  </PropertyGroup>
```

**Comment by davkean** [comment] 2017-03-21 06:08
Do you even need that check? I thought we already did the right thing here in the automatic binding redirect target.

**Comment by nguerrera** [comment] 2017-05-19 13:29
Fixed by #1178

**Closed by nguerrera** 2017-05-19 13:29 UTC
Labels: up-for-grabs

**Comment by Jose-CF** [comment] 2017-06-16 04:16
Has this shipped? Experiencing the same problem over here.

**Comment by davkean** [comment] 2017-06-16 04:22
@Jose-CF Please open a new bug on any issue that you are running into.

**Comment by Jose-CF** [comment] 2017-06-16 04:25
The issue is this very same one. Should I duplicate it?

**Comment by davkean** [comment] 2017-06-16 04:27
Yes. We will mark it as a duplicate if its the same issue.

**Comment by Jose-CF** [comment] 2017-06-16 04:39
Ok, I created #1351. You were right, the issue is indeed different.
