### ISSUE TITLE
error MSB3105: The item "XXX.cs" was specified more than once in the "Sources" parameter. 

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/sdk#604] opened 2017-01-09 01:50 UTC
While trying to build this PR https://github.com/Microsoft/Docker.DotNet/pull/144 for some reason it is thinking I have a duplicated file in the CI build at AppVeyor.
```
C:\Program Files\dotnet\sdk\1.0.0-preview5-004460\Roslyn\Microsoft.CSharp.Core.targets(71,5): error MSB3105: The item "AnonymousCredentials.cs" was specified more than once in the "Sources" parameter.  Duplicate items are not supported by the "Sources" parameter. [C:\projects\docker-dotnet\Docker.DotNet\Docker.DotNet.csproj]
```

`1.0.0-preview5-004232` build it just fine. However, the latest version `1.0.0-preview5-004460` throw this error for the same project...

Any ideas?

**Comment by eerhardt** [comment] 2017-01-09 02:52
The latest SDK adds all .cs files by default now without any "Compile" lines.

To fix the error either:

1. Remove all "Compile" elements from your .csproj and let the SDK add all .cs files to your project automatically.
2. If you want to control which files are added and don't want the SDK to automatically added them, set <EnableDefaultItems>false</EnableDefaultItems> property in your .csproj.

This experience will get better once #600 is fixed.

**Comment by galvesribeiro** [comment] 2017-01-09 14:24
AHHH, that is why :) 

I would suggest have a repo only for announcements just like asp.net guys did so, whenever a breaking change happen on public API surface, they push an issue there. Its a readonly repo where everyone who is using latest release watch it for news.

Now I changed the AppVeyor script like this and the build work:

```
version: '2.124.2.{build}'
pull_requests:
  do_not_increment_build_number: true
init:
- ps: (new-object net.webclient).DownloadFile('https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-win-x64.latest.exe', "c:/dotnet-install.exe")
- ps: Start-Process c:\dotnet-install.exe -ArgumentList "/install","/quiet" -Wait
build_script:
- ps: dotnet restore
- ps: dotnet build .\Docker.DotNet\Docker.DotNet.csproj -c Release
- ps: dotnet build .\Docker.DotNet.X509\Docker.DotNet.X509.csproj -c Release
- ps: dotnet build .\Docker.DotNet.BasicAuth\Docker.DotNet.BasicAuth.csproj -c Release
```

One caveat there. If I `dotnet build` at the solution level, the build now fail saying that Docker.DotNet.dll is being used by another process. I had to build every project isolated... Is that an issue with this release as well? 

Thanks @eerhardt !

**Comment by galvesribeiro** [comment] 2017-01-09 14:51
@eerhardt more one problem detected... Even if `dotnet build` "works" as I stated, if you open in VS2017 the project here is what happen:

![image](https://cloud.githubusercontent.com/assets/4714040/21770410/48679500-d66a-11e6-9d48-a01e73604470.png)

No files are loaded :(

**Comment by eerhardt** [comment] 2017-01-09 15:14
> I would suggest have a repo only for announcements just like asp.net guys did so, whenever a breaking change happen on public API surface, they push an issue there. Its a readonly repo where everyone who is using latest release watch it for news.

@srivatsn - thoughts?

> If I dotnet build at the solution level, the build now fail saying that Docker.DotNet.dll is being used by another process. I had to build every project isolated... Is that an issue with this release as well?

That should work.  @nguerrera @dsplaisted - any ideas why that would happen?

>if you open in VS2017 the project here is what happen:  No files are loaded :(

I assume that is because your install of VS2017 still has the old SDK, which doesn't automatically add the files.  And since you removed them from your .csproj, when you load the project in VS2017, no one is adding the files.

**Comment by galvesribeiro** [comment] 2017-01-09 16:23
> I assume that is because your install of VS2017 still has the old SDK, which doesn't automatically add the files. And since you removed them from your .csproj, when you load the project in VS2017, no one is adding the files.

@eerhardt I just added the SDK install from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-win-x64.latest.exe which is listed here https://github.com/dotnet/cli/#installers-and-binaries

How to update the one Visual Studio is using? It is very confusing that command line is using one thing and Visual Studio using other (and yes, I have no global.json at the solution)...

**Comment by galvesribeiro** [comment] 2017-01-09 16:24
BTW, the announcements repo for aspnet is this one: https://github.com/aspnet/Announcements

**Comment by describeme** [comment] 2017-01-13 11:48
@galvesribeiro: hey, did u get around this? 

> How to update the one Visual Studio is using? It is very confusing that command line is using one thing and Visual Studio using other (and yes, I have no global.json at the solution)...

@eerhardt:
im also running preview5-004478 and even have it set in the global.json... but no *.cs files show up in the projects

**Comment by eerhardt** [comment] 2017-01-13 15:07
> How to update the one Visual Studio is using? It is very confusing that command line is using one thing and Visual Studio using other (and yes, I have no global.json at the solution)...

@davkean @srivatsn - can someone help here?  I don't know how to update the SDK that Visual Studio is using.

**Comment by srivatsn** [comment] 2017-01-13 19:39
The SDKs, currently, ship with VS itself. Acquisition\upgrade of newer SDKs has not been implemented yet. https://github.com/Microsoft/msbuild/issues/1493 tracks the design and the work to do that.

Until then, VS and CLI use their own SDKs. @galvesribeiro, you can set a property `<EnableDefaultCompileItems>false</EnableDefaultCompileItems>` and then the globs won't get added by default. That way VS will still see the files.

**Comment by galvesribeiro** [comment] 2017-01-14 00:50
@srivatsn ok, thanks for the reply! Will try that and report back. Thanks!

**Comment by srivatsn** [comment] 2017-01-19 06:47
We've now added a warning for this scenario. Closing this issue. Please reactivate if you're still running into problems.

**Closed by srivatsn** 2017-01-19 06:47 UTC

**Comment by stevescot** [comment] 2017-05-10 08:30
In my case this was a problem as the .csproj.user file had a reference in it as well as the .csproj - so have a look in both files - if it exists in both this can cause the problem

**Comment by ARMoir** [comment] 2018-06-02 14:30
Confirmed removing the Compile references from .csproj.user rather then .csproj resolved the issue keeping the .cs file available in Solution explorer.

**Comment by davkean** [comment] 2018-06-03 22:51
@ARMoir @stevescot Do you have a repro of this?

**Comment by SidShetye** [comment] 2019-12-16 04:18
On linux this can happen when you have case duplicates e.g. `folder/class.cs` as well as `Folder/class.cs`. IMHO, the error message needs to capture this situation and give a more useful message to users.
