### ISSUE TITLE
Can't override properties like OutputType in a .props file

### ISSUE THREAD

**Issue by jeffkl** [dotnet/sdk#850] opened 2017-02-09 23:06 UTC
Since the property `OutputType` is set in [Microsoft.NET.Sdk.props](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.props#L37) with no condition, my project can't set it like:

```xml
<Project>
  <PropertyGroup>
    <OutputType>Exe</AssemblyTitle>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
...
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
```

I can't set it my `.targets` file either because its already in use.  So the only way to change it is after the import of the props.

I propose that all of the properties in `Sdk.props` should have a condition.

Example:

```xml
<!-- User-facing configuration-agnostic defaults -->
<PropertyGroup>
  <OutputType Condition=" '$(OutputType)' == '' ">Library</OutputType>
  <FileAlignment Condition=" '$(FileAlignment)' == '' ">512</FileAlignment>
  <ErrorReport Condition=" '$(ErrorReport)' == '' ">prompt</ErrorReport>
  <AssemblyName Condition=" '$(AssemblyName)' == '' ">$(MSBuildProjectName)</AssemblyName>
  <RootNamespace Condition=" '$(RootNamespace)' == '' ">$(MSBuildProjectName)</RootNamespace>
  <Deterministic Condition=" '$(Deterministic)' == '' ">true</Deterministic>
</PropertyGroup>
```

Tracking for us at https://github.com/Microsoft/msbuild/issues/1660

CC @dotnet/msbuild

**Comment by tannergooding** [comment] 2017-02-09 23:11
Dupe of https://github.com/dotnet/sdk/issues/752

**Comment by srivatsn** [comment] 2017-02-09 23:14
Yes closing as dupe of https://github.com/dotnet/sdk/issues/752

**Closed by srivatsn** 2017-02-09 23:14 UTC
