### ISSUE TITLE
GenerateBuildRuntimeConfigurationFiles is not incremental

### ISSUE THREAD

**Issue by pranavkm** [dotnet/sdk#951] opened 2017-03-07 16:13 UTC
Running `dotnet build` on an application causes it to write runtime config files out to the OutputPath when nothing has changed. Here's the log from an application that was already built:

```
Target "GenerateBuildRuntimeConfigurationFiles: (TargetId:64)" in file "dotnet\sdk\1.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets" from project "d:\temp\test\test.csproj" (target "_CheckForCompileOutputs" depends on it):
Building target "GenerateBuildRuntimeConfigurationFiles" completely.
Input file "d:\temp\test/runtimeconfig.template.json" does not exist.
Using "GenerateRuntimeConfigurationFiles" task from assembly "dotnet\sdk\1.0.0\Sdks\Microsoft.NET.Sdk\build\..\tools\netcoreapp1.0/Microsoft.NET.Build.Tasks.dll".
Task "GenerateRuntimeConfigurationFiles" (TaskId:23)
 Task Parameter:AssetsFilePath=d:\temp\test\obj\project.assets.json (TaskId:23)
 Task Parameter:TargetFramework=.NETCoreApp,Version=v1.1 (TaskId:23)
 Task Parameter:RuntimeConfigPath=d:\temp\test\bin\Debug\netcoreapp1.1\test.runtimeconfig.json (TaskId:23)
 Task Parameter:RuntimeConfigDevPath=d:\temp\test\bin\Debug\netcoreapp1.1\test.runtimeconfig.dev.json (TaskId:23)
 Task Parameter:PlatformLibraryName=Microsoft.NETCore.App (TaskId:23)
 Task Parameter:UserRuntimeConfig=d:\temp\test/runtimeconfig.template.json (TaskId:23)
Done executing task "GenerateRuntimeConfigurationFiles". (TaskId:23)
Added Item(s): FileWrites=d:\temp\test\bin\Debug\netcoreapp1.1\test.runtimeconfig.json
Added Item(s): FileWrites=d:\temp\test\bin\Debug\netcoreapp1.1\test.runtimeconfig.dev.json
```

Related:
`dotnet run` attempts to build the application prior to executing it. https://github.com/dotnet/cli/blob/master/src/dotnet/commands/dotnet-run/RunCommand.cs#L31. Consequently, invoking `dotnet run` on an already built application concurrently causes it to fail due to file contention produced by `GenerateBuildRuntimeConfigurationFiles`.

**Comment by rainersigwald** [comment] 2017-03-07 17:14
Duplicate of https://github.com/dotnet/sdk/issues/496.

(I know this because I filed a duplicate of the same issue yesterday 😇)

**Closed by rainersigwald** 2017-03-07 17:14 UTC
