### ISSUE TITLE
[Bug]: `-getProperty` shows workloads update message

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/sdk#37520] opened 2023-12-14 20:27 UTC
### Issue Description

When running msbuild with `-getProperty`, from `dotnet build`, if there are workload updates available, the command will return more content than required.

### Steps to Reproduce

`dotnet build --getProperty:TargetFramework`

### Expected Behavior

`net8.0` or something similar

### Actual Behavior

```
net8.0

Workload updates are available. Run `dotnet workload list` for more information.
```

### Analysis

It may not be an msbuild problem specifically, but rather a `dotnet` issue which adds a message after a command has been executed.

### Versions & Configurations

`8.0.100`

**Comment by ShreyasJejurkar** [comment] 2023-12-25 09:53
I tried to repro this, but it did not. 
![image](https://github.com/dotnet/sdk/assets/17148381/43587e9a-0863-422b-9c91-d7a1f3346330)

**Comment by WeihanLi** [comment] 2023-12-29 01:56
+1
I had the same issue, even I uninstalled all workloads

**Comment by WeihanLi** [comment] 2023-12-29 02:06
may come from 
https://github.com/dotnet/sdk/blob/1c0404394bc925ceb9bf8596165145ae30e947ad/src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs#L147-L153

**Comment by baronfel** [comment] 2023-12-29 02:31
that's exactly what the problem is, and it's part of a larger unit of work we need to do in the CLI - output that isn't _directly_ related to the operation in question needs to go to StdErr instead of StdOut - especially in cases where the user is performing operations that may want to parse the StdOut stream. The CLI's logging/output needs to be audited and situations like the workload update message need to be changed, but we need to do it _explicitly_ as part of an agreed-upon effort.

**Comment by marcpopMSFT** [comment] 2024-01-05 23:35
Assigning to Forgind since he did the original MSBuild work and can follow up in 3xx with an improvement for at least this experience (as this could affect automation that getProperty is useful for)

**Comment by jeromelaban** [comment] 2024-01-08 13:28
Note that setting `DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE` to `true` is enough to get the expected behavior (for that particular message, at least).

**Comment by baronfel** [comment] 2024-01-08 13:32
I want to look at the interaction here with the verbosity flag - naively I'd hope that '-v quiet' (or whatever our most minimal logging level is) would prevent these status messages from being fired as well.

**Closed** 2024-03-26 20:31 UTC
Labels: Area-CLI
