### ISSUE TITLE
[Arch Linux] MSBUILD : error MSB1025 

### ISSUE THREAD

**Issue by redni** [dotnet/sdk#1916] opened 2018-01-30 11:49 UTC
**.NET Command Line Tools (2.1.4)**

**Product Information:**
 _Version:          2.1.4
 Commit SHA-1 hash:  5e8add2190_

**Runtime Environment:**
 _OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /opt/dotnet/sdk/2.1.4/_

**Microsoft .NET Core Shared Framework Host**
  _Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54_
 

Attempting to run dotnet on Arch Linux SERVER restore ends with an error. And it is very strange. I have a PC with Arch Linux and Gnome and it works there perfectly (checked just now). However, I rented and checked 2 different servers dedicated to OVH from Arch Linux without gui and there are always these errors. Clean systems, the only difference that I have on a PC with Gnome and there is only a server version. Regardless of what project it is. On the example of neo-cli:

```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.InvalidOperationException: The terminfo database is invalid.
at System.TermInfo.Database..ctor(String term, Byte[] data)
at System.TermInfo.Database.ReadDatabase(String term, String directoryPath)
at System.TermInfo.Database.ReadDatabase(String term)
at System.TermInfo.Database.ReadActiveDatabase()
at System.ConsolePal.TerminalFormatStrings.<>c.<.cctor>b__27_0()
at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
at System.Lazy`1.CreateValue()
at System.ConsolePal.EnsureInitializedCore()
at System.ConsolePal.ControlCHandlerRegistrar.Register()
at System.Console.add_CancelKeyPress(ConsoleCancelEventHandler value)
at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine) in E:\A\_work\17\s\src\MSBuild\XMake.cs:line 526

Unhandled Exception: System.InvalidOperationException: The terminfo database is invalid.
at System.TermInfo.Database..ctor(String term, Byte[] data)
at System.TermInfo.Database.ReadDatabase(String term, String directoryPath)
at System.TermInfo.Database.ReadDatabase(String term)
at System.TermInfo.Database.ReadActiveDatabase()
at System.ConsolePal.TerminalFormatStrings.<>c.<.cctor>b__27_0()
at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
at System.Lazy`1.CreateValue()
at System.ConsolePal.EnsureInitializedCore()
at System.ConsolePal.ControlCHandlerRegistrar.Register()
at System.Console.add_CancelKeyPress(ConsoleCancelEventHandler value)
at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine) in E:\A\_work\17\s\src\MSBuild\XMake.cs:line 748
at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args) in E:\A\_work\17\s\src\MSBuild\XMake.cs:line 215
```

**Steps to reproduce:**
```
git clone https://github.com/neo-project/neo-cli
cd neo-cli
dotnet restore
```

**Comment by livarcocc** [comment] 2018-01-30 17:27
cc @rainersigwald

**Comment by rainersigwald** [comment] 2018-01-30 18:06
With that error, I'm inclined to blame CoreFX. It's thrown [here](https://github.com/dotnet/corefx/blob/45b724f6b6391910edea8a70f3f22a4a7996696d/src/System.Console/src/System/TermInfo.cs#L125) or [here](https://github.com/dotnet/corefx/blob/45b724f6b6391910edea8a70f3f22a4a7996696d/src/System.Console/src/System/TermInfo.cs#L139).

Either the validation checks are bad or there's something wrong with terminfo on the server machine.

@Redni can you share the following:
* The contents of the `TERM` environment variable in the failing case
* The contents of the `TERMINFO` environment variable
* The contents of `~/.terminfo` if it exists
* The contents of `/etc/terminfo` if it exists
* The contents of `/lib/terminfo` if it exists
* The contents of `/usr/share/terminfo` if it exists
* The output of `strace -e trace=file dotnet build` on the failing machine

**Comment by livarcocc** [comment] 2018-01-30 20:34
also adding @steveharter so that he can help point to the right person in corefx.

**Comment by Redni** [comment] 2018-01-30 20:36
- The contents of the `TERM` is a `xterm-256color`
- The contents of the `TERMINFO` is not set
- The contents of `~/.terminfo` is not exist
- The contents of `/etc/terminfo` is not exist
- The contents of `/lib/terminfo` is in the attachment [lib.terminfo.zip](https://github.com/dotnet/sdk/files/1679151/lib.terminfo.zip)
- The contents of `/usr/share/terminfo` is in the attachment [share.terminfo.zip](https://github.com/dotnet/sdk/files/1679264/share.terminfo.zip)
- The output of `strace -e trace=file dotnet build` is in the attachment [dotnet.log](https://github.com/dotnet/sdk/files/1679259/dotnet.log)

**Comment by steveharter** [comment] 2018-01-31 15:49
I didn't find a corefx issue that matches the InvalidOperationException + terminfo.

However other platforms have issues with terminfo:
https://github.com/dotnet/corefx/issues/24259

cc @wfurt

**Comment by TFSThiagoBR98** [comment] 2018-01-31 16:25
Probably the problem is in ncurses 6.1

**Comment by Redni** [comment] 2018-01-31 16:37
@TFSThiagoBR98 you are right. On PC I had ncurses 6.0 and on server 6.1 I changed the version on the server to 6.0 and everything works fine. We already know what causes the problem. However, how to make the dotnet also work properly on the newer version of ncurses?

**Comment by livarcocc** [comment] 2018-01-31 22:03
I think this issue should be moved to corefx, where it will have far better visibility.

**Comment by superriva** [comment] 2018-02-20 14:16
Same errors. I have to downgraded to 6.0+20170902-3 too.

**Comment by peterhuene** [comment] 2018-02-20 18:52
I believe this issue belongs to corefx and dotnet/corefx#26966 captures the issue.  Closing in favor of that issue.

I also run Arch and can confirm that downgrading to 6.0+20170902-3 is a passable workaround until the framework has a fix.

**Closed by peterhuene** 2018-02-20 18:52 UTC

**Comment by peterhuene** [comment] 2018-02-20 18:54
Also note that this does not occur when using `TERM=xterm`, so another workaround to this issue is to invoke `dotnet` with this set:

```
$ TERM=xterm dotnet
```

**Comment by firhatnawfanh** [comment] 2018-03-10 02:02
Hi @peterhuene Thanks for the solution, why would TERM=xterm fix the problem though?

**Comment by wfurt** [comment] 2018-03-10 02:08
New terminfo database start using some new features and older dotnet is not able to parse it correctly. 
'xterm' however did not change so everything works as it used to.

**Comment by mausworks** [comment] 2018-04-12 16:06
For now, I added:

```.bashrc
alias dotnet='TERM=xterm dotnet'
```
To my `~/.bashrc`. 

But it [looks to be resolved shortly.](https://github.com/dotnet/core-setup/issues/3976#issuecomment-380546024) :+1:
