### ISSUE TITLE
dotnet test ignores -property command line parameters

### ISSUE THREAD

**Issue by nagya** [dotnet/sdk#29115] opened 2022-11-18 04:28 UTC
### Describe the bug.

In a command like `dotnet test something.csproj -property:foo=bar`, the property is ignored.

### To Reproduce

In the attached solution, the following all correctly fail with a warning treated as error:

```
dotnet build -property:TreatWarningsAsErrors=true
dotnet test -property:TreatWarningsAsErrors=true
dotnet build TestProject2.sln -property:TreatWarningsAsErrors=true
dotnet build TestProject2.csproj -property:TreatWarningsAsErrors=true
```

However, the following succeed and merely produce a warning, ignoring the property:

```
dotnet test TestProject2.sln -property:TreatWarningsAsErrors=true
dotnet test TestProject2.csproj -property:TreatWarningsAsErrors=true
```

### Further technical details

```
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.6
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

[TestProject2.zip](https://github.com/dotnet/sdk/files/10037706/TestProject2.zip)

**Comment by baronfel** [comment] 2022-11-18 04:34
Hi @nagya - This is a duplicate of https://github.com/microsoft/vstest/issues/4014. We've merged a fix already and the fix will be available in 7.0.101 early/mid next month.

**Closed by baronfel** 2022-11-18 04:34 UTC
Labels: Area-DotNet Test, untriaged
