### ISSUE TITLE
$(TargetPath) or $(TargetDir) are empty on PostBuild event on netstandard project

### ISSUE THREAD

**Issue by marcusien** [dotnet/sdk#1055] opened 2017-03-30 08:47 UTC
Hi,

There's an issue with post build event on netstandard library.
when executing a post build event, the $(TargetDir) et $(TargetPath) macros are empty while they are not empty on the "post build event command line" wizard on visual studio.

You can reproduce it easily by

creating a netstandard project library
put an echo "Target path is : " $(TargetPath)"
then build the project
take a look at output window
This works for $(SolutionDir) or other macros

**Comment by AlexeyRipenko** [comment] 2017-04-05 10:04
ProjectDir, OutDir, ProjectName don't work also

**Comment by nivinj** [comment] 2017-04-05 11:58
Also ConfigurationName

**Comment by dsplaisted** [comment] 2017-04-09 15:23
We will probably be disabling pre and post build events and recommend people use targets instead.  For example:

```xml
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="echo Before Build: $(OutDir)" />
  </Target>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="echo After Build: $(OutDir)" />
  </Target>
```

Closing this issue as a duplicate of #677.  See also https://github.com/dotnet/project-system/issues/1569 which is for updating the property pages in VS.

**Closed by dsplaisted** 2017-04-09 15:23 UTC

**Comment by QuantumHive** [comment] 2017-07-09 09:59
Where can we find these recommendations? I had to find it out the hard way after banging my head for hours why the events didn't work.

**Comment by CaledoniaProject** [comment] 2020-06-30 03:10
This saved my day. The easiest solution is to remove `<PostBuildEvent>` in the csproj file then recreate the script in Visual Studio.

**Comment by icnocop** [comment] 2020-11-25 01:17
Related: https://github.com/dotnet/try-convert/issues/269

**Comment by paul-datatech911** [comment] 2022-01-11 16:15
> This saved my day. The easiest solution is to remove `<PostBuildEvent>` in the csproj file then recreate the script in Visual Studio.

What do you mean by this @CaledoniaProject ?  We have PostBuild events that use signtool.exe to sign assemblies from .NetFramework projects that were then run through the upgrade-assistant for VS2022/net6 targeting.  Those no longer work presumably because many of the macros we use no longer exist in the SDK-style projects and/or VS2022.  

`"C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool\signtool.exe" sign /f "G:\codesign.pfx" /p ******  /tr  "http://timestamp.sectigo.com"  /td sha256 /fd sha256 ""`

What does "recreate the script in Visual Studio" mean exactly?

**Comment by imtrobin** [comment] 2022-02-25 08:14
Hmm, I deleted the old PostbuildEvent and recreated from UI. I see  in csproj that they are changed to Target already but $(TargetPath) is still empty

**Comment by krypt-lynx** [comment] 2022-11-06 21:22
```
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="echo &quot;pre-build&quot;&#xD;&#xA;&#xD;&#xA;git describe --tag --dirty --always &gt; &quot;$(ProjectDir)\git.txt&quot;&#xD;&#xA;&#xD;&#xA;cd &quot;$(TargetDir)&quot;&#xD;&#xA;&#xD;&#xA;echo &quot;target dir:&quot;&#xD;&#xA;echo &quot;$(TargetDir)&quot;&#xD;&#xA;echo &quot;current dir:&quot;&#xD;&#xA;cd&#xD;&#xA;&#xD;&#xA;del /Q *.*" />
  </Target>
```

I have this...
