### ISSUE TITLE
CA2252 warnings with .NET 7 RC1 SDK

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/sdk#28049] opened 2022-09-16 02:18 UTC
**Version Used**: .NET 7 RC1 SDK

**Steps to Reproduce**:

1. Clone the .NET Community Toolkit at https://github.com/CommunityToolkit/dotnet/commit/338172af682a5910ca33962211be1751d0dd2008
2. Run `dotnet build` on the solution

**Expected Behavior**:

The solution should build fine like it did up until now.

**Actual Behavior**:

A whole bunch of CA2252 warnings from the CommunityToolkit.HighPerformance.UnitTests project. This is using a bunch of types from CommunityToolkit.HighPerformance that are marked as `[RequiresPreviewFeatures]`, but the test project using it _is_ using `<EnablePreviewFeatures>` in the .csproj, so I'm not really sure why with the .NET 7 SDK this is causing issues.

Failing CI run: https://dev.azure.com/dotnet/CommunityToolkit/_build/results?buildId=78431&view=results.

cc. @333fred

**Comment by dsplaisted** [comment] 2022-09-20 19:02
@terrajobst It sounds what might be happening here is that a project stops working when moving from the .NET 6 SDK to the .NET 7 SDK, as it targets .NET 6.0 and no longer automatically gets opted in to preview features with the .NET 7 SDK.

What is the expected behavior here?

**Comment by jeffhandley** [comment] 2022-09-20 22:20
For reference, here's the PR that introduced this logic: #18815

**Comment by Youssef1313** [comment] 2022-09-20 22:23
I guess https://github.com/dotnet/designs/pull/232 explains it. It looks by-design?

**Comment by jeffhandley** [comment] 2022-09-20 22:30
Ah, you're right @Youssef1313!

The key section is here:
https://github.com/dotnet/designs/blob/main/accepted/2021/preview-features/preview-features.md#meaning-of-property-in-multi-targeted-projects

This design detail was intended to handle scenarios around preview features that ship as part of the .NET SDK. The reported issue here does not involve .NET SDK preview feature, but the logic gets applied nonetheless.

The workarounds are to either target `net7.0` or use the .NET 6 SDK. We should consider updating that logic to avoid this pitfall, but I think that would be out of scope for .NET 7 at this point.

**Comment by dsplaisted** [comment] 2022-09-26 17:04
@jeffhandley Can you handle tracking any changes for .NET 8 you might want to do for this?

**Comment by jeffhandley** [comment] 2023-07-26 18:27
Looking back at this as we wind down .NET 8, and I think we should close this as by-design without making any changes. As mentioned above, this behavior was intentional as the behavior of Preview Features was that it requires having the runtime and SDK aligned on their versions as either side could have incompatible changes to the feature in the next version; enforcing the alignment keeps you on the understood pairing of versions for that preview feature.

**Closed by jeffhandley** 2023-07-26 18:27 UTC
Labels: Area-CLI
