### ISSUE TITLE
use different assembly version for different build task

### ISSUE THREAD

**Issue by heejaechang** [dotnet/sdk#3328] opened 2019-06-13 00:22 UTC
a lot of times, I get something like this whenever I do branch switch and restore and open solution in VS

![image](https://user-images.githubusercontent.com/1333179/59394912-5d06fc00-8d36-11e9-81c1-d2f0ad724168.png)

and I believe that is happening because different dll that has same assembly version is already loaded in the msbuild which got reused.

can we make different build task dll to use different assembly version so that we don't get into this problem?

**Comment by nguerrera** [comment] 2019-06-13 05:10
Yes. This regressed with infrastructure change. This is a dupe. I will fix this.

**Comment by nguerrera** [comment] 2019-06-13 05:12
Duplicate of #2953

**Closed by nguerrera** 2019-06-13 05:12 UTC
