### ISSUE TITLE
Building project with twice (or more) transitive dependencies explodes.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/sdk#353] opened 2016-11-03 00:10 UTC
## Repro
Given the following setup: Project1 => Project2 => Project3.

When you restore Project1 you get an entry for Project2 and Project3 in the assets.json file. However, when you build Project1 Project3 is never passed to csc.

Trying restoring/building the following: [TransitiveCSCRepro.zip](https://github.com/dotnet/sdk/files/567987/TransitiveCSCRepro.zip)

## dotnet info:
```
.NET Command Line Tools (1.0.0-preview3-004007)

Product Information:
 Version:            1.0.0-preview3-004007
 Commit SHA-1 hash:  80ec02b4da

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

## SDK: `1.0.0-alpha-20161029-1`

**Comment by dsplaisted** [comment] 2016-11-03 00:59
I think I recall that this is the intended behavior.  You will get transitive project references in the output folder, but only direct project references get passed to the compiler.

**Comment by srivatsn** [comment] 2016-11-03 01:02
Isn't this just https://github.com/dotnet/roslyn-project-system/issues/199 - that we don't support transitive project references yet.

**Comment by NTaylorMullen** [comment] 2016-11-03 17:33
So NuGet handles this correctly (updates the assets.json). The bits that are left is letting MSBuild bits (this issue) and the UI work to show the inherited dependencies. Unless I'm missing something dotnet/roslyn-project-system#199 would still require work in this repo to be done.

This issue ends up also being a `dotnet pack` problem as well.

**Comment by nguerrera** [comment] 2016-11-18 18:24
Closing as dup of #200

**Closed by nguerrera** 2016-11-18 18:24 UTC
