### ISSUE TITLE
dotnet build does not include Norwegian resource files in the output

### ISSUE THREAD

**Issue by Dzeneralen** [dotnet/sdk#23493] opened 2022-01-19 10:10 UTC
### Describe the bug
Building a .sln og .csproj file with `dotnet build` does not behave as expected for Norwegian resource files. 

This seems to work ok with msbuild (if you trigger the build through VS and not directly with dotnet cmdline)

### To Reproduce
1. Create an ASP.NET Core Web App in Visual Studio 2022
2. Add a folder named `Resources`
3. Add resource files for `en`, `de` and `no` with a single resource of key-value `"Hello": "World"`
4. Build the solution or project with `dotnet build`
5. Navigate to the bin folder and see that only `en` and `de` folders are created, there is no `no` folder
6. Change name of `no` to `nb` and rebuild.
7. Verify `nb` folder now exists

![screenshot](https://user-images.githubusercontent.com/3482008/150136192-1af94919-417a-4e2b-bdac-4f1c91e1b2cf.png)

### Further technical details
- Running on Visual Studio 2022
- .NET SDK: Version:   6.0.101

**Comment by KalleOlaviNiemitalo** [comment] 2022-01-19 10:49
I thought this might be related to <https://github.com/dotnet/msbuild/issues/1454> and<https://github.com/dotnet/msbuild/issues/3897>, but "no" is already listed at <https://github.com/dotnet/msbuild/blob/c9eb9dd64e9a2e8a433900a1a626d65a2bce4428/src/Tasks/CultureInfoCache.cs#L644>.

**Comment by marcpopMSFT** [comment] 2022-02-02 00:50
@Dzeneralen Are you able to provide an https://aka.ms/binlog?  You should be able to review the binlog to try to determine why one language is included and the other is not. Are these .resources files or resx files or something else?

**Comment by DamianEdwards** [comment] 2022-02-10 00:19
Confirmed I can reproduce this. Here's the relevant part of the binlog:
<img width="525" alt="image" src="https://user-images.githubusercontent.com/249088/153312817-6fea2ff3-4a11-43c2-8747-b7df95758e55.png">

**Comment by tarekgh** [comment] 2022-02-10 18:16
>  why can the system resolve "no" to a valid CultureInfo instance with correct data, but not include "no" in the list of cultures returned by CultureInfo.GetCultures(CultureTypes.AllCultures)

There are many aliased cultures. aliased cultures have different names but share the culture data for other standard cultures. Enumeration using `CultureInfo.GetCultures` doesn't return the aliased cultures. There are many reasons for that, one is having users use the standard names instead of the aliased ones. The second reason is listing 2 cultures in the enumerations which point to same data can cause issues (e.g. someone populating the list in a dropdown UI list using the display names which can show a duplicate at that time). 

MSBuild has a tracking issue https://github.com/dotnet/msbuild/issues/3897 to fix the build as it is not right to scope the support to the cultures returned only by `CultureInfo.GetCultures`. 

Last, I want to emphasize, anyone using `CultureInfo.GetCultures` to check if any culture is supported or limit the functionality support to such list would be wrong and need to fix that. Now on Windows 10 and any Linux/MacOS when using ICU library, can create any culture with any name conforming to the BCP-47 spec even the system not having a data for that culture. That means it is impossible to return any list satisfying what you want to do. Therefore, we have exposed the [API](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.getcultureinfo?view=net-6.0#system-globalization-cultureinfo-getcultureinfo(system-string-system-boolean)) to create the culture and having a Boolean flag to pass if you want to restrict the creations to the cultures has a data in the system.

**Comment by marcpopMSFT** [comment] 2022-04-01 21:17
Closing this item since msbuild already has issues for tracking this.

**Closed by marcpopMSFT** 2022-04-01 21:17 UTC
Labels: untriaged, Area-NetSDK
