### ISSUE TITLE
Error on update and install after the successful workload update

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#18077] opened 2021-06-03 22:57 UTC
I get the same error message about JSON for both install and update.  For install, it then gives me the help output which is probably shouldn't.  For update, it gives me the full exception stack.

<snipped>
Pack Microsoft.iOS.Templates version 14.5.100-preview.5.889 is already installed.
Writing workload pack installation record for Microsoft.iOS.Templates version 14.5.100-preview.5.889...
Garbage collecting for SDK feature bands 6.0.100...
**System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.**
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes) in System.Text.Json.dll:token 0x60000da+0x0
   at System.Text.Json.Utf8JsonReader.Read() in System.Text.Json.dll:token 0x600028e+0x2a
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in System.Text.Json.dll:token 0x6000746+0x8
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex) in System.Text.Json.dll:token 0x6000114+0x8d
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in System.Text.Json.dll:token 0x6000746+0x10c
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in System.Text.Json.dll:token 0x6000745+0x0
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in System.Text.Json.dll:token 0x600033b+0x14
   at System.Text.Json.JsonSerializer.ReadUsingMetadata[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount) in System.Text.Json.dll:token 0x600033c+0x26
   at System.Text.Json.JsonSerializer.ReadUsingMetadata[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo) in System.Text.Json.dll:token 0x6000356+0x4c
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options) in System.Text.Json.dll:token 0x600034f+0x22
   at Microsoft.DotNet.Workloads.Workload.Install.NetSdkManagedInstaller.GarbageCollectInstalledWorkloadPacks() in dotnet.dll:token 0x60001b5+0x16f
   at Microsoft.DotNet.Workloads.Workload.Update.WorkloadUpdateCommand.UpdateWorkloads(Boolean includePreviews) in dotnet.dll:token 0x6000156+0xb1
   at Microsoft.DotNet.Workloads.Workload.Update.WorkloadUpdateCommand.Execute() in dotnet.dll:token 0x6000154+0x131
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args) in dotnet.dll:token 0x60008ca+0x5e
   at Microsoft.DotNet.Workloads.Workload.WorkloadCommand.Run(String[] args) in dotnet.dll:token 0x6000146+0x6
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient) in dotnet.dll:token 0x6000933+0x2e8
   at Microsoft.DotNet.Cli.Program.Main(String[] args) in dotnet.dll:token 0x6000931+0x6f

**Comment by sfoslund** [comment] 2021-06-04 15:51
@marcpopMSFT do you know the SDK version you repro'ed this with? What are the repro steps?

**Comment by sfoslund** [comment] 2021-06-04 16:24
Were you working off of a SDK that had been updated? We introduced the json reading relatively recently so I expect it's trying to garbage collect old pack install records that were written by the old SDK. Since we don't have any conpat requirements across previews I think this is probably not a real bug, unless it can be repro'ed with the newer SDKs without an upgrade.

**Comment by marcpopMSFT** [comment] 2021-06-04 17:04
I originally installed using preview 4 ( 6.0.100-preview.4.21255.9 I believe) and then tried the update command using 6.0.100-preview.5.21302.13.  Yeah, I figured it might be a preview to preview issue but shared it anyway in case it wasn't.

**Comment by sfoslund** [comment] 2021-06-04 17:20
Sounds good, I confirmed that the json change did come after that prev 4 version but before that prev 5 version. I'm going to close this as a preview to preview issue.

**Closed by sfoslund** 2021-06-04 17:20 UTC
Labels: Area-Workloads, untriaged

**Comment by steveisok** [comment] 2021-07-16 19:49
I've seen this happen intermittently on the garbage collecting step in `6.0.100-preview.7.21366.53`.

The workloads install, but dotnet drops out with:

```
Garbage collecting for SDK feature bands 6.0.100...
Workload installation failed: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
```

**Comment by sfoslund** [comment] 2021-07-16 20:03
@steveisok do you have any repro steps? Is preview 7 installed on a clean machine or are you seeing this when you've had previous SDKs installed in the past? Does it happen when you run install alone or did you run any other commands?

**Comment by steveisok** [comment] 2021-07-16 20:15
I uninstalled P6 and then installed the p7 build I referenced.  I was running install w/ `--skip-manifest-update`

**Comment by sfoslund** [comment] 2021-07-16 21:46
Did you install any workloads with prev 6? Do you know what build of prev 6 it was?

**Comment by steveisok** [comment] 2021-07-16 22:11
Yeah, I installed a few, but I don't recall what version I had.
