### ISSUE TITLE
dotnet-install.sh fails to download dotnet-sdk-8.0.201-linux-x64.tar.gz: BlobNotFound

### ISSUE THREAD

**Issue by akirayamamoto** [dotnet/sdk#38819] opened 2024-02-16 02:28 UTC
### Describe the bug
The script to download and install DotNet SDK 8.0 on Linux fails because it cannot find the file.

### To Reproduce
```
wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
chmod +x ./dotnet-install.sh
./dotnet-install.sh --channel 8.0
```

It fails to download this file: https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.201/dotnet-sdk-8.0.201-linux-x64.tar.gz

### Exceptions (if any)
```
<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:10476ddf-f01e-00b2-237f-60c313000000 Time:2024-02-16T02:22:38.7946313Z</Message>
</Error>
```

**Comment by baronfel** [comment] 2024-02-16 02:30
Duplicate of dotnet/core#9163 - we're tracking this there.

**Closed by baronfel** 2024-02-16 02:30 UTC
Labels: Area-Infrastructure, untriaged
