### ISSUE TITLE
Wrong error message in some cases for TFMs without built-in support

### ISSUE THREAD

**Issue by onovotny** [dotnet/sdk#663] opened 2017-01-16 23:14 UTC
Repro steps:

* Create a project with e.g. `<TargetFrameworks>netstandard1.0;invalid12.0`
* Unload and reload project

Expected:

*  error about invalid12.0 framework not being supported

Actual:

* error about not being able to find .NET Framework reference assemblies for v12.0

In a small repro, this incorrect error disappears quickly from the error list, but in a larger case (dotnet migrate of Rx.NET without yet applying the temporary workarounds that are currently required for targeting uap10.0), it stays there for a while.

**Comment by dsplaisted** [comment] 2017-05-22 20:36
This looks like a dupe of #798, so I'm closing it.

**Closed by dsplaisted** 2017-05-22 20:36 UTC
Labels: Blocking Partner, Bug
