### ISSUE TITLE
Need to set defaults for properties to make VS happy

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#400] opened 2016-11-17 04:16 UTC
There's lots of property defaults that aren't being set by the build, which is confusing VS causing it to put properties in an indeterminate state, here's the one's that I've found:

![image](https://cloud.githubusercontent.com/assets/1103906/20376210/c6bc0528-acd8-11e6-95b9-b059422928b9.png)

- Allow unsafe code
- Treat Warnings as Errors
- Output path
- Sign the assembly
- Delay sign only

**Comment by srivatsn** [comment] 2016-11-21 20:09
Dupe of https://github.com/dotnet/roslyn-project-system/issues/437. We had decided to not set the property in msbuild itself but to read the default values from XAML rules.

**Closed by srivatsn** 2016-11-21 20:09 UTC
