### ISSUE TITLE
Self-Contained publish fails when explicit restore is run beforehand with -r

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/sdk#2312] opened 2018-06-06 22:46 UTC
## Repo Steps ##
1. Install cli 2.1.301-preview-008906
2. mkdir app
3. dotnet new console --no-restore
4. dotnet restore -r linux-musl-x64
5. dotnet publish -c Release -o /sandbox --no-restore -r linux-musl-x64

## Actual Results ##
  You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
/app2/app2.csproj : error : The project was restored using Microsoft.NETCore.App version 2.1.0, but with current settings, version 2.1.1-servicing-26605-02 would be used instead.  To resolve this issue, make sure the same settings are used for restore and for subsequent operations such as build or publish.  Typically this issue can occur if the RuntimeIdentifier property is set during build or publish but not during restore.

## Expected Results ##
Publishing would succeed.

Regression appears to be caused by https://github.com/dotnet/sdk/pull/2085 
Related to https://github.com/dotnet/sdk/issues/1570

**Comment by eerhardt** [comment] 2018-06-06 22:50
/cc @dsplaisted 

Looking into this, it appears that `dotnet restore -r linux-musl-x64` sets the `RuntimeIdentifiers` (note plural) property during Restore.  Which means that `SelfContained=false`.  Thus when you `dotnet restore -r linux-musl-x64`, it thinks you are not a self-contained app, which means it restores for `2.1.0`.

Then later when you `dotnet publish --no-restore -r linux-musl-x64`, the `-r linux-musl-x64` sets the `RuntimeIdentifier` (note **NOT** plural) property, which means `SelfContained=true`. Thus it wants to use `2.1.1-servicing` (the latest patch).

**Comment by MichaelSimons** [comment] 2018-06-07 13:34
@livarcocc - curious why this was added to the 2.1.4xx milestone when this was a regression introduced in 2.1.301?

**Comment by livarcocc** [comment] 2018-06-07 17:06
I believe this is a regression between 2.1.2xx and 2.1.3xx, not within 2.1.3xx. That's when we introduced the self-publish work to guarantee that self-contained apps would publish for the highest runtime we knew of.

**Comment by dsplaisted** [comment] 2018-06-11 19:13
This was an intentional change in 2.1.300.  If you want to publish as self-contained but use `--no-restore`, you can set the `TargetLatestRuntimePatch` property in your project to true.  See the docs on [Self-contained deployment runtime roll forward](https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-patch-selection) for more details.

**Comment by livarcocc** [comment] 2018-06-12 17:13
Closing this as by design.

**Closed by livarcocc** 2018-06-12 17:13 UTC
