### ISSUE TITLE
Question: $(TargetFrameworkMonikerDisplayName) is blank on .NET 6.0 and .NET 5.0

### ISSUE THREAD

**Issue by borgdylan** [dotnet/sdk#23191] opened 2021-12-28 13:51 UTC
### Describe the bug
I am a compiler author and was enhancing my MSBuild support. I generate the TargetFrameworkAttribute as part of the build and want to always fill in the Framework Display Name. For "full" framework I use $(TargetFrameworkMonikerDisplayName) which prints out the full official name of the framework. I cannot get this to work with .NET 5/6., .NET Standard etc. Is this no longer supported or am I using the wrong MSBuild property?

### To Reproduce
Have an MSBuild SDK style project and try to output a message with $(TargetFrameworkMonikerDisplayName) while targeting .NET 6/5, .NET Standard etc.

### Further technical details
- Include the output of `dotnet --info`

```dylan@ubuntu-server:~$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  21.10
 OS Platform: Linux
 RID:         ubuntu.21.10-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  2.1.818 [/usr/share/dotnet/sdk]
  2.2.402 [/usr/share/dotnet/sdk]
  3.0.103 [/usr/share/dotnet/sdk]
  3.1.416 [/usr/share/dotnet/sdk]
  5.0.404 [/usr/share/dotnet/sdk]
  6.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
N/A (irrelevant to issue as build is triggered with dotnet build)

**Comment by KalleOlaviNiemitalo** [comment] 2021-12-28 15:28
Also reported in <https://github.com/dotnet/sdk/issues/10774>.

**Comment by dsplaisted** [comment] 2022-03-30 21:30
Closing as duplicate of #10774

**Closed by dsplaisted** 2022-03-30 21:30 UTC
Labels: untriaged, Area-NetSDK
