### ISSUE TITLE
platform bitness mismatch with self-contained publish RID will compile/publish but will fail to run

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/sdk#698] opened 2017-01-20 07:43 UTC
Moved from https://github.com/dotnet/cli/issues/2922 on behalf of @guardrex

----

@blackdwarf Yes, it's still there with MSBuild. The setup is like this ...

```xml
<PropertyGroup>
  <TargetFramework>netcoreapp1.2</TargetFramework>
  <OutputType>Exe</OutputType>
  <RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>
  <PlatformTarget>x86</PlatformTarget>
</PropertyGroup>
```
It will compile without any indication of a problem using `dotnet publish -r win10-x64` ...

![capture](https://cloud.githubusercontent.com/assets/1622880/22138730/b364e37c-dea7-11e6-95ac-70a6d0de0a77.PNG)
When you try to run the app, it :boom: with ...
```
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 
'testselfcontained.dll'. An attempt was made to load a program with an incorrect format.
```

**Comment by nguerrera** [comment] 2017-01-31 19:14
Closing as duplicate of #396, the plan for which will fix this.

**Comment by nguerrera** [comment] 2017-02-03 20:50
This is not covered by #396.

**Closed** 2017-07-21 21:26 UTC
Labels: Bug, In PR, Urgency-Soon
