### ISSUE TITLE
Build errors/warnings in multi-targeting are ambiguous 

### ISSUE THREAD

**Issue by onovotny** [dotnet/sdk#661] opened 2017-01-16 22:43 UTC
When a warning or error occurs in a multi-targeting solution, it's very hard to tell which inner build the error came from.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp1.0;net45</TargetFrameworks>
  </PropertyGroup>

  <Target Name="BreakBuild" BeforeTargets="Build" Condition="'$(TargetFramework)' == 'net45'">
    <Error Text="Inner build failing example" />
  </Target>
</Project>
```
![i1](https://cloud.githubusercontent.com/assets/1427284/22001460/33a4b2a2-dbfa-11e6-8615-f08832c1c17a.png)
![i2](https://cloud.githubusercontent.com/assets/1427284/22001459/339f8c46-dbfa-11e6-81e2-91271ec03b92.png)

**Comment by livarcocc** [comment] 2017-10-04 18:41
@nguerrera is this one ours?

**Comment by dsplaisted** [comment] 2018-02-21 19:59
Compilation errors do report the target framework they apply to:

![image](https://user-images.githubusercontent.com/145043/36502319-6a335ebe-16fe-11e8-9960-d902405eac80.png)

@rainersigwald @AndyGerlicher @jeffkl @cdmihai Any thoughts on whether it would be possible to add information to an error message about which inner build it came from for multi-targeted projects?

**Comment by rainersigwald** [comment] 2018-02-21 21:28
It's pretty hard, unfortunately. But it's a longstanding problem in MSBuild. I filed https://github.com/Microsoft/msbuild/issues/3015 to describe the problem and think about options (and collect proposals if anyone wants to make one).

**Comment by nguerrera** [comment] 2018-02-21 23:47
Duplicate of Microsoft/msbuild#3015

**Closed by nguerrera** 2018-02-21 23:47 UTC
Labels: Bug, Requires Design
