### ISSUE TITLE
APICompat.Task targets file should be validated in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/sdk#28300] opened 2022-10-03 16:26 UTC
Apparently, the APICompat.Task.targets file in the `build` folder isn't validated on CI. That was noticed in https://github.com/dotnet/sdk/commit/0a1f5cdffe8f9e4badc6a4c9da22644b74bc9b18.

**Comment by ericstj** [comment] 2022-10-03 16:48
Is it straight forward to produce a test assembly which references this (either through package or direct targets import) in the SDK's test infrastructure?

**Comment by ViktorHofer** [comment] 2022-10-03 16:58
I believe existing tests already do validate the msbuild file but are disabled because of https://github.com/dotnet/sdk/issues/23533.

**Comment by smasher164** [comment] 2022-10-19 19:55
Closing as duplicate of #23533.

**Closed by smasher164** 2022-10-19 19:55 UTC
Labels: untriaged, Area-ApiCompat
