### ISSUE TITLE
dotnet pack replaces wildcard version of reference with current actual version

### ISSUE THREAD

**Issue by 7enderhead** [dotnet/sdk#26167] opened 2022-06-18 13:42 UTC
### Description

`PackageReference` with wildcard version is replaced with currently available version of referenced package in packaged nuspec file

### Reproduction Steps

- reference nuget package with wildcard version, e.g. `<PackageReference Include="Some.Package" Version="1.2.*" />`
- run `dotnet pack`

### Expected behavior

Packaged nuget mimics same semantics of wildcard version in included nuspec file (i.e, use the latest "1.2.whatever" version in the example).

### Actual behavior

Wildcard version is resolved to currently matching package; this version is "hardcoded" into the nuspec file and package.

### Known Workarounds

You can edit the wildcard pattern back into the packaged nuspec file, which will then produce the desired behaviour. Of course, not really a feasable thing to do in real development.

### Configuration

Linux Mint 20.3 with `dotnet --info`:

```
Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  2.1.818 [/usr/share/dotnet/sdk]
  5.0.404 [/usr/share/dotnet/sdk]
  6.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by marcpopMSFT** [comment] 2022-07-06 21:13
@aortiz-msft @nkolev92 would this logic be on the sdk side or nuget side?

**Comment by nkolev92** [comment] 2022-07-06 21:20
The logic is on the NuGet side, but this behavior is by design. 
Floating versions are not supported in the version element. 

Documented here: https://docs.microsoft.com/en-us/nuget/reference/nuspec#dependencies-element

Enabling a floating behavior for transitive dependencies can lead to an inconsistent restore where you would be affected by changes in the feeds.

**Comment by 7enderhead** [comment] 2022-07-09 14:44
@nkolev92 : Sorry, but in the reference to `dependencies-element` I cannot really find a description of the behaviour you mentioned.

Nevertheless, IMHO the current behaviour is misleading, since it effectively drops information about a range of permissible versions (encoded in the wildcard).

There should be at least the possibility to specify a way that the wildcard version is preserved (which is possible, see my comment about editing the wildcard back into the nuspec file).

**Comment by nkolev92** [comment] 2022-07-11 16:31
![Floating](https://user-images.githubusercontent.com/2878341/178312642-9ae41bba-d841-4127-87ae-1b43fe4f02ce.png)

Resolving lowest compatible for transitive dependency is a core behavior by NuGet. Any behavior you may get by hand editing is not guaranteed or supported.

**Closed** 2022-07-13 21:17 UTC
Labels: untriaged, needs team triage, Area-NetSDK
