### ISSUE TITLE
Solution-based project references broken across netcoreapp versions

### ISSUE THREAD

**Issue by bradwilson** [dotnet/sdk#2560] opened 2018-09-30 02:08 UTC
This is a weird bug that I discovered on @xunit and seems to have been introduced fairly recently.

The repro project is here: https://github.com/bradwilson/netcoreapp-build-failure-repro

Pull down the source, and run `msbuild /t:"Restore;Build"` from a VS 2017 command prompt. You will see this build failure:

![image](https://user-images.githubusercontent.com/16944/46252212-8850f180-c41a-11e8-98bb-ebb79646e070.png)

The repro project is simple:

* Project A builds for `netcoreapp1.0`
https://github.com/bradwilson/netcoreapp-build-failure-repro/blob/a6a4582714c553e555495f4d950ccf672b1f5172/A/A.csproj#L4

* Project B builds for `netcoreapp1.0;netcoreapp1.1;netcoreapp2.0`
https://github.com/bradwilson/netcoreapp-build-failure-repro/blob/a6a4582714c553e555495f4d950ccf672b1f5172/B/B.csproj#L4

* There is a solution-level build dependency from B => A so that A builds first, but there are no project references between the two projects.
https://github.com/bradwilson/netcoreapp-build-failure-repro/blob/a6a4582714c553e555495f4d950ccf672b1f5172/netcoreapp-build-failure-repro.sln#L10

------

`dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

`msbuild /version`

```
Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.8.169.51996
```

**Comment by nguerrera** [comment] 2018-09-30 02:27
Thanks for the report. This is a duplicate of  https://github.com/Microsoft/msbuild/issues/3626, which was introduced in VS 15.8 and fixed for VS 15.9.

See https://github.com/Microsoft/msbuild/issues/3626#issuecomment-413889441 for workaround (setting AddSyntheticProjectReferencesForSolutionDependencies=false).

**Closed by nguerrera** 2018-09-30 02:27 UTC
