### ISSUE TITLE
dotnet tool has a verbosity mode but it isn't silent in mode "quiet"

### ISSUE THREAD

**Issue by WernerMairl** [dotnet/sdk#35173] opened 2023-09-06 04:13 UTC
I'm using 

`dotnet tool install --prerelease --verbosity quiet`

but it prints out some success message (in green):

```
You can invoke the tool using the following command: XXXXXXX
Tool 'XXXXXXXXX' (version '999.999.999.999') was successfully installed.
```

BR
Werner

### Describe the bug

in some way it should be possible to do a silent call
- a really silent version of "-v quiet"
- a commandline option like "--silent"
- ...

### Further technical details

```
.NET SDK:
 Version:   7.0.307
 Commit:    7b77e35a2b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.5
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.307/

Host:
  Version:      7.0.10
  Architecture: arm64
  Commit:       a6dbb800a4
```

**Comment by pedroveiga99** [comment] 2023-10-16 14:03
I'm in exactly in the same situation. Is there any preview for when this is going to be solved?

**Comment by Markliniubility** [comment] 2023-10-18 01:35
This looks interesting. Could I work on it?

**Comment by JL03-Yue** [comment] 2023-10-20 19:20
@Markliniubility Thanks we'd be happy to review

**Comment by Markliniubility** [comment] 2023-10-20 23:11
Should we output error and warning for `--verbosity quiet`. The definition of quiet is in [logger verbosity](https://learn.microsoft.com/en-us/dotnet/api/microsoft.build.framework.loggerverbosity?view=msbuild-17-netcore): Quiet -- only display a summary at the end of build.

I assume that the requirment is we will skip warning logs and success logs, and keep some summary logs and error logs.

In other words, the following senarios are intended. Others will have empty logs.
```
> dotnet tool install GitVersion.Tool --global --prerelease --verbosity quiet
Skipping NuGet package signature verification.
```
(there is no success message, but has a summary from some dependencies like NeGet Downloader)

```
> dotnet tool install non-existed --global --prerelease --verbosity quite
Unhandled exception: Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageNotFoundException: non-existed::[*-*, ) is not found in NuGet
```
(Have Error output)

**Comment by JL03-Yue** [comment] 2023-10-25 21:14
It seems to me that the user is looking for an option that give minimal returns in successful installs. For example, a `--silent` option for `dotnet tool install` that return no messages when successful. This option might also skip the warning logs and output the error logs. I upvoted the scenarios that @Markliniubility provided. 

@baronfel Do you have any suggestions for this? A `--silent` option might provide users more configurable options than changing the default `--quiet`, yet it adds user complexity as a new option. I'm also considering from a user's perspective how much output should we include in the minimal "silent" situation.

**Comment by baronfel** [comment] 2023-10-25 22:24
`--quiet` is our version of `--silent` - there are detailed documentations for the intent of the levels here: https://learn.microsoft.com/en-us/dotnet/standard/commandline/syntax#the---verbosity-option. Does that help?

**Comment by Markliniubility** [comment] 2023-11-09 11:17
Sorry for the delay. It took me a long long time to setup the enviroment on my new computer. https://github.com/dotnet/sdk/pull/36505 should help resolve this issue.

BTW, I found that in the past the default option is `quiet`, which according to official documentation should be `minimal`. Is there are any more intended behavior change needed, I would be happy to help

**Comment by Forgind** [comment] 2024-08-27 16:18
This was fixed with your PR, right @Markliniubility? So this should be closed?

**Comment by Markliniubility** [comment] 2024-08-27 20:01
> This was fixed with your PR, right @Markliniubility? So this should be closed?

Yeah it should be closed. Thanks!!

**Comment by Forgind** [comment] 2024-08-28 15:54
Thanks for making the change!

**Closed by Forgind** 2024-08-28 15:54 UTC
Labels: Area-Tools
