### ISSUE TITLE
Icon.Save(stream) each time returns different results

### ISSUE THREAD

**Issue by 87Alex** [dotnet/sdk#22549] opened 2021-11-11 11:14 UTC
We use the following code to compare two icons:
```
private static bool IconEquals(Icon icon1, Icon icon2) {
                var stream1 = new System.IO.MemoryStream();
                icon1.Save(stream1);
                var stream2 = new System.IO.MemoryStream();
                icon2.Save(stream2);
                return System.Linq.Enumerable.SequenceEqual(stream1.ToArray(), stream2.ToArray());
        }
```
With the net6.0 release the stream.ToArray() method each time returns different results for the same Icon.
You can modify the IconEquals as follows and it will return false:
```
private static bool IconEquals(Icon icon1) {
                var stream1 = new System.IO.MemoryStream();
                icon1.Save(stream1);
                var stream2 = new System.IO.MemoryStream();
                icon1.Save(stream2);
                return System.Linq.Enumerable.SequenceEqual(stream1.ToArray(), stream2.ToArray());
        }
```

**Comment by KalleOlaviNiemitalo** [comment] 2021-11-11 12:10
Which operating system is this? The Icon.Save(Stream) method is implemented separately for Windows.

**Comment by 87Alex** [comment] 2021-11-11 12:15
Windows 10

**Comment by 87Alex** [comment] 2021-11-16 08:03
Any news?

**Comment by 87Alex** [comment] 2021-11-24 08:15
Hello guys, its a real problem for us. We believe that a check and a fix shouldn't take long.

**Comment by eerhardt** [comment] 2021-12-03 19:03
Closing as a duplicate of https://github.com/dotnet/runtime/issues/62270.

**Closed by eerhardt** 2021-12-03 19:03 UTC
Labels: untriaged
