### ISSUE TITLE
Incremental Csc is broken in our SDK when you have a .resx

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#284] opened 2016-10-14 21:04 UTC
## Repro:

```
dotnet new -t msbuild
Add a .resx file
dotnet restore3
dotnet build3
dotnet build3
```

## Expected results:
The 2nd `build3` should be faster than the first, by a lot since nothing has changed.

## Actual results:
The 2nd `build3` takes the same amount of time on my machine.  Doing a `/v:diag` produces:

```
Building target "CoreCompile" completely.
Input file "obj\Debug\netstandard1.3\NuGet.Frameworks.Strings.resources" is newer than output file "bin\Debug\\netstandard1.3\NuGet.Frameworks.xml".
```

and earlier that generated the `NuGet.Frameworks.Strings.resources`
```
Target "CoreResGen: (TargetId:32)" in file "F:\cli\artifacts\win10-x64\stage2\sdk\1.0.0-preview3-003844\Microsoft.Common.CurrentVersion.targets" from project "F:\git\JoelNuGet\src\NuGet.Core\NuGet.Frameworks\NuGet.Frameworks.csproj" (target "ResGen" depends on it):
Set Property: GenerateResourceMSBuildArchitecture=CurrentArchitecture
Set Property: ResgenToolPath=
Set Property: GenerateResourceMSBuildRuntime=CurrentRuntime
Using "GenerateResource" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
Task "GenerateResource" (TaskId:15)
```

[build.log.txt](https://github.com/dotnet/sdk/files/530439/build.log.txt)

@rainersigwald - I'm not seeing where the problem is off the top of my head.  It looks like the CoreResGen task in `Microsoft.Common.CurrentVersion.targets` should be incremental, but isn't.

**Comment by nguerrera** [comment] 2016-10-26 05:14
Closing this as the issue is in msbuild and adequately tracked there.

**Closed by nguerrera** 2016-10-26 05:14 UTC
