### ISSUE TITLE
Commas result in unexpected results in `dotnet test`

### ISSUE THREAD

**Issue by fscottmiller** [dotnet/sdk#23481] opened 2022-01-18 17:19 UTC
### Describe the bug
When using the dotnet test filter, tests with commas in their names are not executed and no error is thrown. We are using Specflow, and this causes issues for scenario outlines, where a single test may look like `My scenario, example a`. We've found that replacing the comma with an HTML encoded comma, `%2c`, is a workaround for this issue. When using this workaround, any instance of `%2c` prints as a comma in the output. We believe that you should be able to pass commas in the CLI, as the workaround is not intuitive.

### To Reproduce

Does not work (and causes no error): `dotnet test --filter 'Name~Payer should click the return to home link after payment, payment with credit card successful'`

This comes directly from the output of `dotnet test $dll --no-build --list-tests`

It prints with the comma, but attempting to pass the output back in via the filter results in the test not executing.

### Exceptions (if any)

There is no error or exception; the tests simply don't execute.

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

dotnet 5.0 running on Ubuntu 18.04, executed via Azure Pipelines

**Comment by nohwnd** [comment] 2022-02-01 07:34
Thanks for reporting this issue, this seems to be caused by the same thing as #10423. I am closing this as a duplicate.

**Closed by nohwnd** 2022-02-01 07:34 UTC
Labels: Area-DotNet Test, untriaged
