### ISSUE TITLE
Errors restoring runtime pack

### ISSUE THREAD

**Issue by lewing** [dotnet/sdk#32038] opened 2023-04-25 16:43 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=251447
Build error leg or test failing: Microsoft.NET.Pack.Tests.dll.1.WorkItemExecution
Pull request: https://github.com/dotnet/sdk/pull/32029

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json

{
  "ErrorMessage": "The runtime pack for Microsoft.NETCore.App.Runtime.Mono.browser-wasm was not downloaded.",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[259234](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259234)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259234&view=ms.vss-test-web.build-test-results-tab&runId=5069456&resultId=103352)|dotnet/sdk#32163|
|[259233](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259233)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259233&view=ms.vss-test-web.build-test-results-tab&runId=5069360&resultId=103352)|dotnet/sdk#32162|
|[259152](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259152)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=259152&view=ms.vss-test-web.build-test-results-tab&runId=5066922&resultId=103352)|dotnet/sdk#29880|
|[257924](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257924)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257924&view=ms.vss-test-web.build-test-results-tab&runId=5036766&resultId=103352)|dotnet/sdk#32138|
|[257825](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257825)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257825&view=ms.vss-test-web.build-test-results-tab&runId=5033306&resultId=103352)|dotnet/sdk#32138|
|[257319](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257319)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257319&view=ms.vss-test-web.build-test-results-tab&runId=5027138&resultId=103352)|dotnet/sdk#32137|
|[257438](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257438)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257438&view=ms.vss-test-web.build-test-results-tab&runId=5025936&resultId=103352)|dotnet/sdk#32140|
|[257253](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257253)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257253&view=ms.vss-test-web.build-test-results-tab&runId=5023616&resultId=103352)|dotnet/sdk#32138|
|[256957](https://dev.azure.com/dnceng-public/public/_build/results?buildId=256957)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=256957&view=ms.vss-test-web.build-test-results-tab&runId=5012118&resultId=103352)|dotnet/sdk#32125|
|[256853](https://dev.azure.com/dnceng-public/public/_build/results?buildId=256853)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=256853&view=ms.vss-test-web.build-test-results-tab&runId=5010132&resultId=103352)|dotnet/sdk#32128|
|[256745](https://dev.azure.com/dnceng-public/public/_build/results?buildId=256745)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=256745&view=ms.vss-test-web.build-test-results-tab&runId=5008394&resultId=103352)|dotnet/sdk#32125|
|[256180](https://dev.azure.com/dnceng-public/public/_build/results?buildId=256180)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=256180&view=ms.vss-test-web.build-test-results-tab&runId=4994144&resultId=103348)||
|[255837](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255837)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255837&view=ms.vss-test-web.build-test-results-tab&runId=4994550&resultId=103349)|dotnet/sdk#32104|
|[255964](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255964)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255964&view=ms.vss-test-web.build-test-results-tab&runId=4989864&resultId=103348)|dotnet/sdk#32116|
|[255301](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255301)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255301&view=ms.vss-test-web.build-test-results-tab&runId=4972176&resultId=103349)|dotnet/sdk#32108|
|[255196](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255196)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255196&view=ms.vss-test-web.build-test-results-tab&runId=4970592&resultId=103348)|dotnet/sdk#32102|
|[255158](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255158)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=255158&view=ms.vss-test-web.build-test-results-tab&runId=4969674&resultId=103333)|dotnet/sdk#30038|
|[254960](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254960)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254960&view=ms.vss-test-web.build-test-results-tab&runId=4965672&resultId=103349)|dotnet/sdk#32103|
|[254657](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254657)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254657&view=ms.vss-test-web.build-test-results-tab&runId=4957808&resultId=103348)|dotnet/sdk#32065|
|[254612](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254612)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254612&view=ms.vss-test-web.build-test-results-tab&runId=4954856&resultId=103348)|dotnet/sdk#32098|
|[254538](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254538)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254538&view=ms.vss-test-web.build-test-results-tab&runId=4950422&resultId=103348)|dotnet/sdk#32095|
|[254545](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254545)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254545&view=ms.vss-test-web.build-test-results-tab&runId=4950770&resultId=103348)|dotnet/sdk#32096|
|[254528](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254528)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254528&view=ms.vss-test-web.build-test-results-tab&runId=4950358&resultId=103348)|dotnet/sdk#32094|
|[254496](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254496)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254496&view=ms.vss-test-web.build-test-results-tab&runId=4949666&resultId=103348)|dotnet/sdk#32093|
|[254171](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254171)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=254171&view=ms.vss-test-web.build-test-results-tab&runId=4942614&resultId=103348)|dotnet/sdk#32065|
|[253959](https://dev.azure.com/dnceng-public/public/_build/results?buildId=253959)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=253959&view=ms.vss-test-web.build-test-results-tab&runId=4936676&resultId=103348)||
|[253719](https://dev.azure.com/dnceng-public/public/_build/results?buildId=253719)|dotnet/sdk|[Microsoft.NET.Sdk.BlazorWebAssembly.Tests.dll.2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=253719&view=ms.vss-test-web.build-test-results-tab&runId=4930568&resultId=103302)|dotnet/sdk#29131|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|27|27|

**Comment by lewing** [comment] 2023-04-25 16:53
@marcpopMSFT is sdk onboarded to known issues?

**Comment by marcpopMSFT** [comment] 2023-04-25 20:25
Don't think we are. Do you have a pointer to how to get onboarded?

**Comment by marcpopMSFT** [comment] 2023-04-25 20:26
Where did you get the failure details?  From the raw helix logs, looks like a space issue: [m[37m      /private/tmp/helix/working/BF5C09E5/p/d/sdk/8.0.100-ci/NuGet.targets(156,5): error : No space left on device [/private/tmp/helix/working/BF5C09E5/w/9828087B/e/testExecutionDirectory/PackMultiTargetedLibrary/PackMultiTargetedLibrary/PackMultiTargetedLibrary.csproj]

**Comment by lewing** [comment] 2023-04-25 20:30
I saw it on several builds but it could definitely be a space issue

**Comment by lewing** [comment] 2023-04-25 20:30
https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-get-onboard

**Comment by lewing** [comment] 2023-04-26 00:30
@marcpopMSFT https://dev.azure.com/dnceng-public/public/_build/results?buildId=252412&view=logs&j=fa59fe4e-195c-56fa-189b-58fd241f10dd&t=71146b80-38e1-5fea-9b74-ba1045aac3e1&l=329 

```
    Microsoft.NET.Sdk.BlazorWebAssembly.Tests.VanillaWasmTests.Build_Works [FAIL]
      Expected command to pass but it did not.
      File Name: C:\h\w\A64108EF\p\d\dotnet.exe
      Arguments: msbuild /t:Build C:\h\w\A64108EF\t\dotnetSdkTests\ys0g00bx.jwf\Build_Works_A---CED90528\VanillaWasm.csproj /restore
      Exit Code: 1
      StdOut:
      MSBuild version 17.7.0-preview-23225-01+6300d22b2 for .NET
        Determining projects to restore...
        Restored C:\h\w\A64108EF\t\dotnetSdkTests\ys0g00bx.jwf\Build_Works_A---CED90528\VanillaWasm.csproj (in 5.21 sec).
      C:\h\w\A64108EF\p\d\sdk\8.0.100-ci\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(287,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [C:\h\w\A64108EF\t\dotnetSdkTests\ys0g00bx.jwf\Build_Works_A---CED90528\VanillaWasm.csproj]
      C:\h\w\A64108EF\p\d\sdk\8.0.100-ci\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(478,5): error NETSDK1112: The runtime pack for Microsoft.NETCore.App.Runtime.Mono.browser-wasm was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'browser-wasm'. [C:\h\w\A64108EF\t\dotnetSdkTests\ys0g00bx.jwf\Build_Works_A---CED90528\VanillaWasm.csproj]
      StdErr:
      
      
      Stack Trace:
           at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
           at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
           at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
           at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
           at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
           at FluentAssertions.Execution.AssertionScope.FailWith(String message)
        /_/src/Tests/Microsoft.NET.TestFramework/Assertions/CommandResultAssertions.cs(33,0): at Microsoft.NET.TestFramework.Assertions.CommandResultAssertions.Pass()
        /_/src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/VanillaWasmTests.cs(30,0): at Microsoft.NET.Sdk.BlazorWebAssembly.Tests.VanillaWasmTests.Build_Works()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
      Output:
        > C:\h\w\A64108EF\p\d\dotnet.exe msbuild /t:Build C:\h\w\A64108EF\t\dotnetSdkTests\ys0g00bx.jwf\Build_Works_A---CED90528\VanillaWasm.csproj /restore
        MSBuild version 17.7.0-preview-23225-01+6300d22b2 for .NET
          Determining projects to restore...
          Restored C:\h\w\A64108EF\t\dotnetSdkTests\ys0g00bx.jwf\Build_Works_A---CED90528\VanillaWasm.csproj (in 5.21 sec).
        C:\h\w\A64108EF\p\d\sdk\8.0.100-ci\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(287,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [C:\h\w\A64108EF\t\dotnetSdkTests\ys0g00bx.jwf\Build_Works_A---CED90528\VanillaWasm.csproj]
        C:\h\w\A64108EF\p\d\sdk\8.0.100-ci\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(478,5): error NETSDK1112: The runtime pack for Microsoft.NETCore.App.Runtime.Mono.browser-wasm was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'browser-wasm'. [C:\h\w\A64108EF\t\dotnetSdkTests\ys0g00bx.jwf\Build_Works_A---CED90528\VanillaWasm.csproj]
```

**Comment by lewing** [comment] 2023-04-26 00:31
on https://github.com/dotnet/sdk/pull/32048

**Comment by lewing** [comment] 2023-04-27 17:24
```
Advertising manifest not updated. Manifest package for microsoft.net.sdk.testworkload doesn't exist.
Installing workload manifest microsoft.net.sdk.android version 34.0.0-preview.4.225…
Installing workload manifest microsoft.net.sdk.maui version 8.0.0-preview.3.8159…
Installing workload manifest microsoft.net.workload.mono.toolchain.current version 8.0.0-preview.4.23227.6…
Installing workload manifest microsoft.net.workload.emscripten.current version 8.0.0-preview.4.23226.1…
Installing workload manifest microsoft.net.workload.emscripten.net6 version 8.0.0-preview.4.23226.1…
Installing workload manifest microsoft.net.workload.emscripten.net7 version 8.0.0-preview.4.23226.1…
Installing workload manifest microsoft.net.workload.mono.toolchain.net6 version 8.0.0-preview.4.23227.6…
Installing workload manifest microsoft.net.workload.mono.toolchain.net7 version 8.0.0-preview.4.23227.6…
Installing pack Microsoft.NET.Runtime.WebAssembly.Sdk version 8.0.0-preview.4.23227.6...
Writing workload pack installation record for Microsoft.NET.Runtime.WebAssembly.Sdk version 8.0.0-preview.4.23227.6...
Installing pack Microsoft.NETCore.App.Runtime.Mono.browser-wasm version 8.0.0-preview.4.23227.6...
Workload installation failed. Rolling back installed packs...
Rolling back pack Microsoft.NETCore.App.Runtime.Mono.browser-wasm installation...
Rolling back pack Microsoft.NET.Runtime.WebAssembly.Sdk installation...
Uninstalling workload pack Microsoft.NET.Runtime.WebAssembly.Sdk version 8.0.0-preview.4.23227.6…
Workload installation failed: microsoft.netcore.app.runtime.mono.browser-wasm::8.0.0-preview.4.23227.6 is not found in NuGet feeds [https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-impl/nuget/v3/index.json;https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-buildservices/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-DotNet-msbuild-Trusted-8ffc3fe3/nuget/v3/index.json".](https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-impl/nuget/v3/index.json;https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-buildservices/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-DotNet-msbuild-Trusted-8ffc3fe3/nuget/v3/index.json%22.)
##[error]Cmd.exe exited with code '1'.
```
Different version of the same problem, it looks like the runtime pack sometimes isn't in the feed when the build starts

**Comment by lewing** [comment] 2023-04-27 17:31
It is basically https://github.com/dotnet/sdk/issues/23820 but for every sdk build

**Comment by marcpopMSFT** [comment] 2023-04-27 18:03
This is because the workload install isn't using a rollback so picks up the latest one AND because the runtimepack version is tied to the workload version?

BTW, to onboard to known issues, I just needed to create the Known Build Error label. That has now been created.

**Comment by marcpopMSFT** [comment] 2023-04-27 23:32
@lewing I'm more confused now. I was expecting to only see this error in tests in the AOT legs as those legs are the ones installing wasm-tools. But I have a PR where I see this fail in the Windows NT leg. Shouldn't it be using the workloads from stage0 to resolve the runtime pack version or is something else happening here?

**Comment by lewing** [comment] 2023-04-28 00:47
Yeah, I think the Known Issue here may be slightly different than the one I described in with the workload install comment; which is also a real issue.

**Comment by dsplaisted** [comment] 2023-05-02 00:36
@lewing I investigated this and it looks like the problem is that the microsoft.net.sdk.webassembly.pack NuGet package is setting `SelfContained` to true.  This is not something that you can safely do in a NuGet package, because setting SelfContained to true may mean that the runtime pack needs to be downloaded, and you can't modify things in a NuGet package that would affect restore.

Can this logic be moved to the SDK or a workload or something?

**Comment by lewing** [comment] 2023-05-02 00:38
yeah i think we can move it pretty easily.

cc @maraf @radical

**Comment by maraf** [comment] 2023-05-03 08:50
Can I close the issue or is there any other problem?

**Comment by dsplaisted** [comment] 2023-05-03 14:25
We should be able to close this.

**Closed by dsplaisted** 2023-05-03 14:25 UTC
Labels: Area-Infrastructure, untriaged, Known Build Error
