### ISSUE TITLE
`linux-x64` framework assemblies contain invalid machine type

### ISSUE THREAD

**Issue by NextTurn** [dotnet/sdk#10772] opened 2020-03-06 00:37 UTC
## Steps to reproduce

Build self-contained assemblies with `linux-x64` RID.

```
dotnet new console
dotnet build --runtime linux-x64 --self-contained true
```

Inspect the PE headers.

```cs
using System;
using System.IO;
using System.Reflection.PortableExecutable;

class Program
{
    static void Main()
    {
        foreach (string path in Directory.EnumerateFiles("bin/Debug/netcoreapp3.1/linux-x64", "*.dll"))
        {
            using PEReader reader = new PEReader(File.OpenRead(path));
            Console.WriteLine(path);
            Console.WriteLine(reader.PEHeaders.CoffHeader.Machine);
            Console.WriteLine();
        }
    }
}
```

## Expected behavior

All assemblies except *mscorlib.dll* have `Amd64` machine type.

## Actual behavior

User assemblies have `Amd64` machine type.

*mscorlib.dll* has `I386` machine type.

Framework assemblies except *mscorlib.dll* have `0xFD1D` machine type. There is no such machine type.

## Environment data

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200-preview-014883
 Commit:    4e2a0ee959

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200-preview-014883\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.200-preview-014883 [C:\Program Files\dotnet\sdk]
```

**Comment by ericstj** [comment] 2020-03-14 16:20
I believe this is by design and characteristic of crossgen since these are Linux-x64 binaries and not Windows. @swaroop-sridhar @sbomer @jkotas @janvorli does that sound correct?

**Comment by jkotas** [comment] 2020-03-14 16:36
Correct. This is duplicate of #33269

**Closed by jkotas** 2020-03-14 16:36 UTC
Labels: question
