### ISSUE TITLE
Generated .exe file is missing version info

### ISSUE THREAD

**Issue by tfenster** [dotnet/sdk#4127] opened 2020-01-04 16:38 UTC
If I publish my 3.1 console app using the following command, then the resulting .exe file does have the version info set:
`dotnet publish "client.csproj" -c Release -r win-x64 --self-contained true /property:PublishTrimmed=true /property:PublishSingleFile=true /property:Version=0.1.0.0 -o /app/publish`

If I do the exact same thing in a container using the mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1809 image, the resulting .exe file does not have the version info set.

Steps to repro: 
1. Create a sample console project using `dotnet new console -o client`
2. cd client
3. Run `dotnet publish "client.csproj" -c Release -r win-x64 --self-contained true /property:PublishTrimmed=true /property:PublishSingleFile=true /property:Version=0.1.0.0 -o /app/publish`
4. Check the properties of file `c:\app\publish\client.exe`. It should show something like this, as is correct in my opinion
![image](https://user-images.githubusercontent.com/15346084/71768566-58df3d80-2f17-11ea-9e4a-4cc5e26dd990.png)
5. Run ` docker run --rm -ti -v "<full-path>\client:c:\app" mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1809` (of course replace `<full-path>` with your path) to get a session in the container
6. cd app
7. Run `dotnet publish "client.csproj" -c Release -r win-x64 --self-contained true /property:PublishTrimmed=true /property:PublishSingleFile=true /property:Version=0.1.0.0 -o /app/publish`, exactly as above
8. Check the properties of file `<full-path>\client\publish\`. It should show something like this, in my opinion a bug
![image](https://user-images.githubusercontent.com/15346084/71768687-bf189000-2f18-11ea-8a49-3e318f494d2a.png)

`dotnet --version` shows `3.1.100` in both cases. Am I missing something?

**Comment by swaroop-sridhar** [comment] 2020-01-05 23:43
If you publish the app without `/property:PublishTrimmed=true /property:PublishSingleFile=true`  does it change the behavior?

**Comment by tfenster** [comment] 2020-01-06 10:27
The generated .dll gets the metadata inside the container as well as directly on my machine. The .exe doesn't get the metadata even without those properties inside of the container

**Comment by tfenster** [comment] 2020-01-14 20:37
@swaroop-sridhar any feedback on this?

**Comment by swaroop-sridhar** [comment] 2020-01-14 23:07
@tfenster  The SDK transfers information (ex: resources/icons) from the App DLL to the Host EXE using the HostModel DLL. Looks like some information (VersionInfo resource) is missing in this transfer.

CC: @wli3

**Comment by swaroop-sridhar** [comment] 2020-01-14 23:11
@wli3 This issue should probably be moved to Runtime repo (wrt HostWriter)
The HostModel simply copies resources between PE Files, not sure how the versioning info can be missed. This needs further investigation.

**Comment by wli3** [comment] 2020-01-15 01:06
@swaroop-sridhar after Immo's permission change, no one can move issues anymore. So i will just use the old copy paste issue mover, is that ok?

**Comment by tfenster** [comment] 2020-01-15 07:20
@wli3 @swaroop-sridhar would that be here https://github.com/dotnet/runtime/issues? I am happy to create a copy there, if that helps

**Comment by swaroop-sridhar** [comment] 2020-01-15 15:56
@tfenster, yes that's the right repo. Let's keep the issue here for now, until we figure out how to transfer the issue. Thanks.

**Comment by bravecobra** [comment] 2020-02-12 15:31
I seem to have the exact same issue, and it is reproducible.

**Comment by tfenster** [comment] 2020-02-12 19:34
@bravecobra absolutely 100% and easily reproducible. Unfortunately there hasn't been any feedback apart from discussing whether or not this is the right repo and how to maybe get it somewhere else

@swaroop-sridhar @wli3 any progress on this?

**Comment by bravecobra** [comment] 2020-02-12 20:44
I can confirm that the version information is compiled into the assembly. With reflection you get the correct version from the assembly itself, however that information isn't copied to the PE header when building on Linux/container targeting win-x64.

**Comment by swaroop-sridhar** [comment] 2020-02-12 21:55
I think I understand the problem here. The PE resources are transferred from App.dll to the host App.exe only when building on Windows -- because the resource handling code currently uses native Win32 API. So, when the app is published from Linux or nanoserver, the resources are not transfered. 

There is an issue https://github.com/dotnet/runtime/issues/3828 filed for implementing ResourceUpdater in managed code. Once this happens, the version information will be transfered regardless of the host machine configuration.

@wli3 I think we can resolve this issue as a dup of https://github.com/dotnet/runtime/issues/3828.
Isn't it?

**Closed** 2020-02-13 16:01 UTC
