### ISSUE TITLE
DOTNET_USE_POLLING_FILE_WATCHER is not respected on the sdk:5.0 image

### ISSUE THREAD

**Issue by Szymon-D** [dotnet/sdk#14081] opened 2020-10-09 19:50 UTC
DOTNET_USE_POLLING_FILE_WATCHER environment variable is not working on the default 5.0 SDK image. 
The problem does not occur on the sdk:5.0-alpine image.

I have created a repository with a reproduction of the issue: https://github.com/Szymon-D/DotnetPollingWatchRepro. 
You can test it by running "start_*.sh" scripts and then making any change to the "Program.cs" file.
From the tested range of images (sdk:3.1, sdk:3.1-alpine, sdk:5.0, and sdk:5.0-alpine), the issue with watcher occurs only on sdk:5.0.

**Comment by elafarge** [comment] 2020-11-13 11:53
We've upgraded our local development stack to .NET 5 yesterday and are facing the same issue :cry: 

Moving to Alpine-based containers did the trick though but (re-)build times seem to be significantly slower than on debian though (maybe because I was forced to downgrade libc6-compat to ensure compatibility with the gRPC Nuget packages we're using :thinking: ), a fix would be warmly welcome :)

**Comment by elafarge** [comment] 2020-11-13 21:19
I was a bit annoyed by the slow build times I was getting in alpine, so I just crafted a quick .NET SDK image for our local development stack based on `ubuntu:focal` relying on the `dotnet-install.sh` script. 

File watching works like a charm (surprisingly, both with and without the polling file watcher on a Linux host).

Out of curiosity, I tried using `debian:buster-slim` as a base image and... it stopped working. I also tried `debian:buster" and `debian:bullseye` and got the same problem.
It seems that the issue is due to the base image (a missing or flaky package maybe ?).

Seems like it will do the job until the official image is fixed.

Here's the dockerfile in case it helps:
```Dockerfile
FROM ubuntu:focal

ENV DOTNET_CLI_TELEMETRY_OPTOUT=true

# Dotnet runtime deps
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        # .NET Core dependencies
        libc6 \
        libgcc1 \
        libgssapi-krb5-2 \
        libicu66 \
        libssl1.1 \
        libstdc++6 \
        zlib1g \
        curl \
    && rm -rf /var/lib/apt/lists/*

# Dotnet SDK
RUN curl -LO https://dot.net/v1/dotnet-install.sh && \
  chmod +x dotnet-install.sh && \
  ./dotnet-install.sh -c Current -i /opt/dotnet && \
  cd .. && \
  rm dotnet-install.sh

ENV PATH="/opt/dotnet:${PATH}"
ENV DOTNET_RUNNING_IN_CONTAINER=true
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
ENV ASPNETCORE_URLS=http://+:80
```

**Comment by MichaelSimons** [comment] 2020-11-19 14:16
Closing this as a duplicate of https://github.com/dotnet/aspnetcore/issues/27950.

**Closed by MichaelSimons** 2020-11-19 14:16 UTC
