### ISSUE TITLE
When multiple TargetFrameworks are used, RunProduceContentAssets is skipped on rebuild

### ISSUE THREAD

**Issue by MatthewSteeples** [dotnet/sdk#25504] opened 2022-05-18 16:39 UTC
### Describe the bug
We depend on a NuGet package that makes use of a `.pp` file to add a class to be compiled into the library. When installing the NuGet package the class is created, and when the project is built the class is created if necessary. When the project is cleaned the file is deleted. When the project is rebuilt, if there are multiple TargetFrameworks specified in the .csproj file then the project will fail to build.

In the linked repo, I've included the log file of the MSBuild output from my computer. Line 3014 and 3018 highlight where I believe the problem lies. The `RunProduceContentAssets` step is where the `.pp` file is transformed into a `.cs` file, and this is not run because MSBuild has been set up so that `_CleaningWithoutRebuilding` is true (on line 2761).

### To Reproduce
See https://github.com/MatthewSteeples/MimeRebuilder. Building the project works fine, but rebuilding the project results in an error. 

### Exceptions (if any)
No exceptions are thrown, but the compilation fails because the referenced class has not been created

### Further technical details
- Output of `dotnet --info` is also in the repo
- Tested in Visual Studio 17.2.1 and 17.3.0
- Also tested using MSBuild 17.2.1+52cd2da31

**Comment by baronfel** [comment] 2022-06-03 17:00
Sorry I missed this. You've identified the root cause correctly, but we've had more conversation/engagement on #25758, so I'm going to close this as a duplicate.

**Closed by baronfel** 2022-06-03 17:00 UTC
Labels: untriaged, Area-NetSDK

**Comment by sharwell** [comment] 2024-06-13 18:28
Duplicate of #25758
