### ISSUE TITLE
dotnet --list-sdks shows empty although .Net core sdks are installed

### ISSUE THREAD

**Issue by sherryhw** [dotnet/sdk#14139] opened 2020-10-14 00:40 UTC
After recent windows update, my Visual studio 2019 cannot load project, and the error is "The project file cannot be opened. Unable to locate the .NET Core SDK."
I checked my machine, in Apps&Features settings, I could see .Net Core Sdk were installed. 
![image](https://user-images.githubusercontent.com/9728796/95930213-c5c31600-0d7a-11eb-8602-c3d9967bbda6.png)

Also in "C:\Program Files\dotnet\sdk", I could see different sdk versions,
![image](https://user-images.githubusercontent.com/9728796/95930263-e1c6b780-0d7a-11eb-9416-208ebd434f4e.png)

However, when I use command line to check the sdks,  "dotnet --list-sdks", it just shows as empty.
![image](https://user-images.githubusercontent.com/9728796/95930285-f6a34b00-0d7a-11eb-9340-8dedb8bb3a52.png)

For now my visual studio 2019 cannot load the projects, even I reinstall the sdk multiple times, but this issue still happens. Any ideas how to fix this issue? Thanks.

**Comment by sherryhw** [comment] 2020-10-14 00:41
![image](https://user-images.githubusercontent.com/9728796/95930417-3e29d700-0d7b-11eb-80e7-d52f0bac47d4.png)
Visual studio 2019 shows as this issue.

**Comment by bmanikrishna** [comment] 2020-10-15 13:15
Follow steps provided in the below issue it worked for me

https://github.com/dotnet/runtime/issues/3242

**Comment by dsplaisted** [comment] 2020-12-03 19:09
Glad you figured out the issue.

**Comment by AlexandreBarros** [comment] 2021-11-04 23:34
Same problem after install VISUAL STUDIO 2022.
Commands like dotnet run doesn't work.

**Comment by ea-orbital8** [comment] 2021-11-09 04:57
> Same problem after install VISUAL STUDIO 2022. Commands like dotnet run doesn't work.

I also had this problem in Visual Studio 2019 after updating Visual Studio 2022 17.1.0 Preview 1.0. After this, in my path environment I had C:\Program Files (x86)\dotnet\ and C:\Program Files\dotnet\ but the sdks were all below C:\Program Files\dotnet\. I removed C:\Program Files (x86)\dotnet\ from my path environment variable, restarted visual studio 2019 and the Powershell window and the issue was resolved

**Comment by NinovanderMark** [comment] 2021-11-09 08:47
I had the same problem after I uninstalled Visual Studio 2022 Preview. Removing the `C:\Program Files (x86)\dotnet\` directory from my PATH variable solved it.

**Comment by samunro** [comment] 2021-11-09 08:58
I had the same issue after upgrading to 17.1 Preview 1 (from 17.0 Preview). The easiest way to test was to run dotnet --list-sdks - this returned no items. It was sufficient for me to move the C:\Program Files\dotnet\ item further up than C:\Program Files (x86)\dotnet\ to get things working again.

![image](https://user-images.githubusercontent.com/1028353/140893461-fcf89926-92cc-4b44-b939-b41302321184.png)

**Comment by Bosch-Eli-Black** [comment] 2021-11-09 09:23
@dsplaisted , Can we please get this reopened? 🙂  This is a huge issue that I think a lot of people are going to run into as they install Visual Studio 2022.

**Comment by Bosch-Eli-Black** [comment] 2021-11-09 09:42
I've filed a VS bug report: https://developercommunity.visualstudio.com/t/installing-vs2022-breaks-dotnet-tool/1575432

If you have a minute, please upvote! 🙂

**Comment by WalissonPires** [comment] 2021-11-09 12:28
> I had the same problem after I uninstalled Visual Studio 2022 Preview. Removing the `C:\Program Files (x86)\dotnet\` directory from my PATH variable solved it.

I had the same problem after upgrading Visual studio 2022 17 Last Preview to Visual Studio 2022 (Current).

Removing the environment variable worked for me.

**Comment by benmccallum** [comment] 2021-11-09 16:35
I had the same problem after upgrading from VS2022 Preview 17.1 Preview 1.0 after being on the 17.0 latest preview.

Not a super great experience. Upvoted the VS bug report.

**Comment by dsplaisted** [comment] 2021-11-10 00:34
Reposting the comment from @marcpopMSFT on the VS feedback issue here:

> Please see the known issue listed below and try the instructions there. Sorry about the impact as we’re still investigating the underlying cause for a fix: https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#2-upgrade-of-visual-studio-or-net-sdk-from-earlier-builds-can-result-in-a-bad-path-configuration-on-windows

**Comment by Bosch-Eli-Black** [comment] 2021-11-10 05:47
Thanks, @dsplaisted 🙂  Would it be appropriate to leave this bug report open until the issue is fixed? It feels like almost all users upgrading from VS2022 Preview to VS2022 official release are going to hit this issue.

It appears that the `dotnet/core` team is pointing people to the documentation and don't have a bug open to fix the root cause of the issue. See https://github.com/dotnet/core/issues/6889#issuecomment-963698890, for example 🙂

**Comment by marcpopMSFT** [comment] 2021-11-10 21:38
Good suggestion, I'll leave this item active for now until the issue is resolved so it's easier to find.

**Comment by Bosch-Eli-Black** [comment] 2021-11-11 06:04
@marcpopMSFT Thank you! 🙂

**Comment by Rick-Anderson** [comment] 2021-11-11 21:07
@marcpopMSFT  do you want to add [Windows or Visual Studio can't find the latest installed .NET SDK](https://stackoverflow.com/questions/67049414/windows-or-visual-studio-cant-find-the-latest-installed-net-sdk) near the top so folks who find this can quickly get instructions of solving the problem? Is my SO response correct?

**Comment by Bosch-Eli-Black** [comment] 2021-11-15 02:38
A fix is pending for VS2022: https://developercommunity.visualstudio.com/t/installing-vs2022-breaks-dotnet-tool/1575432#T-N1582491 🙂

Looks like it basically has the VS2022 installer remove the x86 folder from the PATH when installing VS2022

**Comment by marcpopMSFT** [comment] 2021-11-17 18:33
> A fix is pending for VS2022: https://developercommunity.visualstudio.com/t/installing-vs2022-breaks-dotnet-tool/1575432#T-N1582491 🙂
> 
> It looks like this fix is basically for the VS2022 installer remove the x86 folder from the PATH when installing VS2022.

We just released a change with 17.1 preview 1.1 and 17.0.1 that will remove the x86 folder path. It was the most targeted and low risk solution we could identify.  Visual Studio installs never add that x86 path and the x86 host should not be used in Visual Studio so this seemed relatively safe. I'm going to close this issue now and encourage customers to update their VS 2022 versions as a solution to this issue.

**Closed by marcpopMSFT** 2021-11-17 18:33 UTC

**Comment by mark-testscouts** [comment] 2023-02-14 10:02
I've been knocking my head against a wall all day. Thanks a bunch!

**Comment by artgmrs** [comment] 2023-04-17 01:08
I just fixed this error. What worked for me was moving the PATH environment variable `C:\Program Files\dotnet\` to on top of `C:\Program Files (x86)\dotnet\`.

**Comment by brian8544** [comment] 2023-10-04 20:51
> I had the same issue after upgrading to 17.1 Preview 1 (from 17.0 Preview). It was sufficient for me to move the C:\Program Files\dotnet\ item further up than C:\Program Files (x86)\dotnet\ to get things working again.
> 
> ![image](https://user-images.githubusercontent.com/1028353/140893461-fcf89926-92cc-4b44-b939-b41302321184.png)

This still is an issue and your solution works, thanks!

**Comment by PStoner3** [comment] 2023-11-08 17:42
> I had the same issue after upgrading to 17.1 Preview 1 (from 17.0 Preview). It was sufficient for me to move the C:\Program Files\dotnet\ item further up than C:\Program Files (x86)\dotnet\ to get things working again.
> 
> ![image](https://user-images.githubusercontent.com/1028353/140893461-fcf89926-92cc-4b44-b939-b41302321184.png)

I removed the x86 folder from my path, and everything in VS 17.5.5 began working. Thanks for the info.

**Comment by jinek** [comment] 2024-03-06 17:54
I'm not using visual studio or windows, rather Fedora. SDK and runtime are installed, but dotnet --list-sdks gives empty list. Is it related may be?
