### ISSUE TITLE
RequiresUnreferencedCode does not seem to work at the class level

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/sdk#18720] opened 2021-07-04 12:40 UTC
Given the following code, with .NET SDK 6.0.100-preview.5.21302.13:

```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;

namespace DemoTrimmedApp
{
    class Program
    {
        static void Main()
        {
            foreach (var type in SuperHandyReflectionUtil.GetTypeNames())
            {
                Console.WriteLine(type);
            }
        }
    }

    class EligibleForTrimming { }

    class AlsoEligibleForTrimming { }

    [RequiresUnreferencedCode("pretending for a moment that we do something more dynamic")]
    class SuperHandyReflectionUtil
    {
        public static IEnumerable<string> GetTypeNames()
        {
            foreach (var type in Assembly.GetCallingAssembly().GetTypes())
            {
                yield return type.Name;
            }
        }
    }
}
```

and given this simple project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

</Project>
```

I would expect that there would be no warnings from within `SuperHandyReflectionUtil` about using reflection, and a warning in `Program.Main` that I am calling code that has the `RequiresUnreferencedCode` attribute.

Instead, I get the following singular warning, which is the exact same warning I get when `RequiresUnreferencedCode` is not present at all (i.e when deleted or commented out):

>  warning IL2026: Using method 'System.Reflection.Assembly.GetTypes()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Types might be removed.

It would appear that even though the attribute has `AttributeTargets.Class`, it only has an effect when applied to every individual method or constructor within said class that requires it.

**Comment by vitek-karas** [comment] 2021-07-07 09:50
This is a dupe of https://github.com/mono/linker/issues/1742. It's currently being worked on.

**Closed by vitek-karas** 2021-07-07 09:50 UTC
Labels: untriaged
