### ISSUE TITLE
InvalidOperationException: Cannot find compilation library location for package

### ISSUE THREAD

**Issue by shaikhimran** [dotnet/sdk#1554] opened 2017-08-30 08:05 UTC
I am working on asp.net core 2.0  and stuck on above issue .i have added class library using services.AddMvc().AddApplicationPart  and return view from class library project

Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List<string> assemblies)

Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()

Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart+<>c.<GetReferencePaths>b__8_0(CompilationLibrary library)

System.Linq.Enumerable+SelectManySingleSelectorIterator.MoveNext()

Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable<ApplicationPart> parts, MetadataReferenceFeature feature)

Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature<TFeature>(TFeature feature)

Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.GetCompilationReferences()

**Comment by nguerrera** [comment] 2017-08-31 04:40
@eerhardt Some similarity in error message to other issues you've commented on? Dupe? Other thoughts?

**Comment by eerhardt** [comment] 2017-08-31 15:12
@shaikhimran - Do you have a project that produces the issue?  We do have an issue with MVC projects when using `<Reference Include=''` to include a .dll on disk.  See https://github.com/dotnet/core-setup/issues/2981 for more information and for workarounds.

@shaikhimran - if this is the issue you are seeing, can you let us know, and we can close this as a dupe of that.

**Comment by livarcocc** [comment] 2018-01-27 05:18
Closing this issue for lack of activity. @shaikhimran if this is still happening, please comment an answer the questions above and we can look/re-activate this issue.

**Closed by livarcocc** 2018-01-27 05:18 UTC
