### ISSUE TITLE
VB.NET 'End' not available and odd error message.

### ISSUE THREAD

**Issue by DualBrain** [dotnet/sdk#3379] opened 2019-06-09 03:00 UTC
Start with a .NET Core 3.0 Console app and simply modify Sub Main.

Module Program
  Sub Main(args As String())
     End '<--- I added this.
  End Sub
End Module

By all appearance, Visual Studio thinks things are just fine (no squiggles).  When I build, the build fails with the following error:

"BC37234: Unstructured exception handling is not supported in current project type."

Huh?  How is 'End' part of unstructured exception handling?  Also, why wouldn't 'End' be supported for a console application on .NET Core?

Thanks.

CC: @KathleenDollard, @cston

**Comment by livarcocc** [comment] 2019-07-01 18:26
I don't quite follow. Why do we need anything special here? Shouldn't this just work out of the box?

**Comment by nguerrera** [comment] 2019-07-10 20:02
Duplicate of https://github.com/dotnet/sdk/issues/2793

**Closed by nguerrera** 2019-07-10 20:02 UTC
