### ISSUE TITLE
Broken incremental build related to SourceLink and generated AssemblyInfo.cs

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/sdk#37027] opened 2023-11-20 01:51 UTC
Starting with .NET 8 I'm observing broken incremental builds related to SourceLink and the generated assembly info file.

When the regular command-line build runs, `EnableSourceControlManagerQueries` is true, so `InitializeSourceControlInformationFromSourceControlManager` runs. Then the Git SHA is added to the informational version during `AddSourceRevisionToInformationalVersion`. Finally `CoreGenerateAssemblyInfo` runs, and writes the full sha such as `1.0.0+60002d5025224f2f2ffd0e1e159226e7c2ff61c3` into `$(GeneratedAssemblyInfoFile)`.

However during design-time build, `EnableSourceControlManagerQueries` is false because DesignTimeBuild = true:
https://github.com/dotnet/sourcelink/blob/4ca4236c10047416251be48339d464f15a697e8b/src/SourceLink.Common/build/Microsoft.SourceLink.Common.props#L13

Then the target `InitializeSourceControlInformationFromSourceControlManager` doesn't run, so ultimately the generated assembly informational version is just `1.0.0`. 

Thus, the file `Foo.AssemblyInfo.cs` gets a different assembly informational attribute after regular and design-time builds, thus flip-flopping and breaking incrementality.

I don't think I've seen this before .NET 8 (maybe because SourceLink stuff wasn't on by default?).

@drewnoakes @tmat

**Comment by KirillOsenkov** [comment] 2023-11-20 01:54
Example workaround:
https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/b0c06f663946af1e251387c232df831e2ec0f38e

**Comment by baronfel** [comment] 2023-11-20 02:03
Correct - SourceLink was added to the SDK and enabled by default starting in .NET 8.0.100 - this actually happened way back in preview4.

**Comment by rainersigwald** [comment] 2023-11-20 02:08
I believe this is a duplicate of https://github.com/dotnet/sdk/issues/36666, fixed by https://github.com/dotnet/sourcelink/pull/1144 for servicing.

**Closed** 2023-11-20 02:30 UTC
Labels: untriaged, Area-NetSDK
