### ISSUE TITLE
Reenable Publish_HostedApp_WithRidSpecifiedAsArgument_NoSelfContained_Works

### ISSUE THREAD

**Issue by tmat** [dotnet/sdk#44210] opened 2024-10-15 23:55 UTC

**Comment by v-wuzhai** [comment] 2024-10-16 01:54
This PR is a duplicate of #44179. To keep the discussion and changes consolidated, I'm closing this one in favor of the other. Please continue the conversation and track progress there. Thank you!

**Closed by v-wuzhai** 2024-10-16 01:54 UTC
Labels: Area-Infrastructure, untriaged
