### ISSUE TITLE
For a web application targeting ASP.NET Core 1.0, the version of Microsoft.NETCore.App in dependencies tree is 1.1.0 instead of 1.0.3

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#701] opened 2017-01-21 01:46 UTC
_From @balachir on January 21, 2017 0:34_

## Steps to reproduce

1. Using VS 2017 RC.3 (d15rel.26118.01)
2. New ASP.NET Core web app (ASP.NET Core 1.0 on Core)
3. View dependencies tree

## Actual behavior
Microsoft.NetCore.App package shows up as 1.1.0
![image](https://cloud.githubusercontent.com/assets/8246794/22170003/c7568c92-df2d-11e6-9f65-83cf9c9fd064.png)

## Expected  behavior
Microsoft.NetCore.App package shows up as 1.0.3

_Copied from original issue: dotnet/roslyn-project-system#1288_

**Comment by nguerrera** [comment] 2017-01-25 02:37
@dsplaisted

**Comment by dsplaisted** [comment] 2017-01-25 02:53
This is the expected behavior.  See here: https://github.com/dotnet/sdk/pull/633#issuecomment-272515440

In the project tree, we are planning on removing this item from the Dependencies\NuGet node and adding it to a Dependencies\SDK node, without displaying the version number in the tree. @abpiskunov

**Comment by davkean** [comment] 2017-01-25 03:08
That comment doesn't explain it for me - please expand on why the version is 1.1.0 when targeting 1.0?

**Comment by dsplaisted** [comment] 2017-01-25 04:08
> That comment doesn't explain it for me - please expand on why the version is 1.1.0 when targeting 1.0?

Because the 1.1.0 package has the right assets for both target framework versions, so functionally it should not matter which one is referenced.  Defaulting to 1.1.0 means that an upgrade to the package won't be offered in the Package Manager UI.  If the version was 1.0.0, and people upgraded the reference in the Package Manager UI, then it would add the following to the project file:

```xml
<PackageReference Update="Microsoft.NETCore.App" Version="1.1.0" />
```

Then when a new version of .NET Core comes out, retargeting the project to the new version wouldn't result in the right version of the `PackageReference`.

Of course, as soon as a new version of the Microsoft.NETCore.App package is released, upgrades will once again be offered in the UI.  I believe that for RTM we are now planning to hide upgrades to implicit package references in the NuGet UI, so this may all be moot.

**Comment by davkean** [comment] 2017-01-25 04:16
>Defaulting to 1.1.0 means that an upgrade to the package won't be offered in the Package Manager UI
That works until the next version comes out, but we're hiding them anyway.

It's very confusing. and I'm not sure how people will be able to reason about versions of the packages if they don't match in versions. You keep saying that they are implementation detail - but they are not, they will bleed out in error messages, assets files, and logs.

**Comment by dsplaisted** [comment] 2017-01-25 04:21
If we hide the package from the upgrade UI, then we could change it so that for Microsoft.NETCore.App the package version matches the target framework version.

But we can't do that for NETStandard.Library, as there aren't any non-prerelease versions of that package below 1.6.0.

**Comment by srivatsn** [comment] 2017-01-31 19:59
Fixed by https://github.com/dotnet/roslyn-project-system/pull/1346

**Closed by srivatsn** 2017-01-31 19:59 UTC
Labels: Blocking-Release, RC3 Known Issue
