### ISSUE TITLE
.NET 8 SDK upgrade breaks MSBuildLocator

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#37111] opened 2023-11-22 20:53 UTC
While I built with the .NET 7 SDK, my .NET 7 processes (including a unit test in my solution) could use the MSBuildLocator to find the MSBuild in the .NET 7 SDK. After upgrading to the .NET 8 SDK, my .NET 7 processes can no longer find MSBuild, and unit tests fail.

Because I use global.json to pin the SDK version, I detected this problem as a direct result of the SDK upgrade and quickly found a workaround.
Had I left the SDK un-pinned, this would have caused failures unpredictably in pipelines and on our dev machines around the team, and it would have taken a lot longer to understand why MSBuildLocator was failing.

**Comment by Forgind** [comment] 2023-12-05 19:47
To be clear, you're using a .NET 7 process to try to find a .NET 8 SDK? If so, that's by design.

**Comment by AArnott** [comment] 2023-12-06 03:24
Not exactly. I'm a .NET 7 process looking for msbuild. I don't know or care what version of the SDK provides it.

If this is by design, then that means that pinning the SDK _is_ important because there is a by-design breaking change for every major version upgrade of the SDK, at least when consuming MSBuild inside the application (or test).

**Comment by Forgind** [comment] 2023-12-06 18:56
Do you still have a .NET 7 (or lower—any lower version than your runtime) SDK on your computer? If so, MSBuildLocator should still be able to find it even if there is a .NET 8 SDK available; it just won't find the .NET 8 SDK. If you pin an SDK, it should still be able to find the other SDKs and return those; if not, this sounds like a bug in MSBuildLocator.

/cc: @YuliiaKovalova @rainersigwald

**Comment by AArnott** [comment] 2023-12-06 22:29
> Do you still have a .NET 7 (or lower—any lower version than your runtime) SDK on your computer?

When I do, MSBuildLocator finds it. But the issue (without pinning the SDK) is that Visual Studio (and Azure Pipelines) just upgrades the SDK installed on the machine without warning, causing these things to mysteriously start failing when .NET 7 SDK is gone and .NET 8 SDK is installed instead, but my app still targets .NET 7.

With pinning in global.json, at least these things only fail when I try updating the pin, making it abundantly obvious what broke the behavior so I know where to start looking for a fix (in this case, either retarget to .NET 8 or install the .NET 7 SDK as well as the .NET 8 SDK). 

In my case, it was a test failure. But in the MessagePack issue linked to this issue, it's a dotnet CLI tool that targets .NET 6 and 7, but not (yet) 8. A customer that has the .NET 8 SDK installed found that the dotnet CLI tool starts failing to find msbuild. So that's a shipping regression due to a .NET 8 SDK upgrade.

**Comment by Forgind** [comment] 2023-12-07 22:00
Yeah; unfortunately that does sound like MSBuildLocator is working as expected in this case. It might be reasonable to change the check in MSBuildLocator to be a little more flexible (as proposed in https://github.com/microsoft/MSBuildLocator/issues/153) or perhaps error if it found some viable SDKs then rejected them because they were too high a version, but that's ultimately a question for the MSBuild/Locator team.

Closing the SDK bug as by-design.

**Closed by Forgind** 2023-12-07 22:00 UTC
Labels: untriaged, Area-Install
