### ISSUE TITLE
GetDependsOnNETStandard emits warning for long named references

### ISSUE THREAD

**Issue by sunahe** [dotnet/sdk#1544] opened 2017-08-28 13:32 UTC
Try to build a project that contains project long-named references starting with ..

E.g. this test repo: https://github.com/sunahe/TestGetDependsOnNetStandard

A build warning occurs:
` Resolved file has a bad image, no metadata, or is otherwise inaccessible. System.IO.DirectoryNotFoundException: The system cannot find the path specified. (Exception from HRESULT: 0x80070003) `

If the HintPath is an absolute path, there is no warning.

**Comment by nguerrera** [comment] 2017-08-31 03:38
cc @ericstj @dsplaisted

**Comment by christopherpaul** [comment] 2017-09-08 10:58
It is worth noting also that the warning message does not specify the path of the file in question - it would be good to fix that.

**Comment by ericstj** [comment] 2017-09-08 16:47
https://github.com/dotnet/sdk/pull/1530 is fixing the warning here.

@christopherpaul did you encounter this for just relative HintPaths or does it have to be both relative and long?

**Comment by sunahe** [comment] 2017-09-08 17:08
@ericstj it has to be both relative and long. I'm guessing AbsolutePath+RelativePath must exceed 260 chars for the exception to occur.

Please see PR #1548 that fixes (or at least is a workaround for) the issue.

**Comment by ericstj** [comment] 2017-09-08 19:15
I see, sounds like a bug (or MAX_PATH issue) in the desktop COM API.  /cc @jeremykuhne

Thanks for the contribution!

**Comment by JeremyKuhne** [comment] 2017-09-08 20:35
It appears that COM has a MAX_PATH limitation here. They explicitly block `> _MAX_PATH`. It might work with relative paths that go over MAX_PATH when normalized if you enable Windows long path support. The error you're getting indicates that you should get further- but there could be other blocks.

**Comment by ericstj** [comment] 2017-09-08 21:06
Is that a bug in the desktop CLR's implementation of IMetaDataAssemblyImport.OpenScope or is it in COM itself?

**Comment by memark** [comment] 2018-01-10 17:42
Any update on this?

**Comment by sevensc** [comment] 2018-01-24 17:01
I can confirm that issue, this happens when the hintpath for any package is too long. In my case this happens only on our TFS-Buildserver, caused by the default path structure (build_vnext/agent1/_work/.../projectpath/...).
And **not** only when the path length exeeds 260 characters.

**Comment by livarcocc** [comment] 2018-01-27 05:24
@ericstj @JeremyKuhne is there a bug tracking the CLR/COM fix that we can close this one against? Is there anything on the SDK layer that we can still do to prevent/improve the experience here?

**Comment by ericstj** [comment] 2018-01-29 16:44
@livarcocc you can close this against  #1548 that fixes this issue in the SDK.

**Comment by ericstj** [comment] 2018-04-17 17:55
Indeed, I am seeing the same.  @livarcocc it looks like this change didn't make it into the bits that install here: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\tools\net46.

**Comment by livarcocc** [comment] 2018-04-17 18:05
The fix will be available in VS only in 15.8, unless we want to port this over to 2xx in Escrow.

**Comment by ericstj** [comment] 2018-04-17 23:02
Are you sure?  I ask because I'm pretty surprised this didn't get fixed with codeflow given its been in master since @nguerrera merged it in October.

**Comment by kasper3** [comment] 2018-05-04 13:58
I am also getting this in 15.7. The PR was merged 7 months ago and yet not propagated to latest VS bits? Since then we have received two or three updates..

**Comment by livarcocc** [comment] 2018-06-28 05:48
This is now in 15.8.

**Closed by livarcocc** 2018-06-28 05:48 UTC
