### ISSUE TITLE
Framework assemblies are no longer transitive via project references

### ISSUE THREAD

**Issue by joelverhagen** [dotnet/sdk#279] opened 2016-10-14 01:30 UTC
**Perhaps this is by design, perhaps this is a migrate bug. Not sure. I know the the whole closure of project references is lifted by `dotnet migrate`. Perhaps the same should happen for framework assemblies?**

## Steps to reproduce

1. Create two projects, one referencing another, say `projecta` depends on `projectb`.
1. Add a framework reference (e.g. `<Reference Include="System.Xml.Linq" />`) to `projectb`.
1. Add code to `projecta` that depends on this framework assembly.
1. `dotnet restore3`
1. `dotnet build3`

Example project: [transitiveframework.zip](https://github.com/dotnet/sdk/files/528490/transitiveframework.zip)

## Expected  behavior

The build should succeed. This works in project.json land, so a migrated project should not be broken in MSBuild land.

## Actual behavior

The build of `projectb` succeeds but `projecta` fails because it can't find the types in that framework assembly.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-003830)

Product Information:
 Version:            1.0.0-preview3-003830
 Commit SHA-1 hash:  90a51bdd00

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

/cc @brthor @emgarten @eerhardt

**Comment by srivatsn** [comment] 2016-10-21 22:40
Dupe of dotnet/roslyn-project-system#199.

**Closed by srivatsn** 2016-10-21 22:40 UTC
