### ISSUE TITLE
.dll in Microsoft.NET.Build.Extensions\net461 targets .NET Framework 4.6.1

### ISSUE THREAD

**Issue by jairbubbles** [dotnet/sdk#1611] opened 2017-09-27 10:04 UTC
I just noticed that most .dll in `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\` directory target .NET Framework 4.7 which does not seem right.

Here is a dotPeek screenshot:
![image](https://user-images.githubusercontent.com/15875066/30907795-fa3577dc-a37b-11e7-92d7-29a2b6cefe6e.png)

**Comment by livarcocc** [comment] 2018-01-19 06:49
This may also be a dup of https://github.com/dotnet/sdk/issues/1324.

cc @dsplaisted

**Comment by nguerrera** [comment] 2018-01-19 18:40
This is not a dupe of that.

@ericstj @joperezr Where should I move this bug?

**Comment by joperezr** [comment] 2018-01-19 18:47
These files are built on corefx release/2.0 branch, so I would move it there. This is weird since when we build them we use the 4.6.1 TP but we should move the issue there and investigate.

**Comment by nguerrera** [comment] 2018-01-19 18:53
This issue was moved to dotnet/corefx#26456

**Closed by nguerrera** 2018-01-19 18:53 UTC
