### ISSUE TITLE
Duplicate NU1701 warnings when multi-targetting to netcoreapp2.0 and net461

### ISSUE THREAD

**Issue by anangaur** [dotnet/sdk#1474] opened 2017-08-04 18:24 UTC
1. Create a new NetCore 2.0 Console App
2. Multi-target to netcoreapp2.0;net461:
`   <TargetFrameworks>netcoreapp2.0;net461</TargetFrameworks>`
3. Add a NuGet reference to a net 461 compat package like RestSharp
**Expected**: One NU1701 warning for .NET Core 2.0 target platform
**Actual**: Two warnings but both for the same .NET Core 2.0 target platform:
![image](https://user-images.githubusercontent.com/14800916/28981661-8089a76c-7907-11e7-9978-6d94c48aee3a.png)

**Comment by nguerrera** [comment] 2017-08-31 04:11
This issue was moved to NuGet/Home#5829

**Comment by mishra14** [comment] 2017-08-31 18:50
@nguerrera this is not a nuget issue. 

This seems like an issue in the sdk target that reads the warnings from assets file because the nuget generated assets file contains only 1 warning - 

![capture](https://user-images.githubusercontent.com/10507120/29939860-392a29e6-8e42-11e7-9a76-915076d557be.PNG)

**Comment by mishra14** [comment] 2017-08-31 19:02
Thanks @nguerrera!

**Comment by livarcocc** [comment] 2018-01-23 23:47
When restoring in the command line, I see only a single warning there, so I imagine this is a project-system issue.

@Pilchie should we move this to project-system?

**Comment by Pilchie** [comment] 2018-01-23 23:55
@natidea - sounds like we're reading it per-target?

**Comment by natidea** [comment] 2018-01-24 20:03
This is a dupe of https://github.com/dotnet/project-system/issues/1511 which in turn is duped against https://github.com/dotnet/project-system/issues/2784
CPS has [added a feature](https://github.com/dotnet/project-system/issues/1511#issuecomment-301531545) to dedup the warnings across configurations (e.g. Release/Debug). Project needs to extend this across TFMs by [implementing](https://github.com/dotnet/project-system/issues/2131) `IBuildableConfiguredProjectsProvider`

**Closed by natidea** 2018-01-24 20:03 UTC
