### ISSUE TITLE
Sln build target framework dependency check is wrong

### ISSUE THREAD

**Issue by onovotny** [dotnet/sdk#1343] opened 2017-06-14 12:23 UTC
This is with 15.3p2 and the .NET Core 2 preview 1 tooling.

I have a solution where one project, that targets netstandard1.1 and net45 needs the binary output of a project that has a netcoreapp2.0 and net46 exe (for including in a package). 

There is no project reference dependency in the csproj. In the solution file, I have a build dependency set instead. The build works fine in VS but fails on the command line if I try to build the solution file:

```
C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.Common.targets(77,5): e
rror : Project 'C:\dev\refit\InterfaceStubGenerator\InterfaceStubGenerator.csproj' targets '.NETFramework,Version=v4.6;
.NETCoreApp,Version=v2.0'. It cannot be referenced by a project that targets '.NETStandard,Version=v1.4'. [C:\dev\refit\
InterfaceStubGenerator\InterfaceStubGenerator.csproj]
C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.Common.targets(77,5): e
rror : Project 'C:\dev\refit\InterfaceStubGenerator\InterfaceStubGenerator.csproj' targets '.NETFramework,Version=v4.6;
.NETCoreApp,Version=v2.0'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.5'. [C:\dev\refit
\InterfaceStubGenerator\InterfaceStubGenerator.csproj]
C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(94,5): error :
Cannot find project info for 'C:\dev\refit\InterfaceStubGenerator\InterfaceStubGenerator.csproj'. This can indicate a mi
ssing project reference. [C:\dev\refit\Refit.Tests\Refit.Tests.csproj]
    116 Warning(s)
    3 Error(s)
```

If I build the csproj files directly, it works. The build system should not be evaluating project TFM compatibility based on solution file build dependencies.

Repro:
Clone https://github.com/paulcbetts/
checkout branch `netcore2` (commit 9a3ef09bf710eb736ec3c924ec00ba8f569577c0)

From cmd line:
1. msbuild /t:restore .\Refit.sln
2. msbuild /t:build .\Refit.sln (fails)
3. git clean -xdf
4. msbuild /t:restore .\Refit.sln
5. msbuild /t:build .\Refit\Refit.csproj (succeeds)

**Comment by rainersigwald** [comment] 2017-06-14 14:07
The problem is probably in the MSBuild layer, so I think we should treat this as a duplicate of https://github.com/Microsoft/msbuild/issues/1915, which I've pulled in for investigation in 15.3/sdk 2.0.0.

**Closed by rainersigwald** 2017-06-14 14:07 UTC
