### ISSUE TITLE
 error NETSDK1005: Assets file 'D:\a\1\s\...\project.assets.json' doesn't have a target for '.NETStandard,Version=v1.5'

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#2720] opened 2018-12-05 13:30 UTC
Very similar to #1321, except that it works fine on my own machine, but [consistently fails when run in Azure Pipelines](https://dev.azure.com/azure-public/vside/_build/results?buildId=816). 

> C:\hostedtoolcache\windows\dncs\2.1.500\x64\sdk\2.1.500\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(198,5): error NETSDK1005: Assets file 'D:\a\1\s\obj\Microsoft.VisualStudio.Composition.LocalizationShell\project.assets.json' doesn't have a target for '.NETStandard,Version=v1.5'. Ensure that restore has run and that you have included 'netstandard1.5' in the TargetFrameworks for your project. [D:\a\1\s\src\Microsoft.VisualStudio.Composition.LocalizationShell\Microsoft.VisualStudio.Composition.LocalizationShell.csproj]

The [LocalizationShell project targets netstandard1.0](https://github.com/Microsoft/vs-mef/blob/7059adf14349b456c8c9e633dc496b0ee1945b4b/src/Microsoft.VisualStudio.Composition.LocalizationShell/Microsoft.VisualStudio.Composition.LocalizationShell.csproj#L7), and is referenced by [a multitargeting project that targets several frameworks including netstandard1.5](https://github.com/Microsoft/vs-mef/blob/7059adf14349b456c8c9e633dc496b0ee1945b4b/src/Microsoft.VisualStudio.Composition/Microsoft.VisualStudio.Composition.csproj#L3).

The odd thing is this works on my machine, on AppVeyor, and even on Azure Pipelines in the past. But now it's consistently failing.

This *may* be a dupe of #2563

**Comment by AArnott** [comment] 2018-12-05 13:32
Please note that all the project.assets.json files and the verbose msbuild log are all available from the Azure Pipeline build I link to above as build artifacts.

**Comment by AArnott** [comment] 2018-12-05 13:38
I think this may be a regression in 15.9.x, since commits we were able to build a couple months ago can no longer be built.

**Comment by nguerrera** [comment] 2018-12-05 15:31
Looking at binlog, there is something wrong in TFM negotiation between P2P here. Microsoft.VisualStudio.Composition is building Microsoft.VisualStudio.LocalizationShell with TargetFramework=netstandard1.5 global property, which is not a valid TFM for the latter. 

There's a solution build dependency that triggers this. This looks like another bug I investigated a little while ago, but I do not recall the msbuild versions impacted. I will search for it.

**Comment by nguerrera** [comment] 2018-12-05 15:36
Looks exactly like https://github.com/Microsoft/msbuild/issues/3626, but that was supposed to be _fixed_ in 15.9, not caused by 15.9.

cc @rainersigwald

**Comment by nguerrera** [comment] 2018-12-05 15:39
Binlog has this:

>     MSBuildVersion = 15.8.169

@AArnott Is it possible you downgraded to 15.8 RTM from 15.9 preview in pipelines rather than upgraded to 15.9 RTM?

**Comment by nguerrera** [comment] 2018-12-05 15:49
Could also have happened if pipelines was previously on 15.7 and now moved to 15.8. That's where the actual regression happened, and it was fixed in 15.9. Actually upgrading to 15.9 should resolve this.

**Comment by AArnott** [comment] 2018-12-05 19:12
Thanks, @nguerrera. Unfortunately I can't influence when these cloud build hosts upgrade to 15.9. 

But since you mentioned solution dependencies are involved (which I *rarely* use, but do in this solution), I tried simply removing the solution dep, which I can't remember why I even needed. I'll see if I can get that route to work. :)

**Comment by nguerrera** [comment] 2018-12-05 19:45
Duplicate of Microsoft/msbuild#3626,

**Closed by nguerrera** 2018-12-05 19:45 UTC

**Comment by AArnott** [comment] 2018-12-05 20:03
Ya, removing the solution dependency (and using ProjectReference with a `ReferenceOutputAssembly=false` metadata) made an adequate workaround.
Thanks again.
