### ISSUE TITLE
GenerateDepsFile should honor ReferenceOutputAssembly="false" on ProjectReference

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#1020] opened 2017-03-21 15:17 UTC
### Repo steps
Create a project with a ProjectReference that looks like:

`<ProjectReference Include="..\Library\Library.csproj" ReferenceOutputAssembly="false" />`

`dotnet build` the outer project.

### Expected results
The build should succeed

### Actual results
The build fails

```
C:\Program Files\dotnet\sdk\1.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Cannot find project info for 'F:\DotNetTest\NoCompile\Library\Library.csproj'. This can indicate a missing project reference. [F:\DotNetTest\NoCompile\App\App.csproj]
```

### Notes
We should look for `ReferenceOutputAssembly` metadata on ProjectReferences, and skip them when generating the `deps.json` file.

**Comment by rainersigwald** [comment] 2017-07-14 21:35
Duplicate of #939.

**Closed by rainersigwald** 2017-07-14 21:35 UTC
