### ISSUE TITLE
Regression in the .Net SDK 6.0.302. It fails compiling MvvmGen projects using WPF which compile correctly if you use .Net SDK 6.0.300

### ISSUE THREAD

**Issue by Dragnalith** [dotnet/sdk#26581] opened 2022-07-14 12:46 UTC
### Describe the bug
Regression in the .Net SDK 6.0.302. It fails compiling MvvmGen projects using WPF which compile correctly if you use .Net SDK 6.0.300

### To Reproduce
This [ConsoleApp8.zip](https://github.com/dotnet/sdk/files/9111822/ConsoleApp8.zip) can reproduce the issue

- Install .Net SDK 6.0.300 (you need to uninstall .Net SDK 6.0.302 to install the 6.0.300)
- Install .Net SDK 6.0.302
- Check both SDK are installed using `dotnet --list-sdks`
- Unzip ConsoleApp8.zip (attached to this issue)
- Run `dotnet build ConsoleApp8.sln`
- _Notice compilation fail_
- Modify the global.json file and change the value from `6.0.302` to `6.0.300`
- Run `dotnet build ConsoleApp8.sln`
- _Notice the compilation is successful_

### Further technical details
- I can also reproduce the problem by executing the build through Visual Studio 2022 GUI
- The problem disappear if you remove the `xmlns:local="clr-namespace:MyNamespace"` on MyApp.xaml
- The compilation error looks like:
```
ConsoleApp8\MvvmGen.SourceGenerators\MvvmGen.ViewModelGenerator\MyNamespace.MyViewModel.g.cs(19,22,19,34): error CS0756: A partial method may not have multiple defining declarations
ConsoleApp8\MvvmGen.SourceGenerators\MvvmGen.ViewModelGenerator\MyNamespace.MyViewModel.g.cs(14,16,14,27): error CS0111: Type 'MyViewModel' already defines a member called 'MyViewModel' with the same parameter types
ConsoleApp8\MvvmGen.SourceGenerators\MvvmGen.ViewModelGenerator\MyNamespace.MyViewModel.g.cs(19,22,19,34): error CS0111: Type 'MyViewModel' already defines a member called 'OnInitialize' with the same parameter types
```

**Comment by baronfel** [comment] 2022-07-14 12:52
This is a duplicate of https://github.com/dotnet/sdk/issues/26557 - there was a bug in WPF that has since been fixed and will roll out through the release process. In the meantime, you can pin your SDK to a previous version to work around the behavior.

**Closed by baronfel** 2022-07-14 12:52 UTC
Labels: untriaged, Area-Install

**Comment by deitry** [comment] 2022-07-15 15:17
Is it possible to set version in `global.json` to 6.0.301 or less?

It seems it could be configured only as "<some version> and greater"
https://docs.microsoft.com/en-us/dotnet/core/tools/global-json
