### ISSUE TITLE
Regression in .NET 6 with -p:SelfContained=true

### ISSUE THREAD

**Issue by am11** [dotnet/sdk#16728] opened 2021-04-04 05:14 UTC
### Repro

With .NET 5 on Ubuntu 20.04:
```sh
$ dotnet new console -n myApp; cd myApp
$ dotnet publish -c Release -r linux-x64 -p:'SelfContained=true;PublishSingleFile=true' -o publish
$ ls -R publish
```
outputs:
```sh
publish:
myApp myApp.pdb
```
with .NET 6 (6.0.100-preview.4.21203.4) and `<TargetFramework>net6.0</TargetFramework>` in csproj, it gives:
```sh
publish:
createdump                                         libclrjit.so                  libmscordaccore.so
libSystem.Globalization.Native.so                  libcoreclr.so                 libmscordbi.so
libSystem.IO.Compression.Native.so                 libcoreclrtraceptprovider.so  myApp
libSystem.Native.so                                libdbgshim.so                 myApp.pdb
libSystem.Net.Security.Native.so                   libhostfxr.so
libSystem.Security.Cryptography.Native.OpenSsl.so  libhostpolicy.so
```
it seems, none of these variants have any effect on the output: `-p:SelfContained=true`, `--self-contained`, `--self-contained true` or `--self-contained=true`.

cc @dsplaisted

**Comment by pranavkm** [comment] 2021-04-05 15:50
Likely a dupe of https://github.com/dotnet/sdk/issues/16487

**Comment by am11** [comment] 2021-04-05 20:16
Yup, it is #16487. It is also reproducible in preview 3.

**Closed** 2021-04-05 20:16 UTC
Labels: untriaged
