### ISSUE TITLE
csproj (c#) project to project reference to fsproj (f#)

### ISSUE THREAD

**Issue by mikehaas763** [dotnet/sdk#1567] opened 2017-09-07 03:36 UTC
Maybe this just is an incomplete part of the sdk as of right now. I have started from latest stable .net core (dotnet cli) 2.0.0. I've created a solution, then an f# lib project and a c# console app. They're both added to the solution. I then used the dotnet cli to add a project to project reference to my C# project, pointing to the F# project. However, I can't import the namespace in my C# file. It just can't find the F# namespace. Should this work?

![image](https://user-images.githubusercontent.com/2096573/30144930-35516e00-935c-11e7-8ff7-0354143f91e2.png)

Here's the contents of my csproj file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RxStore.Core\RxStore.Core.fsproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

</Project>
```

**Comment by nguerrera** [comment] 2017-09-12 20:24
cc @KevinRansom

**Comment by DustinCampbell** [comment] 2017-09-12 20:36
This is https://github.com/OmniSharp/omnisharp-vscode/issues/371.

**Comment by nguerrera** [comment] 2017-09-12 20:41
@mikehaas763 To confirm what @DustinCampbell said, is this only happening to you in VS Code or also in Visual Studio? Does `dotnet build` on the command line succeed?

**Comment by cbioley** [comment] 2017-09-21 10:53
Just adding my two cents here, but I do face the same error.

@nguerrera Here is what works fine:

- Visual Studio 2017
- Visual Studio for Mac
- `dotnet build`

Only VS Code (Omnisharp) is having trouble loading the referenced F# project.

```
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        No solution files found in '/Users/cbioley/code/castle-black/src/CastleBlack'
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: /Users/cbioley/code/castle-black/src/CastleBlack/CastleBlack.csproj
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        The target "GetTargetPath" does not exist in the project.
/Users/cbioley/code/castle-black/src/CastleBlack/CastleBlack.csproj

[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Update project: CastleBlack
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Found referenced project outside root directory: /Users/cbioley/code/castle-black/src/CastleBlack.F/CastleBlack.F.fsproj
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: /Users/cbioley/code/castle-black/src/CastleBlack.F/CastleBlack.F.fsproj
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        The target "Compile" does not exist in the project.
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file '/Users/cbioley/code/castle-black/src/CastleBlack.F/CastleBlack.F.fsproj'.
/Users/cbioley/code/castle-black/src/CastleBlack.F/CastleBlack.F.fsproj

[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Unable to resolve project reference '/Users/cbioley/code/castle-black/src/CastleBlack.F/CastleBlack.F.fsproj' for 'CastleBlack'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/cbioley/code/castle-black/src/CastleBlack'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Services.WorkspaceHelper
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Startup
        Configuration finished.
```

**Comment by mikehaas763** [comment] 2017-09-29 22:44
@nguerrera I'll try out my project again this weekend and post back

**Comment by cspaniard** [comment] 2017-10-09 11:41
@mikehaas763 Hi... any updates on this... ? I am having the same problem...

TIA,
David

**Comment by an-dr-eas-k** [comment] 2017-10-11 11:47
I am facing this issue with similar errors, when referencing a managed c++ vcxproj project.

```
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Update project: CsProject
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Found referenced project outside root directory: c:\tmp\cpt\vsCodeCppCs\CppProject\CPTCommon.vcxproj
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: c:\tmp\cpt\vsCodeCppCs\CppProject\CPTCommon.vcxproj
```

It says: `The type or namespace name 'xxx' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by nguerrera** [comment] 2017-10-11 15:36
Closing as duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/371

**Closed by nguerrera** 2017-10-11 15:36 UTC
