### ISSUE TITLE
MSB4242: SDK Resolver Failure due to System.Threading.AbandonedMutexException

### ISSUE THREAD

**Issue by breidikl** [dotnet/sdk#28488] opened 2022-10-11 23:05 UTC
### Describe the bug
Updating our build environment to use .NET 6 SDK 6.0.402 (from 6.0.401) and the associated 6.0.10 runtime packages is now resulting in intermittent failures as follows during dotnet restore calls:

> Name.csproj : error MSB4242: SDK Resolver Failure: "The SDK resolver "NuGetSdkResolver" failed while attempting to resolve the SDK "Office.Build.Before". Exception: "System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
> Name.csproj : error MSB4242: at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout)
> Name.csproj : error MSB4242: at System.Threading.WaitHandle.WaitOne(TimeSpan timeout, Boolean exitContext)
> Name.csproj : error MSB4242: at NuGet.Common.Migrations.MigrationRunner.Run()
> Name.csproj : error MSB4242: at Microsoft.Build.NuGetSdkResolver.NuGetSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)
> Name.csproj : error MSB4242: at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.TryResolveSdkUsingSpecifiedResolvers(IList`1 resolvers, Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio, SdkResult& sdkResult)"

"Name" varies build to build and appears to be a random set of csproj files being restored for each build.  We have not been able to repro when rebuilding the same projects locally for the same environment. 

Using 6.0.401 (with the 6.0.9 runtime packages) did not hit this with everything else in our environment being the same.

### Further technical details
We are currently using MSBuild 17.3.4, and running "dotnet --info" shows the following:

> .NET SDK (reflecting any global.json):
>  Version:   6.0.402
>  Commit:    6862418796
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.22621
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   <trimmedpath>dotnetsdkbootstrapper\sdk\sdk\6.0.402\
> 
> global.json file:
>   <srcpath>\global.json
> 
> Host:
>   Version:      6.0.10
>   Architecture: x64
>   Commit:       5a400c212a
> 
> .NET SDKs installed:
>   3.1.424 [<trimmedpath>dotnetsdkbootstrapper\sdk\sdk]
>   5.0.408 [<trimmedpath>dotnetsdkbootstrapper\sdk\sdk]
>   6.0.402 [<trimmedpath>dotnetsdkbootstrapper\sdk\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 3.1.30 [<trimmedpath>dotnetsdkbootstrapper\sdk\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.17 [<trimmedpath>dotnetsdkbootstrapper\sdk\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.10 [<trimmedpath>dotnetsdkbootstrapper\sdk\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.1.30 [<trimmedpath>dotnetsdkbootstrapper\sdk\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.17 [<trimmedpath>dotnetsdkbootstrapper\sdk\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.10 [<trimmedpath>dotnetsdkbootstrapper\sdk\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.30 [<trimmedpath>dotnetsdkbootstrapper\sdk\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.17 [<trimmedpath>dotnetsdkbootstrapper\sdk\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.10 [<trimmedpath>dotnetsdkbootstrapper\sdk\shared\Microsoft.WindowsDesktop.App]

**Comment by dfederm** [comment] 2022-10-11 23:24
Likely related to: https://github.com/NuGet/NuGet.Client/commit/3c1bf9decc8a114c091a6164c42f524ae2bb1e21 by @kartheekp-ms

**Comment by dfederm** [comment] 2022-10-11 23:26
I believe the solution is to add somethign like this:

```cs
            catch (AbandonedMutexException)
            {
                // Abandoned by another process, we acquired it.
            }
```

`AbandonedMutexException` is seemingly thrown even in some success cases.

**Comment by marcpopMSFT** [comment] 2022-10-12 21:47
@jeffkl

**Comment by jeffkl** [comment] 2022-10-12 21:53
Looks like a bug in our new MigrationRunner code, I will follow up with my team.

**Comment by kartheekp-ms** [comment] 2022-10-13 18:14
NuGet side tracking bug https://github.com/NuGet/Home/issues/12159

**Comment by kartheekp-ms** [comment] 2022-10-14 01:33
@breidikl - Sorry for the inconvenience caused by this bug. 
As a workaround, would it be possible to execute `dotnet nuget --version` before running the restore. In that way we don't hit the race condition that is causing these failures intermittently.

**Comment by marcpopMSFT** [comment] 2022-10-17 16:36
This issue will be tracked with the nuget side issue 12159. Closing for now.

**Closed by marcpopMSFT** 2022-10-17 16:36 UTC
Labels: untriaged, Area-SdkResolvers
