### ISSUE TITLE
 How to build? build.ps1 fails on windows

### ISSUE THREAD

**Issue by mfkl** [dotnet/sdk#11759] opened 2020-05-23 19:33 UTC
Hi,

There appears to be something broken regarding the Chinese localization build generation.

Running `build.cmd` as per https://github.com/dotnet/sdk/blob/master/toolset/Documentation/project-docs/developer-guide.md#windows gives
```
sdk\.dotnet\sdk\5.0.100-preview.6.20266.3\Microsoft.Common.CurrentVersion.targets(3035,5): error MSB3552: Resource file "sdk\artifacts\obj\Debug\Sdks\Microsoft.NET.Build.Extensions\msbuildExtensions\Microsoft\Microsoft.NET.Build.Extensions\tools\Debug\netcoreapp3.1\Microsoft.NET.Build.Extensions.Tasks.xlf\Microsoft.NET.Build.Tasks.Strings.zh-Hans.resx" cannot be found. [sdk\src\Tasks\Microsoft.NET.Build.Extensions.Tasks\Microsoft.NET.Build.Extensions.Tasks.csproj]

sdk\.dotnet\sdk\5.0.100-preview.6.20266.3\Microsoft.Common.CurrentVersion.targets(3035,5): error MSB3552: Resource file "sdk\artifacts\obj\Debug\Sdks\Microsoft.NET.Build.Extensions\msbuildExtensions\Microsoft\Microsoft.NET.Build.Extensions\tools\Debug\netcoreapp3.1\Microsoft.NET.Build.Extensions.Tasks.xlf\Microsoft.NET.Build.Tasks.Strings.zh-Hant.resx" cannot be found. [sdk\src\Tasks\Microsoft.NET.Build.Extensions.Tasks\Microsoft.NET.Build.Extensions.Tasks.csproj]
```

It does seem to fail to process the chinese strings resources for some reason. I couldn't check your CI logs to compare since they are not publicly accessible.

```
sdk\artifacts\obj\Debug\Sdks\Microsoft.NET.Build.Extensions\msbuildExtensions\Microsoft\Microsoft.NET.Build.Extensions\tools\Debug\netcoreapp3.1> ls

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        23/05/2020     20:55                Microsoft.NET.Build.Extensions.Tasks.xlf
-a----        23/05/2020     20:55           3910 Microsoft.NET.Build.Extensions.Tasks.assets.cache
-a----        23/05/2020     20:55           6980 Microsoft.NET.Build.Extensions.Tasks.csproj.FileListAbsolute.txt
-a----        23/05/2020     20:29           4220 Microsoft.NET.Build.Extensions.Tasks.csproj.GenerateResource.cache
-a----        23/05/2020     20:36          90690 Microsoft.NET.Build.Extensions.Tasks.csprojAssemblyReference.cache
-a----        23/05/2020     20:55          26075 Microsoft.NET.Build.Tasks.Strings.cs.resources
-a----        23/05/2020     20:55          27448 Microsoft.NET.Build.Tasks.Strings.de.resources
-a----        23/05/2020     20:55          27022 Microsoft.NET.Build.Tasks.Strings.es.resources
-a----        23/05/2020     20:55          27666 Microsoft.NET.Build.Tasks.Strings.fr.resources
-a----        23/05/2020     20:55          27591 Microsoft.NET.Build.Tasks.Strings.it.resources
-a----        23/05/2020     20:55          31489 Microsoft.NET.Build.Tasks.Strings.ja.resources
-a----        23/05/2020     20:55          28412 Microsoft.NET.Build.Tasks.Strings.ko.resources
-a----        23/05/2020     20:55          28657 Microsoft.NET.Build.Tasks.Strings.pl.resources
-a----        23/05/2020     20:55          26572 Microsoft.NET.Build.Tasks.Strings.pt-BR.resources
-a----        23/05/2020     20:55          24493 Microsoft.NET.Build.Tasks.Strings.resources
-a----        23/05/2020     20:55          35548 Microsoft.NET.Build.Tasks.Strings.ru.resources
-a----        23/05/2020     20:55          26447 Microsoft.NET.Build.Tasks.Strings.tr.resources
```

The `Microsoft.NET.Build.Tasks.Strings.zh-Hans.resources` and `Microsoft.NET.Build.Tasks.Strings.zh-Hant.resources` are missing, but `Microsoft.NET.Build.Tasks.Strings.zh-Hans.resx` is present at `sdk\artifacts\obj\Debug\Sdks\Microsoft.NET.Build.Extensions\msbuildExtensions\Microsoft\Microsoft.NET.Build.Extensions\tools\Debug\netcoreapp3.1\Microsoft.NET.Build.Extensions.Tasks.xlf`.

It appears that the .NET framework build at `sdk\artifacts\obj\Debug\Sdks\Microsoft.NET.Build.Extensions\msbuildExtensions\Microsoft\Microsoft.NET.Build.Extensions\tools\Debug\net472` does generate `.resources` files for the zh-Hant/s rsx.

Building on Linux as a temporary workaround is not currently an option because of https://github.com/dotnet/sdk/issues/11684

**Comment by mfkl** [comment] 2020-06-30 16:04
ping @wli3 it would be great if you could look into this.

**Comment by wli3** [comment] 2020-06-30 20:04
Sorry we have a high volume of deliverables these months. Expect long delay for replying.

**Comment by asumner** [comment] 2020-07-08 11:29
@mfkl @wli3 I got the exactly the same problem but I just solved this by moving the SDK to d:\sdk to get the path shorter and it works!
"\artifacts\obj\Debug\Sdks\Microsoft.NET.Build.Extensions\msbuildExtensions\Microsoft\Microsoft.NET.Build.Extensions\tools\Debug\net472\Microsoft.NET.Build.Extensions.Tasks.xlf\Microsoft.NET.Build.Tasks.Strings.zh-Hant.resx"  is pretty long! perhaps rename or add a note to build from a shorter path.
I have a successful build.
My original path that failed was 267 chrs long
moved to D:\ was 237
Windows max path is 260 chrs.

**Comment by asumner** [comment] 2020-07-08 16:34
@wli3 @mfkl You _may_ want to remove the limit instead of moving the sdk out of your repos path as I did...

"The Windows 10 Anniversary Update finally adds the option to abandon that maximum path length.
There is one caveat. This new setting won’t necessarily work with every application out there, but it will work with most. Specifically, any modern applications should be fine, as should all 64-bit applications."

https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

I can confirm after editing my registry the build works in the long path location (after a machine reboot).

**Comment by wli3** [comment] 2020-10-22 03:53
Looks like the issue is resolved. Closing

**Closed by wli3** 2020-10-22 03:53 UTC
