### ISSUE TITLE
Private dependencies appear in an app's deps.json file

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/sdk#39400] opened 2024-03-11 14:28 UTC
### Describe the bug
The deps.json file contains entries that are development-only and which shouldn't leak into shipping output artifacts.

The [`ExcludeFromCompilation`](https://github.com/dotnet/sdk/blob/ba45654d71b1da7cc139285b312e2f152febc008/src/Tasks/Microsoft.NET.Build.Tasks/DependencyContextBuilder.cs#L866) property exists and checked in multiple places but never gets set. I then noticed that the code that sets it got removed in [Unify more build and publish logic by dsplaisted · Pull Request #3348 · dotnet/sdk (github.com)](https://github.com/dotnet/sdk/pull/3348/files).

This might have worked before and got broken by this change.

### To Reproduce
```xml
<Project Sdk="Microsoft.NET.Sdk">
 
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
 
  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.7.48-alpha" PrivateAssets="all" />
  </ItemGroup>
 
</Project>
```

1. `dotnet new console`
2. Add the PackageReference item from above.
3. `dotnet build`
4. Observe the generated deps.json file in the output directory.
5. Find NerdBank.GitVersioning in the deps.json file.

![image](https://github.com/dotnet/sdk/assets/7412651/1c5ad178-8a4b-45c7-9d5b-5ee11cb18780)

Note that `PrivateAssets` metadata isn't even required on this package reference as the package is marked as `developmentDependency` in its nuspec. This also reproduces with any other development only package, i.e. `Microsoft.DotNet.XliffTasks`. I.e. look at the `dotnet.deps.json` file in the sdk folder. It lists `XliffTasks`. These packages aren't compile or runtime dependencies, they extend the build process.

The loader ignores the empty entry and hence doesn't try to resolve the dependency from disk.

### Further technical details
.NET 8.0.201 SDK

cc @dsplaisted

**Comment by ViktorHofer** [comment] 2024-03-11 14:49
No idea. I saw https://github.com/NuGet/NuGet.Client/commit/3efaf6fb21a5f275b0e7dd3a0f4e48d0b93cc4f3 which made me assume that developmentDependency packages are treated differently. For this issue it doesn't really matter if it's a package with the developmentDependency metadata or if the `PrivateAssets="all"` metadata is explicitly set on the PackageReference. That package dependency shouldn't leak into the deps.json file.

**Comment by Forgind** [comment] 2024-03-28 19:19
@dsplaisted, assigned this to you as it seems that your PR caused this issue. Is there any reason you needed to delete that part? Could we just bring it back?

**Comment by ViktorHofer** [comment] 2024-05-08 14:31
gentle ping @dsplaisted

**Comment by dsplaisted** [comment] 2024-05-17 14:56
I haven't had time to dive into the code and the history to look at this, so let me try to share what I do remember (hopefully accurately).

The behavior of `PrivateAssets="all"` is weird.  It stops the assets from the package from being included in your build output, and from showing up as a package dependency if you pack your project, but if you publish the project then the assets from the package *will* be included in the publish output.  This was the behavior in .NET Core 1.0, and when we realized it around .NET Core 2 or 3 we thought it didn't make much sense, but I think there were some scenarios that relied on this behavior so we didn't want to make a breaking change.  We did add a way to prevent the assets of a package from being included in the publish output, to do this you set `PrivateAssets="all" Publish="false"`.

I'm not sure exactly how this relates to `ExcludeFromCompilation`.  Maybe the assets should be excluded from the deps.json of the build output but not from the publish output (unless `Publish="false"` is specified in which case they should be excluded from both).

What happens if you add `Publish="false"` to the `PackageReference` in the repro?  If NerdBank.GitVersioning is still in the deps.json then, that seems like something we could probably fix without worrying too much about being a breaking change.

We can also consider changing the default behavior of `PrivateAssets="all"` so that it won't include the assets the publish output (or in the deps.json).  That will be a trickier discussion though because we'll have to try to dig up or remember the history of why it works like that and what the scenarios were.  I do think it's more sensible behavior, we would have liked to have made the change back in the 2.x or 3.x days but didn't because we had already shipped the other behavior.

**Comment by Forgind** [comment] 2024-05-17 20:28
I'm a little confused about the PrivateAssets="all" leading to Publish="true" comment—isn't it the reverse? That was what led to https://github.com/dotnet/sdk/issues/39465

**Comment by nkolev92** [comment] 2024-05-17 21:16
DevelopmentDependency in the nuspec is just a hint yeah, you need to manually express that in the XML. 
It's why the development dependency packages when installed through the PM UI or dotnet add package, they end up with: 

```xml
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
```

DevelopmentDependency was implement after everything was shipped, so the metadata was a non-breaking way of changing how it works. 

In fact, when you look at it today, even `runtime` being part of IncludeAssets is questionable.

PrivateAssets by itself, doesn't really make a dependency development only. It only means that it doesn't flow to parents, be it packages or project.
You *can* take compile time & runtime dependencies on a package marked with PrivateAssets. 

As @dsplaisted, the whole experience is a bit weird, since arguably most of the time, when people are using PrivateAssets, they want to use Exclude/Include Assets as well.
TBH, the individual knobs are maybe too powerful. 


> We can also consider changing the default behavior of PrivateAssets="all" so that it won't include the assets the publish output (or in the deps.json)

Same like @Forgind, I actually think it was implemented as PrivateAssets="all" was treated as Publish false. It's what led to https://github.com/dotnet/sdk/issues/8991. 

However, a quick test with 9.0.100-preview.3.24212.42, I see they do get copied.

Did this change at some point?

**Comment by marcpopMSFT** [comment] 2024-05-21 20:26
Triage: So it sounds like PrivateAssets originally meant publish was false but that changed at some point. Should we switch to that behavior intentionally even though it's a breaking change?

So open questions:
What's the current behavior around privateassets and publish?
Would changing the publish behavior be sufficient to remove it from the deps.json?
Would this break customers?

@Forgind can you go through the behavior of private assets and publish and outline the current behaviors?

**Comment by Forgind** [comment] 2024-05-24 22:21
@nkolev92, can you clarify what you did with the 9.0.100-preview.3 SDK that led you to conclude that PrivateAssets="all" no longer automatically includes Publish="false"? I used the 9.0.100-preview.4 SDK and the repro from https://github.com/dotnet/sdk/issues/39465 (the original bug used a global.json to pin to the 6.0 SDK), and I could still reproduce the (perceived) bug, which seems to indicate that it still publishes only if PrivateAssets!="all"

I didn't see a change in the deps.json file with respect to the transitive dependency.

Changing the publishing behavior would mean there'd be an extra assembly in the publish directory. If the expectation is to load it from elsewhere, I could see this breaking customers...though I have to say that I'd find it a bit unusual to want to build with a particular version then use whatever other version happens to be on hand though not impossible. Like if you wanted to use MSBuildLocator to find a version of MSBuild on the customer's computer and use that rather than shipping your own MSBuild to them, that could be a potential time when it would be helpful to not include MSBuild in your publish directory.

**Comment by nkolev92** [comment] 2024-06-01 01:47
Apologies for the delay, in my repro I apparently set `PrivateAssets="true"` instead of all. 
My observations are the same as @Forgind's.
What I'm seeing: 

| PrivateAssets | Publish behavior |
| all | not published |
| literally any other value | published |

Regarding the deps.json, it's the same regardless of whether PrivateAssets is set or not. 

This is inconsistent for sure, since PrivateAssets, ExcludeAssets and IncludeAssets are so granular that you can easily get yourself in a situations where it doesn't really make a lot of sense. 

In theory, when you look at what the compiler sees, deps.json might be correct, since you can take compile and runtime dependencies on something you've marked as PrivateAssets, so it's a dependency you'd need at runtime. 
But if it's a dependency you need, why would you stop it from propagating by setting PrivateAssets all?

Setting ExcludeAssets="runtime" makes it even weirder. It doesn't get published (which is for once, undeniably correct), but it's still in the deps.json.

**Comment by marcpopMSFT** [comment] 2024-06-04 20:31
Triage: If privateassets=all removes the reference from both publish and output, we think it should be safe to remove from the deps.json. Then Publish=true would add it back to the publish folder and the deps.json. 

@nkolev92 does that seem reasonable? Do we need a way for the customer include in the deps.json but not in publish (the example was a plugin architecture where it doesn't bring its own copy of the binary along)? Should we have additional metadata for that on the package references? Dependency=true?

**Comment by dsplaisted** [comment] 2024-06-04 20:46
For what it's worth, I've dug up the original PR where the `Publish` metadata support was added to `PackageReference`: https://github.com/dotnet/sdk/pull/1171

**Closed** 2024-12-18 18:48 UTC
Labels: Area-NetSDK

**Comment by dsplaisted** [comment] 2025-01-21 21:54
Note: this broke in at least one case: https://github.com/dotnet/roslyn/issues/76797

We're not sure how widespread it is, but we may want to roll back the change.  An alternative could be to automatically remove libraries from the deps.json if there aren't any assets associated with those libraries.

**Comment by ericstj** [comment] 2025-01-23 18:41
I wonder if we should be using PrivateAssets to control deps file behavior -- wouldn't ExcludeAssets=runtime be more appropriate?  

PrivateAssets is more about what flows out of a project to folks referencing it, not about what the project's own output is.

**Comment by Forgind** [comment] 2025-01-23 18:45
> I wonder if we should be using PrivateAssets to control deps file behavior -- wouldn't ExcludeAssets=runtime be more appropriate?
> 
> PrivateAssets is more about what flows out of a project to folks referencing it, not about what the project's own output is.

@ericstj, see https://github.com/dotnet/roslyn/issues/76797 and https://github.com/dotnet/sdk/pull/46218

So yes 🙂
