### ISSUE TITLE
`dotnet publish` fails during BrotliCompress Stage

### ISSUE THREAD

**Issue by dantronik-markus** [dotnet/sdk#26126] opened 2022-06-21 11:39 UTC
### Describe the bug
I'm trying to publish my project using dotnet publish, using the following command:
`dotnet publish -c Release IKON_2_0/Server/IKON_2_0.Server.csproj /p:PublishProfile=publish -v d > output.txt`

I'm getting the following output:
[output.txt](https://github.com/dotnet/sdk/files/8948441/output.txt)

here's the .pubxml:
[publish.pubxml.txt](https://github.com/dotnet/sdk/files/8948505/publish.pubxml.txt)

The error message is:
C:\Program Files\dotnet\sdk\6.0.301\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWeb
       Assembly.6_0.targets(614,5): error MSB6006: "C:\Program Files\dotnet" wurde mit dem Code 1 beendet. [C:\Users\Co
       mmander\AppData\Local\Jenkins\.jenkins\workspace\IKON 2 (HETIKON)\IKON_2_0\Client\IKON_2_0.Client.csproj]

### Further technical details
- Include the output of `dotnet --info`
<details>
<summary>dotnet --info </summary>
>dotnet --info
.NET SDK (gemäß "global.json"):
 Version:   6.0.301
 Commit:    43f9b18481

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.301\

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  3.1.416 [C:\Program Files\dotnet\sdk]
  5.0.404 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details> 
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: No IDE, publishing using .NET SDK

**Comment by baronfel** [comment] 2022-06-21 12:13
This is a duplicate of https://github.com/dotnet/sdk/issues/26061, which we have a PR in progress for.

**Closed** 2022-06-21 12:14 UTC
Labels: untriaged
