### ISSUE TITLE
dotnet pack fails using UseArtifactsOutput=true with multi-targeting and global usings

### ISSUE THREAD

**Issue by martincostello** [dotnet/sdk#32675] opened 2023-05-19 11:30 UTC
### Describe the bug

I'm testing out an internal library with .NET 8 preview 4 and `UseArtifactsOutput=true` and `dotnet pack` fails with the following error (as we have treat warnings as errors turned on):

```
[/runner/_work/LambdaWorker/LambdaWorker/src/LambdaWorker/JustEat.LambdaWorker.csproj::TargetFramework=net7.0]
  JustEat.LambdaWorker -> /runner/_work/LambdaWorker/LambdaWorker/artifacts/bin/JustEat.LambdaWorker/release_net6.0/JustEat.LambdaWorker.dll
  JustEat.LambdaWorker -> /runner/_work/LambdaWorker/LambdaWorker/artifacts/bin/JustEat.LambdaWorker/release_net7.0/JustEat.LambdaWorker.dll
  JustEat.LambdaWorker -> /runner/_work/LambdaWorker/LambdaWorker/artifacts/bin/JustEat.LambdaWorker/release_net8.0/JustEat.LambdaWorker.dll
  Successfully created package '/runner/_work/LambdaWorker/LambdaWorker/artifacts/package/release/JustEat.LambdaWorker.8.0.304-preview.293.nupkg'.
Error: /home/runner/.dotnet/sdk/8.0.100-preview.4.23260.5/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(221,5): error NU5118: Warning As Error: File '/runner/_work/LambdaWorker/LambdaWorker/artifacts/obj/JustEat.LambdaWorker/release_net7.0/JustEat.LambdaWorker.GlobalUsings.g.cs' is not added because the package already contains file 'src/LambdaWorker/JustEat.LambdaWorker.GlobalUsings.g.cs' [/runner/_work/LambdaWorker/LambdaWorker/src/LambdaWorker/JustEat.LambdaWorker.csproj]
Error: /home/runner/.dotnet/sdk/8.0.100-preview.4.23260.5/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(221,5): error NU5118: Warning As Error: File '/runner/_work/LambdaWorker/LambdaWorker/artifacts/obj/JustEat.LambdaWorker/release_net8.0/JustEat.LambdaWorker.GlobalUsings.g.cs' is not added because the package already contains file 'src/LambdaWorker/JustEat.LambdaWorker.GlobalUsings.g.cs' [/runner/_work/LambdaWorker/LambdaWorker/src/LambdaWorker/JustEat.LambdaWorker.csproj]
  Successfully created package '/runner/_work/LambdaWorker/LambdaWorker/artifacts/package/release/JustEat.LambdaWorker.8.0.304-preview.293.symbols.nupkg'.
```

dotnet pack seems to be trying to add the same compiler-generating global using files for each TFM to the symbols package and emitting a warning.

### To Reproduce

Pending: I haven't yet worked out what the "magic combination" of factors is that causes this problem to make a simple repro. The repository I'm hitting this with is private so I can't share as-is.

### Exceptions (if any)

None.

### Further technical details

.NET SDK `8.0.100-preview.4.23260.5`

**Comment by ViktorHofer** [comment] 2023-05-19 13:51
@martincostello how do you make NuGet include the C# files into the package?

**Comment by martincostello** [comment] 2023-05-19 13:53
That's the thing - I don't really know 😅

We do have this set in `Directory.Build.props`:

```xml
<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
```

I did try and create a small repro for this before raising the issue, but I couldn't seem to make it play ball and fail.

**Comment by ViktorHofer** [comment] 2023-05-19 13:58
That setting makes sure that symbol files are included but isn't related to C# code. Look for something like:

```
<None Include="..." Pack="true" />
<Content Include="..." PackagePath="..." />
<TfmSpecificPackageFile />
<BuildOutputInPackage />
```

**Comment by martincostello** [comment] 2023-05-19 14:00
The closes to any of those we have is this:

```xml
<PropertyGroup>
  <PackageIcon>package-icon.png</PackageIcon>
  <PackageReadmeFile>README.md</PackageReadmeFile>
</PropertyGroup>
<ItemGroup>
  <None Include="$(MSBuildThisFileDirectory)$(PackageIcon)" Pack="True" PackagePath="" />
  <None Include="$(MSBuildThisFileDirectory)$(PackageReadmeFile)" Pack="True" PackagePath="" />
</ItemGroup>
```

**Comment by ViktorHofer** [comment] 2023-05-19 14:02
That isn't related either. If you want to, you can send me a binlog of the build and I can take a look. Send it to the mail address mentioned in my GH profile page. You can capture a binlog by appending `/bl` to the build command.

**Comment by martincostello** [comment] 2023-05-19 14:03
Sure - I'll send that over shortly.

**Comment by martincostello** [comment] 2023-05-19 14:08
Sent 📬

**Comment by ViktorHofer** [comment] 2023-05-19 15:47
Regarding why source files are included, that's because the `IncludeSource` property is globally passed in:

<img width="212" alt="image" src="https://github.com/dotnet/sdk/assets/7412651/df25af40-d96a-47e3-96ed-a71ae9973118">

**Comment by ViktorHofer** [comment] 2023-05-19 15:55
@nkolev92 @zivkan this appears to be a bug in NuGet's SourceFiles pack feature when using GlobalUsings:

<img width="441" alt="image" src="https://github.com/dotnet/sdk/assets/7412651/55c43d86-f419-4950-92ad-aded84d717c3">

https://github.com/NuGet/NuGet.Client/blob/a05cda05be4d51d155eaf711e776271e187eae47/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L252

The `TargetPath` metadata of all three GlobalUsings source files point to the same location which is why NuGet then complains. What's the expected behavior here and is this actually related to using `UseArtifactsOutput=true`? cc @dsplaisted

**Comment by martincostello** [comment] 2023-05-22 09:03
> Regarding why source files are included, that's because the `IncludeSource` property is globally passed in:

I can't actually find this anywhere in the repo.

**Comment by martincostello** [comment] 2023-05-24 09:39
> I can't actually find this anywhere in the repo.

It's because we call `dotnet pack` with `--include-source` 🤦

**Comment by ViktorHofer** [comment] 2023-05-24 12:13
@martincostello would you mind opening a bug in nuget/nuget.client mentioning the issue when using `--include-source` and `GlobalUsings` with a multi-targeting project? You can include my screenshot from above which displays the issue that the generated global using files have the same target path in the package.

@dsplaisted do you think this is related to the `UseArtifactsOutput` feature at all?

**Comment by martincostello** [comment] 2023-05-24 12:48
I think it's related at least to some degree, as the error only started after I enabled `UseArtifactsOutput`. The commit I have in our repo immediately prior to that still used `--include-source` and was using the .NET 8 preview 4 SDK.

**Comment by dsplaisted** [comment] 2023-05-25 13:46
> @dsplaisted do you think this is related to the `UseArtifactsOutput` feature at all?

Probably, I need to take a look at the binlog.

**Comment by martincostello** [comment] 2023-05-25 15:08
> would you mind opening a bug in nuget/nuget.client

@ViktorHofer That repo doesn't appear to have Issues enabled - is there an alternative one you'd like me to copy this to?

I just tried to create a repro for this, but still failed. The paths don't seem to clash:

![image](https://github.com/dotnet/sdk/assets/1439341/5a9f33a2-2644-4df4-adb2-88936cef0f04)

### Command

```sh
dotnet pack --include-symbols --include-source
```

### `dotnet-sdk-32675.csproj`

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0;net7.0;net8.0</TargetFrameworks>
    <RootNamespace>DotNetSdk32675</RootNamespace>
  </PropertyGroup>
</Project>

```

### `Class1.cs`

```csharp
namespace DotNetSdk32675;

public class Class1
{

}
```

### `Directory.Build.props`

```xml
<Project>
  <PropertyGroup>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <DebugType>embedded</DebugType>
    <Deterministic>true</Deterministic>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <EnablePackageValidation>true</EnablePackageValidation>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <UseArtifactsOutput>true</UseArtifactsOutput>
  </PropertyGroup>
</Project>

```

**Comment by martincostello** [comment] 2023-05-26 08:52
Done: https://github.com/NuGet/Home/issues/12615

**Comment by dsplaisted** [comment] 2023-05-26 17:21
@martincostello In your repro, is the `Directory.Build.props` file in the project folder or in a parent folder?

I looked at this and it looks like it's caused by having the intermediate output path outside of the project folder, which wouldn't be the case if you set `UseArtifactsOutput` and have a `Directory.Build.props` file directly in the project folder.

**Comment by martincostello** [comment] 2023-05-26 17:26
Yes, it's in the root of the repo with the solution file. The layout is something like this:

```
artifacts/
Directory.Build.props
MyProject.sln
src/
  MyProject/
    MyProject.csproj
test/
  MyProject.Tests/
    MyProject.Tests.csproj
```

**Comment by dsplaisted** [comment] 2023-06-27 19:49
Closing this bug as it's tracked by https://github.com/NuGet/Home/issues/12615

**Closed by dsplaisted** 2023-06-27 19:49 UTC
Labels: untriaged, Area-NetSDK
