### ISSUE TITLE
With .NET 6 SDK, run failed for .NET 6 winforms/wpf.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#15226] opened 2021-01-08 07:22 UTC
Repro steps:
Install .NET 6 SDK(6.0.100-alpha.1.21057.10)  from https://github.com/dotnet/installer
Create winforms or wpf(.NET) in CLI and modify *cproj file to update tfm from net5.0-windows to net6.0-windows.
dotnet build and run

**Expected Result**
dotnet run successfully

**Actual Result:**
Below error occurred
![image](https://user-images.githubusercontent.com/65637796/103986108-1f45b000-51c5-11eb-8294-7b287350fd98.png)

Dotnet --info:
.NET SDK (reflecting any global.json):
 Version:   6.0.100-alpha.1.21057.10
 Commit:    87c80e2837

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21057.10\

Host (useful for support):
  Version: 6.0.0-alpha.1.21057.2
  Commit:  81b9558199

.NET SDKs installed:
  6.0.100-alpha.1.21057.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-alpha.1.21057.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-alpha.1.21057.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-alpha.1.21056.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by ryalanms** [comment] 2021-01-09 02:01
WinForms and WPF are working with dotnet-sdk-6.0.100-alpha.1.20560.3-win-x64 but both fail with dotnet-sdk-6.0.100-alpha.1.21056.10-win-x64.  

/cc @merriemcgaw

**Comment by ryalanms** [comment] 2021-01-09 02:21
> 'QualityVaultFrontEnd.exe' (Win32): Loaded 'C:\Program Files (x86)\dotnet\host\fxr\6.0.0-alpha.1.21057.2\hostfxr.dll'. Symbols loaded.
> A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.0-alpha.1.21056.6'.

**Comment by ryalanms** [comment] 2021-01-10 01:46
This is a duplicate of "Windows desktop apps can't be run on 6.0.100-alpha.1.21056.10" (https://github.com/dotnet/sdk/issues/15198) and can be closed.

Regression:

Switch to new Microsoft.DotNet.SharedFramework.Sdk (https://github.com/dotnet/windowsdesktop/pull/909)

Fix: 

Update Arcade and make changes to match previous working runtimeconfig (https://github.com/dotnet/windowsdesktop/pull/1332)

Working version of `Microsoft.WindowsDesktop.App.runtimeconfig.json`: 

```json
{
  "runtimeOptions": {
    "tfm": "net6.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "6.0.0-alpha.1.20561.11",
      "rollForward": "LatestPatch"
    }
  }
}
```

Non-working version: 

```json
{
  "runtimeOptions": {
    "tfm": "net6.0",
    "includedFrameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "6.0.0-alpha.1.21054.6"
      }
    ]
  }
}

**Comment by vdanche** [comment] 2021-01-12 09:36
@ryalanms "Windows desktop apps can't be run on 6.0.100-alpha.1.21056.10" ([#15198](https://github.com/dotnet/sdk/issues/15198)) has been closed, but issues still repro on WPF project on  6.0.100-alpha.1.21060.3(runtime-6.0.0-alpha.1.21059.3).

**Comment by ryalanms** [comment] 2021-01-12 18:54
@jkoritzinsky:  Your fix should have flowed to the SDK by now.  Can you confirm?  Thanks.

**Comment by jkoritzinsky** [comment] 2021-01-12 18:58
I have confirmed that the fix is in .NET SDK version 6.0.100-alpha.1.21062.4.

**Comment by ryalanms** [comment] 2021-01-12 18:59
Thanks.

**Comment by vdanche** [comment] 2021-01-13 09:47
@ryalanms Thanks, today we checked on NET 6 SDK: 6.0.100-alpha.1.21062.16(runtime-6.0.0-alpha.1.21061.20), WPF for net6.0 can run successfully. But for WPF created in CLI, the default tfm is net5.0-windows not net6.0-windows.

**Closed** 2021-01-13 09:56 UTC
Labels: needs triage
