### ISSUE TITLE
[NETSDKE2E] With Net9 preview 6 installed, running `dotnet razor.dll' failed after opening http://localhost:5000 via browser.

### ISSUE THREAD

**Issue by v-shuli1** [dotnet/sdk#41776] opened 2024-06-25 03:31 UTC
Reproduction Steps
1.install net9 preview 6 sdk(9.0.100-preview.6.24324.8) on win11.
2.dotnet new razor
3.dotnet build
4.dotnet bin\Debug\net9.0\razor.dll
5.open http://localhost:5000 via broswer

Expected Result:
The .dll profile execute successfully.
Actual Result:
The .dll profile execute failed.
![image](https://github.com/dotnet/sdk/assets/92559256/e791c395-ff4d-4300-a42e-24f6c6063294)

Log:
C:\Users\v-danche\myrazor>dotnet bin\Debug\net9.0\myrazor.dll
info: Microsoft.Hosting.Lifetime[14]
Now listening on:
http://localhost:5000/
info: Microsoft.Hosting.Lifetime[0]
Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
Content root path: C:\Users\v-danche\myrazor
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
Failed to determine the https port for redirect.
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The file 'myrazor.styles.css.gz' could not be found.
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.get_FileInfo()
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.SendAsync(StaticAssetInvocationContext context)
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The file 'lib/jquery/dist/jquery.min.js.gz' could not be found.
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.get_FileInfo()
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.SendAsync(StaticAssetInvocationContext context)
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The file 'lib/bootstrap/dist/css/bootstrap.min.css.gz' could not be found.
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.get_FileInfo()
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.SendAsync(StaticAssetInvocationContext context)
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The file 'lib/bootstrap/dist/js/bootstrap.bundle.min.js.gz' could not be found.
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.get_FileInfo()
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.SendAsync(StaticAssetInvocationContext context)
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The file 'css/site.css.gz' could not be found.
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.get_FileInfo()
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.SendAsync(StaticAssetInvocationContext context)
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The file 'js/site.js.gz' could not be found.
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.get_FileInfo()
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.SendAsync(StaticAssetInvocationContext context)
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The file 'favicon.ico.gz' could not be found.
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.get_FileInfo()
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.SendAsync(StaticAssetInvocationContext context)
at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)

dotnet --info:
C:\Users\v-shuli1>dotnet --info
.NET SDK:
 Version:           9.0.100-preview.6.24324.8
 Commit:            9941bdf3a6
 Workload version:  9.0.100-manifests.de958006
 MSBuild version:   17.11.0-preview-24318-05+4a45d5633

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.6.24324.8\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      9.0.0-preview.6.24321.8
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  9.0.100-preview.6.24324.8 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.6.24324.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.6.24321.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.6.24322.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by v-xiaofchen** [comment] 2024-06-25 06:36
This issue also repro on Mac OS.
![image](https://github.com/dotnet/sdk/assets/99376012/a332a52e-22dd-4d77-bb04-8e0d1bdc7914)

**Comment by v-jieyan2** [comment] 2024-06-25 06:37
This problem is also reproduced on Win ARM64.
![image](https://github.com/dotnet/sdk/assets/106043919/5fa3fec8-352a-4b3a-ac88-0e96a261f89c)

**Comment by vdanche** [comment] 2024-06-27 06:15
This issue still repro on coherent preview 6 build 9.0.100-preview.6.24325.8

**Comment by mkArtakMSFT** [comment] 2024-06-27 18:06
So it seems that running the project with `dotnet run` without the assembly works. So this doesn't seem to be a blocker.

@adityamandaleeka do you know if this may be a blocker for Aspire ? Is this `dotnet run ....dll` how aspire starts the app?

**Comment by joperezr** [comment] 2024-06-27 18:56
I only tested main CLI scenarios for aspire, but this doesn't seem to be a blocker either. Looks like Aspire AppHost launches projects using `dotnet run --no-build ...` and `dotnet watch ....` and so this seems to be non blocking for Aspire either:

https://github.com/dotnet/aspire/blob/88c5c19567a12e2957e06952bbd9ef7a1a25a20e/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs#L1049-L1067

**Comment by mkArtakMSFT** [comment] 2024-06-27 18:59
@javiercn assigning this to you to tackle when you're back during preview 7.

**Comment by javiercn** [comment] 2024-07-08 14:10
In which scenario are we running the app like `dotnet bin\Debug\net9.0\razor.dll`? During development the app must always run using `dotnet run` or similar functionality provided by the IDE.

In this scenario this is not working because static web assets are not wired up, as they are only wired-up during development. This happened to work in the past for simple apps because the `StaticFiles` middleware will serve the `wwwroot` folder which is all that's needed for these minimal apps.

However, this doesn't work for things like Blazor for example (you can give it a try) because the files aren't part of the wwwroot folder.

Since we've now introduced compression which puts the compressed assets in the the `obj` folder and remaps them to the `wwwroot` folder via static web assets, this scenario won't work, but again, I'll insist in that this didn't work earlier either, it just happened to not fail for this minimal app.

All development scenarios should be based on `dotnet run` or the equivalent gesture by the IDE. Directly running your app via `dotnet <<path-to-dll>>` is not something ASP.NET Core apps support nor something we test against, even if it works in some simple cases.

**Comment by vdanche** [comment] 2024-07-09 09:38
@javiercn Thanks for your explanation. we only tried to open hyperlink after running dotnet bin\Debug\net9.0\razor.dll in below scenario which does not require us to do that. now we understand that it don's support. so we'll close it
![image](https://github.com/dotnet/sdk/assets/65637796/8b484cbd-f4d1-4a39-a817-d5a3a944f9db)

**Closed** 2024-07-09 09:41 UTC
Labels: Bug, Area-AspNetCore
