### ISSUE TITLE
Add ReferencePath to Microsoft.NET.Sdk.props AssemblySearchPaths

### ISSUE THREAD

**Issue by greyb** [dotnet/sdk#2809] opened 2019-01-10 18:38 UTC
AssemblySearchPaths has no ReferencePath, why?

**Comment by nguerrera** [comment] 2019-01-11 23:07
I assume you mean this:

https://github.com/Microsoft/msbuild/blob/3a844ce00a873d8ca6ba0a8abc0c6b64f772d937/src/Tasks/Microsoft.Common.CurrentVersion.targets#L549

We made an effort in the SDK to be very restrictive about which things are included in the search path as many of the classic defaults are very problematic: $(OutDir) is a race condition, GAC and registry are machine-dependent, etc. 

I don't know the history of $(ReferencePath) in the .user file as commented in Common targets, but that seems to be another source of problems if some users use different references than others. 

You can add it to the search path yourself via

``` xml
<PropertyGroup>
  <AssemblySearchPaths>$(AssemblySearchPaths);$(ReferencePath)</AssemblySearchPaths>
</PropertyGroup>
```

Closing as the limited default search paths by default in SDK are by design.

**Closed by nguerrera** 2019-01-11 23:07 UTC
