### ISSUE TITLE
Port "Microsoft.WindowsDesktop.App" to ARM/ARM64 Windows

### ISSUE THREAD

**Issue by tester962** [dotnet/sdk#2916] opened 2019-02-07 15:41 UTC
Hi! I can't find the "Microsoft.WindowsDesktop.App" framework in ARM builds of the SDK.
Can this be added?

**Comment by livarcocc** [comment] 2019-02-07 16:03
Closing as a duplicate of https://github.com/dotnet/core-sdk/issues/405.

**Closed by livarcocc** 2019-02-07 16:03 UTC
