### ISSUE TITLE
.Net SDK 6.0 RC2 Missing error message when dotnet test can't find older, targeted framework

### ISSUE THREAD

**Issue by ArturDorochowicz** [dotnet/sdk#22311] opened 2021-10-25 18:51 UTC
### Describe the bug
When you run `dotnet test` on a test project that references a web project which targets a framework that is not installed, the message that is printed lacks a detailed error message. It says: `Testhost process exited with error: . Please check the diagnostic logs for more information.`   

### To Reproduce
In a Docker volume set up a web project and a referencing test project targeting netcoreapp3.1
```
docker run --rm -it -v net6a:/src -w /src mcr.microsoft.com/dotnet/sdk:3.1
# In container
dotnet new web --name MyProject
dotnet new xunit --name MyProject.Tests  
dotnet add MyProject.Tests reference MyProject
dotnet test MyProject.Tests
# Test passes
exit 
```

Now reuse the volume and try to use .Net SDK 6.0 RC2:
```
docker run --rm -it -v net6a:/src -w /src mcr.microsoft.com/dotnet/sdk:6.0.100-rc.2
# In container
dotnet test MyProject.Tests
```

This fails with:
```
[...]
Microsoft (R) Test Execution Command Line Tool Version 17.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Testhost process exited with error: . Please check the diagnostic logs for more information.

Test Run Aborted.
``` 

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by nohwnd** [comment] 2022-02-01 11:42
@Evangelink  please quickly investigate this to see if there is anything we can do to report the error better. Or if we fixed it since this release. 

@ArturDorochowicz we don't want to download additional runtimes on your behalf, it is not the core responsibility of dotnet test, it adds "invisible" delays and traffic to runs, and makes incorrectly setup tests magically run. We prefer to fail with a reasonable error message, and let dotnet-install scripts handle the acquisition story.

**Comment by Evangelink** [comment] 2022-02-14 18:59
@ArturDorochowicz If you enable diag logs (e.g. `dotnet test MyProject.Tests --diag logs.txt`) you can see that in the logs we say that we cannot find the framework `netcoreapp3.1` (in the logs: `The framework 'Microsoft.AspNetCore.App', version '3.1.0' (x64) was not found.`). This is normal because your projects still target this framework but you updated the docker container to have only `net6`.

I will dig a bit more to understand what's causing the error messages not to be printed to the console (only available in the logs).

**Comment by Evangelink** [comment] 2022-02-16 11:07
@ArturDorochowicz I am closing the issue here as the investigation determined the issue is on vstest side. Please follow https://github.com/microsoft/vstest/issues/3375.

**Closed** 2022-02-16 11:08 UTC
Labels: Area-DotNet Test, untriaged

**Comment by Joe4evr** [comment] 2022-02-21 09:20
@Evangelink 
> you can see that in the logs we say that we cannot find the framework `netcoreapp3.1` (in the logs: `The framework 'Microsoft.AspNetCore.App', version '3.1.0' (x64) was not found.`). This is normal because your projects still target this framework but you updated the docker container to have only `net6`.

We're experiencing a similar problem but in Azure DevOps Pipelines. Using the image `windows-latest` and an explicit step to install .NET SDK 6.0, `dotnet test` keeps failing with
> Testhost process exited with error: It was not possible to find any compatible framework version
> The framework 'Microsoft.NETCore.App', version '6.0.0' was not found.
>   \- The following frameworks were found:
>       3.1.22 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
>       5.0.13 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

6.0 is not listed even though the pipeline step is claiming it was successfully installed.

**Comment by Evangelink** [comment] 2022-02-21 09:35
Do you also have the `Testhost process exited with error: . Please check the diagnostic logs for more information.` error at the end? If you are adding a `dotnet --list-sdks` does it show the version?

**Comment by Joe4evr** [comment] 2022-02-21 09:38
> Do you also have the `Testhost process exited with error: . Please check the diagnostic logs for more information.` error at the end?

Yes, but there's no way to download said logs from the pipeline run.

> If you are adding a `dotnet --list-sdks` does it show the version?

I'll check.

**Comment by Evangelink** [comment] 2022-02-24 09:26
@Joe4evr I have a couple of questions:
1/ You said you have a step that installs dotnet 6 sdk. Are you doing a global installation or local one (e.g. `dotnet-install` or zip extract...)?
2/ In case you have a "local" version of `dotnet`, could you confirm that you are running `dotnet test` with the local `dotnet`?
3/ Are you using disabling the multi-level lookup? (see https://docs.microsoft.com/dotnet/core/tools/dotnet-environment-variables#dotnet_multilevel_lookup)

**Comment by Joe4evr** [comment] 2022-02-24 20:09
> 1/ You said you have a step that installs dotnet 6 sdk. Are you doing a global installation or local one (e.g. `dotnet-install` or zip extract...)?

[Whatever AzDO Pipelines defaults to](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops).
```yaml
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  continueOnError: false
  inputs:
    version: 6.0.200
```

> 2/ In case you have a "local" version of `dotnet`, could you confirm that you are running `dotnet test` with the local `dotnet`?

Not entirely sure how to confirm that. At the very least, when it runs `dotnet restore`, it shows the first-time setup stuff
(`Welcome to .NET 6.0! --------------------- SDK Version: 6.0.200`), but the subsequent `dotnet` tasks don't show that version.

> 3/ Are you using disabling the multi-level lookup? (see https://docs.microsoft.com/dotnet/core/tools/dotnet-environment-variables#dotnet_multilevel_lookup)

"Multi-level Lookup" disabled is the default option, according to the task page.

**Comment by Evangelink** [comment] 2022-02-28 12:42
Sorry for the late reply @Joe4evr. 

It seems like the main problem is a platform/architecture issue. Most likely you are running tests for a code that's targeting x86 so `dotnet test` tries to find a `x86` version but only the `x64` is installed. I am wondering if your issue could be linked to https://github.com/microsoft/azure-pipelines-tasks/issues/15487.

I suspect that after the installation of the v6, if you run `& "C:\Program Files (x86)\dotnet\dotnet" --list-sdks` it won't show the v6 there. I will try to reproduce the issue locally and dig a bit into the task but I will need a couple more days.

**Comment by PiotrKowalski93** [comment] 2023-02-03 14:30
Any news? Same issue

```
Starting: Use .NET 6
==============================================================================
List:
5.0.303
5.0.404
6.0.300
6.0.400
7.0.102
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.207.2
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
Tool to install: .NET Core sdk version 6.0.400.
Found version 6.0.400 in channel 6.0 for user specified version spec: 6.0.400
Version 6.0.400 was not found in cache.
Getting URL to download .NET Core sdk version: 6.0.400.
Detecting OS platform to find correct download package for the OS.

```
