### ISSUE TITLE
Framework references do not flow transitively through project references

### ISSUE THREAD

**Issue by jgoshi** [dotnet/sdk#714] opened 2017-01-23 22:10 UTC
These are a few new ones that we've come across when migrating various projects that are not explicitly stated in the project.json file. But they are implicitly used in the build.

System.Security
System.ComponentModel.DataAnnotations
System.Runtime.Serialization

**Comment by dsplaisted** [comment] 2017-01-23 22:37
The implicitly referenced framework assemblies were based on the ones that had APIs that were part of .NET Standard.  Currently System.IO.Compression and System.Net.Http are disabled due https://github.com/Microsoft/msbuild/issues/1329 (though I think other workarounds we've added since then may mean it's not necessary to disable them anymore).

Where's the list of all the references that the .NET CLI added for project.json?

**Comment by jgoshi** [comment] 2017-01-23 22:50
There could be others, but these are the three I ran across:
System.Security
System.ComponentModel.DataAnnotations
System.Runtime.Serialization

**Comment by livarcocc** [comment] 2017-01-25 06:25
This is weird, this is where we used to add these references for full framework: https://github.com/dotnet/cli/blob/6fcbefa4f7a0016a68d3cda52779298a5cd20837/src/Microsoft.DotNet.ProjectJsonMigration/Microsoft.DotNet.Internal.ProjectModel/Resolution/ProjectDependencyProvider.cs#L55.

The references above are not in the list. The project must be getting them in project.json through some other mechanism that seems to be missing in msbuild. We should try to understand that.

**Comment by livarcocc** [comment] 2017-01-27 02:44
For the DataProtection repo:
1. DataProtection-dev\test\Microsoft.AspNetCore.DataProtection.Test is the failing project
2. It references a project Microsoft.AspNetCore.DataProtection which in turn references System.Xml.dll, System.Xml.Linq.dll, System.Security.dll

For some reason the build is not honoring project reference framework dependencies.

@nguerrera do you have any ideas?

**Comment by nguerrera** [comment] 2017-01-27 06:12
cc @natidea 

I believe we only inject project references with the transitivity feature. I'm not even sure we have a way to discover non-project references.

**Comment by NTaylorMullen** [comment] 2017-01-27 23:15
I believe this can be written off as a duplicate of: https://github.com/dotnet/cli/issues/5494. project.json specifies these framework assemblies directly which enables migrate to properly transition them into their csproj counterparts.

**Comment by natidea** [comment] 2017-02-03 02:10
Closing as a dupe of https://github.com/dotnet/cli/issues/5494

**Closed by natidea** 2017-02-03 02:10 UTC
Labels: Bug, Urgency-Soon
