### ISSUE TITLE
[Aspire]: dotnet watch changing files in a leaf node project causes the entire project hierarchy to process to exit

### ISSUE THREAD

**Issue by davidfowl** [dotnet/sdk#44543] opened 2024-10-31 06:44 UTC
Using the aspire starter project changing the WeatherForecast class should only cause changes to the ApiService but it triggers changes in the entire project graph.

https://github.com/user-attachments/assets/49bb4d43-1c76-429b-a401-1a687dfcbff3

**Comment by tmat** [comment] 2024-10-31 20:30
The problem is that there is a build error. Still shouldn't behave like it does.

**Comment by tmat** [comment] 2024-11-24 17:14
Fixed by  https://github.com/dotnet/sdk/issues/44543

**Closed by tmat** 2024-11-24 17:14 UTC
Labels: Area-Watch, Aspire

**Comment by davidfowl** [comment] 2024-11-24 19:43
@tmat that link is another issue, did you mean to link a pull request?

**Comment by tmat** [comment] 2024-11-24 22:38
@davidfowl Updated link
