### ISSUE TITLE
PublishSingleFile,After run,system error:api-ms-win-crt-runtime-l1-1-0.dll is missing

### ISSUE THREAD

**Issue by xianyun666** [dotnet/sdk#10505] opened 2019-09-20 10:41 UTC
## Steps to reproduce
Run the software
## Expected  behavior
Run successfully

## Actual behavior
system error,api-ms-win-crt-runtime-l1-1-0.dll is missing

## Environment data
windows7 sp1 64bit
Installed KB2533623
Not installed KB2999226

PublishSingleFile,This error will occur.But,--self-contained does not.
I also found that,Found it in my cache directory.
**C:\Users\liu\AppData\Local\Temp\\.net\myApp\hym3u0df.ls0**
There are many files whose filenames begin with 'api-ms'

**Comment by swaroop-sridhar** [comment] 2020-02-20 21:01
Duplicate of https://github.com/dotnet/runtime/issues/13356

**Comment by swaroop-sridhar** [comment] 2020-02-20 21:02
@nguerrera  This is a dup of https://github.com/dotnet/runtime/issues/13356.
There are no plans to support Win7 targets with PublishSingleFile in the near future.

**Closed** 2020-02-20 21:03 UTC
