### ISSUE TITLE
NullableContextOptions error during build

### ISSUE THREAD

**Issue by sebastienros** [dotnet/sdk#3245] opened 2019-05-17 16:19 UTC
Using the latest build of the SDK, since yesterday.

```
C:\Users\Administrator\AppData\Local\Temp\BenchmarksServer\xx1da5ap.ru4\sdk\3.0.100-preview6-011991\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.Compilation.targets(156,10): error MSB4064: The "NullableContextOptions" parameter is not supported by the "Csc" task. Verify the parameter exists on the task, and it is a settable public instance property. [C:\Users\Administrator\AppData\Local\Temp\BenchmarksServer\2hgsxukz.hiy\benchmarks\src\Benchmarks\Benchmarks.csproj]
C:\Users\Administrator\AppData\Local\Temp\BenchmarksServer\xx1da5ap.ru4\sdk\3.0.100-preview6-011991\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.Compilation.targets(120,5): error MSB4063: The "Csc" task could not be initialized with its input parameters.  [C:\Users\Administrator\AppData\Local\Temp\BenchmarksServer\2hgsxukz.hiy\benchmarks\src\Benchmarks\Benchmarks.csproj]
```

**Comment by nguerrera** [comment] 2019-05-20 17:14
Duplicate of aspnet/AspNetCore#10218

https://github.com/dotnet/roslyn/pull/35716 should fix it if bits have flowed. Can you try the latest build?

**Closed by nguerrera** 2019-05-20 17:14 UTC
Labels: blocking-partner

**Comment by sebastienros** [comment] 2019-05-20 17:18
I confirm it works now with `3.0.100-preview6-012016`, thanks
