### ISSUE TITLE
Add Fractions<T> to System.Numerics

### ISSUE THREAD

**Issue by hjrb** [dotnet/sdk#25874] opened 2022-06-06 18:55 UTC
Fractional numbers are important for high precision computing. see https://github.com/danm-de/Fractions for a widely used implementation. That implementation isn't complete and maybe not giving the best precision. Fractions should be a first-class citizen of .NET 7.

**Comment by KalleOlaviNiemitalo** [comment] 2022-06-07 06:49
Seems similar to <https://github.com/dotnet/runtime/issues/21588>.

**Comment by hjrb** [comment] 2022-06-07 10:46
Thank your for the hint. Searching for Fraction – not Rational. So this can be merged.

Von: KalleOlaviNiemitalo ***@***.***>
Datum: Dienstag, 7. Juni 2022 um 08:49
An: dotnet/sdk ***@***.***>
Cc: Reister Hansjoerg (CI/XTE3) ***@***.***>, Author ***@***.***>
Betreff: Re: [dotnet/sdk] Add Fractions<T> to System.Numerics (Issue #25874)

Seems similar to dotnet/runtime#21588<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fruntime%2Fissues%2F21588&data=05%7C01%7Cret2fe%40bosch.com%7C5a398f88e07f44838fab08da4851e5ed%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C637901813827961384%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Z%2F1AMPq6DZL41LDnUji5i7afjAuOf%2F7JXelBD023ob4%3D&reserved=0>.

**Comment by vitek-karas** [comment] 2022-06-29 12:06
Closing as duplicate of https://github.com/dotnet/runtime/issues/21588.

**Closed by vitek-karas** 2022-06-29 12:06 UTC
Labels: untriaged, Area-CLI
