### ISSUE TITLE
upgrade asp.net core targeting framework 4.6.1 from vs2015 to vs2017 - One or more compilation references are missing

### ISSUE THREAD

**Issue by ErezSavir** [dotnet/sdk#958] opened 2017-03-08 12:43 UTC
have upgraded my asp.net core,using project.json and targeting .net framework 4.6.1 on visual studio 2015 to visual studio 2017.

I have multiple projects in the solution where the main application is referencing them by project reference(all of them target net461).

When running the application I get

`One or more compilation references are missing. Possible causes include a missing 'preserveCompilationContext' property under 'buildOptions' in the application's project.json.`
Screenshot:
![11](https://cloud.githubusercontent.com/assets/6003926/23704391/55508f08-040d-11e7-9cdf-88532fa2965d.png)

And my csproj:
[webapp.txt](https://github.com/dotnet/sdk/files/827601/webapp.txt)

I'll try to create a project to see if I can reproduce.

**Comment by livarcocc** [comment] 2017-03-08 17:40
how are you running your project? I would not expect project.json to be referenced at all when running a migrated (csproj) project.

**Comment by ErezSavir** [comment] 2017-03-08 17:43
I have tried via VS2017 and multiple cli version (even tried the nightly alpha build).

Did not understand what you meant by the second statement? can you please explain?

**Comment by livarcocc** [comment] 2017-03-08 17:46
The error message that you pasted above: 
```
One or more compilation references are missing. Possible causes include a missing 'preserveCompilationContext' property under 'buildOptions' in the application's project.json.
```

It mentions properties that exist in project.json and mentions project.json. But my understanding is that you have migrated to csproj.

So, my guess is that you are using a project.json based CLI to run your project. Can you check if you have a global.json file in the root of you repo and if it has a version property in it pointing to preview2 or preview2-1 of the CLI. The property should be under sdk in the global.json.

**Comment by ErezSavir** [comment] 2017-03-08 17:51
I don't have global.json(I deleted the file before the migration). I'm mainly running via visual studio. I assume vs uses it owns tools therefore the version installed is not relevant?(correct me if i'm wrong).
Regardless, I have tried the latest version with the same result(also the same error message)

**Comment by dasMulli** [comment] 2017-03-08 18:31
@livarcocc The "project.json" error message is actually hardcoded in MVC: https://github.com/aspnet/Mvc/blob/rel/1.1.2/src/Microsoft.AspNetCore.Mvc.Razor/Internal/DefaultRoslynCompilationService.cs#L158

**Comment by livarcocc** [comment] 2017-03-09 01:07
cc @mlorbetske

**Comment by mlorbetske** [comment] 2017-03-09 04:37
+ @vijayrkn @dsplaisted it looks like the compilation context hasn't been preserved even though it's set in the project file, any ideas?

cc @Eilon for the hard coded string

**Comment by Eilon** [comment] 2017-03-09 04:56
Derp. I filed https://github.com/aspnet/Mvc/issues/5931 to track it.

**Comment by ErezSavir** [comment] 2017-03-09 07:45
Update - Created a new project from VS template, copied all the source code into the new project and it's working. I don't know why but something in the migration process was :see_no_evil:.
Also, there is no preserveCompilationContext in my csproj anymore. Thoughts?

**Comment by mlorbetske** [comment] 2017-03-09 10:38
@ErezSavir the PreserveCompilationContext flag is set by default to True in Microsoft.NET.Sdk.Web, so it's not required to be present in the project file. Migration likely adds it as this setting is not web specific, but it's not defaulted on the other SDKs

**Comment by mlorbetske** [comment] 2017-03-09 10:39
Sorry, closed by accident

**Comment by nguerrera** [comment] 2017-03-10 15:56
@ErezSavir We still need to track down the migration issue. Can you provide a repro with a project.json project that ends up in this bad state after migration?

**Comment by ErezSavir** [comment] 2017-03-13 08:37
@nguerrera I didn't managed to repro the issue. I can upload the original projects project.json if it would help.

**Comment by nguerrera** [comment] 2017-03-13 15:57
@ErezSavir So, as of now, if you `dotnet migrate` the original project.json, the resulting project works fine?

**Comment by livarcocc** [comment] 2017-03-15 00:00
Since this does not seem to be a problem anymore and we can't repro the issue, I am closing it. Please, re-activate if you run into it again and provide the original project.json that migrated to a bad state.

**Comment by AlexBar** [comment] 2017-05-21 11:06
Looks like I found a way how to reproduce it:
1) Create a new "ClassLibrary2", targets "net461".  
2) Create a new ASP.NET CORE app, targets "net461"
3) Build ClassLibrary2 project into dll 
4) Add reference for web app to this dll
5) Add to some razor page "using ClassLibrary2" (ClassLibrary2 - default namespace for the library)
6) Run web app and you will see this error
"The type or namespace name 'ClassLibrary2' could not be found (are you missing a using directive or an assembly reference?)
+
@using ClassLibrary2

example: [WebApplication1.zip](https://github.com/dotnet/sdk/files/1016852/WebApplication1.zip)

**Comment by sjaase** [comment] 2017-06-21 08:44
This seems related to an issue I had with Visual Studio 2017 when I moved from VS2015.

If you have targetframework = net461 and you have mscorlib.dll in your project folder or subfolders (not bin, obj), you will get the "One or more compilation references are missing" error message.

This can happen if you publish to a folder other than the default bin directory.

If you build using the dotnet cli from the command line, mscorlib.dll needs to be in the root project folder for the issue to appear. If you are using Visual Studio 2017 to build your project, mscorlib.dll can be in any subfolders.

To reproduce it: 
- Create a ASP.NET Core Webapplication in VS2017. 
- Change targetframework to net461
- Create a folder in the project folder e.g. "publish" and put mscorlib.dll in it.
- Build the project (or rebuild if it was built).
- Run the web application and error should appear.

**Comment by dominicrooijackers** [comment] 2017-07-03 18:18
I got the same error message, in my case I had to fully qualify my Model (@model Project.Namespace.Classname) and then it worked. 

Best regards
Dominic Rooijackers

**Comment by GeorgDangl** [comment] 2017-10-20 21:36
I'm encountering the issue with a just-migrated project:
https://github.com/GeorgDangl/xbim-meets-angular

Is there already some workaround available?

**Comment by livarcocc** [comment] 2019-05-08 22:34
We have no plans to continue to change dotnet migrate at this moment. As such, I am going to close this issue.

**Closed by livarcocc** 2019-05-08 22:34 UTC
