### ISSUE TITLE
Dev17 breaks ability to compile some WPF projects

### ISSUE THREAD

**Issue by jaredpar** [dotnet/sdk#18062] opened 2021-06-03 16:38 UTC
Dev17 breaks WPF project builds when project files were using the `Microsoft.Net.Sdk` and manually listing out the XAML files in the project. For example: 

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <!-- few more omitted for brevity -->
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Include="App.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </ApplicationDefinition>
    <Page Include="MainWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

</Project>
```

This approach worked in both Dev15 and Dev16 but breaks in Dev17. I ran into this when migrating VsVim to work on top of Dev17. The break here is subtle because under the hood it's just not passing the `.g.cs` files to the compiler anymore. That means you end up with strange errors like in ability to access controls by name that you designed in a XAML file. If you have purely design XAML then likely you end up with compiling code but strange runtime behavior. 

The repro is a bit involved here so I created a GitHub repo that contains the full code that will reproduce the issue. The `README.md` has instructions. 

https://github.com/jaredpar/Dev17WpfUpgradeIssue

**Comment by dsplaisted** [comment] 2021-06-03 18:10
@ryalanms Can you take a look?

**Comment by dsplaisted** [comment] 2021-06-03 19:40
This may be a dupe of https://github.com/dotnet/wpf/issues/4515

**Comment by jaredpar** [comment] 2021-06-03 20:21
@dsplaisted yes that does look very similar

**Comment by ryalanms** [comment] 2021-06-03 21:01
Yes, this is a duplicate of dotnet/wpf#4515.  Set `ImportFrameworkWinFXTargets` to `true` to temporarily work around it.

**Comment by Nirmal4G** [comment] 2021-06-04 14:28
Here, the root of the problem is where the PBT that ships with Windows Desktop SDK is failing. We should look into that!

**Comment by dsplaisted** [comment] 2021-06-04 15:08
In this case the PBT from the Windows Desktop SDK is not being imported, since the project doesn't specify the SDK or set `UseWPF` to true.  So in the .NET 5 SDK the PDT from full MSBuild was being imported, but the props change in .NET 6 accidentally disabled that.

**Comment by Nirmal4G** [comment] 2021-06-04 15:33
Yeah, found that it was the case. Just now, I was combing through the `binlog`s of the repro project mentioned above. So, we need to preserve the imports of Common targets even if `UseWPF` or the Windows Desktop SDK is not used! IMO, very roundabout way of doing things but fine.

You could use the Desktop SDK (projects using < v5 SDK) or set `UseWPF` to true but I understand that this is very well be a breaking change for existing projects!

**Closed** 2021-06-04 16:01 UTC
Labels: untriaged
