### ISSUE TITLE
.NET 6 preview 7 - Microsoft.NET.Runtime.RuntimeConfigParser.Task sdk not resolved by workload resolver

### ISSUE THREAD

**Issue by mrward** [dotnet/sdk#19189] opened 2021-07-23 09:46 UTC
.NET 6 preview 7 installed from https://github.com/dotnet/installer

```
 dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21372.19
 Commit:    456900dd18

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-preview.7.21372.19/
```

 - 6.0.100-preview.7.21372.19 - Bad
 - 6.0.100-preview.7.21371.16 - OK

The workload resolver seems to fail to resolve the `Microsoft.NET.Runtime.RuntimeConfigParser.Task` sdk.

```
cd /usr/local/share/dotnet

pwd
/usr/local/share/dotnet

grep "Microsoft.NET.Runtime.RuntimeConfigParser.Task" . -r
./sdk-manifests/6.0.100/microsoft.net.sdk.macos/WorkloadManifest.targets:	<Import Project="Sdk.props" Sdk="Microsoft.NET.Runtime.RuntimeConfigParser.Task" Condition="'$(TargetPlatformIdentifier)' == 'macOS'" />
```

The WorkloadManifest.targets file imports this sdk but there does not seem to be any entries in any WorkloadManifest.json file. The .json file from the sdk-manifests/6.0.100/microsoft.net.sdk.macos directory has:

```
{
	"version": "12.0.100-preview.7182",
	"workloads": {
		"macos": {
			"description": "Microsoft macOS SDK for .NET",
			"packs": [
				"Microsoft.macOS.Sdk",
				"Microsoft.macOS.Ref",
				"Microsoft.macOS.Templates"
			],
			"extends": [ 
				"microsoft-net-runtime-mono-tooling"
			]
		}
	},
	"packs": {
		"Microsoft.macOS.Sdk": {
			"kind": "sdk",
			"version": "12.0.100-preview.7182"
		},
		"Microsoft.macOS.Ref": {
			"kind": "framework",
			"version": "12.0.100-preview.7182"
		},
		"Microsoft.macOS.Templates": {
			"kind": "template",
			"version": "12.0.100-preview.7182"
		}
	}
}
```

Current impact is that Visual Studio for Mac cannot load any projects with this .NET 6 preview 7 sdk installed.

**Comment by dsplaisted** [comment] 2021-07-23 17:51
@Redth @jonathanpeppers @rolfbjarne Can you take a look at this?  Is there supposed to be a `Microsoft.NET.Runtime.RuntimeConfigParser.Task` workload pack defined somewhere?

**Comment by jonathanpeppers** [comment] 2021-07-23 18:07
This task is from dotnet/runtime:

* https://github.com/dotnet/runtime/tree/main/src/mono/nuget/Microsoft.NET.Runtime.MonoTargets.Sdk
* https://github.com/dotnet/runtime/blob/main/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Manifest/WorkloadManifest.targets.in
* https://github.com/dotnet/runtime/blob/main/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Manifest/WorkloadManifest.json.in

The mobile workloads use this task through `extends` on Mono's workloads. It converts `runtimeConfig.json` to a binary format that Mono can load at runtime.

**Comment by dsplaisted** [comment] 2021-07-23 18:09
Also @lewing @pjcollins

@mrward It looks like this should be defined in a different WorkloadManifest.json file.  Did you look for it in all of them or just in the MacOS one?

**Comment by pjcollins** [comment] 2021-07-23 18:17
This looks relevant - https://github.com/xamarin/xamarin-macios/commit/f67a47f8a68373cb3d444da1b8e8437583136bb4 - the pack seemingly no longer exists. Maybe there's some sync issue with the combination of maciOS / runtime manifests on disk?

**Comment by mrward** [comment] 2021-07-23 18:21
I grepped from the /usr/local/share/dotnet directory for "Microsoft.NET.Runtime.RuntimeConfigParser.Task" and there was nothing in any WorkloadManifest.json file. The microsoft.net.workload.mono.toolchain WorkloadManifest.json file does not contain this RuntimeConfigParser sdk.

**Comment by mrward** [comment] 2021-07-23 18:26
Deleting the sdk-manifests directory and installing .NET 6 preview 7 (dotnet-sdk-6.0.100-preview.7.21372.19) and the macOS WorkloadManifest.targets file contains:

```
<Project>
	<Import Project="Sdk.props" Sdk="Microsoft.macOS.Sdk" Condition="'$(TargetPlatformIdentifier)' == 'macOS'" />

	<Import Project="Sdk.props" Sdk="Microsoft.NET.Runtime.RuntimeConfigParser.Task" Condition="'$(TargetPlatformIdentifier)' == 'macOS'" />

	<ItemGroup Condition=" '$(TargetFrameworkIdentifier)' == '.NETCoreApp' and $([MSBuild]::VersionGreaterThanOrEquals($(TargetFrameworkVersion), '6.0')) ">
		<SdkSupportedTargetPlatformIdentifier Include="macos" DisplayName="macOS" />
	</ItemGroup>
</Project>

```

**Comment by dalexsoto** [comment] 2021-07-23 18:28
Probably we need a newer version since that was fixed two days ago on our preview 7 bits https://github.com/xamarin/xamarin-macios/commit/543bc83548804ec73b13d5a096b2beff6e1bb601

**Comment by rolfbjarne** [comment] 2021-07-23 19:17
@dalexsoto is correct, this is already fixed in xamarin-macios.

@jonathanpeppers I guess we'll have to bump to a newer workload manifest version in dotnet/installer?

**Comment by jonathanpeppers** [comment] 2021-07-23 20:40
dotnet/installer/preview7 has:

https://github.com/dotnet/installer/blob/895bd58f87ce53409afff9274e82ecb5d48619ee/eng/Versions.props#L166-L170

I can update when we have builds (looks like they are still going).

**Comment by jonathanpeppers** [comment] 2021-07-26 17:52
@mrward I could reproduce the problem with a console app containing:

```xml
<TargetFramework>net6.0-macos</TargetFramework>
```
It seems `$(TargetPlatformIdentifier)` has to be `macos` to hit the issue? I was scared at first that we might have broken any `net6.0` project.

The problem goes away if I install the latest `macos` workload:

```bash
$ sudo dotnet workload install macos --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json --source https://aka.ms/maui-preview/index.json
```

Since we'll be shipping a version with the fix to NuGet.org, is there anything we need to do here? /cc @rolfbjarne

**Comment by mrward** [comment] 2021-07-26 18:03
On the Mac you do not need to specify the framework to be net6.0-macos for this to happen. It happens with every .NET 6 project created from the dotnet cli when it is opened in VS Mac. I am guessing the TargetPlatformMoniker is being set to macOS by default somewhere.

I have a workaround for VS Mac (not yet merged) so if a fix does not make it into .NET 6 preview 7 it is not a big problem for us.

**Comment by rolfbjarne** [comment] 2021-07-27 05:25
If VSMac has a workaround, I think it's fine to not do anything here.

**Comment by dsplaisted** [comment] 2021-07-28 15:37
Looks like this is fixed or will be when we update the baseline manifest in dotnet/installer.  If I'm closing this prematurely, feel free to reopen.

**Closed by dsplaisted** 2021-07-28 15:37 UTC
Labels: Area-MacOS, Area-SdkResolvers, Area-Workloads
