### ISSUE TITLE
Error: CS1703: System.Runtime, Version=4.1.2.0

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/sdk#2116] opened 2018-04-05 23:23 UTC
_From @tarekgh on November 16, 2017 19:42_

_From @Vohuman on November 15, 2017 5:6_

When my MVC.core project tries to open any page, I face with the following error:

> CS1703: An assembly with the same identity 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has already been imported.

I tried to clean Temporary folder and checked about the conflicts within the projects but I found nothing.  

_Copied from original issue: dotnet/corefx#25260_

_Copied from original issue: aspnet/Mvc#7058_

**Comment by nguerrera** [comment] 2018-04-05 23:27
Re-asking my question here. Is this a different issue from the others? Is it fixed already? @joperezr @AlexGhiondea @dsplaisted

**Comment by joperezr** [comment] 2018-04-05 23:29
I believe that this issue would be solved by using VS 15.6.3 or newer. At least the people that were facing this when targeting 4.7.1.

**Comment by nguerrera** [comment] 2018-04-05 23:48
Which bug does this duplicate?

**Comment by nguerrera** [comment] 2018-04-17 22:07
Ping @joperezr Can you link this to a dupe bug or PR so we can track *why* we expect this is fixed. I will close this once we have that.

**Comment by AlexGhiondea** [comment] 2018-04-18 16:28
@nguerrera are you asking about the PR that we did in the SDK to help with the binding redirects issues?

**Comment by nguerrera** [comment] 2018-04-18 17:10
@AlexGhiondea AFAIK, there were many different issues that you guys helped fix in this repo. It's unclear to me which one fixed the symptoms here. I would like to link to a specific PR or issue before closing. I'm not keen on closing a bug based on "I believe that this issue would be solved by using VS 15.6.3 or newer" without linking to the presumed fix or dupe.

**Comment by AlexGhiondea** [comment] 2018-04-18 18:10
@nguerrera I understand. I'll let @joperezr add that link.

**Comment by in10se** [comment] 2018-06-06 14:52
I can confirm that targeting .NET Framework 4.7.1 and using the latest VS2017 (15.8.0 PREVIEW 2.0) fixed the problem for me.

**Comment by livarcocc** [comment] 2018-06-06 16:14
It seems to me like we have lost the root of this issue. Given that we have at least one report of this being fixed, I am going to go ahead and close it. I suggest folks file new separate issues with new repro steps if they run into any related issues.

**Closed by livarcocc** 2018-06-06 16:14 UTC

**Comment by misterspeedy** [comment] 2018-06-20 13:49
I had exactly this issue with a .NET 4.6.2 ASP.NET site and VS 2017 15.7.3.  Started happening after I upgraded to 15.3, went away again when I upgraded to 15.7.4.  No code changes throughout.

**Comment by shashikantn** [comment] 2018-06-26 07:53
I am facing this issue while using .Net4.6.2 with some NetStandard lib(2.0.0 Preview). Is there any way to handle this in VS2013?

@misterspeedy did it solve when you upgraded from 15.7.4? that means, it was still issue 15.7.3 but fixed with 15.7.4?

Thanks In advance.

**Comment by misterspeedy** [comment] 2018-06-26 08:40
@shashikantn Yes, it looked from my one example like 15.7.4 fixed an issue in 15.7.3.

**Comment by misterspeedy** [comment] 2018-06-28 10:30
This issue just came back for me, after a single, unrelated one line code change. (Still using 15.7.4.) I deleted everything below [solution]/obj and the problem went away... for now.  It may also be related to changing between git branches.

**Comment by rcfearn** [comment] 2018-10-17 11:05
I get this error when deploying via Octopus to IIS - I have to "stop" IIS and "start" it rather than "restart" it to clear the issue.
