### ISSUE TITLE
restore/build/publish hanging on .NET > 6.0.401

### ISSUE THREAD

**Issue by ZeroSkill1** [dotnet/sdk#29662] opened 2022-12-25 20:20 UTC
### Describe the bug
Any CLI command involving the restoration of a project will hang on `Determining projects to restore...`
This applies to existing projects as well as completely fresh ones.

### To Reproduce

```
dotnet new console -o test
```
output:
```
Die Vorlage "Konsolen-App" wurde erfolgreich erstellt.

Aktionen nach der Erstellung werden verarbeitet...
Wiederherstellung /home/zeroskill/test/test.csproj:
  Wiederherzustellende Projekte werden ermittelt...
```

This goes on and on while CPU usage rises. It does not finish.
I can however execute the above command on .NET 6.0.401 just fine. Any version higher than that seems to have the same issues.

### Further technical details
```
$ dotnet --info
.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Laufzeitumgebung:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.101/

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  7.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
  ```

**Comment by ZeroSkill1** [comment] 2023-01-13 18:02
The issue persists even with the latest .NET 7 SDK version 7.0.102.

**Comment by ZeroSkill1** [comment] 2023-01-13 18:33
```./dotnet new -o test --debug:disable-project-context```
Same result.

```
DOTNET_CLI_DISABLE_PROJECT_EVAL=true ./dotnet new -o test --debug:disable-project-context
```
Does not have any effect either.

**Comment by baronfel** [comment] 2023-01-13 18:47
The message `Wiederherzustellende Projekte werden ermittelt...` is the `DeterminingProjectsToRestore` message, which comes from NuGet's restore task. Can someone from the @dotnet/nuget-team help triage this?

**Comment by ZeroSkill1** [comment] 2023-01-13 18:52
I don't think it's NuGet necessarily. I just tested some more commands, and it seems like this occurs with every command, including something as simple as `dotnet -h`. As of SDK 7.0.102, the only commands that consistently work are `dotnet` and `dotnet --version`.

**Comment by baronfel** [comment] 2023-01-13 18:55
There's a way to validate that - if you run `dotnet build --no-restore` for example, does the build hang?

**Comment by ZeroSkill1** [comment] 2023-01-13 18:56
It doesn't look like it's doing anything. `dotnet build --no-restore`, even while not being in a project folder, does not output any errors, warnings, or anything.

**Comment by ZeroSkill1** [comment] 2023-01-13 19:05
Huh... I've made an interesting discovery. Running the same commands as the root user solves basically everything. Build works, `-h` prints help, and `dotnet new` successfully creates a new project.

**Comment by ZeroSkill1** [comment] 2023-01-13 19:17
Alright, I have found the root cause of the problems. The absence of `$HOME/.dotnet/7.0.102.dotnetFirstUseSentinel` will cause these issues. Looking at some source code, it seems the file is used to determine whether or not `dotnet` is being run for the first time.

**Comment by baronfel** [comment] 2023-01-13 19:26
Great find! So the root cause was permissions issues on that directory?

**Comment by ZeroSkill1** [comment] 2023-01-13 19:29
It appears during some initialization code, it will create some files, including this `firstUseSentinel`. However, it doesn't seem to be able to create it, even though it *is* able to create `7.0.102.toolpath.sentinel`. I have verified that the `.dotnet` folder has correct ownership settings (same user running .dotnet and full read/write permissions).
Somehow it hangs while trying to create `firstUseSentinel`.

**Comment by ZeroSkill1** [comment] 2023-01-13 20:40
After even more investigation, it looks like it is indeed related to NuGet. [In the DotnetFirstTimeUseConfigurer](https://github.com/dotnet/sdk/blob/main/src/Cli/Microsoft.DotNet.Configurer/DotnetFirstTimeUseConfigurer.cs#L62), [NuGet.Common.Migrations.MigrationRunner.Run()](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/Migrations/MigrationRunner.cs#L14) is called, which appears to handle some kind of logic using Mutexes. I can very clearly see that it is waiting for a mutex by tracing the syscalls of the `dotnet` binary.

**Comment by jeffkl** [comment] 2023-01-13 21:47
@kartheekp-ms what version was the MigrationRunner mutex logic fixed in?

**Closed** 2023-01-13 23:02 UTC
Labels: untriaged, Area-NuGet
