### ISSUE TITLE
Windows Container nanoserver:1809 errors out with self-contained ASP.NET 5 app

### ISSUE THREAD

**Issue by prabh-62** [dotnet/sdk#13784] opened 2020-09-22 13:51 UTC
## Steps to reproduce the issue
- git clone [aspnet5-window-container](https://github.com/prabh-62/aspnet5-window-container)
- `> docker build -t paymentsapp .`
- `> docker run -p 8080:80 paymentsapp` (API successfully runs on http://localhost:8080/api/health)
- Now update [Dockerfile](https://github.com/prabh-62/aspnet5-window-container/blob/master/Dockerfile) and swap base image `nanoserver:2004` with `nanoserver:1809`
```dockerfile
FROM mcr.microsoft.com/windows/nanoserver:2004 AS runtime  //old
```
with
```dockerfile
FROM mcr.microsoft.com/windows/nanoserver:1809 AS runtime ///new
```

- `> docker build -t paymentsapp .`
- `> docker run -p 8080:80 paymentsapp` (API errors out)
```
Failed to map file. CreateFileMappingW(C:\app\PaymentsService.exe) failed with error 5
Failure processing application bundle.
Failed to map bundle file [C:\app\paymentsservice.runtimeconfig.json]
```
![nanoserver-1809-error](https://user-images.githubusercontent.com/13006107/93891145-17ffa280-fcb9-11ea-93bd-7b8eef34d44a.PNG)

## Expected behavior
- Self-contained ASP.NET 5 should work on `nanoserver:1809` base image

## Actual behavior
- Self-contained ASP.NET 5 errors out on `nanoserver:1809` base image

## Additional information
- Self-contained ASP.NET 5 works on `nanoserver:2004` base image

## Output of `docker version`
```
Client: Docker Engine - Community
 Azure integration  0.1.15
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:43:18 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:57:30 2020
  OS/Arch:          windows/amd64
  Experimental:     false
```

## Output of `docker info`
```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.12
 Storage Driver: windowsfilter
  Windows: 
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19041 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows 10 Pro Version 2004 (OS Build 19041.508)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 11.84GiB
 Name: User-dev
 ID: VKKG:XOWC:PWG5:P24F:YDDN:ZDM3:CLXR:NNRV:3BYY:IZKX:KLAY:PZRF
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 61
  System Time: 2020-09-22T09:47:20.0758564-04:00
  EventsListeners: 2
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

Original Thread: https://github.com/dotnet/dotnet-docker/issues/2257

**Comment by MichaelSimons** [comment] 2020-09-23 18:10
Moved to https://github.com/dotnet/sdk because this appears to be an issue with PublishSingleFile on older versions of Nano Server.

**Comment by twgraham** [comment] 2020-11-19 04:44
I'm also experiencing this issue using windows servercore image 1809 build 1518. The single file publish binaries work fine outside of docker.

**Comment by twgraham** [comment] 2020-11-19 09:32
I've found if I run the single file app through powershell, it works fine. e.g.

This works:
```ENTRYPOINT ["powershell.exe", "./my-app.exe"]```

This doesn't work:
```ENTRYPOINT ["my-app.exe"]```

**Comment by hotchkj** [comment] 2021-05-06 14:31
Are there any more details as to what is failing here, or what needs fixing with `PublishSingleFile`? It's going to be a long time yet before 1809 can be moved off e.g. all workloads on Server 2019. As NET consumers more heavily use the single file feature, I would imagine this will become more of a visible problem. I'm also curious as to how the indirection above works around the problem and how reliable that is, given the failure 5 looks suspiciously like Access Denied...

**Comment by anderson-dev** [comment] 2021-07-18 12:51
Is this a clue? When I use jenkins' base windowsservercore-1809 it works but when ran in other windowsservercore-1809(ltsc2019) images it does not. For reference, GitVersion.Portable is a .net 5 app apparently built using publishsinglefile as referenced in https://github.com/GitTools/GitVersion/issues/2681

This works:
```
FROM  jenkins/agent:4.6-2-jdk11-windowsservercore-1809
ENV chocolateyUseWindowsCompression false
RUN iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1')); `
    choco feature disable --name showDownloadProgress; `
    choco install make -y; `
    choco install docker-cli -y;`
    choco install GitVersion.Portable -y
```

This does not:
```
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
ENV chocolateyUseWindowsCompression false
RUN iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1')); `
    choco feature disable --name showDownloadProgress; `
    choco install cmake --installargs "ADD_CMAKE_TO_PATH=System" -y; `
    choco install conan -y; `
    choco install GitVersion.Portable -y
```

**Comment by anderson-dev** [comment] 2021-07-20 19:10
I'm not sure what changed but I had to rebuild my jenkins agent (still same version and container) and now it fails for .net singlefile apps too.

**Comment by hotchkj** [comment] 2022-02-21 15:49
With apologies for the ping, @MichaelSimons who in the MS teams should be investigating this? As it stands the issue is unassigned and looks to be untriaged (but lacks any labels). Thanks in advance for any assistance.

**Comment by MichaelSimons** [comment] 2022-02-24 15:06
@marcpopMSFT - Can you comment on the status of this issue?

**Comment by marcpopMSFT** [comment] 2022-03-16 21:16
@agocke for single file questions

**Comment by agocke** [comment] 2022-03-16 23:10
This was a bug in Windows Server 1809 that is fixed in later versions, and also worked-around in .NET 6. Upgrading to .NET 6 should fix this problem.

**Comment by hotchkj** [comment] 2022-03-17 09:04
@agocke Thanks for the response; given that many workloads cannot yet upgrade from 1809 until Server 2022 is more widely adopted & has passed evaluation by IT teams etc., can you please clarify more on the need to upgrade to NET 6.

Are you saying the creators of the single file executables need to re-build with NET 6? I'm trying to grasp if this is something consumers can fix in the environment, or need an update from each maintainer of affected products.

**Comment by agocke** [comment] 2022-03-17 18:40
I believe there are two options: upgrade from 1809, or rebuild the app with .NET 6.

Please note: .NET 5 is exiting support shortly (May 8, 2022), so rebuilding with .NET 6 is going to be necessary regardless.

**Comment by marcpopMSFT** [comment] 2023-05-24 20:21
Closing as fixed as all supported versions of .NET should have the workaround

**Closed by marcpopMSFT** 2023-05-24 20:21 UTC
Labels: untriaged, Area-SingleFile
