### ISSUE TITLE
Option to Set DOTNET_ROOT in CreateAppHost

### ISSUE THREAD

**Issue by Arthri** [dotnet/sdk#35800] opened 2023-10-01 02:47 UTC
### Is your feature request related to a problem? Please describe.
I have a scenario where I have multiple apps. These apps are guaranteed to run on the same runtime version, so I'd like to make them use one single runtime installation rather than multiple. However, I can not perform a system runtime installation so I install the runtime to a folder above all the apps. But there's one missing link, DOTNET_ROOT. Ideally, I'd like to avoid creating platform-specific shell files which set DOTNET_ROOT then run the app host.

### Describe the solution you'd like
Provide an option to set the default DOTNET_ROOT the app host uses through MSBuild

**Comment by vitek-karas** [comment] 2023-10-02 12:58
This is effectively a duplicate of https://github.com/dotnet/runtime/issues/71282.

One possible workaround is to create a custom native host for the apps which uses different way to determine the "dotnet root". But it requires building a native executable and then either custom logic to determine which app to launch or some SDK hacking to make it use this executable as the apphost.

**Closed by vitek-karas** 2023-10-02 12:58 UTC
Labels: untriaged
