### ISSUE TITLE
[Loc]With .NET 7 SDK, the description about "--disable-build-servers" is unlocalized when running "dotnet build --help" in CLI on locale OS.

### ISSUE THREAD

**Issue by WenJunJi01** [dotnet/sdk#24040] opened 2022-02-21 09:56 UTC
**Environment:** SDK 7.0.100-preview.3.22118.7(runtime-7.0.0-preview.2.22116.9)

**Repro steps:**
1. Install .NET SDK 7.0.100-preview.3.22118.7 on a clean local OS
2. Run "dotnet build --help" in CLI

**Expected Result:**
The output about help description should be unlocalized.

**Actual Result:**
The description about "--disable-build-servers" is unlocalized when running "dotnet build --help" in CLI 
TK:
![image](https://user-images.githubusercontent.com/87680983/154930129-f5895639-49db-4cdd-a68e-f7793145b8f8.png)
SC:
![image](https://user-images.githubusercontent.com/87680983/154930389-690865f7-e446-4a50-8ff0-14b956e3e9a8.png)
JP:
![image](https://user-images.githubusercontent.com/87680983/154930623-3230d63e-7810-4cc8-a764-4e2c83893547.png)
DE:
![image](https://user-images.githubusercontent.com/87680983/154930962-87b87fa1-a9d4-4c89-9d6e-47aa70fd37d3.png)

**Dotnet info**
.NET SDK (varsa global.json dosyasını yansıtır):
 Version:   7.0.100-preview.3.22118.7
 Commit:    332b35cafb

Çalışma Zamanı Ortamı:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-preview.3.22118.7\

Host (useful for support):
  Version: 7.0.0-preview.2.22116.9
  Commit:  793185a239

.NET SDKs installed:
  6.0.200 [C:\Program Files\dotnet\sdk]
  7.0.100-preview.3.22118.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.3.22117.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.2.22116.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.3.22116.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by baronfel** [comment] 2022-02-23 23:03
It seems that this is still untranslated in general: https://github.com/dotnet/sdk/blob/3b684c6ff1464a1b5fa026542e096f74f2ed33a0/src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hans.xlf#L40-L44

It should get taken care of in due time by the localization team.

**Comment by WenJunJi01** [comment] 2022-03-04 09:45
This issue can also repro with .NET 7 Preview 1(7.0.100-preview.1.22110.4) and .NET 7 Preview 2(7.0.100-preview.2.22152.5).
![image](https://user-images.githubusercontent.com/87680983/156739532-a86be5d9-ad79-4803-83da-949a0c8ca292.png)

**Comment by vijayrkn** [comment] 2022-06-14 00:42
Removing websdk label since this is related to the CLI.

**Comment by vdanche** [comment] 2022-09-26 06:16
The issue is fixed on NET7 RC2 SDK
E.g DE
![image](https://user-images.githubusercontent.com/65637796/192205959-3ccbae23-85c2-4623-b796-352f25afdf3d.png)
JP
![image](https://user-images.githubusercontent.com/65637796/192206003-9824c76a-1e34-4285-bbec-84071600db62.png)

**Closed** 2022-09-26 06:21 UTC
Labels: localization, Area-CLI
