### ISSUE TITLE
CreateAppHost failed Unexpectedly - The process must have the UseShellExecute property set to false in order to redirect IO streams

### ISSUE THREAD

**Issue by Webreaper** [dotnet/sdk#19653] opened 2021-08-11 08:16 UTC
## Issue Description: 

Compiling a Blazor Server application using .Net 6 preview 7 results in the following error:

```
/usr/local/share/dotnet/sdk/6.0.100-preview.7.21379.14/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(5,5): Error MSB4018: The "CreateAppHost" task failed unexpectedly.
System.InvalidOperationException: The Process object must have the UseShellExecute property set to false in order to redirect IO streams.
  at System.Diagnostics.Process.StartWithShellExecuteEx (System.Diagnostics.ProcessStartInfo startInfo) [0x00121] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/System/System.Diagnostics/Process.cs:622 
  at System.Diagnostics.Process.Start () [0x00032] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs:2001 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) [0x0001b] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs:2490 
  at Microsoft.NET.HostModel.AppHost.HostWriter.CodeSign (System.String appHostPath) [0x0003b] in <78897ac455df4139ac4b39ad370e5af6>:0 
  at Microsoft.NET.HostModel.AppHost.HostWriter.CreateAppHost (System.String appHostSourceFilePath, System.String appHostDestinationFilePath, System.String appBinaryFilePath, System.Boolean windowsGraphicalUserInterface, System.String assemblyToCopyResorcesFrom, System.Boolean enableMacOSCodeSign) [0x0010d] in <78897ac455df4139ac4b39ad370e5af6>:0 
  at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore () [0x0004e] in <4fff4a87d21946bfabeb7e26e299df67>:0 
  at Microsoft.NET.Build.Tasks.TaskBase.Execute () [0x0002e] in <4fff4a87d21946bfabeb7e26e299df67>:0 
  at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:578 
  at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002b9] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:807  (MSB4018) (Dotnet6Sqlite)
```

The problem appears to happen for any Blazor Server project built with .Net 6 preview 7 (I first saw it in [my project](https://github.com/Webreaper/Damselfly) and then reproduced it in a simpler, [sample project](https://github.com/Webreaper/Dotnet6Sqlite). I attempted to try it with a clean, brand new Blazor Server project created using the .Net 6 preview 7 templates, but was unable to get it to compile due to #19652 (raised separately). 

## Development Environment
- M1 MacBook Pro running Big Sur 11.5 beta
- Visual Studio for Mac v8.10.6 (build 10)
- .Net SDK 6.0.100-preview.7.21379.14 (x64)

**Comment by KalleOlaviNiemitalo** [comment] 2021-08-11 09:31
This seems a duplicate of <https://github.com/dotnet/runtime/issues/55992>, which was fixed in <https://github.com/dotnet/runtime/pull/56010>.

**Comment by Webreaper** [comment] 2021-08-11 09:43
Ah, yes, so it is - I saw another issue about CreateAppHost failures, but it was something different; I didn't see that issue. Reading the comments it looks like it was too late to get into P7, but there's a workaround (use `<UseAppHost>false</>`) so I'll give that a try. Thanks!

**Closed** 2021-08-11 09:45 UTC
Labels: Area-External, untriaged
