### ISSUE TITLE
[Loc]With .NET 7 Preview 3 SDK zip installed on local OS, some garbled characters appear when installing wasm-tools for the first time

### ISSUE THREAD

**Issue by WenJunJi01** [dotnet/sdk#24757] opened 2022-04-08 06:51 UTC
**Environment:** .NET SDK 7.0.100-preview.3.22179.4(runtime-7.0.0-preview.3.22175.4)

**Repro steps:**

1. Set up a clean local OS machine with .NET SDK 7.0.100-preview.3.22179.4 zip installation
2. Run dotnet workload install wasm-tools --source https://pkgs.dev.azure.com/dnceng/public/_packaging/7.0.100-preview.3.22179.4-shipping-1/nuget/v3/index.json

**Expected Result:**
wasm-tools workload install successfully in CLI and strings are localized well.

**Actual Result:**
Some garbled characters appear when installing wasm-tools for the first time.
SC:
![image](https://user-images.githubusercontent.com/87680983/162380014-b7ecc5a4-3fd1-4343-8dc0-abcd6594bfbb.png)
DE:
![image](https://user-images.githubusercontent.com/87680983/162379849-0cd19c60-59e8-4b05-ae1e-e19cfb8e09e9.png)
TK:
![image](https://user-images.githubusercontent.com/87680983/162380242-094f5028-f4f4-47e8-be11-746e98bc2d70.png)

**Note:**
After uninstalling and reinstalling it, the localized characters can be displayed normally.
![image](https://user-images.githubusercontent.com/87680983/162379281-91d1c16d-d6e3-4f63-bb2f-cd642d6435d1.png)

**Dotnet info:**
.NET SDK (gemäß "global.json"):
 Version:   7.0.100-preview.3.22179.4
 Commit:    c48f2c30ee

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\tt\sdk\7.0.100-preview.3.22179.4\

Host (useful for support):
  Version: 7.0.0-preview.3.22175.4
  Commit:  162f83657c

.NET SDKs installed:
  7.0.100-preview.3.22179.4 [C:\tt\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0-preview.3.22178.4 [C:\tt\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0-preview.3.22175.4 [C:\tt\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.3.22177.1 [C:\tt\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by WenJunJi01** [comment] 2022-04-20 08:48
This issue can not repro with .NET 7 Preview 4 from main branch of https://github.com/dotnet/installer
SDK version: 7.0.100-preview.4.22219.19(runtime-7.0.0-preview.4.22217.5)
TK:
![image](https://user-images.githubusercontent.com/87680983/164187536-ce79c1be-efd9-4bd8-bd8c-007dae99bc2f.png)

**Comment by vdanche** [comment] 2022-06-09 06:55
The issue repro again with .net7 preview 5 coherent build-7.0.100-preview.5.22307.18 (runtime- 7.0.0-preview.5.22301.12 )
e.g JP
![image](https://user-images.githubusercontent.com/65637796/172783869-39f3c90c-cca4-4b90-9e8e-0770ede07d86.png)

**Comment by vdanche** [comment] 2022-07-25 08:54
this issue also happens when using dotnet pack for the first time.
JP:
![image](https://user-images.githubusercontent.com/65637796/180738192-b45650c5-fddd-4457-bc4c-a79841f816d6.png)
SC:
![image](https://user-images.githubusercontent.com/65637796/180738086-5202e4ab-d771-4d85-9bdd-cba4294a85a7.png)

**Comment by vdanche** [comment] 2022-08-19 08:13
Also repro on JP on .net 7 RC1 SDK when dotnet build project for the first time.
![image](https://user-images.githubusercontent.com/65637796/185574922-6bf6ddf7-70af-43af-89e9-fbdb871f35bc.png)

**Comment by baronfel** [comment] 2022-08-24 21:21
@vdanche @WenJunJi01 what terminal applications are you using? is this `cmd` shell, powershell, or something else entirely?

**Comment by nagilson** [comment] 2022-08-24 21:28
Confirming this is reproable in the `VS 2022 cmd`

**Comment by vdanche** [comment] 2022-08-25 01:23
> 

It's in cmd

**Comment by vdanche** [comment] 2022-09-26 03:09
Still repro on NET7 RC2 SDK(7.0.100-rc.2.22471.15)
e.g TK
![image](https://user-images.githubusercontent.com/65637796/192186416-5f1399aa-4c6f-4033-b0c2-a5c35033919b.png)

**Comment by v-maylei6** [comment] 2022-11-14 08:51
On the CHS OS, this issue still repro on the latest Dev17.5 preview 2 build(install form main branch), also repro on Dev17.5 preview 1 and Dev17.4 GA.
![image](https://user-images.githubusercontent.com/83049161/201615209-18af36be-688f-486f-b4c4-1f8e279facdb.png)

**Comment by nagilson** [comment] 2022-12-14 00:33
It is quite strange how this could happen. Let's follow up @baronfel tomorrow to see if the fact that it's CMD is of any help.

**Comment by drasticactions** [comment] 2022-12-14 01:23
@nagilson This also happened for me with Powershell Core and CMD; it did not matter which.

**Comment by nagilson** [comment] 2022-12-15 00:40
The first CHCP page is set to 437 for me, but then when we set it manually by using the command `chcp 65001` the symbols become ungarbled. Maybe we can manually force UTF-8 charsets at the beginning of the SDK invocation if `DOTNET_CLI_UI_LANGUAGE` differs.

**Comment by nagilson** [comment] 2023-01-05 00:16
It appears this too is actually a duplicate of https://github.com/dotnet/sdk/issues/8833. Looking into a fix.

**Comment by nagilson** [comment] 2023-01-20 19:35
We expect this to be fixed in preview 1 of .NET 8.

**Comment by vdanche** [comment] 2023-01-29 05:48
> A change has been merged and we expect this to be fixed in preview 1 of .NET 8.

Checked on non-ENU OS(German/Janpanese) with NET SDK 8.0.100-alpha.1.23077.6 installed, this issue not repro. Thanks.
German
![image](https://user-images.githubusercontent.com/65637796/215307509-70c1fd7a-b4e8-4e02-bfb5-12a6e2b44866.png)
Japanese
![image](https://user-images.githubusercontent.com/65637796/215307628-f9f195d5-4ad6-4b2a-863e-a777c3d8f966.png)

**Comment by nagilson** [comment] 2023-01-30 17:23
Heck yeah, thanks for confirming.

**Closed by nagilson** 2023-01-30 17:23 UTC
Labels: Area-CLI

**Comment by vdanche** [comment] 2023-02-02 09:37
@nagilson Currently this issue still repro on 7.0.200. There will be a fix on 7.0.20x, right?

**Comment by nagilson** [comment] 2023-02-02 17:07
7.0.2xx is already closed for changes unfortunately, maybe we can port it to 7.0.300 though, or port it to 7.0.200 next month.

**Comment by vdanche** [comment] 2023-02-07 03:02
> 
ok, Thanks, currently repro on 7.0.300 preview sdk, we'll keep tracking.

**Comment by vdanche** [comment] 2023-02-07 03:03
> 7.0.2xx is already closed for changes unfortunately, maybe we can port it to 7.0.300 though, or port it to 7.0.200 next month.
Ok, Thanks, currently repro on 7.0.300 preview sdk, we'll keep tracking.
