### ISSUE TITLE
IncludeNativeLibrariesForSelfExtract includes XML and other files into output binary

### ISSUE THREAD

**Issue by titanix** [dotnet/sdk#19322] opened 2021-07-26 07:15 UTC
### Description

I'm building a command line tool and want a single executable. Since `PublishSingleFile` does *not* publish a single file (seriously...), I found on the web that the additional `IncludeNativeLibrariesForSelfExtract` property is required.

The project has 4 data files in a `data` folder with property `CopyToOutputDirectory` set to `PreserveNewest`.

#### Issue

The problem is that after publishing (dotnet publish -c Release) half of the data are missing in the `data` folder. In addition, at least one of those file is (the XML one) is actually included in the executable binary instead of being outputted to the file system.

### Step to reproduce

1. Clone the following repository: https://github.com/titanix/BonetCLI
2. Use the following project file instead of the one in the repository:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <Nullable>disable</Nullable>

    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HyperGraph.Core" Version="3.4.0" />
    <PackageReference Include="HyperGraph.Extras" Version="3.4.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="data\ids.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="data\ids.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="data\wiki.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="data\bonet.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```

3. Publish the project (dotnet publish)
4. You can see that `ids.txt` and `ids.xml` are missing from the `data` folder. Looking at the binary content with an hex editor shows that the XML file is included in the executable. While I'm not sure if `ids.txt` is included as well, the binary contains the following two strings: `data/ids.txt` and `data/ids.xml` and it's missing from the data folder, so I guess it included as well in the binary.

### Configuration

Dotnet 5.0.302

Windows 11 (10.0.22000 Build 22000)

x64

**Comment by dsplaisted** [comment] 2021-08-17 21:17
@agocke  @vitek-karas for triage

**Comment by dsplaisted** [comment] 2021-08-17 21:17
Also should we have an Area-SingleFile label or something similar?

**Comment by vitek-karas** [comment] 2021-08-17 22:09
I verified that this reproes even on .NET 6 latest (also targeting net6.0).

Workaround is to add `<ExcludeFromSingleFile>true</ExcludeFromSingleFile>` to each of the data assets. This fixes the issue fully.

Since this app turns on trimming I also tried retargeting to net6.0 which doesn't need `IncludeNativeLibrariesForSelfExtract=true` anymore, since it has superhost even on Windows. It also produces a lot smaller executable (22MB on net6.0 versus 40MB on net5.0). Although it produces trimmer warnings, so it's possible the app is broken (I tried only simple stuff and it worked). These could be issues even in .NET 5 though. That said the default trimmer mode in 6 is much more agressive.

**Comment by vitek-karas** [comment] 2021-08-17 22:14
@dsplaisted I think it would make sense to add single-file area.

**Comment by agocke** [comment] 2021-08-17 23:50
@VSadov Can you take a look?

**Comment by VSadov** [comment] 2021-08-18 20:22
I will take a look. I think it might be by design though. 
IncludeNativeLibraries is basically "include everything". Let me check if we do any filtering of content.

**Comment by vitek-karas** [comment] 2021-08-18 20:46
Well - the repro has 4 data files - 2 get included and 2 are excluded - that is the "weird" part.

**Comment by titanix** [comment] 2021-08-18 23:29
> Well - the repro has 4 data files - 2 get included and 2 are excluded - that is the "weird" part.

This and the fact in one case the type of file (plain txt) is not treated consistently: excluded in two cases, included in one.

**Comment by VSadov** [comment] 2021-08-20 21:25
I was able to repro the issue and here is what I could gather so far:

`IncludeNativeLibrariesForSelfExtract` specifies that the singlefile executable should include native binaries and somehow bundler classifies ids.txt and ids.xml as native binaries. As a result they are included in the executable and extracted upon the start of the app in a temp location. The app expects to see files next to the binary in /data folder and thus crashes.

There is an easy workaround for this behavior - you can force the files not be included by adding `ExcludeFromSingleFile` metadata:

```xml
    <None Update="data\ids.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </None>
    <None Update="data\ids.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </None>
```

**Comment by titanix** [comment] 2021-08-20 21:45
Well I didn't open the issue to solve my the problem on this project in particular (Windows terminal doesn't handle unicode well enough to make it useful there anyway), but because the bug might impact other people.

The issue is clearly that non-binary files are classified as binary (maybe because they contain codepoints outside the BMP) when they shouldn't. Also the behavior is inconsistent in-between platform because it impacts Windows only, which is problematic for portability.

**Comment by VSadov** [comment] 2021-08-20 21:45
Now, we still have an issue of misclassified files. These .txt and .xml files are certainly not native executable files.

The way we detect if a file is a native binary differs depending on the target platform and that explains why this is a Windows-only problem. 
For non-windows targets we check if a file starts with a predefined "magic" sequence, but detection of Windows PE files is slightly different - since we need to figure if a file is a managed assembly anyways, we try opening it in `PEReader` and if that operation does not throw `BadImageFormatException` we conclude that it is a PE file. 

This is as far as I got - my current theory is that `PEReader` does not throw on these files or throws a different exception. 

I am not sure if this code has changed in 6.0, it is also possible that it is something changed on the `PEReader` side (it from `System.Reflection.Metadata`)

**Comment by VSadov** [comment] 2021-08-20 21:51
@titanix - Sure, and thanks for reporting the issue!!  
The workaround is just to make sure you are not blocked while the bug is being investigated/fixed.

**Comment by VSadov** [comment] 2021-08-20 22:57
It looks like these two files are "lucky" enough that `PEReader` does not throw.

In addition to regular PE files `PEReader` supports COFF-only/.OBJ files that do not start with DOS signature ("MZ"). When the signature is not present `PEReader` just tries to parse headers and since we only ask for `CorHeader`, there is a chance that the reader will not throw. 

I think we can check for the DOS signature in addition to seeing that `PEReader` does not throw. That would make PE detection more strict. Such change could technically be compat breaking, although any scenario that would rely on current behavior would seem very artificial.

@vitek-karas @agocke - any thoughts on this?

**Comment by dsplaisted** [comment] 2021-08-20 23:06
I think ideally we wouldn't have to guess what is a native file and what isn't.

**Comment by VSadov** [comment] 2021-08-20 23:17
> I think ideally we wouldn't have to guess what is a native file and what isn't.

There is a possibility of including all files (`IncludeAllContentForSelfExtract`) and excluding individual files (`ExcludeFromSingleFile`). This way it is possible to specify exactly what files to include.

Including just native files was a fairly common scenario when runtime binaries were in that set (coreclr.dll, and such), so a special option exists to pick just native binaries. Now, that runtime is a part of the host, It is a less important option, but it is still supported - at least for cases when an app does include some extra native libraries.

**Comment by vitek-karas** [comment] 2021-08-23 08:26
> I think ideally we wouldn't have to guess what is a native file and what isn't.

If the SDK has such knowledge I would definitely prefer to flow this from the SDK into the bundler. @dsplaisted do you think SDK knows this?

We should always use [`IsNativeBinary`](https://github.com/dotnet/runtime/blob/3d5d26181cd7bc07ea6c6f87710c14ccd043b415/src/installer/managed/Microsoft.NET.HostModel/Bundle/TargetInfo.cs#L74-L77) - it should work on all platforms and uses a much more precise check.

Personally I would be OK making this change - even though it can be considered breaking. If somebody relies on this they can use `global.json` to select a specific version of SDK. We should just list this in the breaking changes list for the next SDK release.

**Comment by VSadov** [comment] 2021-08-23 13:12
IsNativeBinary is not exactly more precise - it can also have false positives.  
Maybe checking both ways is the most reliable, especially since we need to use PEReader to detect if the file has COR header anyways.

**Comment by vitek-karas** [comment] 2021-08-23 14:06
Technically nothing will be precise... we could also add a check that the file extension is `.dll` - I know that technically it can be anything, but in reality nobody would expect the SDK to recognize `my.native` as native library even if it really were.

**Comment by ALIENQuake** [comment] 2023-02-26 08:14
@vitek-karas 
So if I understand the previous replies, currently there is no way to exclude files/folders when using `IncludeAllContentForSelfExtract`? Even by using a custom `Before/AfterTargets` actions?

**Comment by vitek-karas** [comment] 2023-02-27 17:09
@ALIENQuake you sbould be able to add `ExcludeFromSingleFile` metadata to the file in question and it should be included. Do you see different behavior?

**Comment by ALIENQuake** [comment] 2023-02-27 18:41
@vitek-karas Yes:

sample project: https://github.com/ALIENQuake/ConsolePowerShellSDKApp - it uses Microsoft.PowerShell.SDK NuGet.

The folders `ref` and `runtime` are part of NuGet Microsoft.PowerShell.SDK - [List of NuGet Package Folders/Files](https://nuget.info/packages/Microsoft.PowerShell.SDK/7.3.3). I want to get rid of them for the single-file executable. I've tried "Before/AfterTargets" for "Build", "Publish", "BeforePublish", "BeforeBuild", "PrepareForPublish", "GetCopyToOutputDirectoryItems", "CopyFilesToOutputDirectory" etc

Does `ExcludeFromSingleFile` or anything else cover the scenario of excluding files from a single-file executable that is actually part of NuGet package?

**Comment by vitek-karas** [comment] 2023-03-01 15:23
@vsadov might have some ideas.

To be honest, I find the behavior of the PowerShell package weird - why would it copy the ref assemblies to the published output - but that's a different question.

The main reason why your "excludes" don't work is that the items in the `None` item group are file paths to the source of the files, so in your case those would be paths to NuGet cache somewhere. I think one would need to write this such to go over all items in the None item group, look for those with `DestinationSubDirectory=ref` (and similar) and mark those as excluded. But I must admit that my msbuild skills are not up to that level.

**Comment by ALIENQuake** [comment] 2023-04-06 08:48
@titanix FWIW, the problem is gone when using net8.0.

**Comment by agocke** [comment] 2023-04-06 17:33
I'm going to close this. I think the properties @VSadov listed are sufficient, and as a last resort, there's also https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli#post-processing-binaries-before-bundling

**Closed by agocke** 2023-04-06 17:33 UTC
Labels: Bug, Area-SingleFile
