### ISSUE TITLE
FSharp.Core explicit dependency downgraded to implicit one

### ISSUE THREAD

**Issue by Szer** [dotnet/sdk#2724] opened 2018-12-06 08:56 UTC
**Problem:**

If I put explicit dependency on FSharp.Core higher than implicit one (which for 2.1.500 is 4.5.2) it will downgrade it to implicit one no matter what.

**Steps to reproduce**
* Net SDK 2.1.500
* FSproj:
```fsproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup> 
  
  <ItemGroup>
    <PackageReference Include="FSharp.Core" Version="4.5.4" />
  </ItemGroup>

</Project>
```
* useless Program.fs
```fsharp
module A
let a = 1
```
* `dotnet restore` or `dotnet build`
* check `FSharp.Core` version in `obj\project.assets.json`

**Expected**

`FSharp.Core` should restore to explicit version, to `4.5.4`

**Actual**

`FSharp.Core` is being restored to implicit version, to `4.5.2`

**Known workarounds**

* Add `<DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>` to fsproj
* Use VisualStudio 15.9.3 `ctrl-shift-B` (strangely it restores OK)
* Use `Paket`

**Notes**

This behavior is the reason for package degradation warnings in case any other packages require something like `>=4.5.4` or `=4.5.4`

**Comment by baronfel** [comment] 2018-12-06 17:09
I think you have to do `Update="4.5.4"` in this case because the reference is already added for you. That would be another workaround.

**Comment by Pilchie** [comment] 2018-12-06 17:55
Tagging @KevinRansom

**Comment by cartermp** [comment] 2018-12-07 18:50
This is by design; the correct thing to do is what @baronfel mentioned:

```xml
<PackageReference Update="FSharp.Core" Version="4.5.4" />
```

**Comment by livarcocc** [comment] 2018-12-07 18:53
Closing it as by design then.

**Closed by livarcocc** 2018-12-07 18:53 UTC
