### ISSUE TITLE
[NetSDKE2E]Running "dotnet publish -f net7.0" with .net7 rc2 SDK,the output shown contains an invalid character "-".

### ISSUE THREAD

**Issue by v-ainigao** [dotnet/sdk#28022] opened 2022-09-20 02:57 UTC
Environment:  7.0.100-rc.2.22466.28(runtime-7.0.0-rc.2.22464.1)
Repro steps:
1.Install 7.0.100-rc.2.22466.28(runtime-7.0.0-rc.2.22464.1)
2.create a console in cli
3.run"dotnet publish -f net7.0"
Expected:
The output shown doesn't contains an invalid character "-".
Actual:
The output shown contains an invalid character "-".
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/106054229/191155042-fd840952-4356-4d70-8b36-0fa2352d1d9f.png)

dotnet --info
C:\Users\v-jiexu1>dotnet --info
.NET SDK:
Version:   7.0.100-rc.2.22466.28
Commit:    60fdbb471d

Runtime Environment:
OS Name:     Windows
OS Version:  10.0.20348
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\7.0.100-rc.2.22466.28\

Host:
  Version:      7.0.0-rc.2.22464.1
  Architecture: x64
  Commit:       c623d96fe3

.NET SDKs installed:
  7.0.100-rc.2.22466.28 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.2.22464.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.2.22464.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.2.22459.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
Environment variables:
  Not set
global.json file:
  Not found
Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by v-xiaofchen** [comment] 2022-09-20 03:03
The same issue also reproduces on ARM64 OS.

**Comment by nagilson** [comment] 2022-09-20 18:20
@baronfel  Is this the regression you were speaking of in the MSBuild property parser, or does it look like something else?

**Comment by baronfel** [comment] 2022-09-20 18:22
It doesn't look the same to my eyes, can you try and repro/get a binlog?

**Comment by nagilson** [comment] 2022-09-20 18:25
Ok, might be a bit

**Comment by baronfel** [comment] 2022-09-23 14:34
Closing because this was fixed in #28059 - this should be fixed in 7.0.100-rc2 next month as well as the final 7.0.100 release.

**Closed by baronfel** 2022-09-23 14:34 UTC
Labels: Area-CLI

**Comment by vdanche** [comment] 2022-10-12 08:14
The issue fixed on NET7 RTM SDK(7.0.100-rtm.22511.20)
![image](https://user-images.githubusercontent.com/65637796/195288173-74c6d70d-544a-4831-a9f3-21d8c445c611.png)
