### ISSUE TITLE
How to debug "GenerateBundle" task failed unexpectedly

### ISSUE THREAD

**Issue by genifycom** [dotnet/sdk#3728] opened 2019-09-30 15:55 UTC
# Issue Title

dotnet publish xxx.csproj -r win-x64 -c Release /p:PublishSingleFile=true

gives me the following:

C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(809,5): error MSB4018: The "GenerateBundle" task failed unexpectedly. [C:\xxx.csproj]
C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(809,5): error MSB4018: Microsoft.NET.HostModel.AppHost.PlaceHolderNotFoundInAppHostException: Exception of type 'Microsoft.NET.HostModel.AppHost.PlaceHolderNotFoundInAppHostException' was thrown. [C:\xxx.csproj]
C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(809,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.BinaryUtils.SearchAndReplace(MemoryMappedViewAccessor accessor, Byte[] searchPattern, Byte[] patternToReplace, Boolean pad0s) [C:\xxx.csproj]
C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(809,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.BinaryUtils.SearchAndReplace(String filePath, Byte[] searchPattern, Byte[] patternToReplace, Boolean pad0s) [C:\xxx.csproj]
C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(809,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.<>c__DisplayClass3_0.<SetAsBundle>b__0() [C:\xxx.csproj]
C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(809,5): error MSB4018:    at Microsoft.NET.HostModel.RetryUtil.RetryOnIOError(Action func) [C:\xxx.csproj]
C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(809,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.SetAsBundle(String appHostPath, Int64 bundleHeaderOffset) [C:\xxx.csproj]
C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(809,5): error MSB4018:    at Microsoft.NET.HostModel.Bundle.Bundler.GenerateBundle(IReadOnlyList`1 fileSpecs) [C:\xxx.csproj]
C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(809,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateBundle.ExecuteCore() [C:\xxx.csproj]
C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(809,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [C:\xxx.csproj]
C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(809,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\xxx.csproj]
C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(809,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\xxx.csproj]

# General

Would love to be able to provide more info, but how?

Is there a debug publish switch?

**Comment by swaroop-sridhar** [comment] 2019-10-08 20:07
Thanks for reporting the issue @dasMulli, I'll add a version check for 3.0 or later. 
@nguerrera  can you please transfer this issue to SDK repo? I don't have permissions to do the transfer.

**Comment by vitek-karas** [comment] 2019-10-08 20:13
(It already is in SDK - I moved it)

**Comment by pleonex** [comment] 2019-11-13 10:07
I have just ran into this issue because I was compiling a console app against .NET Core 2.1 instead of .NET Core 3.0. Would it be possible to improve the error message so the user has the hint to target .NET Core 3.0 instead of getting an exception?

I am using .NET Core 3.1 preview 2 (`3.1.100-preview2-014569`).

**Comment by taori** [comment] 2020-01-10 13:51
Is this supposed to work now? I am running into this issue with 3.1.100 still

**Comment by vitek-karas** [comment] 2020-01-10 16:45
It seems the PR hasn't been merged due to schedule restrictions: https://github.com/dotnet/sdk/pull/3766
I'll check on it again.

**Closed** 2020-01-30 17:50 UTC

**Comment by jstawski** [comment] 2020-02-05 21:47
Hello, according to #3766 the fix is for version check, but not to the actual issue. I am running into this error on a .NET Core 3.1 Console App. Any other info I can provide?

**Comment by jstawski** [comment] 2020-02-05 22:44
Apparently this was caused by another nuget package. Removing it solved the issue

**Comment by enricobenedos** [comment] 2020-02-07 13:28
I've the same issue `error MSB4018: The "GenerateBundle" task failed unexpectedly. `.
I'm able to compile XX times and then without a valid reason I'm not able to publish the exe anymore. 
Also deleting `bin ` and `obj` nothing change. 
Another strange thing is that after the first broken publish I need administrator permissions to delete bin folder.

**Comment by swaroop-sridhar** [comment] 2020-02-07 20:02
@enricobenedos  Can you please provide mode details about the failure? 
If this is not the TargetFramework check, please file a new issue along with a repro. 
Thanks.

**Comment by swaroop-sridhar** [comment] 2020-02-07 20:03
> Apparently this was caused by another nuget package. Removing it solved the issue

@jstawski  what was the problem caused by including the targets from the nuget package? Was the failure because of duplicate entries passed into GenerateBundle() call?

**Comment by jstawski** [comment] 2020-02-07 22:49
@swaroop-sridhar to tell you the truth, we didn’t investigate further as the package was trivial and not really needed. The package name: StackTraceFormatter.Source.

By the way, this is using Visual Studio for Mac. Furthermore, we have noticed that packages were being duplicated on the IDE, so maybe it was related to that.

**Comment by enricobenedos** [comment] 2020-02-10 07:08
@swaroop-sridhar this is the VS 2019 pop-up error:
```
Publish has encountered an error.
Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 

A diagnostic log has been written to the following location:
"C:\Users\enricobenedos\AppData\Local\Temp\tmp616C.tmp"
```
`.tmp` file content
```
2/10/2020 8:02:07 AM
System.AggregateException: One or more errors occurred. ---> System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<>c__DisplayClass26_0.<IsBuildCompletedSuccessfully>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<DefaultCorePublishStep>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__213.MoveNext()
---> (Inner Exception #0) System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. <---

System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 

===================
```
and with PowerShell the result is the same
```
dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 725.51 ms for C:\Projects\FCSSystem\Supervisore.NET\FCSInstallerGUI\FCSInstallerCore\FCSInstallerCore.csproj.
  Restore completed in 725.48 ms for C:\Projects\FCSSystem\Supervisore.NET\FCSInstallerGUI\FCSInstallerGUI\FCSInstallerGUI.csproj.
  FCSInstallerCore -> C:\Projects\FCSSystem\Supervisore.NET\FCSInstallerGUI\FCSInstallerCore\bin\Release\netcoreapp3.1\FCSInstallerCore.dll
  FCSInstallerGUI -> C:\Projects\FCSSystem\Supervisore.NET\FCSInstallerGUI\FCSInstallerGUI\bin\Release\netcoreapp3.1\win-x64\FCSInstallerGUI.dll
C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(868,5): error MSB4018: The "GenerateBundle" task failed unexpectedly. [C:\Projects\FCSSystem\Supervisore.NET\FCSInstallerGUI\FCSInstallerGUI\FCSInstallerGUI.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(868,5): error MSB4018: System.ArgumentException: Invalid input specification: Found multiple entries with the same BundleRelativePath [C:\Projects\FCSSystem\Supervisore.NET\FCSInstallerGUI\FCSInstallerGUI\FCSInstallerGUI.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(868,5): error MSB4018:    at Microsoft.NET.HostModel.Bundle.Bundler.GenerateBundle(IReadOnlyList`1 fileSpecs) [C:\Projects\FCSSystem\Supervisore.NET\FCSInstallerGUI\FCSInstallerGUI\FCSInstallerGUI.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(868,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateBundle.ExecuteCore() [C:\Projects\FCSSystem\Supervisore.NET\FCSInstallerGUI\FCSInstallerGUI\FCSInstallerGUI.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(868,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [C:\Projects\FCSSystem\Supervisore.NET\FCSInstallerGUI\FCSInstallerGUI\FCSInstallerGUI.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(868,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\Projects\FCSSystem\Supervisore.NET\FCSInstallerGUI\FCSInstallerGUI\FCSInstallerGUI.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(868,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\Projects\FCSSystem\Supervisore.NET\FCSInstallerGUI\FCSInstallerGUI\FCSInstallerGUI.csproj]
```

**Comment by msc4266** [comment] 2020-03-06 10:45
I ran into the same issue. My problem was the "Publish" section in my csproj:
```
<Target Name="PostPublish" AfterTargets="Publish">
   ...
    <Exec Command="xcopy &quot;$(TargetDir)vs-code.code-workspace&quot; &quot;$(PublishDir)&quot; /Y /I" />
  </Target>
```

I simply did not copy the file`vs-code.code-workspace` to my output directory. So, it wasn't there and _PostPublish_ caused trouble.
