### ISSUE TITLE
'Private' metadata is not propagated to transitive dependencies

### ISSUE THREAD

**Issue by sharwell** [dotnet/sdk#1467] opened 2017-08-02 19:33 UTC
### Steps to reproduce

1. Create project **A**
2. Create project **B**, and add a project reference to **A**
3. Create project **C**, and add a project reference to **B**
4. In **C.csproj**, update the project reference to include the `<Private>false</Private>` metadata
5. Build the solution

### Expected results

The build directory for **C** contains **C.dll**, but does not contain **B.dll** or **A.dll**.

### Actual results

The build directory for **C** contains **C.dll** and **A.dll**.

**Comment by nguerrera** [comment] 2017-08-02 20:03
#1366

**Comment by sharwell** [comment] 2017-08-02 20:20
💭 It's hard for me (a user outside the project) to tell if this is a duplicate or not. Even if so it would be good to have a separate test covering the steps I described here.

**Comment by nguerrera** [comment] 2017-08-02 21:37
I will close this as a duplicate of #1366 and add information to use this nice description of the general issue as a test case.

**Closed by nguerrera** 2017-08-02 21:37 UTC
Labels: Bug
