### ISSUE TITLE
_CopyFilesMarkedCopyLocal Issue

### ISSUE THREAD

**Issue by stwolfe** [dotnet/sdk#1448] opened 2017-07-25 01:12 UTC
In Microsoft.Net.SDK project, the copying of files to be copied locally is not respecting the relative directory structure, at least with resource files.

Example Output:

```
Target _CopyFilesMarkedCopyLocal:
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.edm\5.8.2\lib\net40\de\Microsoft.Data.Edm.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.Edm.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.edm\5.8.2\lib\net40\es\Microsoft.Data.Edm.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.Edm.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.edm\5.8.2\lib\net40\fr\Microsoft.Data.Edm.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.Edm.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.edm\5.8.2\lib\net40\it\Microsoft.Data.Edm.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.Edm.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.edm\5.8.2\lib\net40\ja\Microsoft.Data.Edm.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.Edm.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.edm\5.8.2\lib\net40\ko\Microsoft.Data.Edm.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.Edm.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.edm\5.8.2\lib\net40\ru\Microsoft.Data.Edm.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.Edm.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.edm\5.8.2\lib\net40\zh-Hans\Microsoft.Data.Edm.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.Edm.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.odata\5.8.2\lib\net40\de\Microsoft.Data.OData.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.OData.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.odata\5.8.2\lib\net40\es\Microsoft.Data.OData.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.OData.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.odata\5.8.2\lib\net40\fr\Microsoft.Data.OData.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.OData.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.odata\5.8.2\lib\net40\it\Microsoft.Data.OData.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.OData.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.odata\5.8.2\lib\net40\ja\Microsoft.Data.OData.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.OData.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.odata\5.8.2\lib\net40\ko\Microsoft.Data.OData.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.OData.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.odata\5.8.2\lib\net40\ru\Microsoft.Data.OData.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.OData.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.odata\5.8.2\lib\net40\zh-Hans\Microsoft.Data.OData.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.OData.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.odata\5.8.2\lib\net40\zh-Hant\Microsoft.Data.OData.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.OData.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.services.client\5.8.2\lib\net40\de\Microsoft.Data.Services.Client.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.Services.Client.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.services.client\5.8.2\lib\net40\es\Microsoft.Data.Services.Client.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.Services.Client.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.services.client\5.8.2\lib\net40\fr\Microsoft.Data.Services.Client.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.Services.Client.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.services.client\5.8.2\lib\net40\it\Microsoft.Data.Services.Client.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.Services.Client.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.services.client\5.8.2\lib\net40\ja\Microsoft.Data.Services.Client.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.Services.Client.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.services.client\5.8.2\lib\net40\ko\Microsoft.Data.Services.Client.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.Services.Client.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.services.client\5.8.2\lib\net40\ru\Microsoft.Data.Services.Client.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.Services.Client.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\microsoft.data.services.client\5.8.2\lib\net40\zh-Hans\Microsoft.Data.Services.Client.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\Microsoft.Data.Services.Client.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\system.spatial\5.8.2\lib\net40\de\System.Spatial.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\System.Spatial.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\system.spatial\5.8.2\lib\net40\fr\System.Spatial.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\System.Spatial.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\system.spatial\5.8.2\lib\net40\it\System.Spatial.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\System.Spatial.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\system.spatial\5.8.2\lib\net40\ja\System.Spatial.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\System.Spatial.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\system.spatial\5.8.2\lib\net40\ko\System.Spatial.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\System.Spatial.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\system.spatial\5.8.2\lib\net40\ru\System.Spatial.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\System.Spatial.resources.dll".
1>    Copying file from "C:\repos\Edge\.packages\system.spatial\5.8.2\lib\net40\zh-Hans\System.Spatial.resources.dll" to "C:\repos\Edge\.out\bin\managed\Microsoft.Hcs\Release\net462\System.Spatial.resources.dll".
```

You can see the output location does not contain the language directory.   This cause these files to be copied every build to the top level of the output directory.

**Comment by nguerrera** [comment] 2018-01-23 23:00
Duplicate of #1006

**Closed by nguerrera** 2018-01-23 23:00 UTC
