### ISSUE TITLE
Ordering of TFMs in class libraries matters

### ISSUE THREAD

**Issue by 333fred** [dotnet/sdk#712] opened 2017-01-23 20:53 UTC
**Steps**:
1. Create a class library
2. Modify the TFM line to TFMs, put `net461;netstandard1.4`. Save
3. Restore happens as expected.
4. Modify TFMs line to `netstandard1.4;net461`. Save.

**Expected**:
No change

**Actual**:
`net461` vanishes from the dependencies tree (assemblies node is gone), and I'm seeing a broken reference to `NETStandard.Library (1.6.1)` in my NuGet dependencies list. Package Manager output has no errors that I can see. I see the following error in the console:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4057	The target "ResolveComReferencesDesignTime" does not exist in the project.	ClassLibrary3	c:\users\frsilb\documents\visual studio 2017\Projects\ClassLibrary3\ClassLibrary3\ClassLibrary3.csproj	1	
```

**Comment by 333fred** [comment] 2017-01-23 20:55
This is with d15prerel/26120.04, with the SDK and NuGet updates that Matt sent via email.

**Comment by srivatsn** [comment] 2017-01-24 19:16
@natidea can you take a look? Is restore somehow getting messed up?

**Comment by nguerrera** [comment] 2017-01-24 21:16
This does not appear to repro with d15prerel/21624.0 with no manual updates.

**Comment by nguerrera** [comment] 2017-01-24 21:45
Correction: I did see `The target "ResolveComReferencesDesignTime" does not exist in the project` a couple of times, but it disappeared quickly.

Another behavior that I'm definitely seeing is that the Assemblies node seems to be populated based on the first TFM and not the union of TFMs. That looks very similar to https://github.com/dotnet/roslyn-project-system/issues/935 which tracks the same for source files. I don't think that's an SDK issue, though.

I cannot managed to get a broken ref to NETStandard.Library.

**Comment by natidea** [comment] 2017-01-26 04:47
What I have observed is that [`DependenciesSubTreeProviderBase.ProjectSubscriptionService_Changed`](https://github.com/dotnet/roslyn-project-system/blob/3f6c9b9995dde7adffa2044b6a5f97403d6852c7/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesSubTreeProviderBase.cs#L242) is only being called with the first TFM, e.g.:

> ProjectConfiguration: "Debug|AnyCPU|net461"

If this is net461, then the `projectSubscriptionUpdate`->`AssemblyReference` rule contains `AddedItems` corresponding to the Assemblies that need to be added. When it is netstandard1.4, the update only contains `RemovedItems` corresponding to the same assemblies.

The [subscription](https://github.com/dotnet/roslyn-project-system/blob/3f6c9b9995dde7adffa2044b6a5f97403d6852c7/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/DependenciesSubTreeProviderBase.cs#L181) is set up to receive a single `IProjectVersionedValue`, instead of [`ImmutableList<IProjectValueVersions>`](https://github.com/dotnet/roslyn-project-system/blob/3f6c9b9995dde7adffa2044b6a5f97403d6852c7/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/NuGet/NuGetRestorer.cs#L116) which can later be cast to `IEnumerable<IProjectVersionedValue<IProjectSubscriptionUpdate>>` 

Perhaps the original design did not anticipate this behavior of the `AssemblyReference` rule in this case. Though for x-plat projects, the tree should consider updates from every TFM.

/cc @abpiskunov @davkean

**Comment by natidea** [comment] 2017-01-26 08:39
Actually, I think this behavior may be by design. The dependency node is reflecting the active configuration. Though I can't figure out how to switch to a different active configuraton. The Target Framework dropdown is disabled.

**Comment by natidea** [comment] 2017-02-03 02:09
Closing as this is essentially by design at this point given the following known issues:

- The ability to switch active TFMs (and have this reflected in the Solution Explorer) should be fixed with https://github.com/dotnet/roslyn-project-system/issues/800

- Ultimately having the solution explorer reflect information from all TFMs regardless of order should be fixed with https://github.com/dotnet/roslyn-project-system/issues/587

**Closed by natidea** 2017-02-03 02:09 UTC
Labels: Bug, RC3 Known Issue, Urgency-Soon

**Comment by davkean** [comment] 2017-02-03 03:13
@natidea I think you might be confused, that first bug isn't tracking selecting the "active" TFM, it's tracking being able to "target" multiple TFMs from project properties. I don't know of a bug that is tracking selecting the active TFM.

To tackle a few points, the error around ResolveComReferencesDesignTime I'm sure is due to stale design-time builds: https://github.com/dotnet/roslyn-project-system/issues/1426. Though I don't know why we're hitting it in the first place - looks like CPS is doing a build with not all state completely in sync.
