### ISSUE TITLE
Building for desktop shouldn't require a RID

### ISSUE THREAD

**Issue by ericstj** [dotnet/sdk#730] opened 2017-01-26 00:01 UTC
When I build for desktop I see 
```
f:\cli\latest\sdk\1.0.0-rc4-004530\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.RuntimeIdentifierInference.targets(49,5): error : RuntimeIdentifier must be set for .NETFramework executables. Consider RuntimeIdentifier=win7-x86 or RuntimeIdentifier=win7-x64.
```

Why do we force folks to specify a RID?  We should be able to restore and build just fine without a RID for desktop.  That's the precedent set by NuGet 2.  At the very least we should probably be just assuming some RID for desktop if the user hasn't specified one.  Forcing it in the project file is busted.

**Comment by 333fred** [comment] 2017-01-26 00:03
Dupe of https://github.com/dotnet/roslyn-project-system/issues/1333.

**Comment by ericstj** [comment] 2017-01-26 00:06
That's fair, but the targets live here so I thought this would be the place to file the issue.  https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.RuntimeIdentifierInference.targets
/cc @nguerrera @dsplaisted

**Comment by srivatsn** [comment] 2017-01-26 00:14
Both are dupes to another issue in the SDK - https://github.com/dotnet/sdk/issues/357  :)

**Closed by srivatsn** 2017-01-26 00:14 UTC

**Comment by ericstj** [comment] 2017-01-26 16:20
Thanks @srivatsn

**Comment by ericstj** [comment] 2017-01-26 16:21
Ha, and that one is a dup of https://github.com/dotnet/sdk/issues/396
