### ISSUE TITLE
After Multi-Target 'Net6.0-Windows;Net48' Why am I getting this error NETSDK1073: The FrameworkReference 'Microsoft.AspNetCore.App' was not recognized

### ISSUE THREAD

**Issue by garevaul** [dotnet/sdk#28859] opened 2022-11-02 19:02 UTC
Hi,

I am getting this build error for 3 of the projects in the solution. I got this error after I multi-targetted all my Perfectly building net6.0 projects to "net6.0;net48". 

But then except these 3 projects, all the other projects in the solution got build correctly. 

I tried various things which I have mentioned below in this question.

-------------------------
22>    Done building project "GoodbyteOurDllsAndCoderMaster.csproj".
22>  Done executing task "MSBuild" -- FAILED.
22>
22>Done building project "GoodbyteOurDllsAndCoderMaster.csproj" -- FAILED.
22>
22>Build FAILED.
22>
22>C:\Program Files\dotnet\sdk\6.0.402\Sdks\[Microsoft.NET.Sdk](http://microsoft.net.sdk/)\targets\[Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(358,5](http://microsoft.net.sdk.frameworkreferenceresolution.targets%28358%2C5/)): **error NETSDK1073: The FrameworkReference 'Microsoft.AspNetCore.App' was not recognized**
22>    0 Warning(s)
22>    1 Error(s)
22>
22>Time Elapsed 00:00:00.87
========== Build: 19 succeeded, **_3 failed_**, 0 up-to-date, 0 skipped ==========

![image](https://user-images.githubusercontent.com/15125247/199578105-9f018d02-c1a0-4c18-8fae-08d3e2cd12bd.png)

The .csproj file is ......
![image](https://user-images.githubusercontent.com/15125247/199578337-b4719987-add5-41ee-b068-a53ee53d4fc7.png)

Somewhere it was mentioned to use this in the csproj file, but I have not tried it, because I think this should NOT be the solution as it seems like a temporary Hack......
**GenerateErrorForMissingTargetingPacks>false**

I have also tried by Installing the latest Sdk, **'C:\Program Files\dotnet\sdk\6.0.402\Sdks'**

I even tried..........
-Close the project
-Delete the bin and obj folders in the projects
-Reopen the solution
-Open Nuget Console: Tools -> Nuget Package Manager -> Nuget Package Manager Console
-Enter dotnet restore in the command line
**And then tried Compiling. BUT it does not work.**

I even tried this......But it does not help
![image](https://user-images.githubusercontent.com/15125247/199578036-f74916d8-c10a-4eb1-8103-87157d6cd154.png)

**Comment by garevaul** [comment] 2022-11-13 10:57
Hi @shanselman @rainersigwald  

Sorry to bother you guys, but it has been 11 days since this question was posted and it has still not been triaged after @rainersigwald moved it to this correct section (thanks to him for that).

You guys are the big guys I can ask to get a "very much Stuck up ball" rolling.

Please see how you can help me.

Thanx in advance

Regards
@garevaul

**Comment by garevaul** [comment] 2022-11-21 18:27
Hi @marcpopMSFT & @joeloff 

I am not too familiar with how the forums work here. 

But it has been 6 days since I guess the issue was assigned by @marcpopMSFT  to @joeloff and it has been 19 days since the issue was first posted.

Is that a long time, or is that normal ?

Regards
@garevaul

**Comment by baronfel** [comment] 2022-11-21 19:39
Hi @garevaul - the issue is up for triage and will be investigated as the team member currently on triage rotation has time.

**Comment by marcpopMSFT** [comment] 2022-11-21 21:39
@garevaul can you please try setting DisableTransitiveFrameworkReferenceDownloads  to true and see if that helps?  If not, can you provide an https://aka.ms/binlog to investigate further? 

For some reason your application is looking for the aspnet targeting pack which should be installed in the packs directory of your SDK.  The property above should suppress looking for the aspnet targeting pack since you're not doing aspnet development. If that doesn't work, most likely something is off in your install would be my best guess but it's hard to say.

**Comment by garevaul** [comment] 2022-11-22 05:30
Hi @marcpopMSFT 

It does not work with 'DisableTransitiveFrameworkReferenceDownloads>true<' .

I have created the .binlog file, but I do not know where to upload it in a Private way so that only you can see it.

Also, I just saw when I was doing "DotNet MSBuild", it says it is using the latest SDK, but it uses an Older SDK version where it gives an error. Please see the image below. Could that be the reason?

(How can I make 'Visual Studio Build' & 'DotNet command' use the latest (or specific) SDK version GLOBALLY? I read somewhere that the latest SDK is usually used unless otherwise specified in a global.json mentioned somewhere. But I do not have any global.json in any of my project folders.)

![image](https://user-images.githubusercontent.com/15125247/203230622-18da472d-059c-48e8-958c-e55e11b0efec.png)


![image](https://user-images.githubusercontent.com/15125247/203226996-4ef3c03b-1380-41ce-bed7-2ecb0ca76bec.png)

**Comment by garevaul** [comment] 2022-11-23 06:15
Hi @marcpopMSFT 

yes, you are right. I used **Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp'"** and Now it is working fine.

Thanx, a Ton for your help.

But I am still worried about why "dotnet build" command took the '6.0.400' SDK instead of the Latest installed SDK (when the above condition is not given), for the same Project where we have 'FrameworkReference to the ASPNetCore package'.  Is it something how MSBuild works?

As shown in the images above, I came to know of the Older version SDK being taken, only because it gave an error and the error line mentions '6.0.400' SDK.

I searched my entire Computer for global.json files, and It is **Not** there in my projects. 
But I found it in these locations in the C-Drive, which I think should not matter. Also, these found files do not have '6.0.400' SDK in any of them.

Regards
@garevaul 

![image](https://user-images.githubusercontent.com/15125247/203482448-2c753187-0e47-483c-9aa9-a7d9ac1d92f6.png)

**Comment by garevaul** [comment] 2022-11-26 05:45
@marcpopMSFT just informing I have shared the bin logs with your email.

Regards
@garevaul

**Comment by garevaul** [comment] 2022-12-03 02:24
@marcpopMSFT just informing I have shared the bin logs with your email. Please take a peek.

Regards
@garevaul

**Comment by marcpopMSFT** [comment] 2022-12-05 23:04
Sorry, we had a review last week and I didn't have time to look at the binlog. Looking now, the only thing I see in the binlog that's suspicious is MSBuildSDKsPath = C:\Program Files\dotnet\sdk\6.0.400\Sdks.  Do you happen to be setting that value in an evironment variable that's getting picked up?  That value is supposed to be set to a default value in the msbuild.app.config file but that's only in the VS copy but you ran dotnet msbuild which doesn't have that file. So somehow that value is getting set incorrectly. You could try overwriting it with an environment variable as well and see if that solves the issue.

**Comment by garevaul** [comment] 2022-12-06 11:10
@marcpopMSFT 

You are right there is this in my Environment Variables. But can you elaborate on each of these Variables, and when they should be mentioned? Sorry, I am a Self Learner, and so I try to do what I feel could be right. Can you explain them in brief and maybe also point to some articles explaining them?

![image](https://user-images.githubusercontent.com/15125247/205894569-d325f757-1073-4b7d-8711-707a35e7232d.png)


=======================================

Also, can you point me to a couple of articles explaining how "global.json" & "MSBuild.app.config" is used in the Build process?

From what I think I know now, 'global.json' is used by SDK and could be used by Powershell's "Dotnet build" command. I may be wrong. 

And I guess "MSBuild.app.config" may be used by MSBuild and maybe or maybe Not by the "Dotnet build" command. Or is it used by the Visual Studio Instance when doing build? But then when are the settings in "global.json" (which I believe is for each project) taken? Maybe they override all other settings elsewhere (like in "MSBuild.app.config").

Also is "MSBuild.app.config" a single file for the Entire Visual Studio instance. because I searched my entire C-Drive for this file, but could not find it. Is it separate for each project? But I think for each project there is 'global.json'.

I am truly confused. Please enlighten me and help.

Regards
@garevaul

**Comment by rainersigwald** [comment] 2022-12-06 15:42
@garevaul there is no "normal user" scenario where you should ever specify `MSBuildSdksPath`. Please remove that from your system environment variables and then forget that it exists :) (What it does is bypass the normal rules for "how should MSBuild find SDKs when it sees a `<Project Sdk="whatever">` tag and search only in that specific directory, which is not good behavior but is useful sometimes for testing or very-specific tooling scenarios.)

> Also, can you point me to a couple of articles explaining how "global.json" & "MSBuild.app.config" is used in the Build process?

The first hit I got for a search for `global.json` was https://learn.microsoft.com/dotnet/core/tools/global-json, which is a good overview. If you have more questions, please feel free to use docs feedback to ask for clarification.

There's no `MSBuild.app.config`, but for Visual Studio (not `dotnet build`) scenarios, there is an `MSBuild.exe.config` that contains some configuration for MSBuild. It is also something that an end user should not know or care about or modify.

**Comment by garevaul** [comment] 2022-12-06 16:34
@rainersigwald thanx a lot for this beautiful-concise -apt answer which covers all required aspects and absolutely filters the non-essentials.

Thanx a lot to @marcpopMSFT also, for all the help and going out of the way and looking into the bin logs, and also keeping this question active and alive.

One last thing before we close this question;
What is "docs feedback". Is it the one we ask a query directly from within Visual Studio Ide?

Regards
@garevaul

**Comment by rainersigwald** [comment] 2022-12-06 16:37
> What is "docs feedback". Is it the one we ask a query directly from within Visual Studio Ide?

If you scroll to the very bottom of a learn.microsoft.com page, you should see a box like this:

![image](https://user-images.githubusercontent.com/3347530/205969517-b8b524fe-8e38-4076-b58a-26164e025428.png)

Pushing the button on the right "This page" will file a "doc feedback" issue on https://github.com/dotnet/docs/issues (or another docs repo) that will be looked at by the docs team.

**Closed** 2022-12-06 16:44 UTC
Labels: untriaged, Area-NetSDK

**Comment by marcpopMSFT** [comment] 2022-12-06 20:28
Glad we were able to track this one down for you.  Thanks for the added explanations, Rainer.
