### ISSUE TITLE
dotnet workload install produces garbage output on non en-us systems.

### ISSUE THREAD

**Issue by drasticactions** [dotnet/sdk#29231] opened 2022-11-25 11:31 UTC
![image](https://user-images.githubusercontent.com/898335/203975950-d442a9d6-5ac5-4745-ab07-3a3eafbd22b1.png)

My system is a freshly installed Windows 11, with an installation of Visual Studio 2022 17.5 Preview 1. Windows 11 and Visual Studio are set to run in ja-jp (Japanese). dotnet 7 was installed through Visual Studio. I wanted to install the other workloads, so I dropped into CLI and ran the workload installer (`dotnet workload install ios (etc. etc.)`) and when it hit the installer, it switched to garbage output. I'm assuming it is using ASCII or some other kind of encoding?

When I reran the command in the same prompt, it worked fine. If I close and reopen the prompt, it fails. This happens in cmd and Powershell. It also only seems to affect the workload install screen.

dotnet info:

```
PS C:\Windows> dotnet --info
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

ランタイム環境:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
 ```

**Comment by nagilson** [comment] 2022-12-14 00:31
This is a duplicate of https://github.com/dotnet/sdk/issues/24757

**Closed by nagilson** 2022-12-14 00:31 UTC
Labels: untriaged, Area-Workloads
