### ISSUE TITLE
`dotnet test` loses `/p:Property=Value` command line arguments at SDK 7.0.100

### ISSUE THREAD

**Issue by SteveGilham** [dotnet/sdk#29066] opened 2022-11-14 21:57 UTC
### Describe the bug
At most one custom property value makes its way into the MSBuild environment from the `dotnet test` command line.

### To Reproduce
With SDK 7.0.100 active do
```
dotnet new mstest
dotnet build
dotnet test -p:AltCover=true "-p:AltCoverAssemblyFilter=nunit|Adapter|FSharp|AltCover" -p:AltCoverReportFormat=OpenCover -p:AltCoverShowStatic=- -p:AltCoverShowSummary=Green -p:AltCoverForce=true -p:AltCoverImportModule=true -p:AltCoverGetVersion=true --verbosity diag "" --configuration Debug
```
The actual properties/values, and the exact tests don't matter, we just want a bunch of the former and something to invoke `dotnet test` with.

The output starts
```
C:\Program Files\dotnet\sdk\7.0.100\MSBuild.dll -nologo -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\7.0.100\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\7.0.100\dotnet.dll -maxcpucount -nodereuse:false -property:Configuration=Debug -p:AltCover=true -property:VSTestArtifactsProcessingMode=collect -property:VSTestSessionCorrelationId=3100_d13a1c5b-80eb-44c7-a816-59a79777ef5a -restore -target:VSTest -verbosity:m -verbosity:diag .\_issue.csproj
Build started 14/11/2022 22:31:11.
Environment at start of build:
DOTNET_CLI_TELEMETRY_SESSIONID = b21d3f17-e7f4-4222-847d-a41cecd9b0dd
DOTNET_HOST_PATH = C:\Program Files\dotnet\dotnet.exe
MSBUILDENSURESTDOUTFORTASKPROCESSES = 1
MSBUILDUSESERVER = 0

22:31:11.936     0>Process = "C:\Program Files\dotnet\dotnet.exe"
                   MSBuild executable path = "C:\Program Files\dotnet\sdk\7.0.100\MSBuild.dll"
                   Command line arguments = "C:\Program Files\dotnet\sdk\7.0.100\MSBuild.dll -maxcpucount -verbosity:m -restore -target:VSTest -nodereuse:false -nologo -property:Configuration=Debug -verbosity:diag -p:AltCover=true -property:VSTestArtifactsProcessingMode=collect -property:VSTestSessionCorrelationId=3100_d13a1c5b-80eb-44c7-a816-59a79777ef5a -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\7.0.100\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\7.0.100\dotnet.dll"
```
and the initial properties block contains
```
                   AllowUnsafeBlocks = false
                   AltCover = true
                   AlwaysIncludeCoreFrameworkInRuntimeConfig = true
```
No evidence can be found for the other property arguments past the first.  

Running exactly the same under the 6.0.403 sdk gives
```
Build started 14/11/2022 22:34:45.
Environment at start of build:
[complete environment dump redacted]
22:34:45.755     0>Process = "C:\Program Files\dotnet\dotnet.exe"
                   MSBuild executable path = "C:\Program Files\dotnet\sdk\6.0.403\MSBuild.dll"
                   Command line arguments = "C:\Program Files\dotnet\sdk\6.0.403\MSBuild.dll -maxcpucount -verbosity:m -restore -target:VSTest -nodereuse:false -nologo -property:Configuration=Debug -verbosity:diag -p:AltCover=true -p:AltCoverAssemblyFilter=nunit|Adapter|FSharp|AltCover -p:AltCoverReportFormat=OpenCover -p:AltCoverShowStatic=- -p:AltCoverShowSummary=Green -p:AltCoverForce=true -p:AltCoverImportModule=true -p:AltCoverGetVersion=true  -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\6.0.403\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\6.0.403\dotnet.dll"
                   Current directory = "C:\Users\steve_000\Documents\GitHub\_issue"
```
and
```
                   AllowUnsafeBlocks = false
                   ALLUSERSPROFILE = C:\ProgramData
                   AltCover = true
                   AltCoverAssemblyFilter = nunit|Adapter|FSharp|AltCover
                   AltCoverForce = true
                   AltCoverGetVersion = true
                   AltCoverImportModule = true
                   AltCoverReportFormat = OpenCover
                   AltCoverShowStatic = -
                   AltCoverShowSummary = Green
                   AlwaysIncludeCoreFrameworkInRuntimeConfig = true
```

Now change the command line so it starts `dotnet test [project] -p:...`, 

At 7.0.100 there is no evidence of any property argument
`                   Command line arguments = "C:\Program Files\dotnet\sdk\7.0.100\MSBuild.dll -maxcpucount -verbosity:m -restore -target:VSTest -nodereuse:false -nologo -property:Configuration=Debug -verbosity:diag _issue.csproj -property:VSTestArtifactsProcessingMode=collect -property:VSTestSessionCorrelationId=11760_ab6ce17c-1b09-4cb0-a04c-8bd8c33a95ba -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\7.0.100\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\7.0.100\dotnet.dll"`

At 6.0.403 the explicit project name is added, and that's all
`                   Command line arguments = "C:\Program Files\dotnet\sdk\6.0.403\MSBuild.dll -maxcpucount -verbosity:m -restore -target:VSTest -nodereuse:false -nologo -property:Configuration=Debug -verbosity:diag _issue.csproj -p:AltCover=true -p:AltCoverAssemblyFilter=nunit|Adapter|FSharp|AltCover -p:AltCoverReportFormat=OpenCover -p:AltCoverShowStatic=- -p:AltCoverShowSummary=Green -p:AltCoverForce=true -p:AltCoverImportModule=true -p:AltCoverGetVersion=true  -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\6.0.403\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\6.0.403\dotnet.dll"`

### Exceptions (if any)
The `dotnet test` program raises no exceptions in and of itself.

### Further technical details
- Include the output of `dotnet --info`
```
dotnet --info
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  3.1.422 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.108 [C:\Program Files\dotnet\sdk]
  6.0.403 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  C:\Users\steve_000\Documents\GitHub\_issue\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
where the `global,json` is
```json
{
  "sdk": {
    "version": "7.0.100",
    "rollForward": "latestMinor"
  }
}
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
All on the command line.

**Comment by baronfel** [comment] 2022-11-14 22:04
Hi @SteveGilham - This is a duplicate of https://github.com/microsoft/vstest/issues/4014. We've merged a fix already and the fix will be available in 7.0.101 early/mid next month.

**Closed by baronfel** 2022-11-14 22:04 UTC
Labels: Area-DotNet Test, untriaged
