### ISSUE TITLE
Blazor WASM AOT publish fails with .NET 8 in Docker: `libatomic.so.1: cannot open shared object file: No such file or directory`

### ISSUE THREAD

**Issue by andrewlangemann** [dotnet/sdk#37668] opened 2023-12-27 19:11 UTC
### Describe the bug
Using the latest `dotnet/sdk:8.0` container image, publishing a Blazor WASM project with AOT fails with the error `error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory`.

In the Dockerfile, I have the following instructions to install the dependencies required for a WASM build:
```
RUN dotnet workload install wasm-tools --skip-manifest-update
RUN apt-get update -y
RUN apt-get install -y python3
```

Note that this works just fine with .NET 7.

### To Reproduce
- Clone this repro repo (just the vanilla Blazor WASM Standalone project template with AOT turned on): https://github.com/andrewlangemann/BlazorWasmAotDotNet8Bug
- Run `docker build .`

Test with .NET 7:
- Checkout the `dotnet7` branch in the repro repo - it is identical to `main` except it's using .NET 7 instead of 8
- Run `docker build .`
- The build runs successfully

### Exceptions (if any)
The `dotnet publish` command failed with this error:
```
57.62   Linking with emcc with -O2. This may take a while ...
57.69    "/usr/share/dotnet/packs/Microsoft.NET.Runtime.Emscripten.3.1.34.Node.linux-x64/8.0.0/tools/bin/node" /usr/share/dotnet/packs/Microsoft.NET.Runtime.Emscripten.3.1.34.Sdk.linux-x64/8.0.0/tools/emscripten/src/compiler.js /tmp/tmp3wpa3obg.json --symbols-only
57.71   /usr/share/dotnet/packs/Microsoft.NET.Runtime.Emscripten.3.1.34.Node.linux-x64/8.0.0/tools/bin/node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
57.71 emcc : error : '/usr/share/dotnet/packs/Microsoft.NET.Runtime.Emscripten.3.1.34.Node.linux-x64/8.0.0/tools/bin/node /usr/share/dotnet/packs/Microsoft.NET.Runtime.Emscripten.3.1.34.Sdk.linux-x64/8.0.0/tools/emscripten/src/compiler.js /tmp/tmp3wpa3obg.json --symbols-only' failed (returned 127) [/src/BlazorApp1.csproj]
57.71 /usr/share/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.0/Sdk/WasmApp.Native.targets(513,5): error MSB3073: The command "emcc "@/usr/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/8.0.0/runtimes/browser-wasm/native/src/emcc-default.rsp" -msimd128 "@/usr/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/8.0.0/runtimes/browser-wasm/native/src/emcc-link.rsp" "@/src/obj/Release/net8.0/wasm/for-publish/emcc-link.rsp"" exited with code 1. [/src/BlazorApp1.csproj]
```
See attached for the full output from the `dotnet publish` command: [docker-build.log](https://github.com/dotnet/sdk/files/13780670/docker-build.log)

### Further technical details
- Tested this on both x64 (WSL2 on Windows 11) and arm64 (Apple Silicon) - same error happens on either architecture
- Also tested with the `jammy` sdk image variant - same error

**Comment by baronfel** [comment] 2023-12-27 19:14
Thanks for reporting - this is a duplicate of https://github.com/dotnet/dotnet-docker/issues/5033, which has a PR out at https://github.com/dotnet/dotnet-docker/pull/5066.

**Closed by baronfel** 2023-12-27 19:14 UTC
Labels: untriaged, Area-NetSDK
