### ISSUE TITLE
"dotnet run" doesn't respect the '/property:property=value' argument syntax

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/sdk#17016] opened 2021-04-19 21:50 UTC
I found `dotnet run` doesn't respect arguments like '/property:property=value', which is respected by `dotnet build`.

#### Repro

The `repro.csproj` file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="$(PerfTargetVersion)" />
  </ItemGroup>

</Project>
```

Run `dotnet build /property:PerfTargetVersion=7.1.3 -v d > C:\arena\tmp\out.txt` successfully.
And the detailed verbose log shows the "/property:PerfTargetVersion=7.1.3" argument is passed to msbuild.

![image](https://user-images.githubusercontent.com/127450/115307585-45f97800-a11e-11eb-9e81-67b648243823.png)

Run `dotnet run /property:PerfTargetVersion=7.1.3 -v d > C:\arena\tmp\out.txt` would essentially fail because the property and its value were not passed to msbuild:

![image](https://user-images.githubusercontent.com/127450/115307784-94a71200-a11e-11eb-9318-32e9d9401ad0.png)

**Comment by daxian-dbw** [comment] 2021-04-19 21:52
It took me some amount of time to realize it's not that I was missing something or made a mistake, but it's an inconsistency in `dotnet run`. It wold be nice if it can be fxed, or have it documented if it's by design, so that we can save some time for the next person who steps in the same pit.

**Comment by sfoslund** [comment] 2021-04-22 19:11
@wli3 it appears that this has been the behavior for some time (at least since 3.1), is it by design?

**Comment by wli3** [comment] 2021-04-22 21:16
@sfoslund looks like it has the behavior forever. It is beyond my memory. There is likely a technical reason behind that(or historical reason, in project.json time, CLI cannot pass msbuild properties for sure). We should document it first, then think about that is the desire behavior going forward

**Comment by am11** [comment] 2021-04-22 21:17
Duplicate of https://github.com/dotnet/sdk/issues/8520.

**Comment by daxian-dbw** [comment] 2021-04-22 21:21
> We should document it first, then think about what is the desire behavior going forward

Yep, all I want for now is to have this behavior documented, so some time can be saved for a user that runs into this.

**Comment by sfoslund** [comment] 2021-04-22 21:45
I submitted a docs issue, closing in favor of https://github.com/dotnet/docs/issues/23889

**Closed by sfoslund** 2021-04-22 21:45 UTC
