### ISSUE TITLE
Segmentation fault (Core Dump)

### ISSUE THREAD

**Issue by massaynus** [dotnet/sdk#18763] opened 2021-07-07 12:02 UTC
Os: 5.10.42-1-MANJARO

installed dotnet 5 sdk from snap, when I try to run run any command except --version a segmentation fault is thrown
doing `export DOTNET_CLI_TELEMETRY_OPTOUT=1` then `dotnet new` runs, but still it couldn't resotre or build any projects

my guess is that the snap sandbox interferes with the permissions dotnet needs to run such as accessing ~/.dotnet and ~/.nuget folders

fix: uninstalled the snap version and installed the SDK from the official repository and it worked fine!

**Comment by marcpopMSFT** [comment] 2021-07-15 21:51
@rbhanda who manages the snap releases?

**Comment by rbhanda** [comment] 2021-07-15 21:53
@NikolaMilosavljevic who can help debug here.

**Comment by NikolaMilosavljevic** [comment] 2021-07-15 22:38
@tarekgh and @safern, this seems to be another instance of the crash that was seen in Snaps. What data is needed for investigation?

**Comment by safern** [comment] 2021-07-15 22:53
I think the data is enough; I just haven't been able to look at it yet. Now that we are feature complete in `dotnet/runtime` I will be able to look at his.

**Comment by tarekgh** [comment] 2021-07-15 22:58
@safern maybe you could ask on https://github.com/dotnet/runtime/issues/54148 if the reporter installed the SDK from the snap too.

**Comment by safern** [comment] 2021-07-15 23:00
Thanks, @tarekgh, good call to double check. Based on the info provided in the issue it seems like it is:
> Base Path: /snap/dotnet-sdk/129/sdk/5.0.301/

**Comment by tarekgh** [comment] 2021-07-15 23:04
I assume we can reproduce it locally so we can debug it. would be good if you can comment there (or even close one as a duplicate of the other).

**Comment by safern** [comment] 2021-07-15 23:37
I will close this as a dupe of: https://github.com/dotnet/runtime/issues/54148 since the other one has more information.

**Closed by safern** 2021-07-15 23:37 UTC
Labels: Area-Install, untriaged
