### ISSUE TITLE
Cannot reference multitargeted project in VSIX

### ISSUE THREAD

**Issue by khyperia** [dotnet/sdk#1580] opened 2017-09-12 15:32 UTC
When moving one of Roslyn's projects (which is referenced by a VSIX) to be multitargeted, we get the following error:

```
"C:\c\roslyn\src\Compilers\Extension\CompilerExtension.csproj" (default target) (1) ->
"C:\c\roslyn\src\Compilers\Server\VBCSCompiler\VBCSCompiler.csproj" (BuiltProjectOutputGroup;GetCopyToOutputDirectoryItems target) (5:5) ->
  C:\c\roslyn\src\Compilers\Server\VBCSCompiler\VBCSCompiler.csproj : error MSB4057: The target "BuiltProjectOutputGroup" does not exist in the project.
```

Note: longstanding community issue [here](https://developercommunity.visualstudio.com/content/problem/64064/vsix-referencing-multi-targeted-class-library-does.html)

cc @jaredpar

**Comment by sharwell** [comment] 2017-09-12 15:55
You need to add workarounds for dotnet/sdk#433 and Microsoft/extendvs#57.

You can see both here:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/a70d5e6687ac818a85fe8c9760f0caf5a78dce99/StyleCop.Analyzers/StyleCop.Analyzers.Vsix/StyleCop.Analyzers.Vsix.csproj#L47-L53

**Comment by nguerrera** [comment] 2017-09-12 20:13
Closing as duplicate of https://github.com/dotnet/sdk/issues/433

See https://github.com/dotnet/sdk/issues/433#issuecomment-320024771 for an approach to select a target framework to use when building the Vsix.

I will follow up on the community feedback item. Thanks for pointing that out too.

**Closed by nguerrera** 2017-09-12 20:13 UTC
Labels: Blocking Partner
