### ISSUE TITLE
Is there any plan or roadmap to add the .net core and .net standard to VB.NET

### ISSUE THREAD

**Issue by tarekgh** [dotnet/sdk#984] opened 2017-03-14 00:49 UTC
@sarah17wu commented on [Sat Mar 11 2017](https://github.com/dotnet/corefx/issues/17021)

Now in VS 2017, we can only create C# projects with .NET Core and .NET Standard, when the VB.NET will supported with .NET Core and .NET Standard.

---

@karelz commented on [Mon Mar 13 2017](https://github.com/dotnet/corefx/issues/17021#issuecomment-286283405)

@terrajobst?

**Comment by aarondglover** [comment] 2017-04-06 10:56
come on Microsoft! 3 weeks and not even a comment. Put VB developers out of their mysery or publish some REAL news about VB support in core and .NET standard.

Your decisions directly impact on the careers of many developers and we surely deserve some HONEST and frank communication regarding VB support on these new platforms.

**Comment by AnthonyDGreen** [comment] 2017-04-07 20:07
Hi @aarondglover 

I don't know if you read my [VB strategy blog post](https://blogs.msdn.microsoft.com/vbteam/2017/02/01/digging-deeper-into-the-visual-basic-language-strategy/) back in February but there was a (buried) sentence about this toward the end in the platform section where I said "And we are working to ensure that Visual Basic can target .NET Standard to ensure your VB assets can continue to add value on .NET Core".

More specifically we're planning to drop a preview of VB support in the BUILD timeframe a little over a month from now. I've confirmed with the engineering team that the VB templates for .NET Standard libraries and .NET Core console apps are checked in. The reason we didn't ship them at RTM was because we didn't feel confident about the quality of what we had at the time. We had templates but some pieces of the experience were missing and others not tested thoroughly enough so we pulled the templates. We had talked internally about shipping a preview via VSIX right after RTM to unblock our earliest adopters but given the short timeframe before a proper preview we elected to hold off until we could ship something more substantial.

So, templates in May. As we get closer to the preview I'll be able to share more specifics about which parts of the overall .NET Core/Standard experience are in or out for VB at that time. For example, because VB hasn't been along for the ride with .NET Core/Standard 1.x we're not making investments in tooling for migrating 1.x projects to 2.0 projects.

Look for an update with more details on the VBTeam blog within the next few weeks.

Does that answer your question?

**Comment by eschneider999** [comment] 2017-05-11 21:02
Thanks, for the update. Any new info?

Why is it so hard to just to let us know?

Hell, you could have made the templates available for download with a warning...

**Comment by eschneider999** [comment] 2017-05-11 21:09
Also I never understood why all the project/solution related settings screens are different for c# and vb.net ?

I used both regularly, seems all it does is make things more difficult for everyone.

**Comment by srivatsn** [comment] 2017-05-11 21:20
The VS 2017 15.3 Preview that was released yesterday has templates for VB .NET Core and .NET Standard projects. See https://www.visualstudio.com/en-us/news/releasenotes/vs2017-preview-relnotes

**Closed by srivatsn** 2017-05-11 21:20 UTC

**Comment by AnthonyDGreen** [comment] 2017-05-12 09:00
@eschneider999 

They're different because they were made by different people who each thought different details were more or less important than others. No one decided to make them different at the time and no one has decided to go back and make them the same since. Sometimes when we redo things we look at both and try to take the best of both worlds but not always. When pressed for time it's safer to just do what was done before so as not to break the muscle memory or the experience of people who are used to it being the way it was.

A lot of the tabs are the same but not all of them and in many cases where there's a different it's because the two compilers exposes different options.

**Comment by eschneider999** [comment] 2017-05-12 19:47
I know why they are different; the point is I know they should not be, worst case they could have a tab for language specific features. Someday day Microsoft will wake up and fix all the stupid things in Visual Studio and stop wasting time on the stupid "Start Page".
