### ISSUE TITLE
RHEL/CentOS 8 missing net46/Microsoft.NET.Sdk.Razor.Tasks.dll

### ISSUE THREAD

**Issue by michaelbarkdoll** [dotnet/sdk#15548] opened 2021-01-28 16:43 UTC
Hi, I have an issue with a missing .dll file.

My C# extension no longer loads in VS Code due to this missing dll.

https://github.com/OmniSharp/omnisharp-vscode/issues/4360

On the Ubuntu 20.04 LTS the dotnet-sdk-5.0 package has the following dll files:
/usr/share/dotnet/sdk/5.0.102/Sdks/Microsoft.NET.Sdk.Razor/tasks/net46/Microsoft.NET.Sdk.Razor.Tasks.dll
/usr/share/dotnet/sdk/5.0.102/Sdks/Microsoft.NET.Sdk.Razor/tasks/net5.0/Microsoft.NET.Sdk.Razor.Tasks.dll

However, my CentOS 8 only has the following file installed after upgrading to 5.0.102:
/usr/lib64/dotnet/sdk/5.0.102/Sdks/Microsoft.NET.Sdk.Razor/tasks/net5.0/Microsoft.NET.Sdk.Razor.Tasks.dll

So it appears that in RHEL/CentOS 8 the following file(s) are missing:
/usr/lib64/dotnet/sdk/5.0.102/Sdks/Microsoft.NET.Sdk.Razor/tasks/net46/Microsoft.NET.Sdk.Razor.Tasks.dll

ls -la tasks/net46/
-rw-r--r-- 1 root root 77192 Dec 14 20:17 Microsoft.NET.Sdk.Razor.Tasks.dll
-rw-r--r-- 1 root root 189832 Dec 14 20:17 System.Collections.Immutable.dll
-rw-r--r-- 1 root root 464776 Dec 14 20:17 System.Reflection.Metadata.dll

**Comment by dagood** [comment] 2021-01-29 07:37
Duplicate of https://github.com/dotnet/installer/issues/9566

**Closed by dagood** 2021-01-29 07:37 UTC
Labels: untriaged
