### ISSUE TITLE
Changing package version from known to unknown version causes unresolved dependency to disappear from solution explorer

### ISSUE THREAD

**Issue by davidfowl** [dotnet/sdk#451] opened 2016-12-03 05:43 UTC
Repro steps

- File new .NET Core Console
- Edit the csproj and add the following entry
    ```xml
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel">
      <Version>1.1.0</Version>
    </PackageReference>
    ```
- Hit save and observe the references in the Solution explorer
    ![image](https://cloud.githubusercontent.com/assets/95136/20857149/2e60c78a-b8d8-11e6-8c5b-1c12f0379d1f.png)
- Edit the csproj and change the version of `Microsoft.AspNetCore.Server.Kestrel` to `1.2.0-*`
- Hit save and observe the references in the Solution Explorer

Expected:

The Microsoft.AspNetCore.Server.Kestrel should show up in the solution explorer with an unresolved symbol.

Actual:

![image](https://cloud.githubusercontent.com/assets/95136/20857154/5cbdf062-b8d8-11e6-8262-73f852064642.png)

/cc @abpiskunov

**Comment by srivatsn** [comment] 2016-12-21 01:42
Assigning to @natidea since Nat's playing around with this diagnostic.

**Comment by natidea** [comment] 2017-01-04 01:28
With commit https://github.com/dotnet/sdk/pull/506/commits/2ecb1fba0e8d20cb3e045c45e2307849e6f12a91 (in PR #506), I've added a diagnostic that reports unresolved packages. Now the unresolved package shows up in the tree:

![image](https://cloud.githubusercontent.com/assets/7732033/21629045/671c67e0-d1d9-11e6-812f-5bbb8bc73075.png)

However, the diagnostic message does not show up under this package. This may be because the dependencies tree does not account for unresolved nodes having children. Additionally the original bug may be because unresolved packages are never sent from a design time build (because they are not added by NuGet to the "libraries" or "targets" in the lock file). This diagnostic causes a new "ParentPackage" to be added to the hierarchy which must be why the unresolved node shows up.

Assigning to @abpiskunov for further investigation of needed dependency node changes.

**Comment by abpiskunov** [comment] 2017-02-02 01:54
Looked at it and there 2 problems:

1. Initial repro steps - they still repro and i have a fix ready. Issue there was we were not matching resolved itemspec with unresolved itemspec when version was updated (since there is a difference resolved itemSpec is "TFM/PackageName/version" when unresolved is just "PackageName". Nat probably saw that unresolved reference after project reload, not after updating version.
2. Diagnostics indeed not showing up because of the same mismatch in itemSpecs and the fact that unresolved PackageReferences are coming form project  items PackageReference which have ItemSpec as "PackageName", when our whole hierarchy logic needs tfm/packagename/version. I could try to work it around ad search for anytfm/PackageName/version and use first one with diagnostics , but it might be not consistent. I think its getting too hacky and we need a consistent way to get packages data since it is special and has hierarchy items. assets.json does have unresolved and resolved packages, so we need to get unresolved packages with the resolved ones in the same data set from ResolvePackageDependencies. This would have consistent data. 

I will send a PR for actual issue here which is my issue 1. above tomorrow morning. For diagnostics, i will open a separate issue for @natidea to get consistent data set if there no better proposals.

**Comment by livarcocc** [comment] 2017-06-27 22:03
This is still reproing and I am sorry, it is not clear to me what is the ask from the SDK in this case. @natidea can you clarify?

**Comment by natidea** [comment] 2017-06-28 20:35
I think the problem reported here (missing unresolved node) is basically fixed. The remaining issue is that the diagnostic explaining why the node is unresolved is missing from the dependencies node (however it does appear in the error list). The root cause for the missing diagnostic is tracked by https://github.com/dotnet/sdk/issues/790 which I've closed in favor of https://github.com/dotnet/project-system/issues/2515

I do sometimes see the unresolved node disappearing after a version change. It returns after closing and reopening solution. I'm tracking this with https://github.com/dotnet/project-system/issues/2515 as well -- I think they have the same root cause.

So this one can be closed.

**Comment by livarcocc** [comment] 2017-06-30 04:27
Thanks @natidea

**Closed by livarcocc** 2017-06-30 04:27 UTC
Labels: Bug, Urgency-Soon
