### ISSUE TITLE
For .Net Core 3.0, create a winforms app, dotnet run without the windows box poping up.

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/sdk#2754] opened 2018-12-17 10:19 UTC
### Description:
Create a winforms app. Build and run. 
dotnet new winforms -o MyWinFormsApp 
cd MyWinFormsApp 
dotnet build 
dotnet run

**Expected**: It should appear a windows box like this
![image](https://user-images.githubusercontent.com/33921754/50080741-c4c90800-0227-11e9-8163-39413bd95ebe.png)

**Actual**: It doesn’t pop up a windows box.
![image](https://user-images.githubusercontent.com/33921754/50080827-f17d1f80-0227-11e9-9d5e-a6298d7667fb.png)
### Test Environment:
D16.0/28414.68(16.0 preview 2.0) + CLI\SDK: 3.0.100-preview-009839 
dotnet --info:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-009839
 Commit:    ee9fe44627

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-009839\

Host (useful for support):
  Version: 3.0.0-preview-27216-02
  Commit:  79edbd4d15

.NET Core SDKs installed:
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.2.200-preview-009648 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-009839 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-18579-0056 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27216-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-alpha-27214-12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by 0xd4d** [comment] 2018-12-17 11:12
Looks like https://github.com/dotnet/winforms/issues/249

**Comment by nguerrera** [comment] 2018-12-17 16:31
Duplicate of dotnet/winforms#249

**Closed by nguerrera** 2018-12-17 16:31 UTC

**Comment by nguerrera** [comment] 2018-12-17 16:33
And the fact that you see no error when the app crashes due to this is https://github.com/dotnet/core-setup/issues/4768, for which there is a PR in progress to show a message box.
