### ISSUE TITLE
Build Output glitches on non-English locales

### ISSUE THREAD

**Issue by hez2010** [dotnet/sdk#30143] opened 2023-01-26 13:18 UTC
### Describe the bug
Build Output glitches on non-English locales.

![image](https://user-images.githubusercontent.com/14960345/214845231-2f28868a-0d41-4f10-817c-475143e5f83d.png)

### Repro
set system locale, default charset and language to ja-JP
```
git clone --recursive https://github.com/AvaloniaUI/Avalonia.git
cd samples/ControlCatalog.NetCore
dotnet build
```

Locale: ja-JP
System: Windows 11
.NET: 7.0.2

**Comment by nagilson** [comment] 2023-01-26 17:14
Closing this as expected to be fixed in 8.0 preview 1... maybe we can port this. Dupe of https://github.com/dotnet/sdk/issues/29151. Let me know if my fix works once it's in :) https://github.com/dotnet/sdk/pull/29755

**Closed by nagilson** 2023-01-26 17:14 UTC
Labels: untriaged
