### ISSUE TITLE
dotnet tool restore interactive doesn't prompt for DeviceFlow since .NET 6 SDK

### ISSUE THREAD

**Issue by tompazourek** [dotnet/sdk#22987] opened 2021-12-09 15:47 UTC
### Describe the bug

If I use .NET 5 SDK, and call `dotnet tool restore --interactive`, I get presented with the DeviceFlow authentication flow from NuGet's MicrosoftCredentialProvider plugin (https://github.com/microsoft/artifacts-credprovider).

I get something like this:

```
[CredentialProvider]DeviceFlow: https://XXX.pkgs.visualstudio.com/_packaging/XXX/nuget/v3/index.json
[CredentialProvider]ATTENTION: User interaction required.

**********************************************************************

To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXXX to authenticate.

**********************************************************************
```

However, if I need the same thing in .NET 6 SDK (using 6.0.100), the output is silent, I don't receive any prompt on the output.

I found a workaround to add `--verbosity minimal` in the command parameters. But without this, it seems that the default verbosity is `quiet` which doesn't include the interactive auth flow prompt.

In .NET 5, the verbosity switch didn't have any effect for `dotnet tool restore`, I even created issue #16535. but in .NET 6, suddenly, the verbosity is working. It's just that the default verbosity is too quiet and is missing the important prompts.

### To Reproduce

- ensure that the tool packages to be restored aren't in NuGet cache
- ensure that you use feed that needs MicrosoftCredentialProvider auth (https://github.com/microsoft/artifacts-credprovider), I'm using Azure DevOps Artifacts
- ensure you don't have any MicrosoftCredentialProvider token already in cache
- call `dotnet tool restore --interactive`
- **expected:** prompt for device login
- **actual:** no output, program keeps running and waiting for the auth

### Further technical details

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff
```

**Comment by ThisWholeDev** [comment] 2021-12-10 15:15
I have started having this issue as well but i am not sure how this has just started, i have had dotnet 6 installed for awhile now and have not had issues.

**Comment by tompazourek** [comment] 2021-12-10 18:06
@ThisWholeDev Maybe the NuGets you're restoring are already in the NuGet cache. Or maybe the session token was already present in the CredentialProvider storage (see https://github.com/microsoft/artifacts-credprovider#session-token-cache-locations). It has an expiration time, so it only does the auth flow from time to time, not always.

But yeah, your output looks like something I'm getting too.

**Comment by cervesus** [comment] 2022-01-10 13:57
I've had the same issue. As a workaround use the -v diag parameter, at least this worked for me

**Comment by tompazourek** [comment] 2022-01-10 15:54
> I've had the same issue. As a workaround use the -v diag parameter, at least this worked for me

Actually, our workaround was similar, but even `--verbosity minimal` worked.

It's as if the default verbosity is `quiet`, which is too quiet.

**Comment by atkinschris** [comment] 2022-03-21 10:14
I'm getting the same issue, thanks @tompazourek for the workaround.

**Comment by gallivantor** [comment] 2022-03-23 06:03
Any plans to fix this? My team is also getting this problem since upgrading to .NET 6, the `--verbosity minimal` works as a workaround, but it's a bad dev experience that causes devs to waste time wondering what's going on before finding this workaround

**Comment by derodriguezat** [comment] 2022-05-01 13:00
Just to confirm that the workaround worked for me. Here's what I used:
dotnet tool install -g try-convert --interactive --verbosity minimal

**Comment by igorrecioh** [comment] 2022-06-01 10:34
Same issue here when trying to gather a NuGet from a private feed. I can confirm that using following command skips the issue:

```bash
dotnet tool update -g <nuget_name> --interactive --verbosity minimal
```

**Comment by carlin-q-scott** [comment] 2022-07-19 21:23
I did not have this issue until I upgraded from dotnet SDK 6.0.301 to 6.0.302 as a part of the Visual Studio 17.2.6 update. The workaround worked for me, thank you.

I do have the nuget CLI installed on it's own. So maybe dotnet CLI was using that one, v6.2.0.146, but when I upgraded my dotnet SDK, it reverted back to the packaged nuget CLI, which is v6.2.1.7.

**Comment by ViRuSTriNiTy** [comment] 2022-07-25 13:38
Same here, total confusion as it is the first time for me that a dotnet command just does do nothing, please fix this.

**Comment by DanielTheCoder** [comment] 2022-08-17 21:36
Same issue reported here https://github.com/dotnet/sdk/issues/24220

**Comment by blueboxes** [comment] 2022-10-17 14:43
I think I can see in the code why this happens.

This bug fix was added https://github.com/dotnet/sdk/issues/10024 to ensure that it sets verbosity minimal (much like the example above).

https://github.com/dotnet/sdk/blob/a30e465a2e2ea4e2550f319a2dc088daaafe5649/src/Cli/dotnet/commands/dotnet-tool/install/ProjectRestorer.cs#L85

however, where the commands are registered, this is set and then overwritten when the verbosity is registered on the next line. Maybe swapping the lines over would work?

```
  command.AddOption(ToolCommandRestorePassThroughOptions.InteractiveRestoreOption);
  command.AddOption(VerbosityOption);
```

https://github.com/dotnet/sdk/blob/2c98ff1381def385256788cfcbaefb3ac32f5778/src/Cli/dotnet/commands/dotnet-tool/restore/ToolRestoreCommandParser.cs#L41

This is the same in the Restore and Update

**Comment by WhitWaldo** [comment] 2023-01-20 00:55
I've experienced this as well on .NET 7. 

Running `dotnet tool install -g Microsoft.dotnet-interactive` in a cmd prompt yields this error, reflecting a package source I have to an Azure DevOps artifacts feed:

>  Determining projects to restore...
C:\Program Files\dotnet\sdk\7.0.102\NuGet.targets(132,5): warning : The plugin credential provider could not acquire cr
edentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /
p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet` [C:\Users\whit_\AppData\Local\
Temp\2f906456-9768-478a-9646-8be22db8893f\restore.csproj]
C:\Users\xyz123\AppData\Local\Temp\2f906456-9768-478a-9646-8be22db8893f\restore.csproj : error NU1301: Unable to load th
e service index for source https://pkgs.dev.azure.com/innovian/Empirica/_packaging/Empirica/nuget/v3/index.json.
  Failed to restore C:\Users\xyz123\AppData\Local\Temp\2f906456-9768-478a-9646-8be22db8893f\restore.csproj (in 8.27 sec)
  .
The tool package could not be restored.
Tool 'microsoft.dotnet-interactive' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

Re-running it with `dotnet tool install -g Microsoft.dotnet-interactive --verbosity minimal --interactive` prompted me to visit https://microsoft.com/devicelogin and provide a code, which after logging in successfully completed the restore and installed the tool (and I later got an email that a personal access token has been issued on my behalf for the vso.drop_write scope.

I'm pretty sure something like this is the basis for the [issue ](https://github.com/microsoft/vscode-jupyter/issues/12586) I'm having with using .NET interactive notebooks in VS Code in that I cannot install the NuGet packages because it cannot authenticate to my private Artifact feeds.

**Comment by blueboxes** [comment] 2023-04-19 17:20
https://github.com/dotnet/sdk/issues/22987#issuecomment-1280977262

The bot closed this however any thoughts on my comment which points to what I believe is the issue in the code that is in this code base?

**Comment by aortiz-msft** [comment] 2023-04-20 23:34
@baronfel - This looks like a regression in .NET 6 and higher. Would it be possible for someone to take a look?

**Comment by jruizx** [comment] 2023-04-27 18:34
I am experiencing the same issue. So bizarre

**Comment by baronfel** [comment] 2023-04-27 18:40
@JL03-Yue can you please take a look at this and see if we can get it fixed? We'll likely want to consider servicing this one, so I'd take a look at the 6.0 codebase first and let any fix flow forward.

**Comment by tengl** [comment] 2023-08-24 08:16
I got this error on Dotnet 7.0.400 in Linux (Pop!_OS) with private NuGet feeds. 
Changed back to Dotnet 6.0.413 (with `global.json`) where it used to work, but still same issue.

It worked (in 7.0.400) when adding `--verbosity minimal` to the command line.

**Comment by brandonh-msft** [comment] 2023-09-01 18:51
this is impacting installation experience of a tool i'm trying to ship now.

**Comment by cermakp** [comment] 2023-09-05 08:44
Hi, do you have any plan where it will be fixed?

**Comment by jamesdooleymsft** [comment] 2023-11-15 05:53
Still broken in 7.0.404, and still requires `--verbosity minimal` in order for the `--interactive` flag to display the interactive DeviceFlow auth request

**Comment by cermakp** [comment] 2023-12-12 11:56
Any updates?

**Comment by brandonh-msft** [comment] 2024-01-12 19:07
still happening here, .NET 8.0 and I can't even get around it w/ the `--verbosity` flag. just simply doesn't pop the auth GUI **or** to device flow

**Comment by xakep139** [comment] 2024-01-19 16:22
This is completely broken on .NET 8 SDK:
```
> dotnet --version
8.0.101
> dotnet tool restore --interactive --verbosity minimal
[NuGet Manager] [Warning] The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`
Unhandled exception: NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://[...].pkgs.visualstudio.com/[...]/_packaging/[...]/nuget/v3/index.json.
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
```

@joperezr @tarekgh @RussKie folks do you happen to know the right folks to tag here?

**Comment by RussKie** [comment] 2024-01-25 12:38
AFAIK, `dotnet tool restore --interactive --verbosity minimal` _is_ working, though in your case there's something else is going on in the NuGet itself. It might be a different problem deserving a separate issue.

@dotnet/nuget-team any thoughts?

**Comment by aortiz-msft** [comment] 2024-01-25 18:00
This is the repository for NuGet issues: https://github.com/NuGet/Home/issues/new/choose

**Comment by xakep139** [comment] 2024-01-26 12:32
@RussKie, so, the issue has gone after updating [Credential Provider](https://github.com/Microsoft/artifacts-credprovider) plugins via the `iex "& { $(irm https://aka.ms/install-artifacts-credprovider.ps1) } -AddNetfx"` command.

**Comment by p10tyr** [comment] 2024-03-18 15:53
After installing that latest credential provider (and clearing all my NuGets locally)
I run Cake Build which tries to reach out to devops private registry because its in the global nuget config.. and now just loops endlessy.. 

![image](https://github.com/dotnet/sdk/assets/1249683/4b0ef6c2-87f5-416b-96fc-f5f4c53fd89a)

**Comment by mdpopescu** [comment] 2024-03-26 06:32
I can confirm that this is still not working with .NET 8 at the end of March:

```
S:\Renfield\CloudSync>dotnet restore --interactive --verbosity minimal
  Determining projects to restore...
S:\Renfield\CloudSync\CloudSync.SharepointAdapter\CloudSync.SharepointAdapter.csproj : error NU1301: Unable to load the
 service index for source https://nuget.telerik.com/v3/index.json. [S:\Renfield\CloudSync\CloudSync.sln]
S:\Renfield\CloudSync\CloudSync\CloudSync.csproj : error NU1301: Unable to load the service index for source https://nu
get.telerik.com/v3/index.json. [S:\Renfield\CloudSync\CloudSync.sln]

```
I have installed the latest credential provider with the `iex "& { $(irm https://aka.ms/install-artifacts-credprovider.ps1) } -AddNetfx"` command.

**Comment by kartheekp-ms** [comment] 2024-06-25 02:16
@mdpopescu - Regarding https://github.com/dotnet/sdk/issues/22987#issuecomment-2019497798, the `iex "& { $(irm https://aka.ms/install-artifacts-credprovider.ps1) } -AddNetfx"` script is meant for private [Azure Artifacts feeds](https://github.com/microsoft/artifacts-credprovider/blob/master/README.md). In your case, it looks like we are using a Telerik feed (https://nuget.telerik.com/v3/index.json). There is some guidance on how to connect to a private Telerik feed [here](https://docs.telerik.com/reporting/getting-started/installation/adding-private-nuget-feed).

**Comment by srikcgaa2** [comment] 2024-08-20 18:14
What I observe is that after doing a "dotnet restore <solution name> --interactive --verbosity minimal", it shows up "https://microsoft.com/devicelogin" along with authentication code using which I am able to restore the NuGet packages from the private feed successfully.  After this when I do "dotnet tool restore --configfile NuGet.config --interactive --verbosity diagnostic", I am seeing that out of multiple tools mentioned in "dotnet-tools.json" file, one of the packages did get restored correctly but after that it failed to restore rest of the tools and shows the "Response code does not indicate success: 401" error

**Comment by aortiz-msft** [comment] 2024-08-20 23:35
@srikcgaa2 - Are you using a "public upstream source" in Azure DevOps/Azure Artifacts? See https://learn.microsoft.com/en-us/azure/devops/artifacts/how-to/public-feeds-upstream-sources?view=azure-devops&tabs=nuget#q-im-trying-to-restore-my-packages-but-i-keep-getting-a-401-unauthorized-error

**Closed** 2024-12-20 16:59 UTC
Labels: Area-Tools
