### ISSUE TITLE
dotnet store failing with: Unable to find resolved path for 'coreclr

### ISSUE THREAD

**Issue by rynowak** [dotnet/sdk#1541] opened 2017-08-25 21:26 UTC
```
D:\k\JitBench\.dotnet\sdk\2.1.0-preview1-007071\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.CrossGen.targets(48,5): error
 : Unable to find resolved path for 'coreclr'. [D:\k\JitBench\CreateStore.proj]
dotnet store failed.
```

**Repro Steps**

Clone https://github.com/aspnet/JitBench
git checkout rel/2.0.0
run steps in https://github.com/aspnet/JitBench/blob/master/README.md 

This will currently fail at step 3a 
`.\AspNet-GenerateStore.ps1 -InstallDir .store -Architecture x64 -Runtime win7-x64`

The part that's failing is running this command:
`& "dotnet" "store", "--manifest", ".\CreateStore.proj", "-f", "$Framework", "-r" "$Runtime" "--framework-version", "$FrameworkVersion", "-w", $temp, "-o", "$InstallDir", "--skip-symbols"`

In my case the framework version is `2.1.0-preview2-25625-01`, framework is `netcoreapp2.0` and runtime is `win7-x64`

**Comment by rynowak** [comment] 2017-08-30 03:53
Any ideas about a solution for this? I can still reproduce this
```
> dotnet --info
.NET Command Line Tools (2.1.0-preview1-007091)

Product Information:
 Version:            2.1.0-preview1-007091
 Commit SHA-1 hash:  8de61cdcdf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\rynowak\git\aspnet\JitBench\.dotnet\sdk\2.1.0-preview1-007091\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview2-25629-02
  Build    : 70f50d0bb6e6a59ef0a46e1a3d34584c36d51afb
```

**Comment by nguerrera** [comment] 2017-08-31 04:20
What happens with TFM=netcoreapp2.1? 

@eerhardt Any thoughts on what might be happening here?

**Comment by rynowak** [comment] 2017-08-31 15:15
Yes, this works if I change the tfm to 2.1... Is this expected? it would seem odd if the 2.1 SDK can't handle the stuff targeting 2.0.

**Comment by eerhardt** [comment] 2017-08-31 15:34
> In my case the framework version is 2.1.0-preview2-25625-01, framework is netcoreapp2.0

This will work in the future, but I assume how it will work isn't the behavior you want @rynowak.  There is a work item (https://github.com/dotnet/core-setup/issues/2437) to allow the latest Microsoft.NETCore.App 2.1.*-* packages to support `netcoreapp2.0` TFM, but it isn't implemented yet.  When it is implemented, you will get the 2.0 assemblies.  Which means your JitBench will be retesting the 2.0 assemblies over and over, even though you are moving up to new builds of Microsoft.NETCore.App 2.1.x-y.

If you actually want to test the latest 2.1 assemblies, you need to use the `netcoreapp2.1` TFM.

**Comment by rynowak** [comment] 2017-08-31 15:37
> If you actually want to test the latest 2.1 assemblies, you need to use the netcoreapp2.1 TFM.

Actually that makes a lot of sense.... 😆 

So is this issue then just about a bad error message?

**Comment by eerhardt** [comment] 2017-08-31 15:43
> So is this issue then just about a bad error message?

The sdk is doing the appropriate thing here.  It restored what you told it to restore, and then looked for the CLR assemblies, but it couldn't find them, so it errored out.

The real issue here is what I linked above https://github.com/dotnet/core-setup/issues/2437.  The 2.1 packages don't support `netcoreapp2.0` yet.

/cc @ericstj

**Comment by nguerrera** [comment] 2017-08-31 16:20
Closing as duplicate of https://github.com/dotnet/core-setup/issues/2437

**Closed** 2017-08-31 16:20 UTC

**Comment by felixfbecker** [comment] 2019-11-15 21:16
The linked issue is closed, however I still see this. Honestly I don't really understand the things said above. I have a simple csproj targeting `netstandard2.0` (although I also tried `netstandard2.1` and `netcoreapp2.1`). Any idea?

```
/usr/local/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.CrossGen.targets(44,5): error NETSDK1016: Unable to find resolved path for 'coreclr'. [/Users/felix/git/PowerGit/PowerGit.csproj]
```

**Comment by nguerrera** [comment] 2019-11-15 21:26
@felixfbecker It's entirely possible that you are seeing the same error message with different root cause. Would you mind opening a fresh issue and listing the full steps to reproduce what you are seeing.
