### ISSUE TITLE
Solution build with RuntimeIdentifier specified as global property can fail with concurrency problems

### ISSUE THREAD

**Issue by vchirikov** [dotnet/sdk#10987] opened 2020-03-25 10:03 UTC
I've tried to publish a complex solution (about 170 projects) as `--self-contained` but ran into some concurrency problems in msbuild targets.
Sometimes build is successful, but sometimes it is failed.
I can't give you the full msbuild binlog from the solution, but I've made a smaller repro.
Sometimes the build is successful, but sometimes it fails. So for now, I found 100% how to reproduce this.

`dotnet build-server shutdown && rmdir /s /q artifacts && dotnet build -c Release -r win-x64`

Also I included binlog with success / fail build state with `dotnet msbuild` and same binlog with full msbuild from VS.

![repro image](https://user-images.githubusercontent.com/40987940/77523532-eedf9000-6e96-11ea-8fe1-b6ff94814ce7.png)

```
CSC : error CS2012: Cannot open 'c:\work\dotnet\projects\msbuild-build-bug\artifacts\obj\Lib2\x64\Release\Lib2.dll' for writing -- 'The process cannot access the file 'c:\work\dotnet\projects\msbuild-build-bug\artifacts\obj\Lib2\x64\Release\Lib2.dll' because it is being used by another process.' [c:\work\dotnet\projects\msbuild-build-bug\src\Lib2\Lib2.csproj]
CSC : error CS2012: Cannot open 'c:\work\dotnet\projects\msbuild-build-bug\artifacts\obj\Lib1\x64\Release\Lib1.dll' for writing -- 'The process cannot access the file 'c:\work\dotnet\projects\msbuild-build-bug\artifacts\obj\Lib1\x64\Release\Lib1.dll' because it is being used by another process.' [c:\work\dotnet\projects\msbuild-build-bug\src\Lib1\Lib1.csproj]
```

These properties are the main cause of these errors:

```
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
```

Without them the build will be ok.

The problem may be related with https://github.com/dotnet/sdk/issues/2902

[msbuild-build-bug.zip](https://github.com/dotnet/sdk/files/4380155/msbuild-build-bug.zip)

cc: @rainersigwald  @davidwengier

**Comment by rainersigwald** [comment] 2020-03-25 22:49
I think this is another instance/symptom of dotnet/sdk#863. You shouldn't specify a runtime identifier (via `-r win-x64` or otherwise) when you're building a _solution_. Instead, build the individual projects you wish to deploy with that RID as outputs.

This isn't ideal and it's not obvious. That bug is to at least make it more obvious.

**Comment by vchirikov** [comment] 2020-03-26 07:22
oh.  :(
thanks for the information

**Comment by dsplaisted** [comment] 2020-04-09 01:50
Closing as a duplicate of #863

**Closed by dsplaisted** 2020-04-09 01:50 UTC
