### ISSUE TITLE
nuget certificate errors in sdk:5.0-buster-slim

### ISSUE THREAD

**Issue by stefanloerwald** [dotnet/sdk#15510] opened 2021-01-27 13:51 UTC
I currently get a large number of certificate validation (NU3028 + NU3037) errors from a multitude of packages when running `dotnet restore`:

```log
/test.csproj : error NU3028: Package 'System.Security.Cryptography.ProtectedData 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/test.csproj : error NU3037: Package 'System.Security.Cryptography.ProtectedData 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
```

To reproduce:

```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS test_and_build

RUN echo '<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFrameworks>net5.0</TargetFrameworks></PropertyGroup><ItemGroup><PackageReference Include="System.Security.Cryptography.ProtectedData" Version="5.0.0" /></ItemGroup></Project>' > test.csproj

RUN dotnet restore test.csproj
```

It does not occur on my host system (which runs Windows 10)

The whole log is:
```cs
#10 2.361   Determining projects to restore...
#10 9.248 test.csproj : error NU3028: Package 'System.Windows.Extensions 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.249 test.csproj : error NU3028: Package 'System.Security.Permissions 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.250 test.csproj : error NU3037: Package 'System.Windows.Extensions 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.250 test.csproj : error NU3028: Package 'System.Windows.Extensions 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.251 test.csproj : error NU3037: Package 'System.Security.Permissions 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.251 test.csproj : error NU3028: Package 'System.Security.Permissions 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.251 test.csproj : error NU3028: Package 'System.Configuration.ConfigurationManager 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.252 test.csproj : error NU3037: Package 'System.Configuration.ConfigurationManager 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.252 test.csproj : error NU3028: Package 'System.Configuration.ConfigurationManager 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.253 test.csproj : error NU3028: Package 'System.Drawing.Common 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.253 test.csproj : error NU3037: Package 'System.Drawing.Common 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.253 test.csproj : error NU3028: Package 'System.Drawing.Common 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.253 test.csproj : error NU3028: Package 'System.Security.AccessControl 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.253 test.csproj : error NU3037: Package 'System.Security.AccessControl 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.253 test.csproj : error NU3028: Package 'System.Security.AccessControl 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.254 test.csproj : error NU3028: Package 'Microsoft.Win32.SystemEvents 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.254 test.csproj : error NU3037: Package 'Microsoft.Win32.SystemEvents 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.254 test.csproj : error NU3028: Package 'Microsoft.Win32.SystemEvents 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.255 test.csproj : error NU3028: Package 'System.Diagnostics.PerformanceCounter 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.256 test.csproj : error NU3037: Package 'System.Diagnostics.PerformanceCounter 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.256 test.csproj : error NU3028: Package 'System.Diagnostics.PerformanceCounter 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.256 test.csproj : error NU3028: Package 'System.Security.Cryptography.ProtectedData 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.256 test.csproj : error NU3037: Package 'System.Security.Cryptography.ProtectedData 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.256 test.csproj : error NU3028: Package 'System.Security.Cryptography.ProtectedData 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.392 test.csproj : error NU3028: Package 'Microsoft.NETCore.Platforms 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.393 test.csproj : error NU3037: Package 'Microsoft.NETCore.Platforms 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.394 test.csproj : error NU3028: Package 'Microsoft.NETCore.Platforms 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.430 test.csproj : error NU3028: Package 'System.Runtime.CompilerServices.Unsafe 4.5.3' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.431 test.csproj : error NU3037: Package 'System.Runtime.CompilerServices.Unsafe 4.5.3' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.439 test.csproj : error NU3028: Package 'System.Runtime.CompilerServices.Unsafe 4.5.3' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.440 test.csproj : error NU3028: Package 'Microsoft.Win32.Registry 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.441 test.csproj : error NU3037: Package 'Microsoft.Win32.Registry 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.442 test.csproj : error NU3028: Package 'Microsoft.Win32.Registry 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.443 test.csproj : error NU3028: Package 'System.Threading.Channels 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.443 test.csproj : error NU3037: Package 'System.Threading.Channels 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.444 test.csproj : error NU3028: Package 'System.Threading.Channels 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.463 test.csproj : error NU3028: Package 'System.IO.Pipelines 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.465 test.csproj : error NU3037: Package 'System.IO.Pipelines 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.466 test.csproj : error NU3028: Package 'System.IO.Pipelines 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.482 test.csproj : error NU3028: Package 'System.Security.Principal.Windows 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.482 test.csproj : error NU3037: Package 'System.Security.Principal.Windows 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.482 test.csproj : error NU3028: Package 'System.Security.Principal.Windows 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.483 test.csproj : error NU3028: Package 'Microsoft.Bcl.AsyncInterfaces 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.484 test.csproj : error NU3037: Package 'Microsoft.Bcl.AsyncInterfaces 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.485 test.csproj : error NU3028: Package 'Microsoft.Bcl.AsyncInterfaces 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.486 test.csproj : error NU3028: Package 'Microsoft.Extensions.DependencyInjection.Abstractions 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.486 test.csproj : error NU3037: Package 'Microsoft.Extensions.DependencyInjection.Abstractions 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.487 test.csproj : error NU3028: Package 'Microsoft.Extensions.DependencyInjection.Abstractions 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.498 test.csproj : error NU3028: Package 'System.Text.Json 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.498 test.csproj : error NU3037: Package 'System.Text.Json 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.499 test.csproj : error NU3028: Package 'System.Text.Json 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.501 test.csproj : error NU3028: Package 'Microsoft.Extensions.Logging.Abstractions 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.501 test.csproj : error NU3037: Package 'Microsoft.Extensions.Logging.Abstractions 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.502 test.csproj : error NU3028: Package 'Microsoft.Extensions.Logging.Abstractions 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.516 test.csproj : error NU3028: Package 'Microsoft.Extensions.Configuration.Abstractions 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.516 test.csproj : error NU3037: Package 'Microsoft.Extensions.Configuration.Abstractions 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.517 test.csproj : error NU3028: Package 'Microsoft.Extensions.Configuration.Abstractions 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.521 test.csproj : error NU3028: Package 'Microsoft.Extensions.Primitives 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.522 test.csproj : error NU3037: Package 'Microsoft.Extensions.Primitives 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.523 test.csproj : error NU3028: Package 'Microsoft.Extensions.Primitives 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.554 test.csproj : error NU3028: Package 'System.Buffers 4.5.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.555 test.csproj : error NU3037: Package 'System.Buffers 4.5.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.556 test.csproj : error NU3028: Package 'System.Buffers 4.5.1' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.558 test.csproj : error NU3028: Package 'System.Numerics.Vectors 4.5.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.558 test.csproj : error NU3037: Package 'System.Numerics.Vectors 4.5.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.559 test.csproj : error NU3028: Package 'System.Numerics.Vectors 4.5.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.559 test.csproj : error NU3028: Package 'System.Threading.Tasks.Extensions 4.5.4' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.559 test.csproj : error NU3037: Package 'System.Threading.Tasks.Extensions 4.5.4' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.559 test.csproj : error NU3028: Package 'System.Threading.Tasks.Extensions 4.5.4' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.560 test.csproj : error NU3028: Package 'System.Text.Encodings.Web 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.561 test.csproj : error NU3037: Package 'System.Text.Encodings.Web 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.562 test.csproj : error NU3028: Package 'System.Text.Encodings.Web 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.568 test.csproj : error NU3028: Package 'System.Memory 4.5.4' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.568 test.csproj : error NU3037: Package 'System.Memory 4.5.4' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.568 test.csproj : error NU3028: Package 'System.Memory 4.5.4' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.571 test.csproj : error NU3028: Package 'System.Runtime.CompilerServices.Unsafe 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.572 test.csproj : error NU3037: Package 'System.Runtime.CompilerServices.Unsafe 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
#10 9.573 test.csproj : error NU3028: Package 'System.Runtime.CompilerServices.Unsafe 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
#10 9.710   Failed to restore test.csproj (in 6.26 sec).
```

**Comment by tankbob** [comment] 2021-01-27 14:08
This is the same as the bug I've raised https://github.com/dotnet/sdk/issues/15509

**Comment by stefanloerwald** [comment] 2021-01-27 14:13
Thanks for letting me know. Seems like you posted while I was still typing...

**Comment by dasMulli** [comment] 2021-01-27 14:16
Seems like a dupe of https://github.com/NuGet/Home/issues/10491

**Closed** 2021-01-27 19:28 UTC
Labels: untriaged

**Comment by avorobjovs** [comment] 2021-01-28 09:30
The workaround:

Changed from 
mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
to
mcr.microsoft.com/dotnet/sdk:5.0-alpine

It works!
