### ISSUE TITLE
Remove workaround for dotnet/cli#9701

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#2422] opened 2018-07-20 17:56 UTC
Now that the bug is fixed, we should remove this workaround: https://github.com/dotnet/sdk/pull/2371/commits/66eea9d631aed24a97b74afc16edc3e29490507b

In this file: src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateADepsFileForATool.cs

**Comment by nguerrera** [comment] 2018-07-23 20:53
Duplicate of #2416

**Closed by nguerrera** 2018-07-23 20:53 UTC
