### ISSUE TITLE
ResolvePackageFileConflicts task throw null reference exception when duplicate references are passed in (and conflicts exist)

### ISSUE THREAD

**Issue by crmann1** [dotnet/sdk#3388] opened 2019-07-02 19:00 UTC
During a build of a project that has duplicate references where the duplicate reference is also a conflict the ResolvePackageFileConflicts task crashes with a null reference exception . 

C:\Program   Files\dotnet\sdk\3.0.100-preview7-012601\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets

The "ResolvePackageFileConflicts" task failed unexpectedly.System.NullReferenceException: Object reference not set to an instance of an object.   at Microsoft.NET.Build.Tasks.ConflictResolution.ResolvePackageFileConflicts.<>c.<ExecuteCore>b__44_0(ITaskItem r) in /_/src/Tasks/Common/ConflictResolution/ResolvePackageFileConflicts.cs:line 160   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)   at Microsoft.NET.Build.Tasks.ConflictResolution.ResolvePackageFileConflicts.ExecuteCore() in /_/src/Tasks/Common/ConflictResolution/ResolvePackageFileConflicts.cs:line 160   at Microsoft.NET.Build.Tasks.TaskBase.Execute() in /_/src/Tasks/Common/TaskBase.cs:line 47   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

The reason is that in ResolvePackageFileConflicts.cs
      var result = new ITaskItem[original.Length - conflicts.Count]; 

The assumption is that the length of the result array is just the original list minus the conflict list. But if the original list has duplicates then the result array will be too large and will have null entries in it. 

Further down that array is processed and fails 

var referenceItemSpecs = new HashSet<string>(ReferencesWithoutConflicts?.Select(r => r.ItemSpec) ?? Enumerable.Empty<string>(),
                                                                     StringComparer.OrdinalIgnoreCase);

r=> r.ItemSpec fails because r is null due to the ReferenceWithoutConflicts enumeration containing a null item  due to the problem above.

Repro for example is to have a file with the following reference items in it

 <ItemGroup>
    <Reference Include="System.Runtime" />
    <Reference Include="System.Runtime" />
  </ItemGroup>

**Comment by livarcocc** [comment] 2019-07-03 06:48
@dsplaisted this seems like the issue you were investigating earlier today.

**Comment by livarcocc** [comment] 2019-07-03 20:55
Closing this as a duplicate of dotnet/cli#11709.

**Closed by livarcocc** 2019-07-03 20:55 UTC
