### ISSUE TITLE
`RuntimeIdentifiers` is not recognized by sdk in new-style csproj

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/sdk#414] opened 2016-11-21 06:07 UTC
Tested with `dotnet-dev-1.0.0-preview3-004056`, and got the error msg.
```
***\.nuget\packages\microsoft.net.sdk\1.0.0-alpha-20161104-2\build\Microsoft.NET.RuntimeIdentifierInference.targets(45,5): error : RuntimeIdentifier must be set for .NETFramework executables. Consider RuntimeIdentifier=win7-x86 or RuntimeIdentifier=win7-x64. [***\src\x1\x1.csproj]

The build failed. Please fix the build errors and run again.
```
Replace the `RuntimeIdentifiers` to `RuntimeIdentifier` works, but according to the [doc](https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/csproj), `RuntimeIdentifiers` should also be an valid property.

The working old-style project.json
```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },

  "dependencies": {
    //"Microsoft.Extensions.Logging.Console": "1.0.0"
  },

  "frameworks": {
    "net45": {

    },
    "netcoreapp1.0": {
      "imports": "dnxcore50",

      "dependencies": {
        "Microsoft.NETCore.App": {
          //"type": "platform",
          "version": "1.0.1"
        },
        "System.Text.Encoding.CodePages": "4.0.1"
      }
    }
  },
  "runtimes": {
    "win7-x64": {}
  }
}
```
upgrade to new-style with `dotnet migrate`.
The not working new-style .csproj
```xml
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  
  <PropertyGroup>
    <TargetFrameworks>net45;netcoreapp1.0</TargetFrameworks>
    <DebugType>portable</DebugType>
    <AssemblyName>x1</AssemblyName>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifiers>win7-x64</RuntimeIdentifiers>
    <PackageTargetFallback Condition=" '$(TargetFramework)' == 'netcoreapp1.0' ">$(PackageTargetFallback);dnxcore50</PackageTargetFallback>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
    <EmbeddedResource Include="compiler\resources\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk">
      <Version>1.0.0-alpha-20161104-2</Version>
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net45' ">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp1.0' ">
    <PackageReference Include="Microsoft.NETCore.App">
      <Version>1.0.1</Version>
    </PackageReference>
    <PackageReference Include="System.Text.Encoding.CodePages">
      <Version>4.0.1</Version>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DefineConstants>$(DefineConstants);RELEASE</DefineConstants>
  </PropertyGroup>
  
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

**Comment by dsplaisted** [comment] 2016-11-21 06:48
@piotrpMSFT for the migrate issue, @blackdwarf for the docs.

@nguerrera @eerhardt Should we support multiple runtime identifiers via a `RuntimeIdentifiers` property in the .NET SDK?  If so, how would that interact if there are multiple target frameworks?

**Comment by nguerrera** [comment] 2016-11-21 17:24
Adding @emgarten for nuget perspective.

**Comment by blackdwarf** [comment] 2016-11-21 20:53
@nguerrera so, for the docs, if there is one of X, we should use singular and if there are multiples of X we should use plural?

**Comment by emgarten** [comment] 2016-11-22 07:40
Restore supports both ``RuntimeIdentifier`` and ``RuntimeIdentifiers``

> how would that interact if there are multiple target frameworks?

For restore the RIDs are applied to all TFMs. Per TFM RIDs are not supported in restore, but it has been considered.

**Comment by srivatsn** [comment] 2017-01-24 22:41
Another report - https://developercommunity.visualstudio.com/content/problem/7153/convert-aspnet-core-targeting-net462-cannot-build.html

**Comment by nguerrera** [comment] 2017-01-31 19:15
Closing as duplicate of #396, the plan for which will fix this.

**Closed by nguerrera** 2017-01-31 19:15 UTC
Labels: Blocking-Release, Bug, RC3 Known Issue, Urgency-Soon
