### ISSUE TITLE
SDK doesn't respect ReferenceOutputAssembly false

### ISSUE THREAD

**Issue by jaredpar** [dotnet/sdk#1096] opened 2017-04-07 06:11 UTC
A common pattern in MSBuild to introduce ordering in the build is the following:

``` xml
<ProjectReference Include="..\..\..\..\Tools\Source\CompilerGeneratorTools\Source\CSharpSyntaxGenerator\CSharpSyntaxGenerator.csproj">
  <Project>{288089C5-8721-458E-BE3E-78990DAB5E2D}</Project>
  <Name>CSharpSyntaxGenerator</Name>
  <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
</ProjectReference>
```

Notice the use of `ReferenceOutputAssembly` to `false` here.  This means that CSharpSyntaxGenerator simply builds before the current project, the current project does not reference it though.  

The new SDK seems to be treating this like an actual reference though:

> C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Sdks\Microsoft.Net.Sdk\build\Microsoft.NET.Sdk.Common.targets(73,5): error : Project 'E :\code\roslyn\src\Tools\Source\CompilerGeneratorTools\Source\CSharpSyntaxGenerator\CSharpSyntaxGenerator.csproj' targets '.NETCoreApp,Version=v1.0'. It cannot be  referenced by a project that targets '.NETStandard,Version=v1.3'. [E:\code\roslyn\src\Tools\Source\CompilerGeneratorTools\Source\CSharpSyntaxGenerator\CSharpSyn taxGenerator.csproj]

The framework targeted here shouldn't be relevant as this reference exists for ordering only.  

Repro:

1. Clone https://github.com/jaredpar/roslyn
1. Sync to branch `repo/sdk2`
1. Run `msbuild /v:m /t:Restore Compilers.sln`
1. Run `msbuild /v:m src\Compilers\CSharp\Test\Syntax\CSharpCompilerSyntaxTest.csproj`

Note: this repos with a post 15.1 build.

**Comment by jaredpar** [comment] 2017-04-07 06:12
Similar issue we've run into in the past with NuGet https://github.com/NuGet/Home/issues/1629

**Comment by Sumo-MBryant** [comment] 2017-05-08 07:52
Also see: https://github.com/dotnet/sdk/issues/1020

**Comment by Sumo-MBryant** [comment] 2017-05-08 07:54
Also see: https://github.com/dotnet/sdk/issues/939

**Comment by rainersigwald** [comment] 2017-07-14 21:35
Duplicate of #939.

**Comment by nguerrera** [comment] 2017-10-23 21:48
Closing as duplicate of #939

**Closed by nguerrera** 2017-10-23 21:48 UTC
