### ISSUE TITLE
`dotnet tool install`s unlisted and depreciated version

### ISSUE THREAD

**Issue by fabiomadge** [dotnet/sdk#32728] opened 2023-05-22 18:46 UTC
### Describe the bug
Installing without a specified version doesn't get me the latest listed version. I would expect to get `4.1.0`, which I get when browsing NuGet, or doing `dotnet tool search dafny`, but I get `4.1.0.50509` instead.

### To Reproduce
```
dotnet tool install --tool-path . dafny
```

**Comment by baronfel** [comment] 2023-05-22 19:03
The NuGet API has that version as the most recent (you can see this in this manifest at the very bottom of the list): https://api.nuget.org/v3-flatcontainer/dafny/index.json, so our behavior is at least consistent with that. I think the presence of that NuGet-style version is throwing things off - I would check with the package authors to see more about when that package was created.

**Comment by baronfel** [comment] 2023-05-22 19:24
Ok, gotcha. I think this is another symptom of the fact that we use 'restore' under the hood here. Restore is allowed to retrieve unlisted versions because for a normal project you don't want to break consumers. Tools shouldn't behave in that same way, however, and when we rewrite these experiences to use the NuGet APIs directly instead of indirectly, we can and will enforce this filtering you intended.

I strongly expect this is a duplicate of an issue we've got linked in the .NET 8 Tools epic, I'll try to link it shortly.

**Comment by nagilson** [comment] 2023-06-08 23:33
@baronfel Should we close this in favor of https://github.com/dotnet/sdk/issues/32092 ?

**Comment by baronfel** [comment] 2023-06-08 23:35
Yes, good call.

**Closed** 2023-06-08 23:35 UTC
Labels: Area-Tools
