### ISSUE TITLE
Want to migrate on dnx to cli with entity framework core

### ISSUE THREAD

**Issue by ankurjasoria** [dotnet/sdk#1709] opened 2017-11-02 08:03 UTC
Hi Team,

I have followed below url as reference
https://github.com/dotnet/cli/blob/master/Documentation/ProjectJsonToCSProj.md

and found below issue with migrate command
Error :
PS C:\yoyo-center-management-system-master\CenterManagementSystem\DEV\src\CenterManagementSystem.Platform> dotnet migrate
No executable found matching command "dotnet-migrate"

I have created separate console application with the use of below cli command

    dotnet new
    dotnet restore
    dotnet build
    dotnet run
    All command working fine but unable to proceed further like What is my next step ?
    I am sharing you my powershall command and status as below

PS C:\test3\myApp> dotnet build
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

myApp -> C:\test3\myApp\bin\Debug\netcoreapp2.0\myApp.dll

Build succeeded.
0 Warning(s)
0 Error(s)

Time Elapsed 00:00:01.02
PS C:\test3\myApp> dotnet run
Hello World!
PS C:\test3\myApp> dotnet migrate
No project.json file found in 'C:\test3\myApp'.
Migration failed.
PS C:\test3\myApp>

Please suggest me for same ?

**Comment by livarcocc** [comment] 2017-11-08 00:15
Duplicate of https://github.com/dotnet/cli/issues/7956

**Closed by livarcocc** 2017-11-08 00:15 UTC
