### ISSUE TITLE
GenerateRuntimeConfigurationFiles is for .Net Core Projects only

### ISSUE THREAD

**Issue by basoundr** [dotnet/sdk#1183] opened 2017-05-05 23:14 UTC
[Refer here](https://github.com/dotnet/sdk/pull/1178#discussion_r115101389)

**Comment by eerhardt** [comment] 2017-05-30 15:05
@livarcocc - is this something I can fix for 2.0?  It is "junk" in desktop project's output.  Desktop projects should never have runtimeconfig.json files, since they don't do anything.  The fix is a simple check for .NET Core and add a test.

I can do the work - I just don't want to do the work if it won't be approved for 2.0.

**Comment by srivatsn** [comment] 2017-06-06 00:00
This is https://github.com/dotnet/sdk/issues/404

**Comment by eerhardt** [comment] 2017-06-06 15:04
Closing as dupe of #404.

**Closed by eerhardt** 2017-06-06 15:04 UTC
