### ISSUE TITLE
MapStaticAssets on component lib that uses CompressionIncludePatterns cannot compile

### ISSUE THREAD

**Issue by davhdavh** [dotnet/sdk#44784] opened 2024-11-11 08:40 UTC
### Describe the bug

Including a lib that already utilized `CompressionIncludePatterns` to compress files blows up compile when including file with `@Asset["_content/Lib/File"]`.

### To Reproduce

1. Make lib
2. Add file in wwwroot, e.g. a css file
3. Add to csproj:
```
   <PropertyGroup>
     <CompressionIncludePatterns>$(CompressionIncludePatterns);**/*.css</CompressionIncludePatterns>
     <BuildCompressionFormats>gzip;brotli</BuildCompressionFormats>
   </PropertyGroup>
```
4. build nuget of lib on build server
5. Make new blazor from template and add nuget
6. Add the css file in App.razor using `<link rel="stylesheet" href="@Assets["_content/thelib/thestyles.css"]" />`
7. build

### Exceptions (if any)

```
1>C:\Program Files\dotnet\sdk\9.0.100-rc.2.24474.11\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.Compression.targets(241,5): error MSB4018: The "ApplyCompressionNegotiation" task failed unexpectedly.
1>C:\Program Files\dotnet\sdk\9.0.100-rc.2.24474.11\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.Compression.targets(241,5): error MSB4018: System.InvalidOperationException: Related asset not found for compressed asset: c:\src\.caches\nuget\thelib\2.0.0\staticwebassets\thestyles.css.br
1>C:\Program Files\dotnet\sdk\9.0.100-rc.2.24474.11\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.Compression.targets(241,5): error MSB4018:    at Microsoft.AspNetCore.StaticWebAssets.Tasks.ApplyCompressionNegotiation.Execute()
1>C:\Program Files\dotnet\sdk\9.0.100-rc.2.24474.11\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.Compression.targets(241,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
1>C:\Program Files\dotnet\sdk\9.0.100-rc.2.24474.11\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.Compression.targets(241,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1>    1 Warning(s)
1>    1 Error(s)
```

### Further technical details
dotnet 9 preview 2.

Debug log from msbuild shows the problem is a folder mixup between the paths build server and dev machine:
```
1>    Asset 'c:\src\.caches\nuget\thelib\2.0.0\staticwebassets\thestyles.css' is not compressed.
1>    The asset 'c:\src\.caches\nuget\thelib\2.0.0\staticwebassets\thestyles.css.br' with related asset 'C:\actions-runner\_work\MyRepo\MyRepo\thelib\wwwroot\thestyles.css' was detected as already compressed with format 'brotli'.
1>    The asset 'c:\src\.caches\nuget\thelib\2.0.0\staticwebassets\thestyles.css.gz' with related asset 'C:\actions-runner\_work\MyRepo\MyRepo\thelib\wwwroot\thestyles.css' was detected as already compressed with format 'gzip'.
```
and thus later when it process the .br file it cannot find the related asset since that is in a  build folder

**Comment by javiercn** [comment] 2024-11-13 01:04
Dupe of https://github.com/dotnet/aspnetcore/issues/57518

**Closed by javiercn** 2024-11-13 01:04 UTC
Labels: untriaged, Area-AspNetCore
