### ISSUE TITLE
Self contained publish includes entire framework

### ISSUE THREAD

**Issue by Kritner** [dotnet/sdk#1563] opened 2017-09-05 17:13 UTC
Sorry if something like this has already been published, didn't find anything at first glance.

I'm attempting to do a self contained dotnet publish since moving over to 2.0 dotnetcore, the publish itself is working, but the publish directory is in the neighborhood of 90MB, most of which is the framework itself.  I expected some sort of "Tree shake" to not include pieces of the framework that aren't referenced in the publish, but that is not the case.

Things such as entityframework, application insights, etc are being included in the publish directory, but not utilized by the code.

csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\proj1.csproj" />
    <ProjectReference Include="..\proj2.csproj" />
    <ProjectReference Include="..\proj3.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="Autofac" Version="4.6.1" />
  </ItemGroup>

</Project>
```

Command run:

`dotnet publish --self-contained -c Release`

Am i just missing a simple flag on my publish options, or something in my csproj?

A co-worker pointed me to this article https://blogs.msdn.microsoft.com/webdev/2017/08/14/announcing-asp-net-core-2-0/ which states:

> What happens at publication time?  We know that you don’t want to publish the entire AspNetCore framework to your target environments, so the publish task now distributes only those libraries that you reference in your code.  This tree-pruning step should help make your publish process much smoother and easier to distribute your web applications.

But that doesn't seem to be the case here

**Comment by Kritner** [comment] 2017-09-06 11:43
Don't know if it helps but when running the following two commands:

`dotnet publish`
`dotnet publish -r win10-x64`

from the repo https://github.com/Kritner/ConsoleMixingNetStandardAndCore

I get this sort of output:

![image](https://user-images.githubusercontent.com/8814983/30109858-ef742bce-92d5-11e7-90e0-e83866a1cd25.png)

the `dotnet publish` is seemingly a framework dependent publish, as only ***my*** code is present. Additionally, the `project.deps.json` file contains very little:

```
{
  "runtimeTarget": {
    "name": ".NETCoreApp,Version=v2.0",
    "signature": "da39a3ee5e6b4b0d3255bfef95601890afd80709"
  },
  "compilationOptions": {},
  "targets": {
    ".NETCoreApp,Version=v2.0": {
      "ConsoleMixingNetStandardAndCore/1.0.0": {
        "dependencies": {
          "StandardLibrary": "1.0.0"
        },
        "runtime": {
          "ConsoleMixingNetStandardAndCore.dll": {}
        }
      },
      "StandardLibrary/1.0.0": {
        "runtime": {
          "StandardLibrary.dll": {}
        }
      }
    }
  },
  "libraries": {
    "ConsoleMixingNetStandardAndCore/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    },
    "StandardLibrary/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    }
  }
}
```

However, when publish via the command `dotnet publish -r win10-x64`, there are many (i'm assuming the entire) framework published along with the published bits, and the `project.deps.json` file reflects many more dependencies than i would expect:

```
{
  "runtimeTarget": {
    "name": ".NETCoreApp,Version=v2.0/win10-x64",
    "signature": "b348c731e02a59ba78cd813014097d82edab6717"
  },
  "compilationOptions": {},
  "targets": {
    ".NETCoreApp,Version=v2.0": {},
    ".NETCoreApp,Version=v2.0/win10-x64": {
      "ConsoleMixingNetStandardAndCore/1.0.0": {
        "dependencies": {
          "Microsoft.NETCore.App": "2.0.0",
          "StandardLibrary": "1.0.0"
        },
        "runtime": {
          "ConsoleMixingNetStandardAndCore.dll": {}
        }
      },
      "Microsoft.NETCore.App/2.0.0": {
        "dependencies": {
          "Microsoft.NETCore.DotNetHostPolicy": "2.0.0",
          "Microsoft.NETCore.Platforms": "2.0.0",
          "NETStandard.Library": "2.0.0",
          "runtime.win-x64.Microsoft.NETCore.App": "2.0.0"
        }
      },
      "Microsoft.NETCore.DotNetAppHost/2.0.0": {
        "dependencies": {
          "runtime.win-x64.Microsoft.NETCore.DotNetAppHost": "2.0.0"
        }
      },
      "Microsoft.NETCore.DotNetHostPolicy/2.0.0": {
        "dependencies": {
          "Microsoft.NETCore.DotNetHostResolver": "2.0.0",
          "runtime.win-x64.Microsoft.NETCore.DotNetHostPolicy": "2.0.0"
        }
      },
      "Microsoft.NETCore.DotNetHostResolver/2.0.0": {
        "dependencies": {
          "Microsoft.NETCore.DotNetAppHost": "2.0.0",
          "runtime.win-x64.Microsoft.NETCore.DotNetHostResolver": "2.0.0"
        }
      },
      "Microsoft.NETCore.Platforms/2.0.0": {},
      "NETStandard.Library/2.0.0": {
        "dependencies": {
          "Microsoft.NETCore.Platforms": "2.0.0"
        }
      },
      "runtime.win-x64.Microsoft.NETCore.App/2.0.0": {
        "runtime": {
          "runtimes/win-x64/lib/netcoreapp2.0/Microsoft.CSharp.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/Microsoft.VisualBasic.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/Microsoft.Win32.Primitives.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/Microsoft.Win32.Registry.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/SOS.NETCore.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.AppContext.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Buffers.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Collections.Concurrent.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Collections.Immutable.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Collections.NonGeneric.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Collections.Specialized.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Collections.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.ComponentModel.Annotations.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.ComponentModel.Composition.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.ComponentModel.DataAnnotations.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.ComponentModel.EventBasedAsync.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.ComponentModel.Primitives.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.ComponentModel.TypeConverter.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.ComponentModel.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Configuration.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Console.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Core.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Data.Common.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Data.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Diagnostics.Contracts.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Diagnostics.Debug.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Diagnostics.DiagnosticSource.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Diagnostics.FileVersionInfo.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Diagnostics.Process.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Diagnostics.StackTrace.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Diagnostics.TextWriterTraceListener.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Diagnostics.Tools.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Diagnostics.TraceSource.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Diagnostics.Tracing.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Drawing.Primitives.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Drawing.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Dynamic.Runtime.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Globalization.Calendars.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Globalization.Extensions.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Globalization.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.IO.Compression.FileSystem.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.IO.Compression.ZipFile.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.IO.Compression.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.IO.FileSystem.AccessControl.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.IO.FileSystem.DriveInfo.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.IO.FileSystem.Primitives.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.IO.FileSystem.Watcher.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.IO.FileSystem.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.IO.IsolatedStorage.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.IO.MemoryMappedFiles.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.IO.Pipes.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.IO.UnmanagedMemoryStream.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.IO.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Linq.Expressions.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Linq.Parallel.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Linq.Queryable.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Linq.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Net.Http.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Net.HttpListener.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Net.Mail.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Net.NameResolution.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Net.NetworkInformation.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Net.Ping.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Net.Primitives.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Net.Requests.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Net.Security.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Net.ServicePoint.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Net.Sockets.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Net.WebClient.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Net.WebHeaderCollection.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Net.WebProxy.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Net.WebSockets.Client.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Net.WebSockets.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Net.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Numerics.Vectors.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Numerics.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.ObjectModel.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Private.DataContractSerialization.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Private.Uri.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Private.Xml.Linq.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Private.Xml.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Reflection.DispatchProxy.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Reflection.Emit.ILGeneration.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Reflection.Emit.Lightweight.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Reflection.Emit.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Reflection.Extensions.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Reflection.Metadata.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Reflection.Primitives.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Reflection.TypeExtensions.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Reflection.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Resources.Reader.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Resources.ResourceManager.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Resources.Writer.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Runtime.CompilerServices.VisualC.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Runtime.Extensions.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Runtime.Handles.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Runtime.InteropServices.RuntimeInformation.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Runtime.InteropServices.WindowsRuntime.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Runtime.InteropServices.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Runtime.Loader.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Runtime.Numerics.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Runtime.Serialization.Formatters.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Runtime.Serialization.Json.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Runtime.Serialization.Primitives.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Runtime.Serialization.Xml.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Runtime.Serialization.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Runtime.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Security.AccessControl.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Security.Claims.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Security.Cryptography.Algorithms.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Security.Cryptography.Cng.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Security.Cryptography.Csp.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Security.Cryptography.Encoding.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Security.Cryptography.OpenSsl.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Security.Cryptography.Primitives.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Security.Cryptography.X509Certificates.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Security.Principal.Windows.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Security.Principal.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Security.SecureString.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Security.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.ServiceModel.Web.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.ServiceProcess.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Text.Encoding.Extensions.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Text.Encoding.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Text.RegularExpressions.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Threading.Overlapped.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Threading.Tasks.Dataflow.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Threading.Tasks.Extensions.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Threading.Tasks.Parallel.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Threading.Tasks.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Threading.Thread.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Threading.ThreadPool.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Threading.Timer.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Threading.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Transactions.Local.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Transactions.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.ValueTuple.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Web.HttpUtility.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Web.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Windows.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Xml.Linq.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Xml.ReaderWriter.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Xml.Serialization.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Xml.XDocument.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Xml.XPath.XDocument.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Xml.XPath.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Xml.XmlDocument.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Xml.XmlSerializer.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.Xml.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/System.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/WindowsBase.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/mscorlib.dll": {},
          "runtimes/win-x64/lib/netcoreapp2.0/netstandard.dll": {}
        },
        "native": {
          "runtimes/win-x64/native/Microsoft.DiaSymReader.Native.amd64.dll": {},
          "runtimes/win-x64/native/System.Private.CoreLib.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-console-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-datetime-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-debug-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-errorhandling-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-file-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-file-l1-2-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-file-l2-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-handle-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-heap-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-interlocked-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-libraryloader-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-localization-l1-2-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-memory-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-namedpipe-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-processenvironment-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-processthreads-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-processthreads-l1-1-1.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-profile-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-rtlsupport-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-string-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-synch-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-synch-l1-2-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-sysinfo-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-timezone-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-core-util-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-crt-conio-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-crt-convert-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-crt-environment-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-crt-filesystem-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-crt-heap-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-crt-locale-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-crt-math-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-crt-multibyte-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-crt-private-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-crt-process-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-crt-runtime-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-crt-stdio-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-crt-string-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-crt-time-l1-1-0.dll": {},
          "runtimes/win-x64/native/api-ms-win-crt-utility-l1-1-0.dll": {},
          "runtimes/win-x64/native/clrcompression.dll": {},
          "runtimes/win-x64/native/clretwrc.dll": {},
          "runtimes/win-x64/native/clrjit.dll": {},
          "runtimes/win-x64/native/coreclr.dll": {},
          "runtimes/win-x64/native/dbgshim.dll": {},
          "runtimes/win-x64/native/mscordaccore.dll": {},
          "runtimes/win-x64/native/mscordaccore_amd64_amd64_4.6.00001.0.dll": {},
          "runtimes/win-x64/native/mscordbi.dll": {},
          "runtimes/win-x64/native/mscorrc.debug.dll": {},
          "runtimes/win-x64/native/mscorrc.dll": {},
          "runtimes/win-x64/native/sos.dll": {},
          "runtimes/win-x64/native/sos_amd64_amd64_4.6.00001.0.dll": {},
          "runtimes/win-x64/native/ucrtbase.dll": {}
        }
      },
      "runtime.win-x64.Microsoft.NETCore.DotNetAppHost/2.0.0": {
        "native": {
          "runtimes/win-x64/native/apphost.exe": {}
        }
      },
      "runtime.win-x64.Microsoft.NETCore.DotNetHostPolicy/2.0.0": {
        "dependencies": {
          "Microsoft.NETCore.DotNetHostResolver": "2.0.0"
        },
        "native": {
          "runtimes/win-x64/native/hostpolicy.dll": {}
        }
      },
      "runtime.win-x64.Microsoft.NETCore.DotNetHostResolver/2.0.0": {
        "dependencies": {
          "Microsoft.NETCore.DotNetAppHost": "2.0.0"
        },
        "native": {
          "runtimes/win-x64/native/hostfxr.dll": {}
        }
      },
      "StandardLibrary/1.0.0": {
        "runtime": {
          "StandardLibrary.dll": {}
        }
      }
    }
  },
  "libraries": {
    "ConsoleMixingNetStandardAndCore/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    },
    "Microsoft.NETCore.App/2.0.0": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-/mzXF+UtZef+VpzzN88EpvFq5U6z4rj54ZMq/J968H6pcvyLOmcupmTRpJ3CJm8ILoCGh9WI7qpDdiKtuzswrQ==",
      "path": "microsoft.netcore.app/2.0.0",
      "hashPath": "microsoft.netcore.app.2.0.0.nupkg.sha512"
    },
    "Microsoft.NETCore.DotNetAppHost/2.0.0": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-L4GGkcI/Mxl8PKLRpFdGmLb5oI8sGIR05bDTGkzCoamAjdUl1Zhkov2swjEsZvKYT8kkdiz39LtwyGYuCJxm1A==",
      "path": "microsoft.netcore.dotnetapphost/2.0.0",
      "hashPath": "microsoft.netcore.dotnetapphost.2.0.0.nupkg.sha512"
    },
    "Microsoft.NETCore.DotNetHostPolicy/2.0.0": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-rm7mMn0A93fwyAwVhbyOCcPuu2hZNL0A0dAur9sNG9pEkONPfCEQeF7m2mC8KpqZO0Ol6tpV5J0AF3HTXT3GXA==",
      "path": "microsoft.netcore.dotnethostpolicy/2.0.0",
      "hashPath": "microsoft.netcore.dotnethostpolicy.2.0.0.nupkg.sha512"
    },
    "Microsoft.NETCore.DotNetHostResolver/2.0.0": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-uBbjpeSrwsaTCADZCzRk+3aBzNnMqkC4zftJWBsL+Zk+8u+W+/lMb2thM5Y4hiVrv1YQg9t6dKldXzOKkY+pQw==",
      "path": "microsoft.netcore.dotnethostresolver/2.0.0",
      "hashPath": "microsoft.netcore.dotnethostresolver.2.0.0.nupkg.sha512"
    },
    "Microsoft.NETCore.Platforms/2.0.0": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-VdLJOCXhZaEMY7Hm2GKiULmn7IEPFE4XC5LPSfBVCUIA8YLZVh846gtfBJalsPQF2PlzdD7ecX7DZEulJ402ZQ==",
      "path": "microsoft.netcore.platforms/2.0.0",
      "hashPath": "microsoft.netcore.platforms.2.0.0.nupkg.sha512"
    },
    "NETStandard.Library/2.0.0": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-7jnbRU+L08FXKMxqUflxEXtVymWvNOrS8yHgu9s6EM8Anr6T/wIX4nZ08j/u3Asz+tCufp3YVwFSEvFTPYmBPA==",
      "path": "netstandard.library/2.0.0",
      "hashPath": "netstandard.library.2.0.0.nupkg.sha512"
    },
    "runtime.win-x64.Microsoft.NETCore.App/2.0.0": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-8jivXDJLuJTxMQuInZaMiD2VbxehFmYAtn2V9mj9juaR5jH54/OBGmGv6SrIUVNqASXB/8dJbce/beIKnOzroQ==",
      "path": "runtime.win-x64.microsoft.netcore.app/2.0.0",
      "hashPath": "runtime.win-x64.microsoft.netcore.app.2.0.0.nupkg.sha512"
    },
    "runtime.win-x64.Microsoft.NETCore.DotNetAppHost/2.0.0": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-GKuVvomClOwspUg3ecEEieg5eOlJ26zA9BNH9tQcCJuz/z9SBdQHIwneCzVV88zEeSQJ+vRopL8nHLqZjGr8Uw==",
      "path": "runtime.win-x64.microsoft.netcore.dotnetapphost/2.0.0",
      "hashPath": "runtime.win-x64.microsoft.netcore.dotnetapphost.2.0.0.nupkg.sha512"
    },
    "runtime.win-x64.Microsoft.NETCore.DotNetHostPolicy/2.0.0": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-3za9dj6qb2OThjGmy/uFz6aKUlpWVi+vQ2l4+5uBrFaYZNXmCTsp87qk/qxK+dXiVdl3tt1YLphI04a4vE3hMw==",
      "path": "runtime.win-x64.microsoft.netcore.dotnethostpolicy/2.0.0",
      "hashPath": "runtime.win-x64.microsoft.netcore.dotnethostpolicy.2.0.0.nupkg.sha512"
    },
    "runtime.win-x64.Microsoft.NETCore.DotNetHostResolver/2.0.0": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-wDXLnFxnAU8hgo4MdvggGHGDcVTK4aqA/If6r0bxFUUxU4XMDjq0stQWqFRtgjrGoDsqVhxbop6HXrF/V28bVQ==",
      "path": "runtime.win-x64.microsoft.netcore.dotnethostresolver/2.0.0",
      "hashPath": "runtime.win-x64.microsoft.netcore.dotnethostresolver.2.0.0.nupkg.sha512"
    },
    "StandardLibrary/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    }
  }
}
```

Though I do expect the framework to be included in the publish, I thought based on the description at https://blogs.msdn.microsoft.com/webdev/2017/08/14/announcing-asp-net-core-2-0/ :

> What happens at publication time?  We know that you don’t want to publish the entire AspNetCore framework to your target environments, so the publish task now distributes only those libraries that you reference in your code.  This tree-pruning step should help make your publish process much smoother and easier to distribute your web applications.

that only the "used" pieces of the framework would be included in the publish.  As it stands currently, this "Hello world" publish is over 60MB

**Comment by eerhardt** [comment] 2017-09-06 21:04
@Kritner - When publishing a self-contained application, the entire framework is copied with your application.  This has been the case for .NET Core 1.0, 1.1, and for 2.0.  See https://docs.microsoft.com/en-us/dotnet/core/deploying/ for our docs on the different app models.

The feature being referenced in that [blog post](https://blogs.msdn.microsoft.com/webdev/2017/08/14/announcing-asp-net-core-2-0/) only applies to "framework-dependent" applications, and specifically it is talking about the ASP.NET runtime assemblies.  In .NET Core 2.0, a new [runtime package store](https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-store) feature was implemented to allow assemblies to be shared across multiple applications.  ASP.NET is taking advantage of that feature.

However, what you are asking for is currently being worked on and is in a preview state.  Check out https://www.hanselman.com/blog/ExperimentalReducingTheSizeOfNETCoreApplicationsWithMonosLinker.aspx for more information.

**Comment by eerhardt** [comment] 2017-09-06 21:05
Closing as this is intended behavior.

**Closed by eerhardt** 2017-09-06 21:05 UTC
