### ISSUE TITLE
[Package Validation]: Deprecating old .NET versions causes validation failure

### ISSUE THREAD

**Issue by dotMorten** [dotnet/sdk#21424] opened 2021-09-26 18:48 UTC
### Describe the bug

If I have a previous nuget package that supported .NET 5, and that build contained a few more members than the netstandard2.0 assembly, and my new version has dropped support for .NET 5 and moved to .NET 6, the validation tool will now compare the net5 assembly to the net2.0 assembly instead of the net5 assembly, and incorrectly say I've removed a set of members (my package has a build task that'll ensure net5 users will get a build error telling them to move to net6).
What I'd really like is to be able to direct the tool to compare net5 on left with net6 on the right, and make sure that beyond increasing the min requirements, there are no other breaking changes.

### To Reproduce
Create a project that has netstandard2.0 + net5.0 targets, and make net5 target have more members than netstandard2.0.
Next upgrade the version, remove net5 and include net6 instead, and compare the versions with the package validation tool.

### Exceptions (if any)
```
1>C:\Users\mn\.nuget\packages\microsoft.dotnet.packagevalidation\1.0.0-preview.5.21302.8\build\Microsoft.DotNet.PackageValidation.targets(24,5): error : API compatibility errors in between lib/net5.0-windows10.0.18362/Esri.ArcGISRuntime.dll (left) and lib/netstandard2.0/Esri.ArcGISRuntime.dll (right) for versions 100.12.0 and 100.13.0 respectively:
1>C:\Users\mn\.nuget\packages\microsoft.dotnet.packagevalidation\1.0.0-preview.5.21302.8\build\Microsoft.DotNet.PackageValidation.targets(24,5): error CP0002: Member 'Esri.ArcGISRuntime.ArcGISRuntimeEnvironment.TempPath.get' exists on the left but not on the right
1>C:\Users\mn\.nuget\packages\microsoft.dotnet.packagevalidation\1.0.0-preview.5.21302.8\build\Microsoft.DotNet.PackageValidation.targets(24,5): error CP0002: Member 'Esri.ArcGISRuntime.ArcGISRuntimeEnvironment.TempPath.set' exists on the left but not on the right
1>C:\Users\mn\.nuget\packages\microsoft.dotnet.packagevalidation\1.0.0-preview.5.21302.8\build\Microsoft.DotNet.PackageValidation.targets(24,5): error CP0002: Member 'Esri.ArcGISRuntime.Location.NmeaLocationDataSource.FromStreamCreator(System.Func<Esri.ArcGISRuntime.Location.NmeaLocationDataSource, System.Threading.Tasks.Task<System.IO.Stream>>, System.Func<Esri.ArcGISRuntime.Location.NmeaLocationDataSource, System.Threading.Tasks.Task>?)' exists on the left but not on the right
1>C:\Users\mn\.nuget\packages\microsoft.dotnet.packagevalidation\1.0.0-preview.5.21302.8\build\Microsoft.DotNet.PackageValidation.targets(24,5): error CP0002: Member 'Esri.ArcGISRuntime.Location.NmeaLocationDataSource.FromSerialPort(Windows.Devices.Enumeration.DeviceInformation, System.Nullable<uint>)' exists on the left but not on the right
1>C:\Users\mn\.nuget\packages\microsoft.dotnet.packagevalidation\1.0.0-preview.5.21302.8\build\Microsoft.DotNet.PackageValidation.targets(24,5): error CP0002: Member 'Esri.ArcGISRuntime.Location.NmeaLocationDataSource.FromBluetooth(Windows.Devices.Bluetooth.Rfcomm.RfcommDeviceService)' exists on the left but not on the right
1>C:\Users\mn\.nuget\packages\microsoft.dotnet.packagevalidation\1.0.0-preview.5.21302.8\build\Microsoft.DotNet.PackageValidation.targets(24,5): error CP0001: Type 'Esri.ArcGISRuntime.Location.SystemLocationDataSource' exists on the left but not on the right
```

### Further technical details
- Using .NET 6 RC1 + `<Sdk Name="Microsoft.DotNet.PackageValidation" Version="1.0.0-preview.5.21302.8" />`

**Comment by KalleOlaviNiemitalo** [comment] 2021-09-27 07:59
> (my package has a build task that'll ensure net5 users will get a build error telling them to move to net6)

If you had not done that, I think the compatibility warning would be entirely justified. However, I don't see a way to tell the compatibility checker that your package no longer supports net5.0 (but still supports netstandard2.0 and thus netcoreapp3.1). It can read a suppression file though, so perhaps you should suppress the warnings that way.

**Comment by dotMorten** [comment] 2021-09-27 13:36
I get that in a way it's right, but as versions go out it's expected that people will be dropping support for older platforms, so was hoping there was a way to handle this.

**Comment by KalleOlaviNiemitalo** [comment] 2021-09-28 04:31
I don't have a doc but the task has parameters for that.

**Comment by safern** [comment] 2022-02-03 20:57
@dotMorten I missed this issue. This is something that we hit on `dotnet/runtime` as well, and I've opened this issue in order to provide a way to ignore TFMs that were previously supported in the baseline package rather than trying to find a matching implementation in the new package, like in this case the `netstandard2.0` one: https://github.com/dotnet/sdk/issues/22901

Given that this is by design, and we already have an issue to ignore TFMs specified by the user, or a way to disable the warning via the suppressions file, I'm going to close this issue.

**Closed by safern** 2022-02-03 20:57 UTC
Labels: Area-Compatibility
