### ISSUE TITLE
Missing application icon for exe if built on Linux

### ISSUE THREAD

**Issue by MarkKoz** [dotnet/sdk#11046] opened 2020-03-30 02:21 UTC
I have an icon specified with `ApplicationIcon` in my .csproj. If I build the project on Windows 10 with runtime ID `win-x64`, the resulting exe has the specified icon - no problems. However, if I build the same project using the same RID on Linux, the exe does not have the application icon. I've seen the same issue on Linux both in CI (Azure agent is Ubuntu 18) and with my local install of Arch.

.NET SDK version: 3.1.102 (both on Windows and Linux)
TargetFramework: netcoreapp3.0
Command used: `dotnet build -c Release -r win-x64 /path/to/.csproj`

**Comment by dsplaisted** [comment] 2020-04-09 02:12
This sounds like a duplicate of https://github.com/dotnet/runtime/issues/486 and/or https://github.com/dotnet/runtime/issues/3828.  @vitek-karas, @swaroop-sridhar, is that correct?

**Closed by dsplaisted** 2020-04-09 02:12 UTC
Labels: needs triage

**Comment by swaroop-sridhar** [comment] 2020-04-09 05:18
Yes this is a dup of dotnet/runtime#3828
