### ISSUE TITLE
"dotnet build --no-restore" restores all dependencies

### ISSUE THREAD

**Issue by Ezneh** [dotnet/sdk#23279] opened 2022-01-05 08:45 UTC
Hi,

It has been a while since I've seen this error, and yet it seems nobody is aware of it:

`dotnet build --no-restore` just restores dependencies, which is totally wrong.

**Comment by Ezneh** [comment] 2022-01-06 04:48
Hi @rainersigwald , what I am seeing is that if I replace a dependency DLL with another one (newer version, but not available on Nuget), then it restores it to the previous version.

What I expect is that the DLL is not replaced until I build the project with implicit restore.

**Comment by KalleOlaviNiemitalo** [comment] 2022-01-06 06:08
In which directory do you replace the DLL?
Would `dotnet restore` copy the DLL to that directory?

**Comment by Ezneh** [comment] 2022-01-06 18:52
I replace the dll in `bin/Debug/net5.0`
Doing `dotnet restore` doesn't replace the dll afterwards, so my expectations on `--no-restore` might be optimistic.

**Comment by rainersigwald** [comment] 2022-01-07 15:50
Files are copied to the output directory as part of the build operation, not the restore operation, so I think the behavior you're seeing is expected.

Some people accomplish your goal by modifying the file in the NuGet package store, so it's the updated one that gets copied. If you choose to do this you should be aware that files in NuGet package store are intended to be immutable, so this will affect other projects and may require restarting processes to flush caches.

I'm going to close this as "by design" since the build seems to be doing the right thing.

**Closed by rainersigwald** 2022-01-07 15:50 UTC
Labels: untriaged, Area-NetSDK
