### ISSUE TITLE
GenAPI incorrectly generates collection-based interface implementation

### ISSUE THREAD

**Issue by mthalman** [dotnet/sdk#31570] opened 2023-03-31 15:45 UTC
When targeting System.Collections.Immutable.1.7.1, GenAPI generates a class implementation which doesn't implement the interface that its member explicitly attempts to implement.

This illustrates the issue:

```c#
public sealed partial class ImmutableHashSet<T> : IEnumerable, ICollection
{
    bool Generic.ICollection<T>.IsReadOnly { get { throw null; } }
}
```

This results in a build error:

```
error CS0540: 'ImmutableHashSet<T>.ICollection<T>.IsReadOnly': containing type does not implement interface 'ICollection<T>'
```

You can see that the generated class doesn't implement any of the generic interfaces that it should:

```c#
public sealed class ImmutableHashSet<T> : IImmutableSet<T>, IReadOnlyCollection<T>, IEnumerable<T>, IEnumerable, IHashKeyCollection<T>, ICollection<T>, ISet<T>, ICollection, IStrongEnumerable<T, ImmutableHashSet<T>.Enumerator>
```

**Comment by mthalman** [comment] 2023-03-31 18:14
There are other issues besides the list of interfaces the class implements as well.

It generates explicit `Item`, `get_Item`, and `set_Item` property interface implementations that shouldn't exist:

```c#
public partial struct ImmutableArray<T> : IEnumerable, IEquatable<ImmutableArray<T>>, IList, ICollection, IStructuralComparable, IStructuralEquatable
{
    T Generic.IList<T>.Item { get { throw null; } set { } }
    object IList.get_Item(int index) { throw null; }
    void IList.set_Item(int index, object value) { }
}
```

**Comment by mthalman** [comment] 2023-03-31 18:39
@ViktorHofer - There are quite a few issues here in how the code is generated for these classes that implement collection interfaces. I had to give up making manual updates in SBRP because there were just too many. I'm going to wait until this is fixed in the tooling. You can see the progress I had made with updates to the generated code in this commit: https://github.com/mthalman/source-build-reference-packages/commit/1448c8df56160cad25d50c26e9d577473fb65e63

**Comment by mthalman** [comment] 2023-04-03 15:08
cc @andriipatsula

**Comment by andriipatsula** [comment] 2023-04-03 15:12
There is a duplicated issue https://github.com/dotnet/sdk/issues/31484. And a PR: https://github.com/dotnet/sdk/pull/31545 that solves the problem.

**Comment by mthalman** [comment] 2023-04-03 15:38
@andriipatsula - The filtering out of interfaces is one thing. But what about the `IList<T>.Item` and `IList.get_Item` that I mention above?

**Comment by andriipatsula** [comment] 2023-04-03 16:53
Viktor is OOF for the next week+. I saw these types of issues when symbol resolution fails. I'll try to debug tomorrow.
If I am not mistaken, there should be `int Generic.IList<T>.this[int index]` instead of `Generic.IList<T>.*Item`.

**Comment by andriipatsula** [comment] 2023-04-05 11:13
```C#
T Generic.IList<T>.Item { get { throw null; } set { } }
T Generic.IList<T>.get_Item(int index) { throw null; }
void Generic.IList<T>.set_Item(int index, T value) { }
```
is a list of members that are present in the symbol metadata for the `IList<T>`, `IList`, `IReadOnlyList<T>` (etc.) interfaces. It appears to be a minor bug or a side effect, and filtering them out should be a simple task.

**Comment by andriipatsula** [comment] 2023-04-05 14:29
There are next 4 members(indexers) in the `ImmutableArray<T>`:
```C#
/*1*/ public T this[int index] { get { throw null; } }
/*2*/ T System.Collections.Generic.IList<T>.this[int index] { get { throw null; } set { } }
/*3*/ T System.Collections.Generic.IReadOnlyList<T>.this[int index] { get { throw null; } }
/*4*/ object System.Collections.IList.this[int index] { get { throw null; } set { } }
```

The indexer №1 is generated correctly and indexers №2, №3, №4 - not.
https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.ilist-1.item?view=net-8.0#system-collections-generic-ilist-1-item(system-int32)
For some reason, the `SyntaxGenerator` does not generate the `IList<T>.Item[Int32]` property as an indexer.

**Comment by MichaelSimons** [comment] 2023-04-05 14:49
> @mthalman, @MichaelSimons is the issue a blocker for you?

This is really impacting the TFM cleanup work.  I can workaround it but it is not ideal.

**Comment by andriipatsula** [comment] 2023-04-05 17:10
Created a PR https://github.com/dotnet/sdk/pull/31628. I was able to get a green build for the `System.Collections.Immutable,1.7.1`. I am pretty sure that the problem is in Roslyn API. I double checked that the SBRP tooling uses the correct reference assemblies.

**Comment by andriipatsula** [comment] 2023-04-06 10:03
@MichaelSimons , @mthalman the `dotnet/sdk` CI is blocked and I am OOF since tomorrow (Plus, as the problem is not related to the GenAPI it'd be better to not push "ugly" code to the main branch). In order to unblock you I suggest you use the local version of the GenAPI (with the work around I developed):
1. checkout a PR https://github.com/dotnet/sdk/pull/31628.
2. run `build.cmd` script in the repo.
3. `cd src\GenAPI\Microsoft.DotNet.GenAPI.Task\` and run `dotnet pack .\Microsoft.DotNet.GenAPI.Task.csproj`
> You must see the output containing:
 Successfully created package 'C:\Users\username\Projects\sdk\artifacts\packages\Release\NonShipping\Microsoft.DotNet.GenAPI.Task.8.0.100-dev.nupkg'.
5. in the `dotnet/source-build-reference-packages` repo:
    5.1. add to the `NuGet.config` file `<add key="local" value="C:\Users\username\Projects\sdk\artifacts\packages\Release\NonShipping\" />` (on windows: the value from the step above; on linux: copy `nuget` file from the step above to a linux machine and use it's path)
    5.2 modify the version of the `Microsoft.DotNet.GenAPI.Task` to `8.0.100-dev` in the `eng\Version.Details.xml` file.
    5.3 modify the valueof the `MicrosoftDotNetGenAPITaskPackageVersion` property to `8.0.100-dev` in the `eng\Versions.props` file.
6. clean nuget cache under the `%userprofile%\.nuget\packages\microsoft.dotnet.genapi.task\8.0.100-dev` (for win and ~ for linux)
7. run the SBRP generator.

**Comment by mmitche** [comment] 2023-04-07 19:28
It looks like the fix didn't correct the generation for net6, though it seems to have worked for net7

**Comment by ericstj** [comment] 2023-04-09 04:57
I spent some time looking at this and I couldn't reproduce any bug here: https://github.com/dotnet/sdk/pull/31678

I wonder if the original issue is caused by missing the reference for System.Collections.Generic.dll when generating source.

**Comment by ericstj** [comment] 2023-04-17 19:47
@mthalman are you still blocked on this?  Per the tests I did, I couldn't reproduce the issue.  Now that @ViktorHofer is baack maybe he can take a look at your repro?

**Comment by ViktorHofer** [comment] 2023-04-18 17:02
> I couldn't get this to fail. The following test passes for me: https://github.com/dotnet/sdk/pull/31678

This could have been an issue with not latest bits being used in SBRP by the A&D team. @mthalman can you please give this another try after https://github.com/dotnet/source-build-reference-packages/pull/642 is merged in?

**Comment by MichaelSimons** [comment] 2023-04-19 13:53
I tried this out on a few packages I was having troubles with earlier and it appears that the issue has been resolved.

**Comment by MichaelSimons** [comment] 2023-07-28 14:26
I am seeing this issue again.  Perhaps it is a slightly different scenario.

Steps to reproduce in https://github.com/dotnet/source-build-reference-packages:

1. ./generate.sh -x -p System.Security.Cryptography.X509Certificates,4.3.0
2. ./build.sh -sb

Build errors from generated code:

```
  /repos/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.security.cryptography.x509certificates/4.3.0/ref/netstandard1.4/System.Security.Cryptography.X509Certificates.cs(339,34): error CS0539: 'X509CertificateCollection.Item' in explicit interface declaration is not found among members of the interface that can be implemented [/repos/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.security.cryptography.x509certificates/4.3.0/System.Security.Cryptography.X509Certificates.4.3.0.csproj::TargetFramework=netstandard1.4] [/root/.nuget/packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23371.1/tools/Build.proj]
  /repos/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.security.cryptography.x509certificates/4.3.0/ref/netstandard1.4/System.Security.Cryptography.X509Certificates.cs(373,34): error CS0683: 'X509CertificateCollection.get_Item(int)' explicit method implementation cannot implement 'IList.this[int].get' because it is an accessor [/repos/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.security.cryptography.x509certificates/4.3.0/System.Security.Cryptography.X509Certificates.4.3.0.csproj::TargetFramework=netstandard1.4] [/root/.nuget/packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23371.1/tools/Build.proj]
  /repos/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.security.cryptography.x509certificates/4.3.0/ref/netstandard1.4/System.Security.Cryptography.X509Certificates.cs(381,32): error CS0683: 'X509CertificateCollection.set_Item(int, object)' explicit method implementation cannot implement 'IList.this[int].set' because it is an accessor [/repos/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.security.cryptography.x509certificates/4.3.0/System.Security.Cryptography.X509Certificates.4.3.0.csproj::TargetFramework=netstandard1.4] [/root/.nuget/packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23371.1/tools/Build.proj]
  /repos/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.security.cryptography.x509certificates/4.3.0/ref/netstandard1.4/System.Security.Cryptography.X509Certificates.cs(319,104): error CS0738: 'X509CertificateCollection' does not implement interface member 'IList.this[int]'. 'X509CertificateCollection.this[int]' cannot implement 'IList.this[int]' because it does not have the matching return type of 'object'. [/repos/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.security.cryptography.x509certificates/4.3.0/System.Security.Cryptography.X509Certificates.4.3.0.csproj::TargetFramework=netstandard1.4] [/root/.nuget/packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23371.1/tools/Build.proj]
```

The System.Collections.IList interface is not being generated correctly

Generated Code:

``` csharp
object Collections.IList.Item { get { throw null; } set { } }
object Collections.IList.get_Item(int index) { throw null; }
void Collections.IList.set_Item(int index, object value) { }
```

Expected Code:

``` csharp
object System.Collections.IList.this[int index] { get { throw null; } set { } }
```

cc @ericstj, @ViktorHofer, @andriipatsula

**Comment by MichaelSimons** [comment] 2023-07-28 14:29
I should mention in my previous repo, the version of Microsoft.DotNet.GenAPI.Task used is 8.0.100-rc.1.23374.2

**Comment by ericstj** [comment] 2023-07-28 16:03
Is it possible you're missing the reference that contains the definition for IList?

**Comment by ericstj** [comment] 2023-07-28 19:26
Root cause is this bug: https://github.com/dotnet/roslyn/issues/53911

The explicitly implemented indexer is not considered `IsIndexer` by the compiler API but SyntaxGenerator only considers this flag when deciding to emit the indexer.
https://github.com/dotnet/roslyn/blob/c6c59b799b84ee1505dab88cc097293bd65f7473/src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs#L741

I think I'll propose a fix to SyntaxGenerator and see where that discussion takes us.

**Comment by ericstj** [comment] 2023-07-28 21:16
So the reason this was "no repro" for me before was because at the time the tests were running from source-symbols.  It looks like this bug is only present for metadata symbols.  I updated the roslyn issue https://github.com/dotnet/roslyn/issues/53911#issuecomment-1656333267

**Closed** 2023-07-31 10:07 UTC
Labels: untriaged, Area-GenAPI
