### ISSUE TITLE
Running publish more than once copies the wrong depencencies with .Net Core 3

### ISSUE THREAD

**Issue by Abarbz** [dotnet/sdk#10913] opened 2020-03-19 10:24 UTC
Since I updated my build server with VS2019 and .Net Core 3, my deployment pipelines are failing.
The setup on my build server:

- .Net core version 3.1.200 installed

- publish command uses Build Engine version 16.5.0+d4cbfca49 for .NET Core.

After investigating, here's what I found:
My project is a rather simple self hostedAsp.Net core project, targeting net461.
If I publish it using
`publish "myAspNetCoreProject.csproj" -o "myOutputPath" -c release` 
The application will work as expected.
If I kill the application, and re-publish with the exact same command, then the application will start and stop immediately, without any trace, even in debug mode.
After checking the differences in "myOutputPath" between the two publish operations, I found that the 2nd publish seems to copy older version of some dependencies.
Here are the modification that are done: 

Changed dependencies          |    version after 1st publish |  version after 2nd publish
------------------------|-------------------------|-----------------------------------------------
System.AppContext.dll | 4.6.25714.01 | 4.6.23123.0
System.Console.dll | 4.6.25714.01 | 4.6.24705.01
System.Diagnostics.FileVersionInfo.dll | 4.6.25714.01 | 4.6.24705.01
System.Diagnostics.StackTrace.dll | 4.6.26011.01 | 4.6.24705.01
System.IO.Compression.dll | 4.6.26011.01 | 4.6.24705.01
System.IO.FileSystem.dll | 4.6.25714.01 | 4.6.24705.01
System.IO.FileSystem.Primitives.dll | 4.6.25714.01 | 4.6.24705.01
System.Runtime.InteropServices.RuntimeInformation.dll | 4.6.26011.01 | 4.6.24705.01
System.Security.Cryptography.Algorithms.dll | 4.6.26011.01 | 4.6.24705.01
System.Security.Cryptography.Encoding.dll | 4.6.25714.01 | 4.6.24705.01
System.Security.Cryptography.Primitives.dll | 4.6.25714.01 | 4.6.24705.01
System.Security.Cryptography.X509Certificates.dll | 4.6.25714.01 | 4.6.24705.01
System.Threading.Thread.dll | 4.6.25714.01 | 4.6.24705.01
System.Xml.ReaderWriter.dll | 4.6.25714.01 | 4.6.24705.01
System.Xml.XmlDocument.dll | 4.6.25714.01 | 4.6.24705.01
System.Xml.XPath.dll | 4.6.25714.01 | .6.24705.01
System.Xml.XPath.XDocument.dll | 4.6.26011.01 | 4.6.24705.01

- If I replace only those dependencies after the 2nd publish by their version produced by the 1st publish, it works.
- If I force an older version of dotnet core with a global.json containing

`"sdk": {
    "version": "2.1.804",
    "rollForward": "disable"
  }` it also works.

As a temporary solution, I have introduced a step that clears "myOutputPath"  before every publish operation, but that does not solve the root cause.

**Comment by wli3** [comment] 2020-04-08 20:39
@sfoslund could you look into this issue? It is in similar area as your publish incremental build improvement.

**Comment by sfoslund** [comment] 2020-05-04 21:59
@Abarbz I haven't been able to repro this issue, can you provide [a binlog](https://github.com/microsoft/msbuild/blob/master/documentation/wiki/Binary-Log.md) with the error?

**Comment by sfoslund** [comment] 2020-05-21 16:13
@Abarbz please reopen this if you can provide a binlog with the repro. Thanks!

**Comment by Abarbz** [comment] 2020-06-09 07:55
@sfoslund should I just provide you a basic binlog from `dotnet msbuild /bl` ?

**Comment by sfoslund** [comment] 2020-06-09 15:11
If you feel comfortable posting them here, that would be great (although please note that binlogs can contain any build secrets you may have, see [this doc](https://github.com/microsoft/msbuild/blob/master/documentation/wiki/Providing-Binary-Logs.md)).

**Comment by sfoslund** [comment] 2020-06-09 16:01
Sure, you can email it to me at sfoslund@microsoft.com

**Comment by dasMulli** [comment] 2020-06-09 16:11
@Abarbz is the output path local to your project directory? If so, does `-o ..\pubout` reproduce the issue?

**Comment by Abarbz** [comment] 2020-06-10 07:20
> @Abarbz is the output path local to your project directory? If so, does `-o ..\pubout` reproduce the issue?

No, it was actually published to a shared directory on a different machine.

**Comment by sfoslund** [comment] 2020-06-15 15:48
It looks like this is related to #10850. We're seeing a double write of the files listed in the original issue on the first publish, but presumably we get lucky and the correct files are written second. Then, when we publish again, we overwrite the correct files with the wrong ones because we think they've been updated, when really it's just a different version of the file.

**Comment by Abarbz** [comment] 2020-06-16 08:38
Anything I can do on my side to fix that? Or do I have to wait for an update of the tooling?

**Comment by sfoslund** [comment] 2020-06-16 15:31
It sounds like you have a work around for the time being, right? Beyond that, you'll likely have to wait for the root cause to be fixed.

**Comment by Abarbz** [comment] 2020-06-16 15:33
I'll keep my quick fix then. Thanks for the update!

**Comment by sfoslund** [comment] 2020-11-04 22:49
Fixed by #14020

**Closed by sfoslund** 2020-11-04 22:49 UTC
