### ISSUE TITLE
5.0 SDK requires an explicit reference to System.IO.Pipelines for a 3.1 classlibrary targeted ASP.NET Core

### ISSUE THREAD

**Issue by rynowak** [dotnet/sdk#14019] opened 2020-10-07 20:19 UTC
I'm getting errors like this when building with the .NET 5.0.100-rc.1.20452.10 SDK:

```
/Users/ryan/github.com/dapr/dotnet-sdk/src/Dapr.AspNetCore/DaprEndpointRouteBuilderExtensions.cs(47,72): error
CS0012: The type 'PipeWriter' is defined in an assembly that is not referenced. You must add a reference to assembly 
'System.IO.Pipelines, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [/Users/ryan/github.com
/dapr/dotnet-sdk/src/Dapr.AspNetCore/Dapr.AspNetCore.csproj]
```

when building a project that:

- targets `netcoreapp3.1`
- is a class library
- references `Microsoft.AspNetCore.App`
- uses `PipeWriter` in code
- does not explicitly reference the `System.IO.Pipelines` package

Example project: https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.AspNetCore/Dapr.AspNetCore.csproj

This is regression from the 3.1.301 SDK - which builds these projects successfully on the CI: https://github.com/dapr/dotnet-sdk/runs/1221898037?check_suite_focus=true

---

I can work around the problem by adding an explicit reference to the `System.IO.Pipelines` package (and I will do) - but it seems like this old bug came back.

**Comment by Pilchie** [comment] 2020-10-07 20:26
Tagging @marcpopMSFT  and @dougbu.  I wonder if the issue here is that the 5.0 SDK isn't actually using the latest version of the 3.1 Targeting pack, and is still picking up an older version that had [this bug](https://github.com/dotnet/aspnetcore/issues/19133).

**Comment by davidfowl** [comment] 2020-10-07 20:32
How does this keep happening 😄

**Comment by dougbu** [comment] 2020-10-07 20:43
> How does this keep happening 😄

If it's the same problem as our occasional out-of-date template versions, the attempted mitigation we've proposed is to update the versions in the dotnet/installer repo while rebranding for the next release i.e. just after each release. But, I don't see anything about 3.1 sharedFx or targeting pack versions in https://github.com/dotnet/installer/blob/master/eng/Versions.props @wtgodbe where should we look for the 3.1 aspnetcore versions pulled into 5.0 installers?

**Comment by wtgodbe** [comment] 2020-10-07 20:57
That's here (and is out of date, but not out of date enough to explain the presence of this bug) https://github.com/dotnet/installer/blob/beba26b3654bac769b3e74352094c0bb082b6054/eng/Versions.props#L111

I think the issue is this: https://github.com/dotnet/installer/blob/beba26b3654bac769b3e74352094c0bb082b6054/src/redist/targets/GenerateBundledVersions.targets#L46-L47. @wli3 @marcpopMSFT @sfoslund should we be updating these when we update the implicit versions in 5.x?

**Comment by wli3** [comment] 2020-10-07 21:00
Yes. Arcade cannot maintain both 5.0 and 3.x implicit versions, so we need to manually update them until there is a solution

**Comment by wtgodbe** [comment] 2020-10-07 21:06
https://github.com/dotnet/installer/pull/8813

**Comment by marcpopMSFT** [comment] 2020-10-07 21:07
@wli3 who would you recommend own these updates for both templates and targeting packs? I assume the owners of those packs/templates rather than us having to monitor for updates?  BTW, I think @joeloff had an internal bug that we determined was related to this that he was tracking: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1221892

**Comment by wli3** [comment] 2020-10-07 21:10
The corresponding teams in this case aspnet, template engine team or runtime team. At the same time, we should push for a better solution in arcade

**Comment by marcpopMSFT** [comment] 2020-10-07 21:12
@wli3 we should also ensure this is covered in tactics so folks are both aware and remember to do this as I don't want to have to remember to remind people.

**Comment by marcpopMSFT** [comment] 2020-10-08 23:51
Closing as the change to the installer repo has been merged.

**Closed by marcpopMSFT** 2020-10-08 23:51 UTC
