### ISSUE TITLE
PP file output is not generated during the build

### ISSUE THREAD

**Issue by emgarten** [dotnet/sdk#1100] opened 2017-04-07 19:09 UTC
PP file output is not being generated during the build.

### Steps
1. dotnet new
1. dotnet add package contentfilesexample -v 1.0.2
1. dotnet restore
1. Add to Program.cs ``Console.WriteLine(ExampleReader.GetDataText());``
1. dotnet build

### Expected
ExampleReader will be in the current namespace from the pp file.

### Actual
ExampleReader does not exist

Originally reported here https://github.com/NuGet/Home/issues/4803 //cc @damianh

From @natidea 

I took a look at the pp file transformation issue and found a couple of things:
- For the [ContentFilesExample](https://www.nuget.org/packages/ContentFilesExample/) package, I don't see pp files listed as dependencies in the assets file. They occur in the "libraries" but we are only processing content from the active TFM here: [Microsoft.PackageDependencyResolution.targets#L213](https://github.com/natidea/sdk/blob/0e64439c0660590ef93b1d86a6811a056b791bd8/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.PackageDependencyResolution.targets#L213)
- For the [LiteGuard](https://github.com/adamralph/liteguard) package, I do see the pp files in the dependencies, but they were not being processed because `CopyLocalLockFileAssemblies`=false here: [Microsoft.PackageDependencyResolution.targets#L414](https://github.com/natidea/sdk/blob/0e64439c0660590ef93b1d86a6811a056b791bd8/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.PackageDependencyResolution.targets#L414)
I was able to fix this by setting the property in my project file:
```xml
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
```
Now I can use the `Guard`. 

So somewhere along the way, some concepts may have been crossed. We default `CopyLocalLockFileAssemblies` to [true](https://github.com/natidea/sdk/blob/0e64439c0660590ef93b1d86a6811a056b791bd8/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.PackageDependencyResolution.targets#L38) in that target file, but it gets set to false in [Microsoft.NET.Sdk.BeforeCommon.targets#L57](https://github.com/natidea/sdk/blob/0e64439c0660590ef93b1d86a6811a056b791bd8/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.BeforeCommon.targets#L57). Perhaps the real issue is that the produce content assets task is tied to `ResolveLockFileCopyLocalProjectDeps` and should instead be triggered in some other way.

**Comment by jonsequitur** [comment] 2017-05-10 21:22
I'm seeing the same behavior with plain old un-preprocessed C# files.

**Comment by emgarten** [comment] 2017-05-10 21:39
@jonsequitur there shouldn't be any extra steps needed for .cs files. Check your props file under ``obj\projectname.csproj.nuget.g.props`` to see how your files are getting referenced from the package.

**Comment by jonsequitur** [comment] 2017-05-17 21:54
I see. I was hitting a bug where Visual Studio needs to be reopened before it will build the referenced file.

**Comment by mynkow** [comment] 2017-08-16 03:03
Please move this to milestone: 2.1.0

**Comment by jainaashish** [comment] 2017-09-29 20:31
This is important for customers to move from packages.config to PackageReference, so can we get some traction on it? And tries to make it for 2.1.0?

**Comment by adamralph** [comment] 2017-10-15 19:09
I'm not sure this problem exists any longer. I just tried to reproduce it like so:

1. Clone or download https://github.com/adamralph/blunt
2. `dotnet add package LiteGuard.Source`
3. `dotnet restore`
4. Open `Foo.cs`, and add `Guard.AgainstNullArgument("baz", baz);` to `Foo.Bar()`
5. `dotnet build`

Everything works perfectly!

<details>
<summary>
λ  dotnet --info
</summary>
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
</details>

**Comment by damianh** [comment] 2017-10-29 21:54
Am going to make another attempt https://github.com/damianh/LibLog/pull/149

**Comment by leastprivilege** [comment] 2018-04-09 16:10
Was this ever resolved. It seems pp files are simply ignored..

**Comment by serialseb** [comment] 2018-04-29 09:41
@adamralph it doesn't seem to me you're using pp files, that may be the reason

**Comment by leastprivilege** [comment] 2018-04-29 10:12
I should mention I got it working in the end.

**Comment by serialseb** [comment] 2018-04-30 05:06
That's good to know. SHould this issue be marked as fixed then?

**Comment by livarcocc** [comment] 2018-05-06 03:55
It seems we can now close this issue. Doing so now. If that's not the case, just comment and we can re-activate, or file a new issue.

**Closed by livarcocc** 2018-05-06 03:55 UTC

**Comment by ahmoh** [comment] 2018-05-10 13:06
I tried to make it work with `LiteGuard.Source` package but the .pp file doesn't get generated. The issue is closed so maybe I'm the issue.

**Comment by adamralph** [comment] 2018-05-24 16:08
@ahmoh I'm not sure what you mean. When you install the `LiteGuard.Source` package in a project, the .pp files are lifted from the package and transformed into .cs files for compilation. There is no _generation_ of .pp files in that workflow.

**Comment by ahmoh** [comment] 2018-05-26 14:10
@adamralph Sorry, wrong choice of word. What I meant is transform .pp into .cs. When I install the package `LiteGuard.Source` shouldn't the file Guard.cs.pp be transformed into Gauard.cs and copied to the root folder of the solution? 


I ran the test project in .net core console application with dotnet version = 2.1.200.

**Comment by adamralph** [comment] 2018-05-27 09:28
@ahmoh it doesn't work like that anymore. The pp file still gets transformed, but the resulting cs file doesn't appear anywhere. You can still use the `Guard` class as if it was part of your project.

Here's an example: [ConsoleApp9.zip](https://github.com/dotnet/sdk/files/2042413/ConsoleApp9.zip)

**Comment by ahmoh** [comment] 2018-05-27 17:04
@adamralph thanks for the example, but I was able to get that outcome also before. I'm disappointed that this feature doesn't work in .net core as it does in .net framework project.

**Comment by adamralph** [comment] 2018-05-30 12:41
@ahmoh what problems does the new mechanism cause you?

**Comment by ahmoh** [comment] 2018-05-30 21:20
@adamralph I want the user to be able to find the source file easily so he/her can edit it. Now it's hidden in my opinion 👎.

**Comment by ahmoh** [comment] 2018-06-03 16:18
adamralph interesting idea about templates. As long as I can accomplish my implementation. I'll give it a go.

**Comment by caioproiete** [comment] 2018-06-06 17:06
> 
> Source code packages are the wrong mechanism to distribute code which is intended to be edited. You should be using templates for that.
>

@adamralph Do you mean [Visual Studio Project Templates](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-project-templates) or something else - that can be distributed via NuGet?

The nice thing about NuGet is the composability it gives us. Let's say I want to create
* An Excel Add-In (say, with [Excel-DNA](https://github.com/Excel-DNA))
* That uses DevExpress controls (say, via [DevExpress-NuGet](https://github.com/caioproiete/DevExpress-NuGet#devexpress-nuget))
* That gets packaged into a single file (say, via [Fody.Costura](https://github.com/Fody/Costura))

With the old NuGet Package reference model, I can:

* Create an empty Class Library project
* Add the [ExcelDna.AddIn NuGet package](https://www.nuget.org/packages/ExcelDna.AddIn/) to it
  * Getting a nice `.dna` config template file **that I can modify / customize for my project**
* Add [DevExpress-NuGet package(s)](https://github.com/caioproiete/DevExpress-NuGet#devexpress-nuget) to it
* Add the [Costura.Fody NuGet package](https://www.nuget.org/packages/Costura.Fody/) to it
  * Getting a nice `.xml` config template file **that I can modify / customize for my project**
 
---

How would the above scenario work with the templates you mention?

If they were project templates, I'd have to choose **1** - either start with an `Excel-DNA project template`, or a `DevExpress project template` or a `Costura.Fody` project template... That doesn't work.

If they were project item templates, I'd have to install 6 different things (3 NuGet packages and 3 VSIX) instead of 3 - or am I missing something?

**Comment by dasMulli** [comment] 2018-06-06 17:10
There's also the new `dotnet new` templates which also supports item templates.
Those can be installed via `dotnet new --install NuGet.Pkg.Name.Of.TemplatesPkg`.

Dropping files into the project will depend on the project type..

Quite a few projects used app.config transforms that were applied to the project's app.config file. But since not all runtimes (.NET Core) use this file or relevant sections of this file, that may be pretty useless.

**Comment by caioproiete** [comment] 2018-06-06 17:15
@dasMulli Good point on `dotnet new`. However, why make that an extra step for the developer - who would have to read the documentation to understand that after installing the nuget packages, he/she needs to run `dotnet new dnaconfig` then `dotnet new fodyconfig` etc...

The current NuGet Package Reference approach is so much better in that aspect, that the user is up and running after a single `install-package bla`, given that it brings everything he/she needs to get started...

**Comment by dasMulli** [comment] 2018-06-06 17:39
`install-package` is a vs-only concept though.
Users are also taught that they can just add `<PackageReference>` items into the csproj on platforms where there is no NuGet tooling. `dotnet add package` does the same as well and afaik doesn't even run `init.ps1` (simply because there isn't a PowerShell Core runtime bundled with `dotnet`).

The next point is that updates never really worked if you needed to roll out a change to the default file..

**Comment by dfoulk** [comment] 2018-06-11 21:36
@adamralph @dasMulli - Are you guys saying that it's no longer possible to add/update files in a user's project? If so, then I think some edge cases have been left unconsidered...

For example, we're trying to work out how to add a **Xamarin.Android/Resources/values/colors.xml** file and update a user's **Xamarin.Android/Resources/values/styles.xml** with the colors from **colors.xml** (via our Xamarin.Forms theme plugin). The changes simply apply our company color scheme to the Android version of the app.

Once installed, these values won't change- but even if they did, the updates would be reflected as desired. Am I missing something?

If this functionality is not possible, it would be great to find out for sure so that we can move to "plan b". I really hope this is doable as it seems like it was possible before!

**Comment by adamralph** [comment] 2018-06-16 07:19
Perhaps there are scenarios which are not covered. WRT to source code I believe the new mechanism is better than the old. For templating, there is also [SideWaffle](http://sidewaffle.com/) which has item templates as well as project templates. Templating is a better mechanism than packages for content that is intended for editing. In that scenario, you effectively want a "snapshot" of external content at some point in time which you then evolve to your needs, rather than taking a permanent _dependency_ on a package, the contents of which will follow it's own path of change.

**Comment by dfoulk** [comment] 2018-06-19 17:45
@adamralph - Thank you for the link. I will check it out!

The example I provided was just a portion of the overall package we were building. The other part(s) of the package contained a Xamarin.Forms theme (resource dictionary) as well as some other Xamarin.Forms controls. The overall package was designed to completely theme each of our new and existing applications to the corporate "theme"/"layout" (which in Xamarin.Forms requires supplemental files to added/updated to achieve).

I suppose it is just frustrating that we can no longer copy files to disk while managing versions via NuGet Package Manager- especially considering that said functionality was present in previous versions.

Can we still copy files to disc using non-.NET Standard libraries? If so, would you mind sharing how we can still do this? I heard mention of .NET Standard packages using Init.ps1 to copy files into the user's project (somehow)? Any information would be greatly appreciated!

**Comment by adamralph** [comment] 2018-06-19 18:02
I'm afraid I don't know anything about these special use cases. I don't have a need for them.

**Comment by dfoulk** [comment] 2018-06-19 18:13
Lol worth a shot- thanks man!
