### ISSUE TITLE
Docker - NU3028: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by tankbob** [dotnet/sdk#15509] opened 2021-01-27 13:46 UTC
Has something changed with the docker images, I am unable to build today as I receive a spate of these errors

error NU3028: Package 'Microsoft.Extensions.DependencyInjection 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
error NU3028: Package 'Microsoft.Extensions.Configuration 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain

This is using a docker file that has the following snippet

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["nuget.config","."]
COPY ["HTMLBuilder/HTMLBuilder.csproj", "HTMLBuilder/"]
RUN dotnet restore "HTMLBuilder/HTMLBuilder.csproj" --configfile nuget.config
COPY . .
WORKDIR "/src/HTMLBuilder"
RUN dotnet build "HTMLBuilder.csproj" -c Release -o /app/tool

**Comment by dasMulli** [comment] 2021-01-27 14:16
Seems like a dupe of https://github.com/NuGet/Home/issues/10491

**Comment by marcpopMSFT** [comment] 2021-01-27 21:28
Closing as the NuGet issue will track this.

**Closed by marcpopMSFT** 2021-01-27 21:28 UTC
Labels: Area-NuGet
