### ISSUE TITLE
MSBuild 17.9.4 no longer reports code style errors in build

### ISSUE THREAD

**Issue by metoule** [dotnet/sdk#39142] opened 2024-03-01 16:52 UTC
### Describe the bug
With .NET SDK 8.0.101, a project using `<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>` correctly reports IDE0036 (for example), while .NET SDK 8.0.200 no longer reports the error.

With MSBuild 17.8.3:

![image](https://github.com/metoule/msbuild-17.9.4-editorconfig/assets/24547430/7e3ceca5-4703-4e17-ad7f-e96d470e4563)

With MSBuild 17.9.4:

![image](https://github.com/metoule/msbuild-17.9.4-editorconfig/assets/24547430/07f91e52-f067-4542-944b-376d0a72c6a1)

### To Reproduce
Github repo: https://github.com/metoule/msbuild-17.9.4-editorconfig

### Further technical details
`dotnet --info`

```
.NET SDK:
 Version:           8.0.200
 Commit:            438cab6a9d
 Workload version:  8.0.200-manifests.cdf2cc8e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.200/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  8.0.200 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

- IDE: `dotnet build`

**Comment by metoule** [comment] 2024-03-07 08:20
It's similar, except that my repro fails even if there's no mix between severity settings from `dotnet_diagnostic.IDExxxx.severity` and `option_name = option_value:severity`, as suggested by https://github.com/dotnet/roslyn/issues/52991#issuecomment-1960692440, contrary to the other issue's repro project.

**Comment by cremor** [comment] 2024-03-07 08:50
@mavasani FYI
Is this also fixed by https://github.com/dotnet/roslyn/pull/72238 and https://github.com/dotnet/sdk/pull/38968 ?

**Comment by js6pak** [comment] 2024-03-07 21:59
@mavasani This is caused by `GetEffectiveCustomTags` only being applied in `DiagnosticHelper.Create`, when diagnostics like [`IDE0058`](https://github.com/dotnet/roslyn/blob/3fa9ffdf035f5e139ef0e1f3e3df9156ab301294/src/Analyzers/Core/Analyzers/FileHeaders/AbstractFileHeaderDiagnosticAnalyzer.cs#L71) or [`IDE0036`](https://github.com/dotnet/roslyn/blob/191840b1c9dad0c4fd2e94d792d93a52c8d31840/src/Analyzers/Core/Analyzers/OrderModifiers/AbstractOrderModifiersDiagnosticAnalyzer.cs#L73-L75) use `Diagnostic.Create` directly.

**Closed** 2024-05-31 19:17 UTC
Labels: untriaged, Area-Workloads
