### ISSUE TITLE
Publishing single file application with custom icon via dotnet cli on Docker

### ISSUE THREAD

**Issue by jacekard** [dotnet/sdk#10670] opened 2020-02-18 14:10 UTC
Hello,
I'm glad that in the newest .NET Core version there's a possibility to change an application icon, however it looks like it's limited to publishing in local environment. Is Docker not supported?

What I'm trying to achieve:
Publishing self-contained, single file executable using 'dotnet publish' command and with the icon file I'm specifying in project's csproj using Docker container. 
It works using Visual Studio 'Publish' button on local Windows. It doesn't work while using dotnet cli using docker container.

My configuration using Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core:

This is .Net Core 3.1 Console Application with defined icon as below:
```
<PropertyGroup>
    ....
   <ApplicationIcon>icon.ico</ApplicationIcon>
</PropertyGroup>
```
Publish command is executed using command:
`dotnet publish -c Release -o out`

On the left side there is executable published on host machine. On the right, docker container.
Not only it lacks icon but also some of the assembly info. Could anyone explain to me why there's such a difference?
![image](https://user-images.githubusercontent.com/26470750/74746193-53d71300-5265-11ea-8d81-75823663a77c.png)

**Comment by swaroop-sridhar** [comment] 2020-02-20 20:55
@nguerrera  @wli 
This work is subsumed by https://github.com/dotnet/runtime/issues/3828
So, I think we can close this as a dup.

**Comment by nguerrera** [comment] 2020-02-20 20:56
Duplicate of dotnet/runtime#3828

**Closed by nguerrera** 2020-02-20 20:56 UTC
