### ISSUE TITLE
Net 7 sdk build freezes computer

### ISSUE THREAD

**Issue by timcassell** [dotnet/sdk#27697] opened 2022-09-06 14:08 UTC
With a simple hello world console app, building with .Net 7 sdk uses a ton of memory and freezes my computer until it is complete. And it takes much longer to complete than .Net 6 sdk.

```cs
class Program
{
    static void Main(string[] args)
    {
        System.Console.WriteLine("Hello World");
    }
}
```

With command `dotnet build -c Release -f net6.0`

![image](https://user-images.githubusercontent.com/35501420/188653760-03fb13f0-6582-41b5-8da0-777742ce7240.png)

I only have 8 GB of memory in my computer, so if I build a larger project (like a BenchmarkDotNet project), it consumes 100% of my memory and locks up my computer for several minutes, where .Net 6 sdk uses very little memory and completes in seconds.

I'm on Windows 7 SP1 x64, with AMD Phenom II X6 cpu, 8GB DDR3 memory. .Net SDK 7.0.100-preview.7

[Edit] Also, the process hangs for a little while after the command has completed and the output printed to the console, while .Net 6 sdk immediately terminates when it's complete (see the trailing memory usage in the image).

**Comment by timcassell** [comment] 2022-11-09 22:30
Still an issue with the new released SDK (7.0.100). I am also getting errors with the build that I am not getting in SDK 6 when I try to compile BenchmarkDotNet:

```
FFaaiilleedd  ttoo  ccrreeaattee  CCoorreeCCLLRR,,  HHRREESSUULLTT::  00xx88000077000000EE

Failed to create CoreCLR, HRESULT: 0x8007000E
C:\Program Files\dotnet\sdk\7.0.100\Roslyn\Microsoft.CSharp.Core.targets(79,5): error : Failed to create CoreCLR, HRESULT: 0x8007000E [C:\BenchmarkDotNet\src\BenchmarkDotNet.Annotations\BenchmarkDotNet.Annotations.csproj::TargetFramework=netstandard2.0]

The build failed. Fix the build errors and run again.
```

**Comment by michaldobrodenka** [comment] 2022-11-14 12:34
My solution can't be build with SDK7. `dotnet publish` with SDK6 takes about 1.5minutes on average PC, with SDK7 - I killed it after 2 hours.

**Comment by lorenblue** [comment] 2022-11-16 10:21
Want to add that this is my experience as well. I simply cannot build a simple console app on my lightsail Ubuntu instance without it freezing the system or getting "killed." .Net 6 is no problem.

**Comment by Pyrdacor** [comment] 2022-11-24 08:18
Yeah have the same issue as well after upgrading Visual Studio to the latest version and the SDK got updated. :/ Can't compile anymore. This is urgent!!!

**Comment by michaldobrodenka** [comment] 2022-11-24 08:21
Only solution I found is to change projects back to net6 and build in net6 sdk docker

**Comment by Pyrdacor** [comment] 2022-11-24 09:07
I use a global.json with SDK 6 as a workaround. If you curious you can find how it's setup here: https://learn.microsoft.com/en-us/dotnet/core/versions/selection

**Comment by MichalPetryka** [comment] 2022-11-25 02:05
.Net 7 is not supported on Win 7, does this reproduce on supported OS versions?

**Comment by timcassell** [comment] 2022-11-25 02:28
> .Net 7 is not supported on Windows 7

Then why does it install and let you try to build without telling you it's not supported? Where's the documentation that says it's not supported? We're talking about the sdk itself, not visual studio. 

> does this reproduce on supported OS versions?

@lorenblue Already mentioned that this issue occurs on Ubuntu also.

**Comment by MichalPetryka** [comment] 2022-11-25 02:34
> Where's the documentation that says it's not supported?

[Here.](https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md)

**Comment by danmoseley** [comment] 2022-11-25 02:48
.NET 7 is indeed not supported on Windows 7. Please update your OS or stick with .NET 6.

Cc @richlander  for the feedback about making the installer block on Windows 7.

Most of the issues above seem to relate to Windows 7: please open a separate issue for other problems (e.g. Ubuntu). If it's a runtime issue rather than related to the SDK/build/CLI then dotnet/runtime might be the right repo.

**Comment by MichalPetryka** [comment] 2022-11-25 02:49
> Cc @richlander for the feedback about making the installer block on Windows 7.

I think that having it warn instead would be a better idea.

**Comment by timcassell** [comment] 2022-11-25 03:02
Or at least link to the list of supported os versions on the download page.

**Comment by michaldobrodenka** [comment] 2022-11-25 06:32
I have similar problem on Win10 and also in official net7 sdk docker

**Comment by Pyrdacor** [comment] 2022-11-25 07:21
> .Net 7 is not supported on Windows 7, does this reproduce on supported OS versions?

Does this mean that I am limited to C#10 on Win7 as well? This would be really bad. In fact a huge amount of my customers still use Win7.

**Comment by MichalPetryka** [comment] 2022-11-25 19:16
> Does this mean that I am limited to C#10 on Win7 as well? This would be really bad. In fact a huge amount of my customers still use Win7.

C#11 is only officially supported with .Net 7 so yes. Most things should work with older runtimes though, but it's not officially supported there.

**Comment by tapika** [comment] 2022-11-26 08:36
I've uninstalled Net 7 SDK once, since it was not working. But then run Visual studio update, and it managed to successfully install Net 7 SDK again.

I've realized this after running all integration tests on [swupd@develop](https://github.com/tapika/swupd/tree/develop) in elevated mode and getting blue screen of death.

Memory usage is quite aggressive - I'm running out of memory immediately for tests, but this maybe related or not related issue to Net 7 SDK.

**Comment by MichalPetryka** [comment] 2022-11-26 15:35
Does this reproduce with `DOTNET_GCName=clrgc.dll` (on Linux the name will be different) set in the environment?

**Comment by timcassell** [comment] 2022-11-27 00:53
> Does this reproduce with `DOTNET_GCName=clrgc.dll` (on Linux the name will be different) set in the environment?

I can't speak for other OSes, but on Win 7, yes it does. And what's worse, I can't even kill the process from the Task Manger. I either have to wait for it to stop, or hard reboot my PC.

![image](https://user-images.githubusercontent.com/35501420/204114400-aa29713d-0b4b-47dc-a077-6bf01edce9bb.png)

**Comment by Pyrdacor** [comment] 2022-12-09 05:53
> .Net 7 is not supported on Windows 7, does this reproduce on supported OS versions?

My question would be why it consumes so much memory. This also happens outside of VS when running from the CLI. This shouldn't be specific to some OS. I guess it only is noticable on systems with low memory (e.g. 8 GB).

Would be interesting to test with Win10 and 8GB ram. I don't think this is caused by OS incompatibility. It's just a very high memory consumption.

**Comment by loop-evgeny** [comment] 2022-12-15 08:44
Happens to me as well with .NET SDK 7.0.101, on two Windows 7 x64 SP1 machines. Completely kills each machine (16GB and 32GB RAM) - it uses up not only all physical RAM, but all swap space as well. One of the machines typically blue-screens eventually!

OK, I get that Windows 7 is "not supported", but it should't do _that_!

I didn't even want to use .NET 7. I just wanted to update VS to 17.4, but that automatically installed the .NET 7 SDK. The rest of VS 17.4 seems to work fine. If this is not going to be fixed the VS installer should not install .NET 7 SDK on Windows 7. (I tried to unselect that under "Individual components", but the only option there is ".NET 7.0 Runtime" and unselecting that removes a bunch of other stuff - basically everything .NET-related.)

**Comment by teo-tsirpanis** [comment] 2022-12-15 10:10
@loop-evgeny [Not even Visual Studio 2022 is supported on Windows 7.](https://learn.microsoft.com/en-us/visualstudio/releases/2022/system-requirements#supported-operating-systems)

**Comment by loop-evgeny** [comment] 2022-12-15 12:11
"Not supported" is fine with me, as long as it works, which it does. Just don't artificially prevent me from installing it is all I'm asking.

**Comment by MichalPetryka** [comment] 2022-12-15 12:12
> "Not supported" is fine with me, as long as it works, which it does. Just don't artificially prevent me from installing it is all I'm asking.

As you literally said before, nothing's blocking it right now.

**Comment by loop-evgeny** [comment] 2022-12-15 12:17
Right. I'm just asking to keep it that way. (Since there is talk of blocking the installation of .NET 7 SDK on Windows 7, and VS 17.4 automatically installs that and is itself not supported on Windows 7, I thought someone might come up with the clever "solution" of blocking the installation of VS 17.4 on Windows 7, too, so I'm pre-emptively asking MS to not do that.)

**Comment by michaldobrodenka** [comment] 2022-12-15 12:29
I've created an issue - similar problem on Windows10 https://github.com/dotnet/sdk/issues/29571

**Comment by pkorsukov** [comment] 2023-01-10 15:01
Thanks to the above Speakers, I found some kind of a workaround for the situation when dotnet freezes and hangs the entire development computer. 
The workaround allows to keep Visual Studio 2022 17.4 (no rollback to 17.3) on Windows 7 and make dotnet utility workable from command line (or from third party applications). Here are the steps you can use on your own risk:
1. Install .NET SDK 6 downloading it from the official website.
2. Navigate to C:\Program Files\dotnet\sdk
3. Make sure you have the .NET 6 version in place (folder 6.0.404 in my case)
4. Rename .NET 7 SDK folder (named 7.0.101 in my case) to 0.0.0
5. Migrate all your projects back to .NET 6

These steps will force any call of dotnet utility to use the .NET 6 SDK as the latest found version even if the dotnet.exe itself is version 7. Visual Studio keep working and I was able to continue the development. I also was able to debug my application which relays on dotnet CLI. So, no need to reinstall VS to 17.3 or older.

On the other hand, after applying the workaround, each time a dotnet build completes I can see a new .NET Host project consuming 350Mb RAM which doesn't get cleared even after the main process closure. So, each time I kill the process manually from Task Manager. It is good enough for debug purposes.

The funniest thing in regards to the bug in this topic: without workaround Visual Studio can build a project, but using CLI or a third party app you can't do it. So, it looks like there is some magic undocumented parameter in place that Microsoft keeps to themselves. My Dear Microsoft, with all respect, please don't be Evil...

**Comment by IS4Code** [comment] 2023-04-25 16:57
Same issue here. What seems to happen is that building runs NuGet verification on the workload packages, whatever that is, resulting in the parallel execution of these commands:
```
dotnet nuget verify --all %tmp%\3804909a-e14d-46bb-b026-704e11402577\microsoft.net.sdk.tvos.manifest-7.0.100.msi.x64\16.1.2551\microsoft.net.sdk.tvos.manifest-7.0.100.msi.x64.16.1.2551.nupkg
dotnet nuget verify --all %tmp%\3804909a-e14d-46bb-b026-704e11402577\microsoft.net.workload.emscripten.net6.manifest-7.0.100.msi.x64\7.0.5\microsoft.net.workload.emscripten.net6.manifest-7.0.100.msi.x64.7.0.5.nupkg
dotnet nuget verify --all %tmp%\3804909a-e14d-46bb-b026-704e11402577\microsoft.net.sdk.maccatalyst.manifest-7.0.100.msi.x64\16.2.2054\microsoft.net.sdk.maccatalyst.manifest-7.0.100.msi.x64.16.2.2054.nupkg
dotnet nuget verify --all %tmp%\3804909a-e14d-46bb-b026-704e11402577\microsoft.net.sdk.ios.manifest-7.0.100.msi.x64\16.2.2054\microsoft.net.sdk.ios.manifest-7.0.100.msi.x64.16.2.2054.nupkg
dotnet nuget verify --all %tmp%\3804909a-e14d-46bb-b026-704e11402577\microsoft.net.sdk.macos.manifest-7.0.100.msi.x64\13.1.2054\microsoft.net.sdk.macos.manifest-7.0.100.msi.x64.13.1.2054.nupkg
dotnet nuget verify --all %tmp%\3804909a-e14d-46bb-b026-704e11402577\microsoft.net.sdk.android.manifest-7.0.100.msi.x64\33.0.46\microsoft.net.sdk.android.manifest-7.0.100.msi.x64.33.0.46.nupkg
```

This matches the lines in <code>dotnet/sdk/*version*/IncludedWorkloadManifests.txt</code>, but changing that file has no effect. These commands are also invoked when you run `dotnet workload update`, so you can test that without building the project.

Now the actual issue (as has been pointed out) is that each `dotnet` instance using any SDK starting from .NET 7 **may take up to 8 GB** memory. This memory is not actually in active use, and it does not appear in Task Manager or Process Explorer, but it is used and creating 6 `dotnet` processes will take any reasonable amount of RAM you may have, and the OS starts swapping like crazy.

Finally this lead me to dotnet/runtime#79469. **Setting `DOTNET_EnableWriteXorExecute=0` eliminated the issue,** at least for now. Not sure what it does, not sure why it prevents this behaviour, but I am sure glad it worked.

@timcassell @michaldobrodenka @lorenblue @Pyrdacor @tapika @loop-evgeny @pkorsukov Tagging to help fellow Windows 7 supporters 😉

**Comment by loop-evgeny** [comment] 2023-05-03 08:16
OMG, it works! Thank you so much, @IS4Code!

**Comment by baronfel** [comment] 2024-01-30 20:30
Going to close this as .NET 7 isn't supported on Windows 7, and users have documented the workaround here.

**Closed by baronfel** 2024-01-30 20:30 UTC
Labels: untriaged, Area-Install
