### ISSUE TITLE
Create a ClassLibrary project in command-line, then execute "dotnet build" failed with error:" Invalid 'nullable' value: 'Enable' for C# 7.3..."

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/sdk#18306] opened 2021-06-17 06:43 UTC
**Azure DevOps work item:** 
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1343540

**Testcases Affected**

[[3.1] WebAppWithClassLibViaCommandLine](https://github.com/aspnet/Tooling-ManualTests/blob/rel/16.10/E2EWalkthroughs/VS/AspNetCore30/30_WebAppMvcViaCmdLine.md)

**Platform**
- [x] Windows
- [x] macOS
- [ ] Linux

**Repro Steps**
1. Run open up a normal Command Prompt (do not run as administrator)
2. Create an empty solution and open up the folder in VS Code:
```
   md CommandLineProjects
   cd CommandLineProjects
   dotnet new sln
   code .
```
3. Create class library:
```
   md ClassLibrary 
   cd ClassLibrary 
   dotnet new classlib -f netstandard2.0
```
4. Build solution and run the web app:
```
   dotnet build
```

**NOTE:**
It can work after adding the code```<LangVersion>8.0</LangVersion>``` in ClassLibrary.csproj file
![image](https://user-images.githubusercontent.com/71361488/122343962-db778380-cf78-11eb-9457-92aadbaa0352.png)

**Actual Result**

CSC: error CS8630: Invalid 'nullable' value: 'Enable' for C# 7.3. Please use language version '8.0' or greater.
![image](https://user-images.githubusercontent.com/71361488/122344080-f9dd7f00-cf78-11eb-8d11-d3c1a2614bfd.png)

**Error Log**

**Comment by v-wenkecheng** [comment] 2021-06-17 09:49
The version on Mac is 8.10 (build 1773)+ 6.0.100-preview.6.21315.23, it also reproduce. When creating a class library, execute the command "dotnet build" failed with error:" Invalid'nullable' value:'Enable' for C# 7.3...

**Comment by balachir** [comment] 2021-06-17 17:23
Closing as it's a dupe of https://github.com/dotnet/sdk/issues/18289

**Closed by balachir** 2021-06-17 17:23 UTC
Labels: untriaged
