### ISSUE TITLE
workloadID --print-downloadlink-only is returning urls of all workloads installed in machine

### ISSUE THREAD

**Issue by GouriKumari** [dotnet/sdk#18919] opened 2021-07-12 14:43 UTC
Dotnet Version ->  6.0.0-preview.6.21352.12
.NET6 Workloads installed in machine -> "maui-android", "maui-ios", "maui-maccatalyst", "tvos", "macos", "net-sdk-webassembly"

Execute: `dotnet workload install microsoft-android-sdk-full  --print-download-link-only` from command line
Expected Behaviour: It should return only dependency urls related to maui and android
Actual Behaviour:  All dependency urls of all workloads installed are returned
```
Resolving package urls for workload(s) microsoft-android-sdk-full...
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .

==allPackageLinksJsonOutputStart==
["https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.net.sdk.tvos.manifest-6.0.100/15.0.100-preview.6.63/microsoft.net.sdk.tvos.manifest-6.0.100.15.0.100-preview.6.63.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.net.sdk.android.manifest-6.0.100/30.0.100-preview.6.62/microsoft.net.sdk.android.manifest-6.0.100.30.0.100-preview.6.62.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.net.sdk.maui.manifest-6.0.100/6.0.100-preview.6.985/microsoft.net.sdk.maui.manifest-6.0.100.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.net.sdk.macos.manifest-6.0.100/12.0.100-preview.6.63/microsoft.net.sdk.macos.manifest-6.0.100.12.0.100-preview.6.63.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.net.sdk.maccatalyst.manifest-6.0.100/15.0.100-preview.6.63/microsoft.net.sdk.maccatalyst.manifest-6.0.100.15.0.100-preview.6.63.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.net.sdk.ios.manifest-6.0.100/15.0.100-preview.6.63/microsoft.net.sdk.ios.manifest-6.0.100.15.0.100-preview.6.63.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.net.workload.mono.toolchain.manifest-6.0.100/6.0.0-preview.6.21352.12/microsoft.net.workload.mono.toolchain.manifest-6.0.100.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.android.sdk.darwin/30.0.100-preview.6.62/microsoft.android.sdk.darwin.30.0.100-preview.6.62.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.android.sdk.bundletool/30.0.100-preview.6.62/microsoft.android.sdk.bundletool.30.0.100-preview.6.62.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.android.ref/30.0.100-preview.6.62/microsoft.android.ref.30.0.100-preview.6.62.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.android.templates/30.0.100-preview.6.62/microsoft.android.templates.30.0.100-preview.6.62.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.netcore.app.runtime.mono.android-arm/6.0.0-preview.6.21352.12/microsoft.netcore.app.runtime.mono.android-arm.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.netcore.app.runtime.mono.android-arm64/6.0.0-preview.6.21352.12/microsoft.netcore.app.runtime.mono.android-arm64.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.netcore.app.runtime.mono.android-x64/6.0.0-preview.6.21352.12/microsoft.netcore.app.runtime.mono.android-x64.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.netcore.app.runtime.mono.android-x86/6.0.0-preview.6.21352.12/microsoft.netcore.app.runtime.mono.android-x86.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.net.runtime.runtimeconfigparser.task/6.0.0-preview.6.21352.12/microsoft.net.runtime.runtimeconfigparser.task.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.net.runtime.monoaotcompiler.task/6.0.0-preview.6.21352.12/microsoft.net.runtime.monoaotcompiler.task.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.tvos.sdk/15.0.100-preview.6.63/microsoft.tvos.sdk.15.0.100-preview.6.63.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.tvos.ref/15.0.100-preview.6.63/microsoft.tvos.ref.15.0.100-preview.6.63.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.tvos.templates/15.0.100-preview.6.63/microsoft.tvos.templates.15.0.100-preview.6.63.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.netcore.app.runtime.mono.tvos-arm64/6.0.0-preview.6.21352.12/microsoft.netcore.app.runtime.mono.tvos-arm64.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.netcore.app.runtime.mono.tvossimulator-x64/6.0.0-preview.6.21352.12/microsoft.netcore.app.runtime.mono.tvossimulator-x64.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.netcore.app.runtime.aot.osx-x64.cross.tvos-arm64/6.0.0-preview.6.21352.12/microsoft.netcore.app.runtime.aot.osx-x64.cross.tvos-arm64.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.netcore.app.runtime.aot.osx-x64.cross.tvossimulator-x64/6.0.0-preview.6.21352.12/microsoft.netcore.app.runtime.aot.osx-x64.cross.tvossimulator-x64.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.core.ref.maccatalyst/6.0.100-preview.6.985/microsoft.maui.core.ref.maccatalyst.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.core.runtime.maccatalyst/6.0.100-preview.6.985/microsoft.maui.core.runtime.maccatalyst.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.controls.ref.maccatalyst/6.0.100-preview.6.985/microsoft.maui.controls.ref.maccatalyst.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.controls.runtime.maccatalyst/6.0.100-preview.6.985/microsoft.maui.controls.runtime.maccatalyst.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.essentials.ref.maccatalyst/6.0.100-preview.6.985/microsoft.maui.essentials.ref.maccatalyst.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.essentials.runtime.maccatalyst/6.0.100-preview.6.985/microsoft.maui.essentials.runtime.maccatalyst.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.aspnetcore.components.webview.maui/6.0.100-preview.6.985/microsoft.aspnetcore.components.webview.maui.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.dependencies/6.0.100-preview.6.985/microsoft.maui.dependencies.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.controls.sdk/6.0.100-preview.6.985/microsoft.maui.controls.sdk.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.extensions/6.0.100-preview.6.985/microsoft.maui.extensions.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.resizetizer.sdk/6.0.100-preview.6.985/microsoft.maui.resizetizer.sdk.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.templates/6.0.100-preview.6.985/microsoft.maui.templates.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maccatalyst.sdk/15.0.100-preview.6.63/microsoft.maccatalyst.sdk.15.0.100-preview.6.63.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maccatalyst.ref/15.0.100-preview.6.63/microsoft.maccatalyst.ref.15.0.100-preview.6.63.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maccatalyst.templates/15.0.100-preview.6.63/microsoft.maccatalyst.templates.15.0.100-preview.6.63.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.netcore.app.runtime.mono.maccatalyst-x64/6.0.0-preview.6.21352.12/microsoft.netcore.app.runtime.mono.maccatalyst-x64.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.netcore.app.runtime.aot.osx-x64.cross.maccatalyst-x64/6.0.0-preview.6.21352.12/microsoft.netcore.app.runtime.aot.osx-x64.cross.maccatalyst-x64.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.core.ref.ios/6.0.100-preview.6.985/microsoft.maui.core.ref.ios.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.core.runtime.ios/6.0.100-preview.6.985/microsoft.maui.core.runtime.ios.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.controls.ref.ios/6.0.100-preview.6.985/microsoft.maui.controls.ref.ios.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.controls.runtime.ios/6.0.100-preview.6.985/microsoft.maui.controls.runtime.ios.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.essentials.ref.ios/6.0.100-preview.6.985/microsoft.maui.essentials.ref.ios.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.essentials.runtime.ios/6.0.100-preview.6.985/microsoft.maui.essentials.runtime.ios.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.ios.sdk/15.0.100-preview.6.63/microsoft.ios.sdk.15.0.100-preview.6.63.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.ios.windows.sdk/15.0.100-preview.6.63/microsoft.ios.windows.sdk.15.0.100-preview.6.63.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.ios.ref/15.0.100-preview.6.63/microsoft.ios.ref.15.0.100-preview.6.63.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.ios.templates/15.0.100-preview.6.63/microsoft.ios.templates.15.0.100-preview.6.63.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.netcore.app.runtime.mono.ios-arm/6.0.0-preview.6.21352.12/microsoft.netcore.app.runtime.mono.ios-arm.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.netcore.app.runtime.mono.ios-arm64/6.0.0-preview.6.21352.12/microsoft.netcore.app.runtime.mono.ios-arm64.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.netcore.app.runtime.mono.iossimulator-x64/6.0.0-preview.6.21352.12/microsoft.netcore.app.runtime.mono.iossimulator-x64.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.netcore.app.runtime.mono.iossimulator-x86/6.0.0-preview.6.21352.12/microsoft.netcore.app.runtime.mono.iossimulator-x86.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.netcore.app.runtime.aot.osx-x64.cross.ios-arm/6.0.0-preview.6.21352.12/microsoft.netcore.app.runtime.aot.osx-x64.cross.ios-arm.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.netcore.app.runtime.aot.osx-x64.cross.ios-arm64/6.0.0-preview.6.21352.12/microsoft.netcore.app.runtime.aot.osx-x64.cross.ios-arm64.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.netcore.app.runtime.aot.osx-x64.cross.iossimulator-x64/6.0.0-preview.6.21352.12/microsoft.netcore.app.runtime.aot.osx-x64.cross.iossimulator-x64.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.netcore.app.runtime.aot.osx-x64.cross.iossimulator-x86/6.0.0-preview.6.21352.12/microsoft.netcore.app.runtime.aot.osx-x64.cross.iossimulator-x86.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.core.ref.android/6.0.100-preview.6.985/microsoft.maui.core.ref.android.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.core.runtime.android/6.0.100-preview.6.985/microsoft.maui.core.runtime.android.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.controls.ref.android/6.0.100-preview.6.985/microsoft.maui.controls.ref.android.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.controls.runtime.android/6.0.100-preview.6.985/microsoft.maui.controls.runtime.android.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.essentials.ref.android/6.0.100-preview.6.985/microsoft.maui.essentials.ref.android.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.maui.essentials.runtime.android/6.0.100-preview.6.985/microsoft.maui.essentials.runtime.android.6.0.100-preview.6.985.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.net.runtime.webassembly.sdk/6.0.0-preview.6.21352.12/microsoft.net.runtime.webassembly.sdk.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.netcore.app.runtime.mono.browser-wasm/6.0.0-preview.6.21352.12/microsoft.netcore.app.runtime.mono.browser-wasm.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.netcore.app.runtime.aot.osx-x64.cross.browser-wasm/6.0.0-preview.6.21352.12/microsoft.netcore.app.runtime.aot.osx-x64.cross.browser-wasm.6.0.0-preview.6.21352.12.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.net.runtime.emscripten.2.0.21.node.osx-x64/6.0.0-preview.6.21275.1/microsoft.net.runtime.emscripten.2.0.21.node.osx-x64.6.0.0-preview.6.21275.1.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.net.runtime.emscripten.2.0.21.python.osx-x64/6.0.0-preview.6.21275.1/microsoft.net.runtime.emscripten.2.0.21.python.osx-x64.6.0.0-preview.6.21275.1.nupkg","https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/584a7373-0b0b-4c82-9b63-389e7f842423/nuget/v3/flat2/microsoft.net.runtime.emscripten.2.0.21.sdk.osx-x64/6.0.0-preview.6.21275.1/microsoft.net.runtime.emscripten.2.0.21.sdk.osx-x64.6.0.0-preview.6.21275.1.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.macos.sdk/12.0.100-preview.6.63/microsoft.macos.sdk.12.0.100-preview.6.63.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.macos.ref/12.0.100-preview.6.63/microsoft.macos.ref.12.0.100-preview.6.63.nupkg","https://pkgs.dev.azure.com/azure-public/3ccf6661-f8ce-4e8a-bb2e-eff943ddd3c7/_packaging/be90bfa8-5c00-452b-ba9f-226ce4366992/nuget/v3/flat2/microsoft.macos.templates/12.0.100-preview.6.63/microsoft.macos.templates.12.0.100-preview.6.63.nupkg"]
==allPackageLinksJsonOutputEnd==
```

**Comment by sfoslund** [comment] 2021-07-15 21:34
@GouriKumari I just added test coverage for this locally and confirmed that we already check to make sure that we're only including urls for packs that are not installed on the machine. It's possible that you were seeing a bug that was fixed in https://github.com/dotnet/sdk/pull/18673, but I think more likely this is a result of a manifest update. 

When the install command is run without the `--skip-manifest-update` option we determine which packs need to be downloaded based on a new set of manifests which are downloaded dynamically, instead of the manifests that are currently installed. This means that the new manifests may define updated versions for any of the packs that are currently installed, including packs from workloads that are already installed. As a result we'll include those pack urls in our output, which can be confusing because they are associated with a workload that is already installed, but is necessary to keep all the packs in sync with the current manifests. If you want to opt out of this behavior and install based on the current manifests, you can always include the `--skip-manifest-update` option. 

I'm going to close this as there appears to be no action, but feel free to follow up if you have further questions, thanks!

**Closed by sfoslund** 2021-07-15 21:34 UTC
Labels: Area-Workloads
