### ISSUE TITLE
'dotnet run' command should fail with unknow arguments

### ISSUE THREAD

**Issue by jmarolf** [dotnet/sdk#23136] opened 2021-12-22 05:07 UTC
##  Description

If someone forgets to put `--project` in front of a path to a csproj file when executing the `dotnet run` command this file path is added as a third argument to the program.

## Repro steps:
1. `dotnet new console --name consoleApp`
1. add the following to `Program.cs`
```csharp
using static System.Console;

WriteLine($"'{args.Length}' arguments passed to program");

for (int i = 0; i < args.Length; i++) {
    WriteLine($"[{i}]: '{args[i]}'");
}
```
1. execute `dotnet run .\consoleApp.csproj -- --list-files nddemo.txt`

## Expected:

I think there are two reasonable things that `dotnet run` could do.

### 1. Implicitly swallow the csproj argument

See that an arg that is given before `--` maps to a project file whose path is identical to the one found in the directory and elide this argument.  Meaning that all three of these commands are equivalent if there is a `consoleApp.csproj` in the working directory:
    - `dotnet run --project .\consoleApp.csproj -- --list-files nddemo.txt`
    - `dotnet run .\consoleApp.csproj -- --list-files nddemo.txt`
    - `dotnet run -- --list-files nddemo.txt`

Running either of these three commands would produce this output for the program given in the repo steps.

```cmd
> dotnet run .\consoleApp.csproj -- --list-files nddemo.txt
'2' arguments passed to program
[0]: '--list-files'
[1]: 'nddemo.txt'
```

### 2. Error stating that there is an unknown argument

Any arguments that are not know and come before a `--` argument should be errors and not silently passed on as additional arguments. So the output in the repo steps should be:

```cmd
> dotnet run .\consoleApp.csproj -- --list-files nddemo.txt
Error: unknown argument '.\consoleApp.csproj '
if you intend to pass this as an additional argument to the program being run place it after '--'
```

## Actual:
```cmd
> dotnet run .\consoleApp.csproj -- --list-files nddemo.txt
'3' arguments passed to program
[0]: '.\consoleApp.csproj'
[1]: '--list-files'
[2]: 'nddemo.txt'
```

**Comment by baronfel** [comment] 2022-01-04 20:56
Completely agree @jmarolf, my preference would be towards eliding the project file if present. This might require some massaging of UnparsedTokens in System.CommandLine parlance, but the UX is worth it, and passing any parameters on the left of the `--` to the invoked program is just wrong.

**Comment by KalleOlaviNiemitalo** [comment] 2022-01-04 21:31
.\consoleApp.csproj could also act as an implicit `--`. So `dotnet run .\consoleApp.csproj --force` would pass `--force` to the executed program but `dotnet run --project .\consoleApp.csproj --force` would parse `--force` as an option of dotnet run. Much like how `nice` and `env` parse their options.

OTOH if someone used `dotnet run .\consoleApp.csproj -- --force` then I don't know whether the `--` should be passed to the program or consumed by dotnet run.

**Comment by jmarolf** [comment] 2022-01-04 22:03
@KalleOlaviNiemitalo I personally disagree

I am fine with `dotnet run .\consoleApp.csproj` being a special case but I think the general behavior of `dotnet run RANDOM_ARG` not failing is bad UX. we should require it to be `dotnet run -- RANDOM_ARG`  and have the `--` be required to clearly indicate what are args to `dotnet run` and what are args to the executable itself.

**Comment by marcpopMSFT** [comment] 2022-01-05 22:53
For 6.0.3xx, let's treat everything to the left of the -- as an argument to run and error if the call is not valid. For 7.0.1xx, we can explore supporting an implied --project.

**Comment by baronfel** [comment] 2022-01-05 23:00
Also for 6.0.3xx, only items to the right of `--` should be forwarded to the executed application.

**Comment by KalleOlaviNiemitalo** [comment] 2022-01-06 06:12
Then the help needs to change from `[[--] [application arguments]]` to `[-- [application arguments]]`.

**Comment by baronfel** [comment] 2022-06-10 17:22
Amending my position somewhat on this one after learning more about `--` handling and POSIX. I now think that we should _only_ allow project selection in the following two ways:
* Implicit discovery when the first argument to `dotnet run` is not a project file, and
* explicit selection by use of the `--project` option

The contract of the `run` command is 'run the selected project, passing all non-run-related parameters to the application'. As mentioned above, if the first parameter is a project file, that creates an ambiguous situation where the first argument could be the selected project _or_ a valid argument to pass to the underlying application. CLI users have a mechanism for disambiguating parameters in such situations: `--`. Per the posix spec, `--` is used when everything to the right of the token should be parsed as an argument (not options, etc) and for `run` all arguments are intended to be pass-throughs to the underlying application.

### Sample Output

```shell
>dotnet run foo.csproj a b c 
Couldn't find a project to run. 'foo.csproj' was passed as a positional argument, but could be interpreted as
* an argument to the project being run, or
* a project to run. 

If you meant to run the project use '--project foo.csproj', as in 'dotnet run --project foo.csproj a b c'
If you intended to pass 'foo.csproj' to the application being run use '-- foo.csproj', as in 'dotnet run -- foo.csproj a b c'
```

**Comment by Tunduk** [comment] 2022-07-28 13:44
@baronfel Hi! I continue to fight with double dash issues =)
Seems like the issue is resolved. One thing - error message isn't like you described 
Output
`Couldn't find a project to run. Ensure a project exists in %currentPath%, or pass the path to the project using --project.`
Should we add more information information in the output  message or we can close the issue?

**Comment by Tunduk** [comment] 2022-08-03 18:59
@baronfel another ping for you. I just want to close the issue =)

**Comment by baronfel** [comment] 2022-08-03 21:57
I think that message is fine for now - we can always extend it later. I think that means we can close this one.

**Comment by Tunduk** [comment] 2022-08-03 22:02
@baronfel  So can we close the issue as resolved by #26761?

**Comment by baronfel** [comment] 2022-08-03 22:03
Completed in #26761

**Closed by baronfel** 2022-08-03 22:03 UTC
Labels: good first issue, Area-CLI

**Comment by Tunduk** [comment] 2022-08-03 22:07
@baronfel  Thanks for your help. Could I mention you in case if I find a similar issue?

**Comment by baronfel** [comment] 2022-08-03 22:08
Of course! And thank you again for all of your help and interest in the CLI :)
