### ISSUE TITLE
Cannot get a .NET Core 3.1 app to run on .NET 6 with `dotnet run` on macos-arm64

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#21401] opened 2021-09-25 00:05 UTC
This is what I tried to.

```bash
rich@MacBook-Air-M1-2020 dotnet-runtimeinfo % rm -r bin obj
rich@MacBook-Air-M1-2020 dotnet-runtimeinfo % dotnet build /p:TargetFramework=net6.0 --restore
Microsoft (R) Build Engine version 17.0.0-preview-21470-01+cb055d28f for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /Users/rich/git/core/samples/dotnet-runtimeinfo/dotnet-runtimeinfo.csproj (in 275 ms).
  Determining projects to restore...
  Restored /Users/rich/git/core/samples/dotnet-runtimeinfo/dotnet-runtimeinfo.csproj (in 32 ms).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  dotnet-runtimeinfo -> /Users/rich/git/core/samples/dotnet-runtimeinfo/bin/Debug/net6.0/dotnet-runtimeinfo.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.85
rich@MacBook-Air-M1-2020 dotnet-runtimeinfo % dotnet run --no-build /p:TargetFramework=net6.0
System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/Users/rich/git/core/samples/dotnet-runtimeinfo/bin/Debug/netcoreapp3.1/dotnet-runtimeinfo' with working directory '/Users/rich/git/core/samples/dotnet-runtimeinfo'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
rich@MacBook-Air-M1-2020 dotnet-runtimeinfo % ls bin/Debug 
net6.0
rich@MacBook-Air-M1-2020 dotnet-runtimeinfo % ./bin/Debug/net6.0/dotnet-runtimeinfo
         42
         42              ,d                             ,d
         42              42                             42
 ,adPPYb,42  ,adPPYba, MM42MMM 8b,dPPYba,   ,adPPYba, MM42MMM
a8"    `Y42 a8"     "8a  42    42P'   `"8a a8P_____42   42
8b       42 8b       d8  42    42       42 8PP"""""""   42
"8a,   ,d42 "8a,   ,a8"  42,   42       42 "8b,   ,aa   42,
 `"8bbdP"Y8  `"YbbdP"'   "Y428 42       42  `"Ybbd8"'   "Y428

**.NET information
Version: 6.0.0
FrameworkDescription: .NET 6.0.0-rc.2.21470.23
Libraries version: 6.0.0-rc.2.21470.23
Libraries hash: 826f81a11ad17f415668fe1cb934bdaf00d36ea2

**Environment information
ProcessorCount: 8
OSArchitecture: Arm64
OSDescription: Darwin 21.1.0 Darwin Kernel Version 21.1.0: Sat Sep 11 12:27:45 PDT 2021; root:xnu-8019.40.67.171.4~1/RELEASE_ARM64_T8101
OSVersion: Unix 12.0.0
``

**Comment by sfoslund** [comment] 2021-09-29 16:45
> An error occurred trying to start process '/Users/rich/git/core/samples/dotnet-runtimeinfo/bin/Debug/netcoreapp3.1/dotnet-runtimeinfo'

Looks like the TargetFramewok property specified on the command line isn't getting passed through. I wonder if it's possible that it's parsing that token as a run argument instead of a property. @richlander does the issue persist if you use the syntax `--property TargetFramework=net6.0` instead?

**Comment by sfoslund** [comment] 2021-11-18 22:34
@richlander I just investigated and found that this is because properties passed using the `/p` option are forwarded to msbuild on restore/ build, so in this case when you've specified the `--no-build` option they have no effect. If you want to specify the TFM on run, you should use the `--framework/-f` option instead. I've confirmed that the app runs correctly on a M1 when the command is `dotnet run --no-build --framework net6.0`, so closing this issue.

**Closed by sfoslund** 2021-11-18 22:34 UTC
