### ISSUE TITLE
dotnet watch run reverts to old behaviour when --launch-profile flag is provided

### ISSUE THREAD

**Issue by ipazanin** [dotnet/sdk#24115] opened 2022-02-26 16:17 UTC
### Describe the bug
`dotnet watch run` reverts to old behaviour when `--launch-profile` option is provided.
Old behaviour meaning - on file changes process is restarted.

### To Reproduce
```sh
mkdir test
cd test
dotnet new webapi
dotnet watch run --launch-profile test
```

### Further technical details
`dotnet --info`:
.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    4c30de7899

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.1
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.200/

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  6.0.200 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by pranavkm** [comment] 2022-02-28 23:43
Thanks for the issue report. This is a dupe of https://github.com/dotnet/aspnetcore/issues/31365. Currently watch does not support specifying arguments when hot reload is enabled. We'll use the other issue to track resolving this.

**Closed by pranavkm** 2022-02-28 23:43 UTC
Labels: untriaged, Area-Watch
