### ISSUE TITLE
Copy runtime libraries from references project

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/sdk#776] opened 2017-02-01 09:13 UTC
Moved from dotnet/cli#5511 on behalf of @oryol

-----

I have Library.csproj with following code:
`<ItemGroup>
    <Content Include="runtimes\win7-x86\native\**\*">
      <PackagePath>.</PackagePath>
      <Pack>true</Pack>
    </Content>
  </ItemGroup>`

When I run dotnet pack, I can see native dll-s in the generated package.
If I reference this NuGet package (using my own feed) in the another project then all libraries are correctly placed into bin folder. But if I reference this project directly then libraries are not copied.

We need to have one uniform way to add native libraries into project and use them in all scenarios:

- Directly in this project
- In other project that references this project
- In the generated NuGet package

**Comment by srivatsn** [comment] 2017-02-01 16:05
Dupe of #765

**Closed by srivatsn** 2017-02-01 16:05 UTC
