### ISSUE TITLE
Unable to obtain lock file access on '/tmp/NuGetScratch/lock/...' since .NET 7

### ISSUE THREAD

**Issue by Socolin** [dotnet/sdk#29394] opened 2022-12-05 18:28 UTC
### Describe the bug

I have 2 users on my computer (Linux, Ubuntu 20.04) one for myself and one used by an azure devops agent that build the solution. 

When I'm working on the solution with my user, the command `dotnet restore` is failing on the build server

This was working fine until I installed .NET 7 sdk

```
Unable to obtain lock file access on '/tmp/NuGetScratch/lock/9d44d83c2af3cfd899a033f524442ea238044935' for operations on '/home/azure-agent/agent1/_work/1/Nuget/tempNuGet_13529.config'. This may mean that a different user or administrator is holding this lock and that this process does not have permission to access it. If no other process is currently performing an operation on this file it may mean that an earlier NuGet process crashed and left an inaccessible lock file, in this case removing the file '/tmp/NuGetScratch/lock/9d44d83c2af3cfd899a033f524442ea238044935' will allow NuGet to continue.
```

### To Reproduce

2 users on linux, trying to restore a similar project  at the same time.

### Further technical details

```
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  3.1.425 [/usr/share/dotnet/sdk]
  5.0.408 [/usr/share/dotnet/sdk]
  6.0.403 [/usr/share/dotnet/sdk]
  7.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.31 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.31 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by kartheekp-ms** [comment] 2022-12-06 00:57
This issue doesn't appear to be caused by October 2022 NuGet servicing. Transferring this issue to NuGet repo for further investigation.

**Comment by kartheekp-ms** [comment] 2022-12-06 03:58
NuGet side tracking issue: https://github.com/NuGet/Home/issues/12299. Please upvote or comment on the NuGet issue so that it can be prioritized based on the customer feedback.

**Closed by kartheekp-ms** 2022-12-06 03:58 UTC
Labels: untriaged
