### ISSUE TITLE
Certain files ignored by EmbeddedResource task

### ISSUE THREAD

**Issue by gliesefire** [dotnet/sdk#42524] opened 2024-08-04 18:57 UTC
### Describe the bug

I am trying to embed some files in my assembly. But any file which ends with *.uk.j(son) is ignored by the build.
e.g. out of the below list of files

- uk.json
- uk.json.txt
- x.dev.uk.json
- x.local.uk..json
- x.local.uk.j
- x.local.uk.js
- x.local.uk.jso
- x.local.uk.json
- x.local.us.json
- x.localuk.json
- x.staging.uk.json
- x.uk.json
- x.uk.json.txt
- x.uk.local.json
- x.uk.txt

Only following files are embedded, and rest all of them are ignored.

- uk.json
- x.local.uk..json
- x.local.us.json
- x.localuk.json
- x.uk.local.json
- uk.json.txt
- x.uk.json.txt

I have tried the following things (and many of it's permutations)

- Building the project
  - in linux OS
  - in Windows OS
  - with .NET 9 preview 6 SDK
  - with .NET 8 SDK
  - with .NET 6 SDK
  - with target framework set as `net9.0`
  - with target framework set as `net8.0`
  - with target framework set as `net6.0`
- Changing the contents of the file
- With / Without a global.json
- `OutputType` as Exe
- `OutputType` as library

I have also inspected the assembly file manually with [ildasm](https://learn.microsoft.com/en-us/dotnet/framework/tools/ildasm-exe-il-disassembler). It doesn't contain the file either. You can view a dump of it [here](https://github.com/gliesefire/embedded-resource-bug-repro/blob/main/net8.0_manifest_output.txt).

### To Reproduce

A minimalistic reproducible build is hosted [here](https://github.com/gliesefire/embedded-resource-bug-repro). It contains all the above file names (the content doesn't seem to matter).

### Exceptions (if any)

- None

### Further technical details

- [dotnet-info output](https://gist.github.com/gliesefire/4ca07185bbcb1cbfb3f907c47e650d1a)
- Tried VS, VS Code, command line

**Comment by baronfel** [comment] 2024-08-04 19:05
My guess is that you are hitting the issue we describe [in this MSbuild issue](https://github.com/dotnet/msbuild/issues/9152) - essentially MSBuild has a legacy behavior of trying to infer a Culture for a given EmbeddedResource, and that detection may be causing your resources to be skipped. Try setting the `Culture` metadata directly on each resource, or setting `WithCulture="false"` on all of the resources.

**Comment by gliesefire** [comment] 2024-08-04 19:22
Setting the `Culture` metadata directly didn't work. I tried various known cultures (both country code format, and `CultureInfo` format), but setting `WithCulture="false"` worked!. Thank you :)

Is this issue documented somewhere? If not, I can add it if needed.

**Comment by baronfel** [comment] 2024-08-04 19:58
The issue I linked is the canonical tracking issue for this, if it's ok with you I'll close this one as a duplicate. Glad the workaround worked for you! 

In the future we hope to ship a build analyzer that will give users warnings when this kind of potentially-unintended behavior happens during the build.

**Comment by gliesefire** [comment] 2024-08-04 20:32
Sure, I'm okay with that. Once again, thank you for the quick response.

**Closed** 2024-08-04 21:15 UTC
Labels: untriaged, Area-CLI
