### ISSUE TITLE
Add .deps.json file for desktop web apps when PreserveCompilationContext = true

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#111] opened 2016-08-31 23:04 UTC
MVC web apps that target the desktop framework need a .deps.json file in order to compile Razor views at runtime.  However, desktop framework apps don't get a .deps.json file written next to the app.  Instead, the file is added as a resource to the app's assembly.

We need to either mimic the CLI's behavior in MSBuild by adding the .deps.json file as a resource to the assembly, or we need to write out a .deps.json file next to the assembly for desktop web apps when PreserveCompilationContext = true.

**Comment by NTaylorMullen** [comment] 2016-12-09 19:39
Was this issue actually fixed? It doesn't look like `preserveCompilationContext` results in the correct bits getting embeded for desktop projects. Few issues sprung up due to this: 
https://github.com/aspnet/Home/issues/1866
https://github.com/aspnet/Razor/issues/890

**Comment by dsplaisted** [comment] 2016-12-09 21:38
Reopening so this doesn't get lost and we can verify whether it's fixed or not.

**Comment by nguerrera** [comment] 2016-12-09 21:41
@NTaylorMullen Please clarify. We agreed above that putting the .deps.json next to the assembly was the right call. Is the problem that deps.json is not embedded (by design, again see above) or that its contents are wrong?

Nobody answered my question about tests, but if something is expecting .deps.json to be embedded, it should be changed to also allow it to be on disk.

**Comment by NTaylorMullen** [comment] 2016-12-09 23:09
What I'm seeing is that File => New Web Application in VS 2017 RC fails to render Razor pages because `preserveCompilationContext` bits aren't being picked up. This ties back to Mvc 1.0.0 bits depending on older extensiosn.dependencymodel bits.

Does `Microsoft.Extensions.DependencyModel 1.0.0` support reading deps.json next to the assembly? If not how should 1.0.0 runtime bits work with newer CLIs?

**Comment by nguerrera** [comment] 2016-12-09 23:17
@pakrym Said above that it "should work fine even with old version of DependencyModel but needs to be tested" and then I never got an answer on how to test. If it conclusively does not support it, then yes, we'll need to support embedding after all.

I'd like to understand better why it was believed that it "should work" but apparently does not. Is it just a bug in 1.0.0 that it's failing to read from disk? Is there a patch release possibility to fix this rather than adding embedding to SDK?

**Comment by pakrym** [comment] 2016-12-10 17:39
@nguerrera I said "should work" because `Microsoft.Extensions.DependencyModel` always reads from disk for .net core apps so this functionality is there and is tested. @NTaylorMullen is there a `.deps` file next to `.exe` when you build?

**Comment by NTaylorMullen** [comment] 2016-12-10 20:58
Yes

**Comment by nguerrera** [comment] 2016-12-10 23:00
I'll try the repro steps in linked bugs and see if there's something incorrect in the deps file.

**Comment by nguerrera** [comment] 2016-12-12 18:56
It's definitely reading from .deps.json on disk (editing it caused a different crash). I found that there are missing references for the Facades coming from desktop targeting path. I believe this is the root issue. I've filed #480 to track that and I'm re-closing this as it tracked producing the .deps.json file, which we do, it's just incomplete.

**Closed by nguerrera** 2016-12-12 18:56 UTC

**Comment by CZEMacLeod** [comment] 2017-04-08 03:52
I know this is closed - but having been searching for a solution to DependencyContext not loading for class libraries since they no longer embed the .deps.json file - I found that I needed to add
`  <PropertyGroup>
    <AllowedReferenceRelatedFileExtensions>$(AllowedReferenceRelatedFileExtensions);.deps.json</AllowedReferenceRelatedFileExtensions>
  </PropertyGroup>`
To ensure that my ProjectReferences took across the file. I don't know if this should be a default now (like .pdb etc.) but it may help others tripping over this issue when using project references rather than build packages.
