### ISSUE TITLE
dotnet test ignores platform argument in 7.0

### ISSUE THREAD

**Issue by jasper-d** [dotnet/sdk#29104] opened 2022-11-17 19:19 UTC
### Describe the bug
I'm upgrading from .NET 6 to .NET 7 and it appears that the behaviour of `dotnet test` changed when specifying a platform.

### To Reproduce
Run the following commands in `mcr.microsoft.com/dotnet/sdk:7.0`

```sh
mkdir src
cd src
dotnet new sln -n test
dotnet new xunit -n project.tests
dotnet sln add ./project.tests
sed -i 's/Any CPU/x64/' test.sln
sed -i 's/Any CPU/x64/' test.sln
dotnet build test.sln -c Release -p:platform=x64
dotnet test ./project.tests/ -c Release -p:platform=x64 --no-build
```

### Exceptions (if any)
`dotnet test` terminates with the following error:

> The argument /src/project.tests/bin/Release/net7.0/project.tests.dll is invalid. Please use the /help option to check the list of valid arguments.

Apparently it uses the wrong directory, instead of `/src/project.tests/bin/Release/net7.0/project.tests.dll` it would need to use `/src/project.tests/bin/x64/Release/net7.0/project.tests.dll` which includes the platform and contains the binary. 

### Further technical details
This is a regression. When running the repro steps in `mcr.microsoft.com/dotnet/sdk:6.0` `dotnet test` succeeds.
When omitting `--no-build` `dotnet test` succeeds but only because it builds the binaries without respecting the platform switch.

`dotnet --info` output:
```
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by baronfel** [comment] 2022-11-17 19:29
Hi @jasper-d - This is a duplicate of https://github.com/microsoft/vstest/issues/4014. We've merged a fix already and the fix will be available in 7.0.101 early/mid next month.

**Closed** 2022-11-17 19:30 UTC
Labels: Area-DotNet Test, untriaged
