### ISSUE TITLE
`dotnet tool install --global` reinstalls even if the same version is already present

### ISSUE THREAD

**Issue by rozumak** [dotnet/sdk#40818] opened 2024-05-10 16:12 UTC
### Describe the bug
`dotnet tool install --global` reinstalls even if the same version is already installed. But it should ignore it as in previous .NET SDK versions. This behavior was probably introduced in #37311. This causes the folder with the installed tool to be cleaned up every time `dotnet tool install` is called from a build script. Previously, this step was failing. Probably there are some workarounds to keep the previous behavior?
### To Reproduce
Run `dotnet tool install --global tailwindcss-dotnet --version 1.0.0`  when this tool is already installed.
To ensure that it tries to reinstall, just open the folder where this tool is installed: `C:\Users\user\.dotnet\tools\.store\tailwindcss-dotnet\1.0.0\tailwindcss-dotnet\1.0.0` in explorer to lock the folder. In that case, it says:
```
Tool 'tailwindcss-dotnet' failed to update due to the following:
Failed to uninstall tool package 'tailwindcss-dotnet': Access to the path 'C:\Users\user\.dotnet\tools\.store\tailwindcss-dotnet\1.0.0' is denied.
```

### Further technical details
```
.NET SDK:
 Version:           8.0.200
 Commit:            438cab6a9d
 Workload version:  8.0.200-manifests.e575128c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.200\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  8.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
```

**Comment by Forgind** [comment] 2024-05-14 21:35
@nagilson, this sounds like a recent regression that we probably want to look into. Assigning to you as the resident dotnet-tool expert.

**Comment by caiogranero** [comment] 2024-06-12 12:54
Hi @Forgind ,

This is my first time here, can I work on this? 

Thank you!

**Comment by nagilson** [comment] 2024-06-12 16:31
You are definitely free to make a PR and have us take a look :)

**Comment by caiogranero** [comment] 2024-06-21 13:26
Hi,

I changed the code to not reinstall the same version, and now I need help deciding whether I should handle the situation as a success or a failure when trying to install a version that is already present. The #37311 was changed to be a success; should I keep it as a success or change it back to a failure?

**Comment by Forgind** [comment] 2024-06-21 16:21
It looks like it was intentional to change that to a success case, so I'd keep it as a success.

**Comment by caiogranero** [comment] 2024-06-23 12:40
I opened a PR with my changes :) 

#41746

**Closed** 2024-06-27 20:19 UTC
Labels: good first issue, Area-Tools
