### ISSUE TITLE
[NETE2ESDK] On Ubuntu 24.04 ARM32 only, creating webapi project failed with error NU1301.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/sdk#40505] opened 2024-04-28 09:34 UTC
Repro steps:
On Ubuntu 24.04 ARM32, using dotnet-sdk-6.0.422-linux-arm.tar.gz from [https://dev.azure.com/dnceng/internal/_build/results?buildId=2438540&view=artifacts&pathAsName=false&type=publishedArtifacts](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fdnceng%2Finternal%2F_build%2Fresults%3FbuildId%3D2438540%26view%3Dartifacts%26pathAsName%3Dfalse%26type%3DpublishedArtifacts&data=05%7C02%7Cv-xiaofchen%40microsoft.com%7C1909a98cbc8b443950ab08dc660e6d2d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638497459679079046%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=mn%2FIVjnPQ4oGcRX3OdePIvwFezNEe0vtpiXxTVmlYeA%3D&reserved=0)

### Describe the bug
creating webapi project failed with error NU1301

### To Reproduce
1.add private azure artifact feeds 
```
<configuration>
  <packageSources>
    <add key="dotnet6" value="https://pkgs.dev.azure.com/dnceng/internal/_packaging/6.0.422-servicing.24223.20-shipping/nuget/v3/index.json" />
  </packageSources>
<packageSourceCredentials>
    <internalPackageSource>
        <add key="Username" value="mmitche" /> <!-- Your username -->
        <add key="CleartextPassword" value="" /> <!-- Insert PAT obtained as shown below -->
    </internalPackageSource>
  </packageSourceCredentials>
</configuration>
```
2.dotnet new webapi -o mywebapi

**Expected behavior**
The project can create successfully.

### Exceptions (if any)
creating webapi project failed with error NU1301
![image](https://github.com/dotnet/sdk/assets/99376012/fd26d6d3-40dc-45cf-826a-c6c8e7b6a1e6)

### dotnet --info
![image](https://github.com/dotnet/sdk/assets/99376012/567fea1d-a3d8-4600-b5d8-702ea6dba929)

**Note:**
1.This issue also repro on publishing application with 'linux-arm --self-contaied'
![image](https://github.com/dotnet/sdk/assets/99376012/8325777a-1c3d-4b7f-85cb-145e97363060)
2.This issue repro on .NET 6,7,8

**Comment by nkolev92** [comment] 2024-04-29 17:21
@kartheekp-ms's out hotseat. 

This seems to be an access problem to nuget.org (rarely tends to be an actual client problem). 

Is this reliably reproable?
Can you try `wget https://api.nuget.org/v3/index.json` and see what happens?

**Comment by richaverma1** [comment] 2024-04-29 21:45
Closing it as by design.  Currently no .NET ARM32 builds work on Ubuntu 24.04

**Closed by richaverma1** 2024-04-29 21:45 UTC
Labels: untriaged, Area-Linux
