### ISSUE TITLE
With .NET 6, need adding RID for Mariner 2.0 

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/sdk#25092] opened 2022-04-27 07:44 UTC
Environment
6.0.300(runtime-6.0.5)

Steps To Reproduce
1. Prepare Mariner 2.0 x64 or Arm64 in docker
2. Installed the 6.0.300 SDK
3. run "dotnet --info"
4. Observe

Expected Behavior
RID for Mariner 2.0 should be displayed correctly.

Actual Behavior
RID shows"Linux-arm64" or "Linux-x64"
![image](https://user-images.githubusercontent.com/1578239/165466716-1a5d386f-e6ec-41c3-a123-7188f45766e9.png)
![image](https://user-images.githubusercontent.com/1578239/165467373-70dd0ddf-5c70-4be2-80a2-53a0c8dfb28e.png)

**Comment by mthalman** [comment] 2022-04-27 13:34
This is a duplicate of https://github.com/dotnet/runtime/issues/65566.

**Closed by mthalman** 2022-04-27 13:34 UTC
Labels: Area-DotNet Test, untriaged
