### ISSUE TITLE
'dotnet new list' crashes for x64 SDK installed on Windows ARM64

### ISSUE THREAD

**Issue by AntonLapounov** [dotnet/sdk#27032] opened 2022-08-09 05:18 UTC
Install the x64 SDK (tested on 7.0.100-rc.1.22408.3) on a Windows 11 ARM64 machine and run `dotnet new list`:
```
C:\>"C:\Program Files\dotnet\x64\dotnet.exe" new list
Unhandled exception: System.BadImageFormatException: Retrieving the COM class factory for component with CLSID {C01B9BA0-BEA7-41BA-B604-D0A36F469133} failed due to the following error: 800700c1  is not a valid Win32 application. (0x800700C1).
   at Microsoft.DotNet.Installer.Windows.InstallerBase..ctor(InstallElevationContextBase elevationContext, ISetupLogger logger, Boolean verifySignatures)
   at Microsoft.DotNet.Installer.Windows.MsiInstallerBase..ctor(InstallElevationContextBase elevationContext, ISetupLogger logger, Boolean verifySignatures, IReporter reporter)
   at Microsoft.DotNet.Workloads.Workload.Install.NetSdkMsiInstallerClient..ctor(InstallElevationContextBase elevationContext, ISetupLogger logger, Boolean verifySignatures, IWorkloadResolver workloadResolver, SdkFeatureBand sdkFeatureBand, INuGetPackageDownloader nugetPackageDownloader, VerbosityOptions verbosity, PackageSourceLocation packageSourceLocation, IReporter reporter)
   at Microsoft.DotNet.Workloads.Workload.Install.NetSdkMsiInstallerClient.Create(Boolean verifySignatures, SdkFeatureBand sdkFeatureBand, IWorkloadResolver workloadResolver, INuGetPackageDownloader nugetPackageDownloader, VerbosityOptions verbosity, PackageSourceLocation packageSourceLocation, IReporter reporter, String tempDirPath, RestoreActionConfig restoreActionConfig)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallerFactory.GetWorkloadInstaller(IReporter reporter, SdkFeatureBand sdkFeatureBand, IWorkloadResolver workloadResolver, VerbosityOptions verbosity, String userProfileDir, Boolean verifySignatures, INuGetPackageDownloader nugetPackageDownloader, String dotnetDir, String tempDirPath, PackageSourceLocation packageSourceLocation, RestoreActionConfig restoreActionConfig, Boolean elevationRequired)
   at Microsoft.DotNet.Workloads.Workload.List.WorkloadInfoHelper..ctor(VerbosityOptions verbosity, String targetSdkVersion, Nullable`1 verifySignatures, IReporter reporter, IWorkloadInstallationRecordRepository workloadRecordRepo, String currentSdkVersion, String dotnetDir, String userProfileDir, IWorkloadResolver workloadResolver)
   at Microsoft.DotNet.Cli.NewCommandParser.CreateHost(Boolean disableSdkTemplates, Boolean enableProjectContext, FileInfo projectPath)
   at Microsoft.TemplateEngine.Cli.Commands.BaseCommand.CreateEnvironmentSettings(GlobalArgs args, ParseResult parseResult)
   at Microsoft.TemplateEngine.Cli.Commands.BaseCommand`1.InvokeAsync(InvocationContext context)
   at Microsoft.TemplateEngine.Cli.Commands.BaseCommand`1.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Cli.Parser.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__17_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass7_0.<<UseExceptionHandler>b__0>d.MoveNext()
```
Note that the zip version of the x64 SDK does not produce the error.  The issue was originally reported [here](https://github.com/dotnet/runtime/issues/71856#issuecomment-1208836697). @joeloff

![image](https://user-images.githubusercontent.com/87680983/183549154-2bbed7b0-f988-49a3-bda4-36af0b2d0d11.png)

**Comment by AntonLapounov** [comment] 2022-08-09 05:23
I think it crashes on this line: https://github.com/dotnet/sdk/blob/09b31215867d1ffe4955fd5b7cd91eb552d3632c/src/Cli/dotnet/Installer/Windows/InstallerBase.cs#L81

**Comment by danmoseley** [comment] 2022-08-09 07:00
"800700c1  is not a valid Win32 application" .. seems a corrupted message.

**Comment by AntonLapounov** [comment] 2022-08-09 07:26
That is our best effort to report the error for the returned `HRESULT`.  The actual message is "%1 is not a valid Win32 application."; however, we do not have the argument.

**Comment by joeloff** [comment] 2022-08-10 00:30
Is this an issue with emulation and COM? So far, we've only seen this with x64 SDK on arm64.

**Comment by AntonLapounov** [comment] 2022-08-10 01:05
The `SystemInformation` class is implemented in `wuapi.dll`, which is not an ARM64X library, so you cannot load it in an x64 process.  Loading `wuapi.dll` on every `dotnet new` command is inefficient and unnecessary.  You might want to initialize the `RebootPending` flag lazily, or even better — just check whether the following registry key exists in the 64-bit registry view:

`HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired`

Note that Windows has other registry keys that may indicate that a reboot is required.  See, for example, [here](https://devblogs.microsoft.com/scripting/determine-pending-reboot-statuspowershell-style-part-1/) and [here](https://jonlabelle.com/snippets/view/powershell/check-pending-reboot).  The `SystemInformation::get_RebootRequired` function checks just the registry key mentioned above, which may suffice or not depending on your needs.

**Comment by joeloff** [comment] 2022-08-10 02:58
That key doesn't cover all the situations. The recommended way is the WU APIs it aggregates data from a much larger set of of locations.

The loading unfortunately happens because templates now rely on data from the workloads, which if we were a global install, goes through the MSI based management for workloads and the very first thing that code does is capture information from the environment for its logs. 

I'll see whether we can make this work better.

**Comment by AntonLapounov** [comment] 2022-08-10 03:12
> That key doesn't cover all the situations. The recommended way is the WU APIs it aggregates data from a much larger set of of locations.

I do not think that's true.  Look at the sources — `CSystemInformation::get_RebootRequired` reads just that single registry key and under it.  You could use Process Explorer to verify that.

**Comment by joeloff** [comment] 2022-08-10 03:23
Thanks, I'll double check. I could have sworn I read other documentation that hinted that it also looked at additional information like pending file renames, etc. If that's not the case, then we can definitely replace this code, though we still need to solve the larger issue around templates and `dotnet new` hitting the workload code.

That's likely because some templates are now coming from workloads, and it's necessary to determine which workloads are installed.

**Comment by joeloff** [comment] 2022-08-11 03:48
This should hopefully be fixed in the next main build from dotnet/installer

**Closed** 2022-08-11 03:47 UTC
Labels: Area-Workloads

**Comment by WenJunJi01** [comment] 2022-08-15 06:29
This issue is fixed and doesn't reproduce with the latest main build (x64 SDK 7.0.100-rc.1.22414.5) from https://github.com/dotnet/installer.
![image](https://user-images.githubusercontent.com/87680983/184586973-73b01cf7-2abb-4f35-8a83-7e1658883dae.png)
![image](https://user-images.githubusercontent.com/87680983/184587034-642d217f-edc6-40d5-9ffc-4a467e42d437.png)
