### ISSUE TITLE
Internal error: new deps file generation did not produce the same result as the old logic

### ISSUE THREAD

**Issue by imsmart-tech** [dotnet/sdk#3204] opened 2019-05-05 23:35 UTC
Got this error which said to file issue here. So here it goes.

[ImSmart.deps.json.txt](https://github.com/dotnet/sdk/files/3146159/ImSmart.deps.json.txt)

[ImSmart.deps.new.json.txt](https://github.com/dotnet/sdk/files/3146160/ImSmart.deps.new.json.txt)

**Comment by livarcocc** [comment] 2019-05-08 17:27
Dupe of https://github.com/dotnet/sdk/issues/3146

**Closed by livarcocc** 2019-05-08 17:27 UTC
