### ISSUE TITLE
[dotnet-cache]: Architecture is prefixed to the --output argument

### ISSUE THREAD

**Issue by pranavkm** [dotnet/sdk#928] opened 2017-03-02 15:37 UTC
Run `dotnet cache –output <dotnet-install-dir>\packages ..`

Expected: The `<dotnet-install-dir>\packages` has the right layout (e.g. `<dotnet-install-dir>\packages\netcoreapp2.0\..`) for the package cache to work

Actual: There's an additional `x64` in the output path e.g. ` <dotnet-install-dir>\packages\x64\netcoreapp2.0\..` which causes the packages to not be found.

**Comment by pranavkm** [comment] 2017-03-02 15:38
cc @eerhardt

**Comment by ramarag** [comment] 2017-03-03 02:20
This is by design 
@pranavkm  can you tell me how are you running the app ?

**Comment by pranavkm** [comment] 2017-03-03 07:00
All I do is do `dotnet run` on the csproj. If I move the directory a folder up, I can see the optimized binaries being used. With the current layout, it's not. If I remove the `--runtime win7-x64` argument, the tool crashes:

```
\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.ComposeCache.targets(48,5): error MSB4018: The "NETSdkError" task failed unexpectedly.\r [D:\work\package-cache\packages.xml]
\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.ComposeCache.targets(48,5): error MSB4018: System.ArgumentNullException: Value cannot be null.\r [D:\work\package-cache\packages.xml]
```

So it doesn't look like it's meant to produce both the x86 and x64 versions of binaries in the absence of specified rid. I'm not sure, what the architecture prefix achieves here since it's inferred from an argument the user specifies.

**Comment by ramarag** [comment] 2017-03-24 02:06
This is by design, if we are going to support developer scenarios for generating  and consuming cache, then we should revisit and add additional architecture neutral probe paths for them.

CC @eerhardt @gkhanna79 Closing this for now

**Comment by eerhardt** [comment] 2017-03-24 15:02
@gkhanna79 - was there ever a decision on whether we were supporting `dotnet cache` developer scenarios for 2.0?  From my understanding, that is what @DamianEdwards wanted, but I'm not sure what the decision was.

/cc @bleroy

**Comment by gkhanna79** [comment] 2017-03-24 16:22
`dotnet cache` is targeted for use for various scenarios - **including** developer scenarios. Here is what I think should happen (and I suspect the issues identified above are independent of whether cache is used in developer or non-developer scenario):

1) Based upon the RID (which could be either explicitly specified or implicitly inferred by dotnet cache implementation), the folder in which cache is generated should have architecture specific subfolder in which the layout is contained. This is what @pranavkm is observing.

2) During activation, the host is probably missing the addition of the architecture to the base path where the layout is expected. If so, this is a bug and should be fixed. @ramarag can you please confirm?

> So it doesn't look like it's meant to produce both the x86 and x64 versions of binaries in the absence of specified rid

@eerhardt my understanding is that if the RID is not specified explicitly as an argument, then it is inferred during cache generation and thus, the target architecture in the cache layout should correspond to inferred RID. @pranavkm I dont believe we will generate for both architectures - because "both" is incorrect count. The architectures supported vary with each platform (e.g. OSX only has one architecture - x64, while Windows has 4).

> If I remove the --runtime win7-x64 argument, the tool crashes:

This sounds like a bug - @pranavkm please file an issue against @ramarag to look into this.

**Comment by eerhardt** [comment] 2017-03-24 16:41
I think the issue here is that sometimes we need the architecture in the path, and sometimes we don't.

When we are reading assemblies from a `dotnet.exe` relative location, the architecture is already decided.  If we are in `%PROGRAMFILES%` on a 64-bit machine, it is x64.  If we are in `%PROGRAMFILES(x86)%, then it is x86.  So putting the architecture in this path is redundant. It will always match the architecture of `dotnet.exe`.

When we are reading assemblies from the `%USERPROFILE%`, we need to have `x86`/`x64` in the path, because there isn't any other context.  On Windows, we could be using both x64 and x86 apps on the machine.

However, when `dotnet cache` generates the cache, it doesn't know if it should or shouldn't generate the architecture in output path, so it always does, because the default is to generate to your `%USERPROFILE%`.

Maybe the solution here is for `dotnet cache` to not put the architecture in the path, if the `-o` option is used.  It only puts the architecture in the path when using the default output path.

**Comment by gkhanna79** [comment] 2017-03-24 16:58
> Maybe the solution here is for dotnet cache to not put the architecture in the path,

What about custom location that is not global or userprofile? Wont we need architecture there as well?

**Comment by eerhardt** [comment] 2017-03-24 17:08
> What about custom location that is not global or userprofile? Wont we need architecture there as well?

Yes, it looks like the architecture gets appended in that case as well.  https://github.com/dotnet/core-setup/blob/master/src/corehost/common/utils.cpp#L270

There are two cases where architecture gets appended:

1. `%USERPROFILE%`
2. `DOTNET_SHARED_PACKAGES` env var.

And two cases where architecture is NOT appended:

1. `dotnet.exe` relative path
2. "Global shared package dir", i.e. `%PROGRAMFILES%` or `$PATH`.

Then, how is the tooling supposed to know if it should append the architecture or not? Make the user supply an option?  How is the user supposed to know what to choose?

**Comment by gkhanna79** [comment] 2017-03-24 17:29
My suggestion would be for the host to always lookup with an architecture appended path for all cases. Sure, it will result in having a redundant architecture specified while within an architecture specific folder (which only happens on Windows), but it is much simpler to reason about and should work consistently. This should also enable tooling to always generate layout under the target architecture subfolder.

**Comment by eerhardt** [comment] 2017-03-24 17:36
That sounds perfect to me.  It's good to have consistency.

**Comment by gkhanna79** [comment] 2017-03-24 17:37
Great - can you please file required issues in various repos against @ramarag to get this addressed?

**Comment by eerhardt** [comment] 2017-03-24 17:39
Why can't we just use this one?  It's already filed, assigned to @ramarag, and describes the issue.

**Comment by pranavkm** [comment] 2017-03-24 18:05
FYI @JunTaoLuo

**Comment by ramarag** [comment] 2017-03-25 00:47
closing this and opening it in https://github.com/dotnet/core-setup/issues/1848
as there is nothing do in sdk repo

**Closed by ramarag** 2017-03-25 00:47 UTC
Labels: Bug

**Comment by bleroy** [comment] 2017-03-27 16:52
> @eerhardt "was there ever a decision on whether we were supporting dotnet cache developer scenarios for 2.0? From my understanding, that is what @DamianEdwards wanted, but I'm not sure what the decision was."

Yes, it's in, but it's not the part of the scenario we wanted necessarily the focus to be on, since building a cache will be relatively infrequent in comparison with running or publishing against one. Since `dotnet-cache` is already in, we're not likely going to yank it out, but what we might do is rename it to reflect the terminology that we settled on: "runtime package store" for the package location, and "target profile" for the file that will describe its contents and that users will be able to publish against. I'll try to find you sometime today.
