### ISSUE TITLE
Condense properties required for strong-name signing

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#520] opened 2016-12-16 19:31 UTC
In order to get strong-name signing to work, a project must have these three properties:

```xml
<PropertyGroup>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)Key.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
    <PublicSign Condition="'$(OS)' != 'Windows_NT'">true</PublicSign>
</PropertyGroup>
```

preview2 supported strong-name signing by [setting just one property](https://github.com/aspnet/Common/blob/3278ee4a7355159f9732d742b7f9f4c56c5a6d7a/src/Microsoft.Extensions.ObjectPool/project.json#L15): "keyFile" in project.json. It would be nice to condense this to one:
```xml
<PropertyGroup>
    <KeyFile>$(MSBuildThisFileDirectory)Key.snk</KeyFile>
</PropertyGroup>
```

cc @davidfowl

**Comment by onovotny** [comment] 2016-12-16 21:40
If there's a `KeyFile` specified, I think it's safe to assume intent; otherwise it wouldn't be there :)

**Comment by nguerrera** [comment] 2016-12-19 02:53
> `<PublicSign Condition="'$(OS)' != 'Windows_NT'">true</PublicSign>`

That's a workaround for https://github.com/dotnet/roslyn/issues/8210. We absolutely must not bake it in to the SDK.

I can see the argument for SignAssembly=true being redundant or even AssemblyOriginatorKeyFile being a mouthful. We could condense those two.

**Comment by davidfowl** [comment] 2016-12-19 04:57
> That's a workaround for dotnet/roslyn#8210. We absolutely must not bake it in to the SDK.

Because behavior changes in SDK updates are bad? Looking at that issue there's no clear conclusion on when it's getting fixed. Forcing that conditional on all consuming projects sucks.

**Comment by nguerrera** [comment] 2016-12-19 20:51
Depends on the behaviour that's changing. There are fundamentally two choices: which key to use, and which type of signing (full, delay, or public) to perform. They are independent. Furthermore, I don't think we should ever public sign or delay sign without an explicit request to do so because there are consequences. 

Consider this case:

* I build the shipping v1 copy of my library on a Windows box.
* I build v2 on a Linux box 
* I get a bug report that v2 broke someone's use case involving shadow copying on desktop.

The roslyn issue in question is marked for 2.0 RTM. @tmat, is that still reasonable?

**Comment by nguerrera** [comment] 2017-06-21 15:01
Thinking about this more, I'm closing this as by design. As I mentioned above, the PublicSign hack is a workaround for a missing compiler feature on non-Windows. I'll be pushing hard to get that fixed in 2.1. 

That leaves only SignAssembly + KeyFile redundancy. However, that is how things have always worked in msbuild projects and there is a scenario for it:

* Put AssemblyOriginatorKeyFile in a common .props
* Opt in to actually signing with the key with SignAssembly on individual projects (e.g. only shipping bits)

I don't think we should break this.

**Closed by nguerrera** 2017-06-21 15:01 UTC
Labels: Bug

**Comment by natemcmaster** [comment] 2017-06-21 15:28
To be clear, the request here was not to change existing behavior of AssemblyOriginatorKeyFile, SignAssembly, or PublicSign. The request was to add a new property (such as `StrongNameKeyFile`)  and infer the other properties from it as necessary to make signing happen. This is a PJ parity request.

It seems this would be as simple as adding this to the SDK:
```xml
<PropertyGroup Condition="'$(StrongNameKeyFile)' != ''">
    <AssemblyOriginatorKeyFile>$(StrongNameKeyFile)</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
    <PublicSign Condition="'$(OS)' != 'Windows_NT'">true</PublicSign>
</PropertyGroup>
```

**Comment by nguerrera** [comment] 2017-06-21 16:07
We could consider that without the public sign part (I'm not budging on that, it's a hack, push on Roslyn not us to get rid of it), but then it would fight with the property page and open questions as to which property wins. I don't think there's enough value to offset that.
