### ISSUE TITLE
dotnet build/run failing (almost) siliently Ubuntu Linux

### ISSUE THREAD

**Issue by cerilewis** [dotnet/sdk#28471] opened 2022-10-11 18:59 UTC
### Describe the bug
Since 7.0.100-rc.1 `dotnet build`, `dotnet run`, `dotnet watch` fails after several succesful executions. After forcing the SDK back to 7.0.100-preview.7 the calls succeed again. The reported error is:
`The build failed. Fix the build errors and run again.`

### To Reproduce
For me just running the cli commands multiple times causes the issue.

### Further technical details
```
.NET SDK:
 Version:   7.0.100-rc.2.22477.23
 Commit:    0a5360315a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /home/cerilewi/.dotnet/sdk/7.0.100-rc.2.22477.23/

Host:
  Version:      7.0.0-rc.2.22472.3
  Architecture: x64
  Commit:       550605cc93

.NET SDKs installed:
  6.0.400 [/home/cerilewi/.dotnet/sdk]
  6.0.401 [/home/cerilewi/.dotnet/sdk]
  7.0.100-preview.7.22377.5 [/home/cerilewi/.dotnet/sdk]
  7.0.100-rc.1.22431.12 [/home/cerilewi/.dotnet/sdk]
  7.0.100-rc.2.22477.23 [/home/cerilewi/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [/home/cerilewi/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [/home/cerilewi/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.7.22376.6 [/home/cerilewi/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.1.22427.2 [/home/cerilewi/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.2.22476.2 [/home/cerilewi/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [/home/cerilewi/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [/home/cerilewi/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.7.22375.6 [/home/cerilewi/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.1.22426.10 [/home/cerilewi/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.2.22472.3 [/home/cerilewi/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set
```

**Comment by burakakca** [comment] 2022-10-12 11:06
I have the same issue. After the first successful dotnet run , Getting the same error.
```bash
.NET SDK:
 Version:   7.0.100-rc.1.22431.12
 Commit:    f1cf61e1c0

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  20.2
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.100-rc.1.22431.12/

Host:
  Version:      7.0.0-rc.1.22426.10
  Architecture: x64
  Commit:       06aceb7015

.NET SDKs installed:
  3.1.423 [/usr/share/dotnet/sdk]
  7.0.100-rc.1.22431.12 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.29 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.1.22427.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.29 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.1.22426.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

```

**Comment by cerilewis** [comment] 2022-10-19 20:24
Captured the output from `dotnet build -v diag`
```
$ dotnet build -v diag
MSBuild version 17.4.0-preview-22470-08+6521b1591 for .NET
/home/cerilewi/.dotnet/sdk/7.0.100-rc.2.22477.23/MSBuild.dll -consoleloggerparameters:Summary -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/home/cerilewi/.dotnet/sdk/7.0.100-rc.2.22477.23/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/home/cerilewi/.dotnet/sdk/7.0.100-rc.2.22477.23/dotnet.dll -maxcpucount -restore -verbosity:m -verbosity:diag ./XXX.csproj
Build started 10/19/2022 10:17:53 PM.
22:17:53.863     0>Process = "/home/cerilewi/.dotnet/dotnet"
                   MSBuild executable path = "/home/cerilewi/.dotnet/sdk/7.0.100-rc.2.22477.23/MSBuild.dll"
                   Command line arguments = "/home/cerilewi/.dotnet/sdk/7.0.100-rc.2.22477.23/MSBuild.dll -maxcpucount -verbosity:m -restore -consoleloggerparameters:Summary -verbosity:diag -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/home/cerilewi/.dotnet/sdk/7.0.100-rc.2.22477.23/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/home/cerilewi/.dotnet/sdk/7.0.100-rc.2.22477.23/dotnet.dll"
                   Current directory = "/home/cerilewi/src/XXX"
                   MSBuild version = "17.4.0-preview-22470-08+6521b1591"

Build FAILED.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.00
´´´

**Comment by rainersigwald** [comment] 2022-10-26 17:41
Duplicate of #28226

**Closed by rainersigwald** 2022-10-26 17:41 UTC
Labels: untriaged, Area-Linux
