### ISSUE TITLE
dotnet watch on net6.0 project results in FileNotFoundException for SystemRuntime

### ISSUE THREAD

**Issue by JoshWoodArup** [dotnet/sdk#28942] opened 2022-11-08 16:10 UTC
### Description

When running the `dotnet watch` from .net 7 on a net6.0 project, a `FileNotFoundException` is thrown claiming that `System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a` could not be found. net7.0 and net5.0 projects work fine.

### Reproduction Steps

```
dotnet new console -f net6.0
dotnet watch run
```

### Expected behavior

The program should output `Hello, World!`.

### Actual behavior

```
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
  watchtest -> D:\Test\watchtest\bin\Debug\net6.0\watchtest.dll
dotnet watch 🚀 Started
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Reflection.Assembly.GetType(String name, Boolean throwOnError)
   at System.StartupHookProvider.CallStartupHook(StartupHookNameOrPath startupHook)
   at System.StartupHookProvider.ProcessStartupHooks()
dotnet watch ❌ Exited with error code -532462766
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...
```

### Regression?

This is a regression from SDK 7.0.100-rc.2

### Known Workarounds

This can be worked around by [creating a global.json file](https://learn.microsoft.com/en-us/dotnet/core/versions/selection#the-sdk-uses-the-latest-installed-version) and pointing it to the v6 SDK (thanks @nicholashead)

``` json
{
    "sdk": {
        "version": "6.0.403"
    }
}
```

Alternatively, adding any argument after `dotnet watch run` will work. e.g.
```
dotnet watch run bogus
```
(thanks @akorchev)

### Configuration

.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

### Other information

It's possible that my installation is corrupted. However I have uninstalled and reinstalled several times

**Comment by nicholashead** [comment] 2022-11-08 21:35
I'm experiencing this as well.

**Comment by VictorMalcov** [comment] 2022-11-09 04:45
> I'm experiencing this as well. I worked around it for now by [creating a global.json file](https://learn.microsoft.com/en-us/dotnet/core/versions/selection#the-sdk-uses-the-latest-installed-version) and pointing it at the v6 SDK:
> 
> ```json
> {
>     "sdk": {
>         "version": "6.0.403"
>     }
> }
> ```

This did not work for me.

**Comment by nicholashead** [comment] 2022-11-09 05:53
@VictorMalcov it should work for the “dotnet” command line. Are you getting an error message or something else?

**Comment by axylophon** [comment] 2022-11-09 08:57
I have the same issue. global.json fixes it temporarily

**Comment by akorchev** [comment] 2022-11-09 09:02
I've hit this too and found this issue. Strangely enough putting anything after "run" seems to fix the problem (even without global.json) e.g. `dotnet watch run bogus`.

**Comment by petunsecn** [comment] 2022-11-10 02:39
Yesterday, After upload to VS 17.4.0, i have the same error. and  I just reinstalled .net 6 and everything works.

**Comment by tanveerbadar** [comment] 2022-11-10 07:12
Adding the global.json specified as a workaround above did not work for me, got this additional error instead:

> error MSB4242: SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.Sdk.Web". Exception: "Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Workload manifest dependency 'Microsoft.NET.Workload.Emscripten' version '6.0.4' is lower than version '6.0.9' required by manifest 'microsoft.net.workload.mono.toolchain' [C:\Program Files\dotnet\sdk-manifests\6.0.300\microsoft.net.workload.mono.toolchain\WorkloadManifest.json]

I have no idea what is supposed to happen here.

However, the other workaround of dotnet watch run bogus did work perfectly.

P.S.: The file is still needed otherwise the project will target dotnet 7 SDK, since the update managed to uninstall dotnet 6 SDK. Again.

**Comment by dmartmsft** [comment] 2022-11-16 03:08
Would be interested to know if anyone got this recently after updating Visual Studio 2022/.NET Core 7.

**Comment by nicholashead** [comment] 2022-11-16 04:00
> Would be interested to know if anyone got this recently after updating Visual Studio 2022/.NET Core 7.

Yes, this is exactly when it started happening for me. I was not running any betas or anything.

**Comment by byroniac** [comment] 2022-11-16 04:33
> > Would be interested to know if anyone got this recently after updating Visual Studio 2022/.NET Core 7.
> 
> Yes, this is exactly when it started happening for me. I was not running any betas or anything.

Same here.

**Comment by Saibamen** [comment] 2022-11-16 09:24
> > > Would be interested to know if anyone got this recently after updating Visual Studio 2022/.NET Core 7.
> > 
> > 
> > Yes, this is exactly when it started happening for me. I was not running any betas or anything.
> 
> Same here.

Same here

**Comment by jquery2005** [comment] 2022-11-17 11:41
Nothing to change, just use "dotnet watch run 【Project Name】" continue to running.

**Comment by byroniac** [comment] 2022-11-17 22:02
> If want to running project, just change path to project path, then execute "dotnet watch run 【.】" or "dotnet watch run 【Project Name】" command to running project, execute "dotnet watch" command can't to running project, "dotnet watch" command just thermal loading.

Used to work with just "dotnet watch run" and it does not seem to matter what you give as the fourth parameter, so currently I have been using "dotnet watch run x" out of laziness.

**Comment by Mrlten** [comment] 2022-11-18 10:38
> > If want to running project, just change path to project path, then execute "dotnet watch run 【.】" or "dotnet watch run 【Project Name】" command to running project, execute "dotnet watch" command can't to running project, "dotnet watch" command just thermal loading.
> 
> Used to work with just "dotnet watch run" and it does not seem to matter what you give as the fourth parameter, so currently I have been using "dotnet watch run x" out of laziness.

Is it me, or is "Ctrl+R" not working when starting the app with the `dotnet watch run` trick?

**Comment by lfiorini** [comment] 2022-11-20 11:14
> > Would be interested to know if anyone got this recently after updating Visual Studio 2022/.NET Core 7.
> 
> Yes, this is exactly when it started happening for me. I was not running any betas or anything.

Same here. I tried to Repair VS 2022 17.4.1 but dotnet --list-sdks still didn't show 6.0.403. I didn't find a way to reinstall .net 6.0 sdk using VS Installer, so I've reinstalled it from the standalone installer. global.json was useless. The only way to make it works again is to use dotnet watch run x.

**Comment by acidrod** [comment] 2022-11-21 04:19
If you do a dotnet watch run . it will work as far as you also have the SDK installed!

**Comment by byroniac** [comment] 2022-11-21 04:24
> If you do a **dotnet watch run .** it will work as far as you also have the SDK installed!
I had no SDK installed but the one installed with Visual Studio and I have to add some meaningless fourth parameter to get it to work: e.g. "dotnet watch run x"

**Comment by stevenrlp** [comment] 2022-11-21 13:42
Same issue here after installing .net 7, only way I seem to be able to get it to work is by using dotnet watch run x. Is there anyway around this, it is annoying to have to add this every time, it should just work without it.

**Comment by tanveerbadar** [comment] 2022-11-23 15:57
I am also pretty certain hot reload is also broken. It is doing full builds for every and any file changes.

**Comment by Alexr03** [comment] 2022-11-25 02:56
> I am also pretty certain hot reload is also broken. It is doing full builds for every and any file changes.

+1 Happening for me to when using the 4th argument workaround.

**Comment by olexandrvynnychenko** [comment] 2023-11-22 11:27
Happening to me after updating my VS 2022 from 17.7.x to 17.8.

.NET SDK 8 is used now by default. And the project is targeted **net5.0**. But everything else is totally the same as described here before.

**dotnet run** works fine while **dotnet watch run** does not.

Adding an arbitrary word to the command does not help.

**global.json** helps.

I would like this issue eventually fixed. Project targeting is planned to switch to net6.0 soon. But switching to .NET 8 is not in the priority now.

**Comment by luizfbicalho** [comment] 2023-11-24 21:01
> Happening to me after updating my VS 2022 from 17.7.x to 17.8.
> 
> .NET SDK 8 is used now by default. And the project is targeted **net5.0**. But everything else is totally the same as described here before.
> 
> **dotnet run** works fine while **dotnet watch run** does not.
> 
> Adding an arbitrary word to the command does not help.
> 
> **global.json** helps.
> 
> I would like this issue eventually fixed. Project targeting is planned to switch to net6.0 soon. But switching to .NET 8 is not in the priority now.

I have this issue after update to 17.9 , my project is net 5.0 , and global .json isn't working, if I run in command line it works fine

**Comment by luizfbicalho** [comment] 2023-11-27 17:04
I'm running with dotnet run and attaching visual studio debugger after

**Comment by RunningDeer** [comment] 2023-11-27 17:07
@luizfbicalho That is a pain, why is nobody from this repo commenting on this issue?

**Comment by baronfel** [comment] 2023-11-27 17:22
I think this is a dupe of another issue related to the browserrefresh middleware, which is used in `watch` and drastically changed TFMs from .NET 7 to .NET 8. This has had a number of different symptoms. There are VS and SDK specific fixes required. The SDK fix in main (will be backported) is https://github.com/dotnet/sdk/pull/37139.

**Comment by tmat** [comment] 2024-05-13 23:43
Fixed by https://github.com/dotnet/sdk/pull/28984

**Closed by tmat** 2024-05-13 23:43 UTC
Labels: untriaged, Area-Watch
