### ISSUE TITLE
dotnet run with a TFM prints restore output to the command line

### ISSUE THREAD

**Issue by pranavkm** [dotnet/sdk#1724] opened 2017-11-10 22:51 UTC
1. Create a new console application `dotnet new console`
2. Do `dotnet run`. The first and only line in the output is from the app's execution (`Hello world!`)
3. Do `dotnet run -f netcoreapp2.1`. 

**Expected:**
`Hello world!`

**Actual**
```
Microsoft (R) Build Engine version 15.5.172.19382 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 12.52 ms for D:\temp\run-test\run-test.csproj.
Hello World!
```

```dotnet --info
.NET Command Line Tools (2.2.0-preview1-007522)

Product Information:
 Version:            2.2.0-preview1-007522
 Commit SHA-1 hash:  d58fc6120d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   \.dotnet\x64\sdk\2.2.0-preview1-007522\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-25907-02
  Build    : 5e5b627d019c82b11a718a90008ce4f737c7e401
```

**Comment by livarcocc** [comment] 2017-11-11 00:35
This is a regression in the CLI from when we introduced restore in the same process. @nguerrera, can you comment? Was this one of the cases that we couldn't work around?

**Comment by nguerrera** [comment] 2017-11-28 23:54
Duplicate of dotnet/cli#8118 (which is newer than this, but in the right repo)

**Closed by nguerrera** 2017-11-28 23:54 UTC
