### ISSUE TITLE
dotnet watch test cannot configure output in .NET 8.0

### ISSUE THREAD

**Issue by FlukeFan** [dotnet/sdk#37244] opened 2023-11-30 14:09 UTC
### Describe the bug
The test logger cannot be configured when using `dotnet watch test` in .NET 8.0.

### To Reproduce
In .NET 6, you could do the following:
```
dotnet new xunit
dotnet watch test --logger "console;verbosity=detailed"
```

In .NET 8, the test logger output is not configured.

(Note, I have also tried `dotnet watch test -- --logger "console;verbosity=detailed"` which also used to work).

### Further technical details
- Include the output of `dotnet --info`
```
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.6a1e483a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\
```

**Comment by baronfel** [comment] 2023-11-30 15:03
Duplicate of https://github.com/dotnet/sdk/issues/34949 - which we are working on a fix for.

**Closed by baronfel** 2023-11-30 15:03 UTC
Labels: Area-DotNet Test, untriaged
