### ISSUE TITLE
NU1507 build failure when updating to 6.0.300 from 6.0.202

### ISSUE THREAD

**Issue by b-a-roberts** [dotnet/sdk#25379] opened 2022-05-12 07:46 UTC
We use central packagement in our library projects. We have 2 nuget sources,  company nuget server and standard nuget.org. This has been working fine since 5.0.X and up to 6.0.202. However when upgrading to 6.0.300 we get NU1507 errors.

The error we are seeing is:
error NU1507: There are 2 package sources defined in your configuration. When using central package management, please map your package sources with package source mapping (https://aka.ms/nuget-package-source-mapping) or specify a single package source.

Package source mapping seems like a step backwards. We also use Local Folders as NuGet source for testing nuget packages. These would then not be picked up,. Our CI/CD pipeline on github picked this up first. We don't even create the nuget.config here, but that is done by the setup-dotnet actions:
 
  uses: actions/setup-dotnet@v2
  with:
    dotnet-version: |
      3.1.x
      5.0.x
      6.0.x
    source-url: https://nuget.pkg.github.com/${{COMPANY}}/index.json 
 env:
    NUGET_AUTH_TOKEN: ${{secrets.GLOBAL_READ_PACKAGES_SECRET}}

However that failed with the release of 6.0.300.
We can force 6.0.202 but that will mean manually updating 50+ repositories.

**Comment by b-a-roberts** [comment] 2022-05-12 10:10
We now have the system working again by adding a NuGet.config to our repositories, which is based on the information contained within:-

https://docs.microsoft.com/en-us/nuget/consume-packages/package-source-mapping#setting-default-sources

FYI, actually the video link to the explanation on Youtube was the most useful.

Still annoying we have to do this for all 50+ repositories we are managing in our company, but at least we can get everything resolved.

**Comment by Zastai** [comment] 2022-05-16 07:57
This is a pretty serious regression in behaviour. Yes, it was a preview feature, but to activate it with different semantics is a very poor approach.
My use case is even more basic: I have to company nuget server, and a local package directory, so that I can test with local builds without pushing them. That scenario seems to be completely broken by this, unless I add an entry to nuget.config for every package I drop in that local override folder.

**Comment by Zastai** [comment] 2022-05-16 08:00
Come to think of it, I have personal projects that set up AppVeyor feeds so that I can test against unreleased CI builds when needed - that would also be broken without constant NuGet.config fiddling.

**Comment by Zastai** [comment] 2022-05-16 08:05
I will also note that https://docs.microsoft.com/en-us/nuget/consume-packages/package-source-mapping says that the feature is "in active development" and lacks some things (like a command-line method for setting up the mappings). So you take central versioning out of preview, but require a different incomplete feature to make it work...

**Comment by vedranstipancic** [comment] 2022-05-18 07:59
Running into this issue as well. Fixed our nuget.config and got dotnet restore working, but Visual Studio 17.2 (this update broke it) will not stop throwing the error _There are 3 package sources defined in your configuration. When using central package management..._

**Comment by WeihanLi** [comment] 2022-05-27 18:43
The same problem, and even add a nuget.config with only one source, there's a sample project: https://github.com/WeihanLi/dotnet-exec

**Comment by baronfel** [comment] 2022-05-27 18:58
Can those of you hitting this issue log the output of `dotnet nuget list source`? I expect that for some of you, you'll see both the NuGet.org source, as well as the default offline package source that Visual Studio creates.  That might be an unanticipated side effect of the NuGet feature. @dotnet/nuget-team is there any guidance or tooling support for creating package mappings for the 'default' sources? Folks seem to be hitting this with some regularity.

**Comment by WeihanLi** [comment] 2022-05-27 19:15
Hi @baronfel , only nuget.org found for me.
![image](https://user-images.githubusercontent.com/7604648/170775988-59fee813-a74f-4381-a520-efbe7cb67052.png)

**Comment by baronfel** [comment] 2022-05-27 19:20
@WeihanLi  in your case that's because of the nuget.config you checked in (I cloned your repo and tried to reproduce your issue), so you've worked around this issue already.  can you remove that file and try again?

**Comment by WeihanLi** [comment] 2022-05-28 03:08
@baronfel it's not a valid work-around for me, I'm still with this `NU1507` warning, maybe there's something not correct with the central package config

![image](https://user-images.githubusercontent.com/7604648/170807501-8f33019e-1072-4427-80a5-4f9318f05290.png)

**Comment by b-a-roberts** [comment] 2022-05-30 07:48
@baronfel we have run the `dotnet nuget list source` and done some checks. Basically all works correctly provided the 'clear' option is present in the NuGet.Config

@WeihanLi your repository looks correctly setup, you don't have a package mapping in the NuGet.Config, but that is expected because you only specify a single NuGet source. The only thing that comes to mind is to clean checkout to a new location, in case you have something left over that is causing an issue. I tend to run a script to clean up all obj & bin directories before building locally on my development PC, just to make sure no asset files remain from previous builds. Sorry, that is all I can think of in your case.

**Comment by audunsolemdal** [comment] 2022-05-31 08:32
> You can also add `NU1507` to `$(NoWarn)` in your project (or `Directory.Build.props`) to make the warning go away.
> 
> It's odd though that VS2022 would not honor a nuget.config that does get used by `dotnet restore` in the same solution folder.

For some  reason most of my team didnt seem to have issues, but for one colleague who was pulling his hair out, doing this in the Directory.build.props file seemed to do the trick

**Comment by b-a-roberts** [comment] 2022-05-31 20:23
@jeffkl thanks for the explanation. In our case we have 50+ company repositories reliant on central package management. We have taken the decision to roll out the package source mapping to all repositories (most now done), so far without any issues. Thanks for the tip about checking the `project.assets.json`, will check that if we ever run into oddball issues. I am happy for this item to be closed now.

**Comment by jeffkl** [comment] 2022-05-31 20:34
@b-a-roberts Thanks for adopting central package management.  I'm working hard to stabilize it and we'll remove the "experimental" tag so we cannot make any more breaking changes.  Feel free to file any issues you experience over at https://github.com/NuGet/Home/issues

**Closed by jeffkl** 2022-05-31 20:34 UTC
Labels: untriaged, Area-NetSDK

**Comment by wekempf** [comment] 2023-05-22 17:22
> 1. Only use a single feed
> 2. Onboard to package source mapping
> 3. Suppress the warning in `Directory.Build.props`

1. I'm using a single feed.
2. I added package source mapping.
3. I've suppressed the warning in `Directory.Build.props`.

I still get the warning.

```
C:\redacted\redacted.csproj : warning NU1507: There  
are 2 package sources defined in your configuration. When using central package management, please map your 
 package sources with package source mapping (https://aka.ms/nuget-package-source-mapping) or specify a sin 
gle package source. The following sources are defined: https://redacted-corporate-repo/, C:\Program Files\dotnet\library-packs [C:\redacted\redacted.sln]        
```

Interesting that it lists 2 sources here, unlike others, but I've not added the `C:\Program Files\dotnet\library-packs` source, nor does it show with list sources.

```powershell
PS> dotnet nuget list source
Registered Sources:
  1.  Nexus [Enabled]
      https://redacted-corporate-repo/
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="Nexus"
      value="https://redacted-corporate-repo/" />
  </packageSources>
  <packageSourceMapping>
    <packageSource key="Nexus">
      <package pattern="*" />
    </packageSource>
  </packageSourceMapping>
</configuration>
```

```xml
<Project>
    <PropertyGroup>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <NoWarn>$(NoWarn);NU1507</NoWarn>
    </PropertyGroup>
</Project>
```
