### ISSUE TITLE
.NET Cli with SQL Server Project Build throws error MSB4019 on build

### ISSUE THREAD

**Issue by dotnetcadet** [dotnet/sdk#32946] opened 2023-05-31 21:56 UTC
I've seen this issue for a few years when running a SQL Server Project build from dotnet cli. It seems like dotnet cli is passing an incorrect reference for the SSDT targets.

I'm not sure what the fix is for this or if I'm doing something wrong, but curious if this is a bug or if there is a way to specify the correct targets? If so, where should that be referenced in the project file?

**Machine Setup**
I'm current using Visual Studio 2022 with no previous version installed on my machine and I have installed only .NET 6 & 7 separately from the Visual Studio Installer.

> Error in the command line when running `dotnet build or dotnet msbuild`
![image](https://github.com/dotnet/sdk/assets/56458944/6471b746-8e4c-48df-b5ea-8a93708490fe)

> Success when running `msbuild`
![image](https://github.com/dotnet/sdk/assets/56458944/4ec459d8-add7-4a7b-9c6f-f6efc1839736)

**Comment by baronfel** [comment] 2023-05-31 22:04
This is a duplicate of https://github.com/dotnet/sdk/issues/10683 - you can find the latest status of sqlproj support on the .NET CLI there.

**Closed by baronfel** 2023-05-31 22:04 UTC
Labels: untriaged, Area-NetSDK
