### ISSUE TITLE
BuiltOutputProjectGroup target does not include runtimeconfig.json file

### ISSUE THREAD

**Issue by rohit21agrawal** [dotnet/sdk#225] opened 2016-10-07 18:58 UTC
@nguerrera @eerhardt

**Comment by dsplaisted** [comment] 2016-11-11 04:32
What does `BuiltOutputProjectGroup` do?  How is the `BuiltProjectOutputGroupOutput` item group used?

**Comment by srivatsn** [comment] 2017-01-27 07:45
Dupe of https://github.com/dotnet/sdk/issues/472

**Closed by srivatsn** 2017-01-27 07:45 UTC
Labels: Bug
