### ISSUE TITLE
Don't load assemblies of the wrong version into devenv.exe

### ISSUE THREAD

**Issue by rrelyea** [dotnet/sdk#745] opened 2017-01-27 16:23 UTC
Causes:
Error occurred while restoring NuGet packages: Method not found: 'NuGet.RuntimeModel.RuntimeGraph NuGet.RuntimeModel.JsonRuntimeFormat.ReadRuntimeGraph(Newtonsoft.Json.Linq.JToken)'.

Was first recorded in NuGet repo: https://github.com/NuGet/Home/issues/4272

Fix for RC3 was taken: https://github.com/dotnet/sdk/pull/699

@onovotny just said on that issue, that it is still reproing with RC3.

??

**Comment by onovotny** [comment] 2017-01-27 16:26
Repro for me on RC3:

clone https://github.com/onovotny/microsoft-authentication-library-for-dotnet
checkout `xamarin-issue-1-rc3`

Open MSAL.sln

I get those errors in the Package Manager window and in the build window

**Comment by rrelyea** [comment] 2017-01-30 21:47
Internal user hit this once too: https://github.com/NuGet/Home/issues/4421

**Comment by dsplaisted** [comment] 2017-01-30 22:53
When I was testing the fix for this, I did still run into this error the first time I opened a solution.  It downloaded the packages during NuGet restore, and then errored out with the Method not found error.  However, After closing and reopening VS, the error went away and I was able to successfully restore and build.

So we still need a definitive solution for this to avoid the mismatches in which assemblies are loaded, but I think generally closing and reopening VS may workaround the issue.

@onovotny What happens if you close and re-open Visual Studio? I've been able to successfully open the MSAL solution without running into the missing method error. I believe whether you hit the issue is now dependent on the timing of how long package restore takes (and perhaps other concurrent operations).

**Comment by onovotny** [comment] 2017-01-31 01:43
With MSAL, if I close and reopen the solution, I don't appear to have that error appear. That said, it's a really bad first run experience and will lead people to form a bad first impression...and you know what people say about first impressions :)

**Comment by dsplaisted** [comment] 2017-01-31 07:55
@rrelyea I think I've come up with a fix for this: #762

See the description of that PR for details

**Closed** 2017-01-31 22:55 UTC
Labels: Blocking-Release, Bug
