### ISSUE TITLE
Clean operation depends on restore to have happened already in latest CLI 5738

### ISSUE THREAD

**Issue by kichalla** [dotnet/sdk#1103] opened 2017-04-08 00:19 UTC
Use the latest CLI `005738`:

Repro steps:
- dotnet new webapi
- make sure the .csproj file looks like below:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.0;net46</TargetFrameworks>
    <RuntimeFrameworkVersion>2.0.0-*</RuntimeFrameworkVersion>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.0-*" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0-*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="2.0.0-*" />
  </ItemGroup>

</Project>
```
- do a `dotnet msbuild /t:Clean`
- You will see an error like
```
C:\Users\kichalla\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview1-005738\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Publish.targets(237,5): error : Assets file 'C:\temp\repro2\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\temp\repro2\repro2.csproj]
C:\Users\kichalla\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview1-005738\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Publish.targets(237,5): error : Assets file 'C:\temp\repro2\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\temp\repro2\repro2.csproj]
```

An earlier related issue which was fixed in websdk: https://github.com/dotnet/sdk/issues/1080

Repeat the same steps with CLI `5418` and it does not repro there.

cc @mikeharder @pranavkm @vijayrkn

**Comment by mikeharder** [comment] 2017-04-08 00:29
This is blocking the ASP.NET build.

@vijayrkn, do you think the issue is in the SDK or WebSDK?

**Comment by pranavkm** [comment] 2017-04-08 00:31
It's fine to require `Restore` to be run prior to `Build`, but doesn't seem like it should be a requirement for `Clean`.

**Comment by mikeharder** [comment] 2017-04-08 01:10
This is unrelated to WebSDK.  Repro steps with console app:

1. Unzip https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview1-005738/dotnet-dev-win-x64.2.0.0-preview1-005738.zip
2. `dotnet new console`
3. Edit csproj and replace `<TargetFramework>netcoreapp2.0</TargetFramework>` with `<TargetFrameworks>netcoreapp2.0;net46</TargetFrameworks>`
4. `dotnet clean`

**Comment by mikeharder** [comment] 2017-04-08 01:19
Please verify both the console and webapi repros when fixing this issue.  They might be separate issues.

**Comment by livarcocc** [comment] 2017-04-08 03:59
@dsplaisted @ericstj This is the dotnet/standard package for 2.0 correct? The one that we are porting over to the dotnet/SDK?

If so, Daniel, in your current PR, can you verify that this scenario will work? If this is not a piece of code that we are porting, @ericstj can you verify that this works on your side?

**Comment by ericstj** [comment] 2017-04-10 16:50
These are happening because I sequenced HandlePackageFileConflicts after ResolvePackageDependenciesForBuild which is scheduled before AssignProjectConfiguration.  AssignProjectConfiguration runs during clean.  HandlePackageFileConflicts depends on _GetLockFileAssemblies (my own target using SDK task) which reads the assets file.  I only did that because I was trying to avoid depending on SDK internals and wanted to make things work the same was "as if" app were published.  This should be fixed by @dsplaisted's port, it uses items raised by RunResolvePackageDependencies which does no asset selection and won't run if the assets file is missing.

This one does look a little different to the original report.  I'll take a look at that to see if it was caused by my package.

**Comment by ericstj** [comment] 2017-04-10 17:01
The OP issue is caused by the following:
`CleanCopiedAssemblies` runs after `Clean` and depends on `RunResolvePublishAssemblies`.

`RunResolvePublishAssemblies` also calls `ResolvePublishAssemblies` which is the same task my targets were using.  One partial fix would be to put a condition on this task around the assets file existing.  That's only a partial fix since it wouldn't handle the case like @mikeharder suggested where you add a target and try to do a clean.  A better fix, in the same vein as what @dsplaisted did to the conflict resolution targets would be to change the behavior of `RunResolvePublishAssemblies` to use items already raised (instead of rereading the assets file) and *delete* the whole `ResolvePublishAssemblies` task.  This is probably general goodness for the SDK to eliminate the multiple reads of the assets file.

Finally, this all exposes a general problem with assets file and clean.  What if the assets file is gone, or if someone changed its content?  Shouldn't clean be smart enough to know what to delete?  Typically this is done using the cleanfile and writing to the cleanfile during build.  I think the SDK should look into using that (or perhaps its own cleanfile).

**Comment by mikeharder** [comment] 2017-04-10 18:11
The issue blocking ASP.NET may be slightly different yet than the two simplified repros shared above.  I will share the actual ASP.NET blocking issue shortly.  This is what needs to be fixed ASAP to unblock ASP.NET from using new SDK builds.

**Comment by mikeharder** [comment] 2017-04-10 18:35
# ASP.NET Blocking Repro
1. VM with clean Win10
2. Install .NET 4.6 Targeting Pack
  A. https://www.microsoft.com/en-us/download/details.aspx?id=48136
3. `git clone https://github.com/aspnet/Hosting`
4. `set KOREBUILD_DOTNET_VERSION=2.0.0-preview1-005738`
5. `build.cmd`

```
> dotnet msbuild @C:\Git\Hosting/artifacts/msbuild/msbuild.rsp
%LocalAppData%\Microsoft\dotnet\sdk\2.0.0-preview1-005738\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Publish.targets(237,5): error : Assets file 'C:\Git\Hosting\test\Microsoft.AspNetCore.Hosting.TestSites\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\Git\Hosting\test\Microsoft.AspNetCore.Hosting.TestSites\Microsoft.AspNetCore.Hosting.TestSites.csproj]
%LocalAppData%\Microsoft\dotnet\sdk\2.0.0-preview1-005738\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Publish.targets(237,5): error : Assets file 'C:\Git\Hosting\test\Microsoft.AspNetCore.Hosting.TestSites\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\Git\Hosting\test\Microsoft.AspNetCore.Hosting.TestSites\Microsoft.AspNetCore.Hosting.TestSites.csproj]
```

**Comment by ericstj** [comment] 2017-04-10 18:56
@mikeharder that looks like the issue I described [above] (https://github.com/dotnet/sdk/issues/1103#issuecomment-293013166).

I looked closer and it looks like this was the change that introduced it: https://github.com/aspnet/websdk/commit/6f022bfa70011de42fe20b696806fde908f2de13

If I comment out that added `CleanCopiedAssemblies` target in `sdk\2.0.0-preview1-005738\Sdks\Microsoft.NET.Sdk.Web.ProjectSystem\build\netstandard1.0\Microsoft.NET.Sdk.Web.ProjectSystem.targets` the problem goes away.  You might be able to override the target with an empty one in your build environment to workaround.

@mlorbetske added this dependency so the quickest thing might be to remove it, then work with SDK folks about getting that publish target he's depending on working in clean.

**Comment by mikeharder** [comment] 2017-04-10 18:59
@vijayrkn, @mlorbetske: Can the WebSDK be updated to unblock ASP.NET here?

**Comment by mlorbetske** [comment] 2017-04-10 19:17
That was added on behalf of @billhiebert, any ideas?

**Comment by mikeharder** [comment] 2017-04-10 19:25
We could also make a change in ASP.NET to workaround this until its fixed.  I'll try overriding the `CleanCopiedAssemblies` target in `Microsoft.AspNetCore.Hosting.TestSites.csproj` with a no-op target.

What would be the downsides of this workaround?  Some files might be left around after `Clean`?

**Comment by ericstj** [comment] 2017-04-10 19:37
@mlorbetske you should just remove those targets completely and use CopyLocalLockFileAssemblies=true as is suggested in the SDK [issue](https://github.com/dotnet/sdk/issues/1054) that was opened.

**Comment by vijayrkn** [comment] 2017-04-10 20:01
Will make the change in websdk to set CopyLocalLockFileAssemblies to true when CreateLocalDeployment is true

**Comment by BillHiebert** [comment] 2017-04-10 20:08
@vijayrkn  is going to remove the targets I added (to support local IIS development) as the functionality is covered by setting the CopyLocalLockFileAssemblies property.

**Comment by vijayrkn** [comment] 2017-04-10 20:13
https://github.com/aspnet/websdk/pull/181

**Comment by livarcocc** [comment] 2017-04-19 04:17
I believe this is fixed now. At least I tried in the latest CLI and I got no errors. Please, re-activate if this is still a problem.

**Closed by livarcocc** 2017-04-19 04:17 UTC
Labels: Blocking Partner, blocking-partner
