### ISSUE TITLE
Razor task ran into copy failure. 

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#29289] opened 2022-11-29 22:10 UTC
Please add a retry or SkipUnchangedFiles or fix the race condition.D:\a\1\s\src\RazorSdk\Tasks\Microsoft.NET.Sdk.Razor.Tasks.csproj(107,5): error MSB3026: Could not copy "D:\a\1\s\src\RazorSdk\Sdk\Sdk.targets" to "D:\a\1\s\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk.Razor\Sdk\Sdk.targets". Beginning retry 1 in 1000ms. The process cannot access the file 'D:\a\1\s\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk.Razor\Sdk\Sdk.targets' because it is being used by another process.  [D:\a\1\s\src\RazorSdk\Tasks\Microsoft.NET.Sdk.Razor.Tasks.csproj]

https://dev.azure.com/dnceng-public/public/_build/results?buildId=96657&view=results <-- first build failed here, I have the binlog if you need it.

**Comment by mkArtakMSFT** [comment] 2022-11-30 17:30
@jaredpar how do you track these issues? Should this move to the razor repo?

**Comment by jaredpar** [comment] 2022-11-30 17:58
> https://dev.azure.com/dnceng-public/public/_build/results?buildId=96657&view=results <-- first build failed here, I have the binlog if you need it.

@marcpopMSFT can you provide the binlog? 

> Please add a retry or SkipUnchangedFiles or fix the race

Definitely "fix the race". 

> Should this move to the razor repo?

Depends on how many we end up getting. If it's a simple one off then probably just leave here. If there is more volume then we'll end up moving to razor to better schedule things.

**Comment by jaredpar** [comment] 2022-11-30 22:51
@marcpopMSFT how do you reproduce this locally? The Target that is causing the problem is `CopyAdditionalFilesToLayout` inside of Microsoft.NET.Sdk.Razor.Task.csproj. Building locally that target is not triggered. 

> Though the target has declared its outputs, the output specification only references empty properties and/or empty item lists.

Trying to get the minimal repro locally so I can work through the problem.

**Comment by marcpopMSFT** [comment] 2022-11-30 23:30
I didn't reproduce locally. I just grabbed the binlog from the PR build and filed the issue.  The PR ran this command:
D:\a\1\s\.dotnet\sdk\7.0.100\MSBuild.dll /nologo -maxcpucount /m -verbosity:m /v:minimal /bl:D:\a\1\s\artifacts\log\Debug\Build.binlog /clp:Summary /logger:D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22561.2\tools\net7.0\Microsoft.DotNet.ArcadeLogging.dll /nr:False /p:ContinuousIntegrationBuild=True /p:TreatWarningsAsErrors=true /p:Configuration=Debug /p:RepoRoot=D:\a\1\s\ /p:Restore=True /p:DeployDeps=False /p:Build=True /p:Rebuild=False /p:Deploy=False /p:Test=False /p:Pack=True /p:IntegrationTest=False /p:PerformanceTest=False /p:Sign=True /p:Publish=False /p:RunTestsAsTool=true /warnaserror D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22561.2\tools\Build.proj

it was part of the test as tool leg of the build:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=96657&view=logs&j=1a72c28d-7a68-5d41-adbe-a7fdc2aec7fb&t=14e40ebc-73fd-5974-cd7e-50927e145076&s=6884a131-87da-5381-61f3-d7acc3b91d76

**Comment by jaredpar** [comment] 2022-12-01 00:50
I've run that command as close as possible locally and cannot reproduce the problem. The command I worked out is the following: 

> dotnet msbuild /nologo -maxcpucount /m -verbosity:m /v:minimal  /clp:Summary /nr:False /p:TreatWarningsAsErrors=true /p:Configuration=Debug /p:Restore=True /p:DeployDeps=False /p:Build=True /p:Rebuild=False /p:Deploy=False /p:Test=False /p:Pack=True /p:IntegrationTest=False /p:PerformanceTest=False /p:Publish=False /p:RunTestsAsTool=true /warnaserror /bl

Given that though I still see no real movement on the `CopyAdditionalFilesToLayout` target. There is only one instance which is not outright skipped and it has this which does not seem to be the symptom in the test run:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/146967/204939261-c496a19a-8560-405f-a2e1-696d61c52fef.png">

I'm more than happy to dig into this and try to make it better, but it's hard to make any progress without the ability to reproduce locally.

**Comment by marcpopMSFT** [comment] 2022-12-01 19:42
So without a local repro, you can't fix the race. Should we do one of the worse solutions then (aka add a retry) as this isn't the first time I've seen copy failures in our PRs though they could have been other files.

**Closed** 2023-01-09 18:02 UTC
Labels: untriaged, Area-AspNetCore
