### ISSUE TITLE
A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll. 

### ISSUE THREAD

**Issue by KanniyappanP** [dotnet/sdk#19363] opened 2021-07-28 16:18 UTC
I am trying to build the WinUI Desktop library project with latest project reunion upgrade 0.8.1, but i am getting a below issue while build the project.

`\Program Files\dotnet\sdk\6.0.100-preview.4.21255.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Windows.targets(50,5): error NETSDK1148: A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll. Please update to a newer .NET SDK in order to reference this assembly.`

But i am not using this package in my lib project.

`<PackageReference Include="Microsoft.Bcl.Build" Version="1.0.21" ExcludeAssets="all" />`

**My machine configuration:**

- VS 2019 16.10.2
- SDK 6.0.100-preview.4.21255.9
- SDK 5.0.302 also has the same issue.

Any workaround would be appreciated.

Thanks.

**Comment by marcpopMSFT** [comment] 2021-08-02 21:36
@angelazhangmsft Is this something that should be routed to the Reunion team or that you've seen before?

**Comment by angelazhangmsft** [comment] 2021-08-02 22:48
@marcpopMSFT looks like a duplicate of: https://github.com/microsoft/microsoft-ui-xaml/issues/5572

Can close this issue and track it there. We believe the issue is that the .NET 6 preview version in use has a lower Microsoft.Windows.SDK.NET.dll version than the .NET 5 SDK installed.

**Comment by DhanushKRaja** [comment] 2021-08-03 06:39
Hi, 

Please find my machine and sdk configuration's in my machine.

**My machine configuration:**

VS 2019 16.10.3
SDK 6.0.100-preview.6.21355.2(x64)
SDK 5.0.302 also has the same issue.

![SDK6](https://user-images.githubusercontent.com/87820212/127968775-1802b6d7-debc-4905-821f-4a61ace69018.jpg)

![WindowSDK](https://user-images.githubusercontent.com/87820212/127968980-b0c6c7d7-9b22-49a3-818f-1c4016998825.jpg)

![WinRT](https://user-images.githubusercontent.com/87820212/127969000-e4c027c3-f016-41d2-a639-736b17af0cfa.jpg)

I am facing the below Error when build the net50 project.

C:\Program Files\dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Windows.targets(55,5): error NETSDK114
8: A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll. Please update to a newer
.NET SDK in order to reference this assembly. [D:\#Development\CI\ribbon-winui\WinUI\Ribbon.WinUI\Src\Syncfusion.Ribbon
.WinUI_Net50.csproj]

Can I any updated solution for this issue.

Thanks in Advance.

**Comment by angelazhangmsft** [comment] 2021-08-03 17:30
@DhanushKRaja based on your .NET SDK versions installed, the project should be referencing the *.18 version of Microsoft.Windows.SDK.NET.dll. Would you be able to upload a binlog? @dsplaisted FYI

As a workaround for now, you could set the following property to override the package version:
```
<PropertyGroup>
    <WindowsSdkPackageVersion>10.0.18362.18</WindowsSdkPackageVersion>
<PropertyGroup>
```

**Comment by DhanushKRaja** [comment] 2021-08-04 05:01
Hi @angelazhangmsft 

Thanks for your update.

I have tried to override the package version as per your suggestion. 

```
<Project>
	<PropertyGroup>
		<WindowsSdkPackageVersion>10.0.18362.18</WindowsSdkPackageVersion>
   </PropertyGroup>
 <ItemGroup>
     <PackageReference Include="Microsoft.ProjectReunion" Version="0.5.6"/>
     <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.18362.18" />
     <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.18362.18" />
 </ItemGroup>
</Project>
```

Still I am having this Error on output window when build this net50 project after override the package version by the above property.

**error NETSDK1148: A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll. Please update to a newer .NET SDK in order to reference this assembly.**

I have repaired my visual studio too.

I have tried also with `<WindowsSdkPackageVersion>10.0.19041.10</WindowsSdkPackageVersion>`. Even though I could not resolve this SDK version update Issue.

My project bin folder was empty after got build my net50 project. Can you please update me, which binlog I should upload?

Thanks in advance

**Comment by angelazhangmsft** [comment] 2021-08-04 16:45
@DhanushKRaja I am not sure where the *.10 version of Microsoft.Windows.SDK.NET is coming from. Do you have a repro project I could look at, or would you be able to upload a [bin log file](https://msbuildlog.com/) by running `msbuild /bl` on your solution?

**Comment by DhanushKRaja** [comment] 2021-08-05 04:52
Hi @angelazhangmsft  Please find the bin log file. 
[binlog.zip](https://github.com/dotnet/sdk/files/6935977/binlog.zip)

Could please update me further ?

**Comment by angelazhangmsft** [comment] 2021-08-05 05:08
@DhanushKRaja from the binlog it looks like another error is occurring:
CS0234: The type or namespace name 'Core' does not exist in the namespace 'Syncfusion.UI.Xaml' (are you missing an assembly reference?) 

I am not seeing the NETSDK1148 error since the build seems to fail earlier. Would you be able to double check?

**Comment by DhanushKRaja** [comment] 2021-08-05 05:48
@angelazhangmsft  please find the updated binlog for the same project.

[updatedlog.zip](https://github.com/dotnet/sdk/files/6936188/updatedlog.zip)

**Comment by angelazhangmsft** [comment] 2021-08-05 15:43
@DhanushKRaja The NETSDK1148 error from the updated log is because you are referencing both 10.0.18362.18 and 10.0.19041.18 versions of the package. So I actually think you should remove the `WindowsSdkPackageVersion` property so we can see where the *.10 version is coming from in your original comment. 

I would remove all package overrides and set the `TargetFramework` to net5.0-windows10.0.19041.0. It looks like the right version of the Windows SDK package is getting pulled in via the TFM and .NET SDK 5.0.302.

**Comment by KanniyappanP** [comment] 2021-08-18 10:36
Thanks, above issue have been resolved after updating net6 preview 6.

**Closed** 2021-08-18 10:39 UTC
Labels: untriaged, Area-NetSDK
