### ISSUE TITLE
Run the publish single file for NET 6.0 failed on MacOS with error no usable version of libssl was found.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#15229] opened 2021-01-08 09:42 UTC
Machine OS:Catalina10.15.7

Repro steps:
1.Install .NET 6 SDK(6.0.100-alpha.1.21057.10) from https://github.com/dotnet/installer
2.Create console app(e.g dotnet new console) in CLI and modify *cproj file to update tfm from net5.0 to net6.0
3.Run dotnet publish with below command
dotnet publish -c Release -r osx-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
will only generate the single-file app and *.pdb file.
4.Copy the single-file app  and run on Mac OS

**Expected Result**
run successfully

**Actual Result**
Failed with error no usable version of libssl
![image](https://user-images.githubusercontent.com/65637796/104000026-a2bccc80-51d8-11eb-9219-25f92df2c8fd.png)

Dotnet --info:
.NET SDK (reflecting any global.json):
Version: 6.0.100-alpha.1.21057.10
Commit: 87c80e2837

Runtime Environment:
OS Name: Windows
OS Version: 10.0.19042
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21057.10\

Host (useful for support):
Version: 6.0.0-alpha.1.21057.2
Commit: 81b9558199

.NET SDKs installed:
6.0.100-alpha.1.21057.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.App 6.0.0-alpha.1.21057.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.0-alpha.1.21057.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.0-alpha.1.21056.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
https://aka.ms/dotnet-download

**Comment by VSadov** [comment] 2021-01-11 21:53
This is the same as https://github.com/dotnet/runtime/issues/46771, a fix is in progress.

**Comment by sfoslund** [comment] 2021-01-12 00:46
Closing as a duplicate of https://github.com/dotnet/runtime/issues/46771 per [this comment](https://github.com/dotnet/sdk/issues/15229#issuecomment-758248846).

**Closed by sfoslund** 2021-01-12 00:46 UTC
Labels: needs triage

**Comment by VSadov** [comment] 2021-01-13 23:58
https://github.com/dotnet/runtime/issues/46771 has been fixed in https://github.com/dotnet/runtime/pull/46640

**Comment by VSadov** [comment] 2021-01-14 00:02
@vdanche @sfoslund  -  I am wondering, was this a regression from 5.0 or we have a similar problem there too? 
Does the same scenario work when compiled with 5.0 SDK and the app is run in the same environment?

**Comment by vdanche** [comment] 2021-01-14 01:04
@VSadov The same scenario work when compiled with 5.0 SDK and the app is run in the same environment

**Comment by VSadov** [comment] 2021-01-14 01:15
Thanks @vdanche, it is good to know! It means that we do not need to port the same fix to 5.0 servicing. 

CC: @jeffschwMSFT

**Comment by vdanche** [comment] 2021-01-18 01:57
Fixed on NET 6 SDK--6.0.100-alpha.1.21064.46(runtime-6.0.0-alpha.1.21063.13)

![image](https://user-images.githubusercontent.com/65637796/104864306-902e5a00-5973-11eb-896e-b2b9a2572558.png)
