### ISSUE TITLE
.NET 5.0 SDK breaks SDK-based projects building WPF

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#12739] opened 2020-08-03 00:25 UTC
I've hit this in two repros that I use. On a box with 5.0 installed (which is installed by default by VS 16.8 builds), I get the following

Repros:

1. Install Version 16.8.0 Preview 2.0 [30402.4.master]
2. Open Developer Command Prompt
3. `git clone http://github.com/dotnet/project-system`
4. `cd project-system`
5. `git checkout 849f6398f79a4aa2ec6131c3ba2171232fee3133`
6. `build.cmd`

Expected: 0 errors
Actual:

```
C:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\PropertyPages\DebugPageControl.xaml.cs(19,13): error CS0103: The name 'InitializeComponent' does not exist in the current context [C:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\PropertyPages\DebugPageControl.xaml.cs(43,28): error CS0103: The name 'dataGridEnvironmentVariables' does not exist in the current context [C:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
C:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\PropertyPages\GetProfileNameDialog.xaml.cs(23,13): error CS0103: The name 'InitializeComponent' does not exist in the current context [C:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj]
```

**Comment by davkean** [comment] 2020-08-03 00:29
Looks like this PR broke this: https://github.com/dotnet/sdk/pull/10998/files.

**Comment by davkean** [comment] 2020-08-03 00:30
Had to workaround this in the following locations:

https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/264887
https://github.com/dotnet/project-system/pull/6458

**Comment by drewnoakes** [comment] 2020-08-03 22:43
Duplicate of #12324.

**Closed** 2020-08-03 23:22 UTC
