### ISSUE TITLE
RuntimeInformation and OSPlatform class does not exist after Upgrading to .NET5.0

### ISSUE THREAD

**Issue by mjebrahimi** [dotnet/sdk#14511] opened 2020-11-11 18:59 UTC
I do not know if this is a good place for this issue or not, but after updating the `Microsoft.Extensions.DependencyInjection.Abstractions` to version 5.0.0 it does not recognize the `RuntimeInformation` and `OSPlatform` classes.

[This repo](https://github.com/mjebrahimi/EasyCompressor) can reproduce this problem.

The strange thing is that these classes are available in versions 4.5 and 4.7, but not in 4.6!

![](https://user-images.githubusercontent.com/23256135/98852256-a815c900-246c-11eb-9468-07ba3150863b.png)

**Comment by eerhardt** [comment] 2020-11-12 18:32
@joperezr @ericstj - thoughts here?

The [`3.1` versions of `Microsoft.Extensions.DependencyInjection.Abstractions`](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection.Abstractions/3.1.10) had the following dependencies:

![image](https://user-images.githubusercontent.com/8291187/98980730-a1c23400-24e2-11eb-9560-72bbeec7e2e2.png)

In 5.0, along with moving repos, the tooling that makes the packages changed. And now the [5.0 dependencies](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection.Abstractions/5.0.0) are listed as:

![image](https://user-images.githubusercontent.com/8291187/98980847-c9b19780-24e2-11eb-8da5-938c40cff66c.png)

So for the net461 build, is the issue that now `netstandard2.0` isn't coming into the compile graph anymore?

**Comment by joperezr** [comment] 2020-11-12 19:11
RuntimeInformation and OSPlatform doesn't come from `Microsoft.Extensions.DependencyInjection.Abstractions` package, but instead from `System.Runtime.InteropServices.RuntimeInformation` package. It is possible that this worked in the past with older versions of the Extensions package due to a transitive dependency to RuntimeInformation, but looks like the newest package doesn't have that transitive dependency any longer (most likely because we added the net461 build). This means that now consumer apps would have to explicitly depend on the RuntimeInformation package if they want to use those types on net461+ which is no different to other packages whenever we decide to remove some transitive dependency for some framework.

**Comment by joperezr** [comment] 2020-11-12 19:13
BTW, having apps require to have an explicit dependency on RuntimeInformation when using those types should be the expectation, so I don't think there is anything we would want to fix here.

**Comment by joperezr** [comment] 2020-11-12 19:18
Actually just looked at it again and what was happening here before (and the reason why it worked) is that when folks used this package in net461 it was causing the netstandard facades to be includded in your project, which in this particular case was helping resolve these two types. That is why @eerhardt you don't see a dependency explicitly on the RuntimeInformation package but it was still getting pulled in. Now this package doesn't require the netstandard facades any longer (also resulting in your bin output folder for net461 to be much cleaner 😄) but that is also meaning in this particular case that these two types are not resolving. As explained above, a simple package Reference to the RuntimeInformation package should resolve this.

**Comment by eerhardt** [comment] 2020-11-12 19:59
Thanks for the investigation, @joperezr. I'm going to close this issue as "by design" since there isn't a change needed in our NuGet packages.

@mjebrahimi - like @joperezr mentions above, you can resolve this by adding a PackageReference to https://www.nuget.org/packages/System.Runtime.InteropServices.RuntimeInformation. Thanks for reporting the issue. This information can unblock someone else if they run into the same problem.

**Closed by eerhardt** 2020-11-12 19:59 UTC
