### ISSUE TITLE
15.8 update breaks system.net.http

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#2479] opened 2018-08-17 00:28 UTC
Reported via https://developercommunity.visualstudio.com/content/problem/311090/158-update-breaks-systemnethttp.html

> My ASP.NET Framework project stopped building after upgrading VS to 15.8 saying I need to add reference to System.Net.Http version 4.0.0.0, the reference is there but shows yellow warning flag. Tried adding/removing Reference, with/without NuGet package, removing HintPath as some other solutions suggest but no luck. I am unable to work. How do I roll the update back, please?

**Comment by dsplaisted** [comment] 2018-08-17 00:39
For those experiencing this issue, I need some additional information to help me investigate it.

The easiest way to do this would be to create an [MSBuild binary log](https://github.com/Microsoft/msbuild/blob/master/documentation/wiki/Binary-Log.md) of the build by passing the `/bl` parameter to `msbuild`, and share the resulting `msbuild.binlog` file.  However, be aware that this file will include lots of detailed information about your build and your machine, such as the contents of all of the project files (and other files such as .props and .targets files imported), the file names for all the source code files, the environment variables on the machine, and the inputs and outputs of all build tasks that are run.  So be sure that none of7 this is sensitive information that you do not want to share.

You can use the log viewer app linked from http://msbuildlog.com/ to inspect a .binlog file to see the kind of information it contains.

Thanks!

**Comment by dsplaisted** [comment] 2018-08-17 00:44
@joperezr @AlexGhiondea @ericstj FYI it looks like there may be an issue with the conflict resolution fix (#2250) in 15.8.

**Comment by bednart** [comment] 2018-08-20 21:49
Hi,
I updated VS 2017 to 15.8.1 and our project stop building on system.net.http error. I was able to delete all unnecessary code from our project and error is still there. Here is our solution [Src_2479.zip](https://github.com/dotnet/sdk/files/2303997/Src_2479.zip).

Steps:

- Open Gaia.Frontend.sln 
- Rebuild Gaia.Frontend solution (Sometimes needs more than one Rebuild to see System.Net.Http error)

After one or more rebuilds of Gaia.Frontend solution you should see `The type 'HttpMessageHandler' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.` error at App_Start\Startup.cs. If not try to rebuild Gaia.Frontend.Core project first and then Gaia.Frontend.Web project.

I tried to install System.Net.Http 4.3.3 NuGet package in both projects but error is still there. But if I tried to remove dotless.Core NuGet package from Gaia.Frontend.Core solution builds successfully. Hmm?

Are you able to simulate same error?

beda

**Comment by joperezr** [comment] 2018-08-20 21:51
Taking a look...

**Comment by joperezr** [comment] 2018-08-21 21:41
@bednart First of all thanks for sharing your solution, and yes, I can confirm that we can repro the issue with your project. I believe we found what the root cause is and we are working on a fix for it. We will update this issue with links to the PRs that will fix the issue as well as with workarounds if we find any.

**Comment by joperezr** [comment] 2018-08-22 20:12
Hey @bednart we were looking closer into the case, and wanted to know why is it that you added custom targets `ReplaceNetFxNetStandardRefWithLib` and `RemoveNetFxForceConflicts`? I wonder since apparently removing those from your .csproj will make the problem go away, so I'm interested into why did you need those two?

**Comment by bednart** [comment] 2018-08-23 07:15
@joperezr We added this to our project back in November 2017 when we updated system NuGet packages  to higher versions (For example System.Collections 4.0.11 -> 4.3.0). I don't know which version of VS 2017 we were using but I know that there was some strange build error similiar to this one. Adding _ReplaceNetFxNetStandardRefWithLib_ and _RemoveNetFxForceConflicts_ fixed it and we left it there since then. 

I've downloaded changeset in which we added those NetFx targets from TFS and try to build it on my current VS 2017 version 15.7.6 (I have to downgraded from 15.8.1). It works with and even with without those NetFx targets. So now it is unnecessary to have it there. It had to have something in common with previous verions of VS2017.

**Comment by joperezr** [comment] 2018-08-23 16:28
Yeah, I think they were supposed to workaround previous issues that were fixed by tooling. The problem here is that having them will expose this new issue you helped us found, so we will still fix that issue but in order for you to be able to have 15.8.1 and your project building, I would suggest removing them, as the tooling has fixed the issues they were trying to work around.

**Closed** 2018-08-30 19:31 UTC
