### ISSUE TITLE
Removing semicolon on C#

### ISSUE THREAD

**Issue by dayo05** [dotnet/sdk#22586] opened 2021-11-13 18:37 UTC
### Describe the solution you'd like
I think semicolon is not necessary and I suggest to make that optional

C# has evolved a lot, and now C# is able to code like other high=level-language which has very high productivity.
```cs
Console.WriteLine("Hello, world!");
Console.WriteLine("Hello, world!")
```
This two code has very less difference, first one has semicolon, second one doesn't have that. But it will improve productivity.

And in present, IDE puts them automatically, that means, It is able to predict where to semicolon exist.

**Comment by KalleOlaviNiemitalo** [comment] 2021-11-13 18:46
Duplicate of <https://github.com/dotnet/csharplang/discussions/496>.

**Closed** 2021-11-14 05:00 UTC
Labels: untriaged
