### ISSUE TITLE
No easy way to make whole app trimmable

### ISSUE THREAD

**Issue by marek-safar** [dotnet/sdk#15613] opened 2021-02-02 10:56 UTC
When trimming while application by setting <IsTrimmable>true</IsTrimmable> property for every assembly. The trimming build fails because of missing root assembly. The logic assumes the root assembly is never trimmed.

https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets#L211

@sbomer

**Comment by sbomer** [comment] 2021-02-02 16:18
I think this is a duplicate of https://github.com/dotnet/sdk/issues/13999 - unless you are asking for an easier way to do it like a simple [TrimAllAssemblies](https://github.com/mono/linker/blob/c45a25d77dfe278bd8fa675cb998cb0573dcb1c0/docs/design/trimmed-assemblies.md#trimallassemblies-global-opt-in) boolean?

**Comment by marek-safar** [comment] 2021-02-02 16:44
Yep, it's same problem.

**Closed** 2021-02-02 17:31 UTC
Labels: untriaged
