### ISSUE TITLE
Explicitly specified targets are run twice when `-f` option is specified with `dotnet build`

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#11305] opened 2020-04-15 23:29 UTC
Create the following project:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp3.1;net472</TargetFrameworks>
  </PropertyGroup>
  <Target Name="X">
    <Message Importance="high" text="hello world targetFramework=$(TargetFramework)"/>
  </Target>
</Project>
```

Run the following command:

```
dotnet build -f net472 /t:X
```

## Expected

The `X` target should be run once

## Actual

The `X` target is run twice:

```
Microsoft (R) Build Engine version 16.6.0-preview-20162-03+00781ad13 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\3.1.300-preview-015048\MSBuild.dll -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\3.1.300-preview-015048\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\3.1.300-preview-015048\dotnet.dll -maxcpucount -target:Restore /t:X -verbosity:m /bl .\CustomTarget.csproj
  Determining projects to restore...
  All projects are up-to-date for restore.
  hello world targetFramework=
C:\Program Files\dotnet\sdk\3.1.300-preview-015048\MSBuild.dll -nologo -consoleloggerparameters:Summary -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\3.1.300-preview-015048\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\3.1.300-preview-015048\dotnet.dll -maxcpucount -property:TargetFramework=net472 -verbosity:m /bl /t:X .\CustomTarget.csproj
  hello world targetFramework=net472
```

## Analysis

The presence of the `-f` parameter causes a separate process to run restore (instead of using msbuild's built-in `/restore` support).  It excludes the `-f` parameter, but not the `-t` parameter, so the custom target gets run once during the restore process and once during the normal build.

A solution would be to add the `-t` parameter to `IsExcludedFromRestore`: https://github.com/dotnet/sdk/blob/ef9005ca03a45d4cc11b16945988726c670b1932/src/Cli/dotnet/commands/RestoringCommand.cs#L72-L73

However, this would mean that specifying a custom target would switch to a separate process for restore, which isn't ideal.  So probably we want a way to exclude the target parameter from the separate restore process, but not by itself cause that to happen.

**Comment by dsplaisted** [comment] 2020-04-15 23:30
@marcpopMSFT This would be a good one for Jacques, though I don't know his GitHub ID right now.

**Comment by Anipik** [comment] 2020-04-15 23:31
cc @ViktorHofer @ericstj

**Comment by ViktorHofer** [comment] 2020-04-17 14:26
This seems trivial to fix. Can we please prioritize this issue as it currently impacts us in dotnet/runtime? Also should we back-port the fix into the 3.x?

**Comment by marcpopMSFT** [comment] 2020-04-21 18:00
@dsplaisted His handle is joeloff.  Looks like I need an outlook rule as this notification ended up in my clutter folder.

**Comment by ViktorHofer** [comment] 2020-07-22 21:36
ping @joeloff

**Comment by sfoslund** [comment] 2021-06-10 17:07
Just confirmed that this was fixed by our previous changes, this no longer repros with the latest main builds: 

> C:\code\tmp>dotnet build -f net472 /t:X
Microsoft (R) Build Engine version 17.0.0-preview-21310-01+0d37e8293 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
  Determining projects to restore...
  All projects are up-to-date for restore.
  hello world targetFramework=net472
Build succeeded.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:00:00.09

**Closed by sfoslund** 2021-06-10 17:07 UTC
