### ISSUE TITLE
dotnet workload update seems to do a lot of stuff

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/sdk#38953] opened 2024-02-22 14:19 UTC
## dotnet workload update seems to do a lot of stuff

I perceived that I was updating the advertising manifests. I am not sure how a normal user would perceive understanding what's available, but this step is requested in the Aspire docs: https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/setup-tooling?tabs=visual-studio#install-net-aspire. I wanted to update to install Aspire.

It said I had no workloads installed in this feature band - cool, but what's a feature band?

Then it asked to change my machine and did this: 

![image](https://github.com/dotnet/sdk/assets/5844318/69bd3f0d-573e-47b0-86ca-52e8b7af3349)

1. what! I do not want some of these, or do not want them right now
2. Were they acctually installed, or just downloaded and removed? (at least fix the output)

## Describe the solution you'd like

Don't download or run msi's until I ask for them.

**Comment by KathleenDollard** [comment] 2024-02-22 14:32
Here is my list after running this and installing aspire:

![image](https://github.com/dotnet/sdk/assets/5844318/3aea664a-bef5-44d9-a585-bcb4b8af30f5)

This might indicate that I had selected these workloads, and then installing them is reasonable. If that is the case, this issue is clarity in output - if it updated those workloads it did not say so, and if it told me where they had come from that would be nice. 

I wish we could have a prompt here before the install to clarify why it is happening and what will be updated.

**Comment by onionhammer** [comment] 2024-03-03 14:30
Workloads, or at least how they're being used/abused seems very anti- the thing nuget did by making dependencies depend on what the csproj says, and pushes us more into the old days of, I dont know, python where you just have whatever your machine has and doing stuff might fail if you happen to have the wrong version.

**Comment by baronfel** [comment] 2024-03-03 18:28
This one is mostly a duplicate of #37163, but with useful questions and details. I'm going to close it as a duplicate, but since it's linked we'll be able to refer to the comments and images here.

**Closed by baronfel** 2024-03-03 18:28 UTC
