### ISSUE TITLE
Windows Update error 0x80070643 trying to install "2021-11 .NET 5.0.12 Update for x64 Client (KB5007884)"

### ISSUE THREAD

**Issue by conioh** [dotnet/sdk#23307] opened 2022-01-06 23:19 UTC
### Description

* Please share a clear and concise description of the problem.

![image](https://user-images.githubusercontent.com/10606081/148465201-6b21719d-e0f4-4f0e-af83-c0596f063b44.png)

* What behavior are you seeing, and what behavior would you expect?
Tried to install "update" to 5.0.12 even when I have runtime 5.0.13 installed (from the latest SDK download) or when I don't have .NET 5 at all.
I expect that update to succeed if needed, and in case I have a newer version or don't have .NET 5 at all not to get an "update" at all.

### Configuration

* What OS and version, and for Linux, what distro?
Windows 11 build 22000.376

* What is the architecture (x64, x86, ARM, ARM64)?
x64

* Do you know whether it is specific to that configuration?
No.

### Regression?

Absolutely.

### Other information

The error code is similar to the one mentioned in dotnet/core#7044 but:
- The workaround of updating the Visual Studio installer is irrelevant (there were no updates, uninstalling VS 2019 didn't help, my VS 2022 doesn't include .NET 5 as an installed component, etc.)
- Installing the latest SDK didn't help. Windows Update actually tries to "update" 5.0.12 to 5.0.13, whatever that means.
- Another user has reported (https://github.com/dotnet/core/issues/7036#issuecomment-1007005557) that upgrading VS 2022 _to the latest preview_ resolves this issue, but not the similar dotnet/core#7093. I have not tried it myself.

![image](https://user-images.githubusercontent.com/10606081/148465691-864d6dd3-c526-4c9c-8a9b-3d2c3f7c4a69.png)

**Comment by Jacques-eMediaIT** [comment] 2022-01-07 06:16
I'm also getting this error.

**Comment by osmankilic29** [comment] 2022-01-07 06:40
i have this error too.
https://answers.microsoft.com/tr-tr/windows/forum/windows_11-wintop_update/2021-11-net-core-3121-update-for-x64-client/a1bfadcc-c245-40c4-ad99-44a59e43ccc2

**Comment by sfc9982** [comment] 2022-01-07 07:54
I'm also getting this error.

**Comment by dotWils** [comment] 2022-01-07 08:13
Exactly the same here, using VS2022.
 VS2019 and VS2022 preview uninstalled....

**Comment by sfc9982** [comment] 2022-01-07 08:15
Solved by install this update from WU catalog:
https://www.catalog.update.microsoft.com/Search.aspx?q=.NET%205.0.12

**Comment by osmankilic29** [comment] 2022-01-07 08:29
> Bu güncelleştirmeyi WU kataloğundan yükleyerek çözüldü: https://www.catalog.update.microsoft.com/Search.aspx?q=.NET%205.0.12

![2022-01-07_11h27_42](https://user-images.githubusercontent.com/97276489/148514875-d8283693-d9cd-4fa9-b105-fc7a509570fa.png)

which ones?

![2022-01-07_11h25_33](https://user-images.githubusercontent.com/97276489/148514917-5d31bda2-10dc-4b98-ba46-dc634fb3fada.png)

![2022-01-07_11h26_42](https://user-images.githubusercontent.com/97276489/148514923-09ce4a83-a10e-45bc-9b4a-4bf78dc65bcb.png)

**Comment by sfc9982** [comment] 2022-01-07 08:32
@osmankilic29 

Unfortunatly, all of them, and ignore those you cant install.
Just install all which you can install successfully, and then check for updates in `System Setting - Windows Update`.
You will be notified that the `.Net` is the latest.

**Comment by redcodefox** [comment] 2022-01-07 12:15
> @osmankilic29
> 
> Unfortunatly, all of them, and ignore those you cant install. Just install all which you can install successfully, and then check for updates in `System Setting - Windows Update`. You will be notified that the `.Net` is the latest.
> 
> **Added: a reboot may be needed**

I can confirm that this has resolved the issue for me. It didn't need a reboot,  I just clicked on 'Retry' again and no more updates popped up!

**Comment by Paresh98000** [comment] 2022-01-07 13:51
I have received same error

**Comment by azhuge233** [comment] 2022-01-07 21:44
What @sfc9982 mentioned above didn't work for me, but while I was trying manually install all the packages, I found out the only two packages I cannot install is `Microsoft Windows Desktop Runtime 5.0.12(x86 and x64)`, I checked the installation log and this appeared

> ...
[3134:0A1C][2022-01-08T05:29:40]i101: Detected package: windowsdesktop_runtime_5.0.12_win_x86.msi, state: Present, cached: Complete
[3134:0A1C][2022-01-08T05:29:40]i052: Condition '((VersionNT > v6.1) OR (VersionNT = v6.1 AND ServicePackLevel >= 1))' evaluates to true.
[3134:0A1C][2022-01-08T05:29:40]i199: Detect complete, result: 0x0
[3134:1164][2022-01-08T05:29:42]e000: Error 0x80070666: Cannot install a product when a newer version is installed.

So I uninstalled the newer version (.NET SDK 5.0.210 on my machine, maybe it was intalled by Visual Studio), then open `Settings  - Windows Update` and try install the update again, the error is gone.

**Comment by sfc9982** [comment] 2022-01-08 00:18
@azhuge233

可能是Windows Update检测出问题了，想办法做Clean Install就行。
把冲突的都卸了，再重新安装
解决了就好。

---

Maybe problem of Windows Update, please try to make a fresh install.
Uninstall all the conflicts one, and do a re-install.
I'm glad you solve that.

**Comment by kybecollins** [comment] 2022-01-08 09:40
> Solved by install this update from WU catalog: https://www.catalog.update.microsoft.com/Search.aspx?q=.NET%205.0.12

All four files?

**Comment by sfc9982** [comment] 2022-01-08 09:42
> > Solved by install this update from WU catalog: https://www.catalog.update.microsoft.com/Search.aspx?q=.NET%205.0.12
> 
> All four files?

Choose which fits your system

**Comment by kybecollins** [comment] 2022-01-08 12:11
It really worked, thank you so much. I had to remove the other versions
tho. Have a good day and an even better year.

**Comment by lonevvolf** [comment] 2022-01-08 20:31
Seems that having newer packages installed (5.0.13) causes this issue.  Searched installed packages with 5.0.13 version, uninstalled these, and then retried the Windows Update.  Then it worked.

**Comment by purplelexy** [comment] 2022-01-09 06:39
I resolved the same issue by uninstalling all updates back to October 2021.  I then did a restart.   Windows automatically reinstalled all updates.  No issues

**Comment by ScruffR** [comment] 2022-01-09 14:19
The interesting thing about this issue is also that MS's own Edge and Defender deems downloads from the WU Catalog as NOT SAVE and requires the user to commit to the risk. 
This might also be big part of the actual reason for the issue in the first place.

**Comment by sfc9982** [comment] 2022-01-09 14:59
Microsoft old customs





 ----------Reply to Message----------
 On Sun, Jan 9, 2022 22:19 PM ***@***.***&gt; wrote:

  

 
The interesting thing about this issue is also that MS's own Edge and Defender deems downloads from the WU Catalog as NOT SAVE and requires the user to commit to the risk.
 This might also be big part of the actual reason for the issue in the first place.

**Comment by bplasmeijer** [comment] 2022-01-09 18:52
removing 5.0.13 solve the problem

**Comment by massimo-de-marinis** [comment] 2022-01-10 08:33
fixed for KB5007885 and KB5007884 by uninstalling older and newer versions of 2021-11 .NET Core 3 and 2021-11 .NET 5

**Comment by xavisegura** [comment] 2022-01-10 09:22
Removing 5.0.13 and installing all mentioned updates worked perfectly, thank you!

**Comment by ashemedai** [comment] 2022-01-10 15:37
If you cannot find it under `.NET`, either search for `5.0.13` or `runtime`. I kept on running into this despite all .NET being gone, only to notice there was still a version of 5.0.13 of `Microsoft Windows Desktop Runtime`.

**Comment by Froosh** [comment] 2022-01-11 03:03
Updating Visual Studio to current version (I'm still using VS2019, so v16.11.8) solved the .NET 5.0.12 and .NET 3.0.21 issues for me.

**Comment by carlitorendon** [comment] 2022-01-11 17:53
I got an even "easier" path. Using [Bulk Crap Uninstaller](https://www.bcuninstaller.com/) I just selected all the .Net packages with version 3.x and 5.x. 

Then I went and refresh the updater in Windows Settings and bingo, it was able to itself take care of it. Hope this helps someone. 

(BTW, don't be concerned about the BCU package. I have used it for years and it is a legit utility).

**Comment by marcpopMSFT** [comment] 2022-02-02 00:33
@joeloff is this a known MU issue?

**Comment by kiwiant** [comment] 2022-02-02 00:48
> @joeloff is this a known MU issue?

Don't know who owns the issue but it resolved after January's patch Tuesday.

**Comment by joeloff** [comment] 2022-02-02 03:55
> @joeloff is this a known MU issue?

There was an issue with one of the offerings. A fix was submitted, but some of the installers got unpublished causing older versions to offer when newer versions were installed. That triggers the downgrade error (where the bundle reports that a newer version is installed).

**Comment by hasancemcerit** [comment] 2022-02-02 18:50
In case anyone is tired of this error until a proper fix is applied, and if you are sure that you are ahead of this SDK versions anyway, an option/workaround is to hide these by:

```
Install-Module -Name PSWindowsUpdate
Import-Module PSWindowsUpdate
```


```
Get-WindowsUpdate

ComputerName Status     KB          Size Title
------------ ------     --          ---- -----
*****        -D-----    KB5007885  180MB 2021-11 .NET Core 3.1.21 Update for x64 Client (KB5007885)
*****        -D-----    KB5007884  115MB 2021-11 .NET 5.0.12 Update for x64 Client (KB5007884)
```

```
Hide-WindowsUpdate -KBArticleID KB5007885

ComputerName Status     KB          Size Title
------------ ------     --          ---- -----
*****        D--H--     KB5007885  180MB 2021-11 .NET Core 3.1.21 Update for x64 Client (KB5007885)
```

```
Hide-WindowsUpdate -KBArticleID KB5007884

ComputerName Status     KB          Size Title
------------ ------     --          ---- -----
*****        D--H--     KB5007884  115MB 2021-11 .NET 5.0.12 Update for x64 Client (KB5007884)
```

**Comment by marcpopMSFT** [comment] 2022-02-05 00:19
> There was an issue with one of the offerings. A fix was submitted, but some of the installers got unpublished causing older versions to offer when newer versions were installed. That triggers the downgrade error (where the bundle reports that a newer version is installed).

Per Jacques reply, it sounds like this was a prior issue with our Microsoft Update release that should be fixed now so closing.

**Closed by marcpopMSFT** 2022-02-05 00:19 UTC
Labels: untriaged, Area-Install

**Comment by ScruffR** [comment] 2022-03-04 08:38
Waiting for it to reappear as it regularly does since at least 2015
