### ISSUE TITLE
RunReadyToRunCompiler task doesn't produce actionable information on failures

### ISSUE THREAD

**Issue by trylek** [dotnet/sdk#15466] opened 2021-01-22 23:28 UTC
While switching over framework compilation to use Crossgen2 I noticed that the RunReadyToRunCompiler task in

https://github.com/dotnet/sdk/blob/d2a44c110494d0db60f873f0273598e60bcc7fbe/src/Tasks/Microsoft.NET.Build.Tasks/RunReadyToRunCompiler.cs#L14

isn't too developer friendly when hitting errors. In most cases the only diagnostic output is the error message "Invalid parameters were passed to RunReadyToRunCompiler task" no matter whether the problem is missing JitPath, DOTNET_ROOT not pointing at the .dotnet folder and preventing execution of the crossgen2 managed executable or anything else.

Even locally it's super complicated to identify what went wrong; on top of that the absence of any diagnostic output makes it very hard to identify whether crossgen or crossgen2 compilation has taken place from AzDO lab jobs. The purpose of this issue is to improve this situation. Here are some suggestions that come to mind:

1) ValidateParameters should spew diagnostic output stating clearly which parameter it doesn't like and for what reason.

2) Similar to CoreCLR Crossgen2 test build, we should display command lines representing the individual Crossgen2 executions when compiling the framework and error information upon failure. I haven't managed to receive any logging information about Crossgen2 executions even after I bumped up msbuild verbosity to diagnostic.

/cc: @dotnet/crossgen-contrib
/cc: @jkoritzinsky, @AntonLapounov

**Comment by AntonLapounov** [comment] 2021-01-22 23:55
I agree on that.  It was too late to fix it for 5.0 release when I hit this issue.

**Comment by AntonLapounov** [comment] 2021-04-20 00:54
@trylek I just tried SDK publishing with normal verbosity:
```cmd
dotnet new console
dotnet publish --packages pkg -p:PublishReadyToRun=True -p:PublishReadyToRunUseCrossgen2=True -c Release -r win-x64 -v:n
```
and that **does** output the Crossgen2 command line. For .NET 5:
```
       _CreateR2RImages:
         C:\HelloWorld\pkg\microsoft.netcore.app.crossgen2.win-x64\5.0.1\tools\crossgen2.exe -O
         --jitpath:"C:\HelloWorld\pkg\microsoft.netcore.app.crossgen2.win-x64\5.0.1\tools\clrjit-win-x64.dll"
         --composite
         --inputbubble
         ...
```
For .NET 6:
```
       _CreateR2RImages:
         C:\HelloWorld\pkg\microsoft.netcore.app.crossgen2.win-x64\6.0.0-preview.5.21218.1\tools\crossgen2.exe --targetos:windows
         --targetarch:x64
         -O
         ...
```
Maybe the issue is not in the SDK?

**Comment by AntonLapounov** [comment] 2021-04-27 20:27
Closing this as fixed on the SDK side.

**Closed by AntonLapounov** 2021-04-27 20:27 UTC
Labels: Area-ReadyToRun, Team:Runtime
