### ISSUE TITLE
.NET Worker Project Fails on macOS When AssemblyName xml tag is provided and its value ends with .Service

### ISSUE THREAD

**Issue by StasPerekrestov** [dotnet/sdk#41724] opened 2024-06-21 13:13 UTC
Hello,

When creating a .NET Worker project using `Microsoft.NET.Sdk.Worker` on macOS, the application fails to start if the AssemblyName ends with .Service. The application exits with a signal SIGKILL (exit code 137) during the startup phase. This issue does not occur on Linux or within Docker containers. Additionally, the application runs successfully when executed directly using `dotnet assembly_name.dll`.

**Reproduction Steps:**

1. 

  ```sh
  dotnet new worker -n TestWorkerService
  cd TestWorkerService
  ```
2. Modify the project file (TestWorkerService.csproj) to set the AssemblyName ending with .Service:
  ` <AssemblyName>TestWorker.Service</AssemblyName>`

3. `dotnet watch`

MacOs: 14.5 (23F79)
SDK: 8.0.302

**Expected Behavior:**

The .NET Worker application should start successfully, regardless of the AssemblyName.

**Actual Behavior:**

The application fails to start, exiting with code 137 (SIGKILL), and no useful logs or errors are produced to diagnose the issue.

**Workaround:**

Changing the AssemblyName to not end with `.Service` allows the application to start successfully.

**Additional Information:**
```sh
lldb -- dotnet run
```

```
(lldb) run
Process 3149 stopped
* thread #26, name = 'RequestBuilder thread', stop reason = signal SIGUSR1
    frame #0: 0x0000000100b11de8 libcoreclr.dylib`GetLastError
libcoreclr.dylib`GetLastError:
->  0x100b11de8 <+0>:  stp    x29, x30, [sp, #-0x10]!
    0x100b11dec <+4>:  mov    x29, sp
    0x100b11df0 <+8>:  bl     0x100f053b8               ; symbol stub for: __error
    0x100b11df4 <+12>: ldr    w0, [x0]
Target 0: (dotnet) stopped.
```

Thank you.

**Comment by vitek-karas** [comment] 2024-06-23 18:50
Duplicate of https://github.com/dotnet/runtime/issues/93716.
Seems to be the OS's behavior, not specific to .NET.

**Closed by vitek-karas** 2024-06-23 18:50 UTC
Labels: untriaged
