### ISSUE TITLE
Assembly.GetExecutingAssembly().GetManifestResourceNames() does not detect files with more than 1 '.' in filename

### ISSUE THREAD

**Issue by pureggerstefan** [dotnet/sdk#13547] opened 2020-09-07 11:37 UTC
I was trying to read resource-files in the executing assembly and I noticed that it couldn't read files with mulitiple '.' in their names. 

Example:

"en-US.json" was found.
"Index.en-US.json" was not found. 

I noticed this in a Blazor-WASM App running on .NET5 and I got the SDK  5.0.100-preview.8.20417.9 installed on my machine.

**Comment by jkotas** [comment] 2020-09-11 22:44
This may be duplicate of https://github.com/dotnet/sdk/issues/13395.

The resource name is generated using a fairly complex algorithm: https://docs.microsoft.com/en-us/dotnet/core/resources/manifest-file-names . If you want to have a full control over the name of the resource, it is best to specify it using `LogicalName` attribute.

**Comment by aersamkull** [comment] 2020-09-15 06:10
I am pretty sure it is a duplicte of #
I think it should be documented properly that this does not work; or even better there should be a compile error. Failing silently is not really nice

**Comment by sfoslund** [comment] 2020-09-16 16:41
Closing this as a duplicate of #13395

**Closed by sfoslund** 2020-09-16 16:41 UTC
Labels: needs triage
