### ISSUE TITLE
`dotnet build` compiler cache does not care about MSBuild property changes

### ISSUE THREAD

**Issue by hjc4869** [dotnet/sdk#2628] opened 2018-10-28 13:37 UTC
Example:

test.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TestProperty)' == '1' ">
    <DefineConstants>TEST_PROPERTY</DefineConstants>
  </PropertyGroup>

</Project>

```

Program.cs
```csharp
using System;

namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
#if TEST_PROPERTY
            Console.WriteLine(1);
#else
            Console.WriteLine(2);
#endif
        }
    }
}
```

```
PS C:\test> dotnet build /p:TestProperty=1 /v:q /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.84
PS C:\test> dotnet run
1
PS C:\test> dotnet build /v:q /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.83
PS C:\test> dotnet run
1
PS C:\test> Remove-Item -Recurse bin,obj
PS C:\test> dotnet build /v:q /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.60
PS C:\test> dotnet run
2
PS C:\test>
```

dotnet --version
2.1.403
dotnet --list-sdks
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.402 [C:\Program Files\dotnet\sdk]
2.1.403 [C:\Program Files\dotnet\sdk]

**Comment by rainersigwald** [comment] 2018-10-29 14:56
This is essentially due to a limitation of MSBuild: incrementality is defined by file timestamps, not ephemeral information like properties. In this particular case, there's a potential fix tracked by an MSBuild bug, which I'll link in the next post.

**Comment by rainersigwald** [comment] 2018-10-29 14:57
Duplicate of https://github.com/Microsoft/msbuild/issues/3350

**Closed by rainersigwald** 2018-10-29 14:57 UTC
