### ISSUE TITLE
Single Executable Permission Issues on Linux (.netcoreapp3.0)

### ISSUE THREAD

**Issue by robsonj** [dotnet/sdk#4085] opened 2019-12-19 20:41 UTC
When running a single exe packaged .Net Core app on Linux, it will first expand itself to a sub directory under /var/tmp/.net .

If /var/tmp/.net does not exist, the directory /var/tmp/.net is created with 700 permissions, instead of 755 permissions (same applies for the individual app folder under the created .net folder)...

```
drwx------   6 joebloggs   domain_users 4096 Dec 19 14:18 .net
```

The means, that only the first person to run the single exe packaged .Net Core application can ever execute the application, and nobody else can run any other .Net Core single exe packaged app on that machine, as it fails with permission issues to the /var/tmp/.net folder.

The /var/tmp/.net folder should probably be created with 777 permissions and each app folder underneath it, be created with 755 permissions.

**Comment by swaroop-sridhar** [comment] 2020-01-03 01:54
This is a dup of https://github.com/dotnet/core-setup/issues/8882

**Comment by swaroop-sridhar** [comment] 2020-01-03 22:02
@livarcocc  This is a runtime issue. The problem is understood (dotnet/core-setup#8882), and we are working on a fix. You can close this as a dup. Thanks.

**Closed** 2020-01-04 00:34 UTC
