### ISSUE TITLE
Cmd.exe exited with code '1'

### ISSUE THREAD

**Issue by Panuchi** [dotnet/sdk#11098] opened 2020-04-01 16:36 UTC
https://github.com/vknet/vk/commit/132484466870dfa5016d41bf8b2365daaafa1bf8

I added two of these parameters from the commit on top, an error occurred and when executing the dotnet nuget push *.nupkg -k *** -s https://www.myget.org/F/vknet/

```
"C:\windows\system32\cmd.exe" /D  E: ON /V: OFF /S /C "CALL" D:\a\_temp\632e1878-73a1-496c-8483-8dd17c58a7e9.cmd ""
error: File does not exist (* .nupkg).
## [error] Cmd.exe exited with code '1'.
```

Here is a mistake

**Comment by dsplaisted** [comment] 2020-04-09 04:35
@rrelyea @nkolev92 Can one of you triage this?  It looks like a NuGet push failure, possibly caused by defining both `TargetFramework` and `TargetFrameworks`.

**Comment by nkolev92** [comment] 2020-04-09 18:16
NuGet doesn't really prevalidate the packages before pushing, so I'd guess the tfm/tfms stuff is a red herring. 

The error message suggests that that what you are trying to push is "* .nupkg", note the extra space @Panuchi. 

Can you double check that you are providing `*.nupkg` instead of `* .nupkg`

@dsplaisted Moving this to the NuGet repo.

**Comment by nkolev92** [comment] 2020-04-09 18:17
Actually I can't move it :( 
It's not letting me move issues cross-orgs.

**Comment by dsplaisted** [comment] 2020-04-09 19:38
@Panuchi if @nkolev92's comment doesn't help you solve the issue, please file it in the NuGet repo: https://github.com/nuget/home

**Closed by dsplaisted** 2020-04-09 19:38 UTC
Labels: needs triage
