### ISSUE TITLE
Issue installing dotnet-sdk-2.0.0 on Ubuntu

### ISSUE THREAD

**Issue by ipinak** [dotnet/sdk#1579] opened 2017-09-12 08:10 UTC
I'm trying to install dotnet sdk  2.0.0 on a ubuntu 16.04 and I get the following error.

```sudo apt-get install dotnet-sdk-2.0.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  aspnetcore-store-2.0.0 dotnet-hostfxr-2.0.0 dotnet-runtime-2.0.0
The following NEW packages will be installed:
  aspnetcore-store-2.0.0 dotnet-hostfxr-2.0.0 dotnet-runtime-2.0.0 dotnet-sdk-2.0.0
0 upgraded, 4 newly installed, 0 to remove and 6 not upgraded.
Need to get 107 MB of archives.
After this operation, 307 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 aspnetcore-store-2.0.0 amd64 2.0.0-1 [18,1 MB]
Get:2 https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 dotnet-hostfxr-2.0.0 amd64 2.0.0-1 [135 kB]
Get:3 https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 dotnet-runtime-2.0.0 amd64 2.0.0-1 [18,6 MB]
Get:4 https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 dotnet-sdk-2.0.0 amd64 2.0.0-1 [70,3 MB]
Fetched 107 MB in 18s (5 771 kB/s)                                                                                 
(Reading database ... 273964 files and directories currently installed.)
Preparing to unpack .../aspnetcore-store-2.0.0_2.0.0-1_amd64.deb ...
Unpacking aspnetcore-store-2.0.0 (2.0.0-1) ...
dpkg: error processing archive /var/cache/apt/archives/aspnetcore-store-2.0.0_2.0.0-1_amd64.deb (--unpack):
 trying to overwrite '/usr/share/dotnet/store/x64/netcoreapp2.0/system.interactive.async/3.1.1/lib/netstandard1.3/System.Interactive.Async.dll', which is also in package dotnet-dev-2.0.0-preview1-005977 2.0.0-preview1-005977-1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package dotnet-hostfxr-2.0.0.
Preparing to unpack .../dotnet-hostfxr-2.0.0_2.0.0-1_amd64.deb ...
Unpacking dotnet-hostfxr-2.0.0 (2.0.0-1) ...
Selecting previously unselected package dotnet-runtime-2.0.0.
Preparing to unpack .../dotnet-runtime-2.0.0_2.0.0-1_amd64.deb ...
Unpacking dotnet-runtime-2.0.0 (2.0.0-1) ...
Selecting previously unselected package dotnet-sdk-2.0.0.
Preparing to unpack .../dotnet-sdk-2.0.0_2.0.0-1_amd64.deb ...
Unpacking dotnet-sdk-2.0.0 (2.0.0-1) ...
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/aspnetcore-store-2.0.0_2.0.0-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

After that nothing new can be installed unless I remove the repo and autoremove everything.

**Comment by Arcanst** [comment] 2017-10-08 16:39
I'm having the same issue. Did you resolve it?

**Comment by ipinak** [comment] 2017-10-08 17:33
This does not help, I have tried it already. I have manually installed it instead.

**Comment by JunTaoLuo** [comment] 2017-10-08 21:38
The problem is that stable releases, in this case 2.0.0, of the runtime store (which is included in the SDK) cannot be installed when the preview releases, 2.0.0-preview1, are installed. This is noted in the line:
```
dpkg: error processing archive /var/cache/apt/archives/aspnetcore-store-2.0.0_2.0.0-1_amd64.deb (--unpack):
 trying to overwrite '/usr/share/dotnet/store/x64/netcoreapp2.0/system.interactive.async/3.1.1/lib/netstandard1.3/System.Interactive.Async.dll', which is also in package dotnet-dev-2.0.0-preview1-005977 2.0.0-preview1-005977-1
```
cc @mikeharder This is a known issue and has been brought up previously. It is documented here: https://github.com/dotnet/core/blame/master/release-notes/download-archives/2.0.0-download.md#L31-L35 though this remains highly undiscoverable. There is https://github.com/aspnet/MetaPackages/issues/232 filed to potentially make this error more clear.

**Comment by livarcocc** [comment] 2017-11-18 23:40
Closing this as this should be tracked by aspnet, who owns the asp.net runtime store package and it seems there is an issue for it already.

**Closed by livarcocc** 2017-11-18 23:40 UTC

**Comment by zipotm** [comment] 2018-04-02 19:43
This is the solution which is working:
sudo dpkg -i --force-overwrite <filename>
