### ISSUE TITLE
NU1505 appears in 17.3.0 Preview 1

### ISSUE THREAD

**Issue by kuuhakumirai** [dotnet/sdk#25387] opened 2022-05-12 15:17 UTC
### Describe the bug
NU1505: Duplicate 'PackageDownload' items warning is raised when the SDK uses PackageDownload to get packages.
The duplicate 'PackageDownload' items are: Microsoft.NETCore.App.Host.win-x64 [6.0.3], Microsoft.NETCore.App.Host.win-x64 [6.0.3], Microsoft.NETCore.App.Host.win-x64 [6.0.3], Microsoft.NETCore.App.Host.win-x64 [6.0.3].

I run into it in 17.3.0 Preview 1, and it doesnt appear in 17.2.0 with the same project.

### To Reproduce
1. Use Microsoft.NETCore.App Version 6.0.3
2. Update Visual Studio to 17.3.0 Preview 1
3. The warning "warning NU1505: Duplicate 'PackageDownload' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior" occurs as below screenshot.
4. It doesnt appear in 17.2.0 with the same project.
5. I notice that a closed issue described this symptom: https://github.com/dotnet/sdk/issues/24747

They are the same project:
![image](https://user-images.githubusercontent.com/34931606/168107802-fbe45c0e-7ab5-409f-b0f2-fe9e852f6195.png)
![image](https://user-images.githubusercontent.com/34931606/168109215-6ccc0048-3a44-4caa-87ca-392b4d37905e.png)
![image](https://user-images.githubusercontent.com/34931606/168107576-8a2e527f-944d-4e72-99f6-02c97031e32b.png)

Using .NET SDK 6.0.300 I think.

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by marbel82** [comment] 2022-05-13 11:35
I have similar warning:


Warning	NU1505	Duplicate 'PackageDownload' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageDownload' items are: Microsoft.NETCore.App.Host.win-x64 [6.0.0], Microsoft.NETCore.App.Host.win-x64 [6.0.0], Microsoft.NETCore.App.Host.win-x64 [6.0.0], Microsoft.NETCore.App.Host.win-x64 [6.0.0].

**Comment by baronfel** [comment] 2022-05-13 17:52
This is a duplicate of #24747, and I've commented more about why this is appearing and what folks can do to resolve it ahead of a proper fix [here](https://github.com/dotnet/sdk/issues/24747#issuecomment-1126298533).

**Closed by baronfel** 2022-05-13 17:52 UTC
