### ISSUE TITLE
The dotnet pack doesn't work together with -p:NuspecProperties when multiple properties provided

### ISSUE THREAD

**Issue by LegacyOfKain** [dotnet/sdk#29661] opened 2022-12-23 21:58 UTC
The dotnet pack doesn't work together with -p:NuspecProperties when multiple properties provided. dotnet sdk version is 6.0.404

**dotnet pack "Code\JavaWrappers\csharp_wrapper\abcd.csproj" -p:NuspecProperties="version=9.9.9,description=Foo" /p:NuspecFile="..\..\..\..\.nuspec"**

MSBuild version 17.3.2+561848881 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
.....
C:\Program Files\dotnet\sdk\6.0.404\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error : Description is required. .....

.nuspec file is as below

`<package >
  <metadata>
    ......
    <version>$version$</version>
    ....
......
    <description>$description$</description>`

**Comment by LegacyOfKain** [comment] 2022-12-23 22:00
.nuspec file as below :-

<package >
  <metadata>
   ...
    <version>$version$</version>
    ....
    <description>$description$</description>

**Comment by baronfel** [comment] 2022-12-23 22:01
@LegacyOfKain I think this is a duplicate of https://github.com/dotnet/sdk/issues/15482 - can you take a look and see what you think?

**Comment by LegacyOfKain** [comment] 2022-12-23 22:04
@baronfel yes , but at the end they asked to upgrade the cli and I did that. I use the lastes sdk 6.0.404. It still did not fix the problem.

**Comment by baronfel** [comment] 2022-12-23 22:06
Correct, but that issue is still open so I wouldn't expect the problem to be resolved. Since we already have an open issue describing your reported problem, I'm going to close this one as a duplicate.

**Closed by baronfel** 2022-12-23 22:06 UTC
Labels: untriaged, Area-CLI

**Comment by LegacyOfKain** [comment] 2022-12-23 22:07
Hi @baronfel , ok thanks , I will keep an eye on https://github.com/dotnet/sdk/issues/15482 then.
