### ISSUE TITLE
Visual Studio 2017 15.7.3 .NET Core Workload installs .NET Core SDK 2.1.201 (.NET Core 2.0) instead of 2.1.300 (.NET Core 2.1)

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#2323] opened 2018-06-12 06:18 UTC
_From @MBODM on June 12, 2018 6:14_

Hey,

the guys from the .NET Core team (https://github.com/dotnet/corefx/issues/30231) said i should maybe ask here:

As title says, you can download and install .net core sdk for 2.1 (named .net core sdk 2.1.300) manually from official MS .net core homepage. All fine and so. But normally Visual Studio do this via update and installer. So i installed Visual Studio 2017 15.7.3 this way (by updating or fresh install), the .net core workload of VS installs the .net core sdk 2.1.201 (latest .net core 2.0) instead of .net core sdk 2.1.300 (.net core 2.1). Why ?

Why does the VS workload target the old 2.0 sdk instead the new 2.1 sdk ? And when will this change ?

Problem is: Even when i install the new SDK manually (and i dont know if that cause problems when VS itself will install the same later, i.e. in 15.8, via Workload) then i have still the problem where i can get the templates for VS for ASP .NET Core 2.1 ? Otherwise i have to target 2.1 and make changes in .csproj by hand, everytime i do a new project. So, installing just the SDK solves not really the problem.

_Copied from original issue: dotnet/project-system#3643_

**Comment by davkean** [comment] 2018-06-12 06:19
@MBODM Sorry for the run around, this is the correct repo.

**Comment by MBODM** [comment] 2018-06-12 06:21
Allright. No problem. Thx for the fast moving to the correct location! Great handling speed! :)

**Comment by livarcocc** [comment] 2018-06-12 17:11
This is by design for now. It was decided that .NET Core 2.1 was going to ship out of band in VS 15.7 and would be put in VS for VS 15.8.

So, for VS 15.8, we will insert the .NET Core SDK 2.1.400 which carries .NET Core 2.1.

**Comment by livarcocc** [comment] 2018-06-12 17:11
@dsplaisted we can use this issue to track the Preview4 insertion into VS in the open.

**Comment by MBODM** [comment] 2018-06-13 02:27
ok, understand. so, no .net core 2.1 for VS users before 15.8. while i have no problem with that concept, i ask myself we even release .net core 2.1 in the first place then before 15.8 ? We have troubles with nuget updates, that already point to 2.1, and on the other hand can not use the sdk because of missing templates etc. So, here is my final question: Who is using .net core 2.1 at the moment, in this case ? And how do ppl use that SDK in the moment ?

Sorry, but i dont really get that stance on this descission by design.

**Comment by dsplaisted** [comment] 2018-06-13 02:38
@MBODM You can use .NET Core 2.1 with VS 15.7, you just need to install it separately.  You can download it from http://get.dot.net, and the download you currently want is the 2.1.300 .NET Core SDK.  (Though from the original issue description it sounds like you may know this).

VS does light up to use the new SDK if you install it.  In particular, you should get templates in VS that target .NET Core 2.1 once you install the correct SDK.  For ASP.NET projects, you might have to change the version number of ASP.NET Core to target in the dropdown in the new Web Application dialog:

![image](https://user-images.githubusercontent.com/145043/41327299-cbeecf14-6e77-11e8-9f3c-0739138e55c2.png)

Later versions of VS may install a later version of the .NET Core SDK.  By default the latest one on your machine will be used, so that shouldn't be an issue either.

It sounds like you may be having some issues even when the 2.1.300 SDK is installed.  If that's the case, please let us know in more detail what is happening.

Thanks!
Daniel

**Comment by MBODM** [comment] 2018-06-14 06:47
I tested this, and indeed you are right!

Since i am very surprised by this, can you explain WHO makes this possible:
- Does the SDK containing VS Templates and Tooling (i assume not) ?
- Or is VS 2017 15.7.3 already prepared for 2.1 (containing the templates, etc.) and just sho them up when it finds a 2.1 SDK, and only the installer just delivers 2.0 at the moment ?

I am very curious about that ?

**Comment by livarcocc** [comment] 2018-06-14 16:56
VS picks up some of its templates from the .NET Core SDK. VS has logic to locate the most appropriate SDK for it and it uses both the SDK templates and also SDK's MSBuild's props/targets to be able to handle .NET Core projects.

Also, the issue seems to be addressed, so I am going to close it. But, if you have more questions, feel free to ask them.

**Closed by livarcocc** 2018-06-14 16:56 UTC
