### ISSUE TITLE
GenAPI generates invalid '$' token in method name

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/sdk#31657] opened 2023-04-06 22:39 UTC
Running GenAPI on Microsoft.Build,16.10.0 (via SBRP) generates the following method

```
namespace Microsoft.Build.Graph
{
    public partial class GraphBuildOptions : System.IEquatable<GraphBuildOptions>
    {
...
        public virtual GraphBuildOptions <Clone>$() { throw null; }
...
```

This causes compiler errors:

  /repos/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/microsoft.build/16.10.0/lib/net5.0/Microsoft.Build.cs(2558,49): error CS1519: Invalid token '$' in class, record, struct, or interface member declaration [/repos/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/microsoft.build/16.10.0/Microsoft.Build.16.10.0.csproj::TargetFramework=net5.0] [/root/.nuget/packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23168.1/tools/Build.proj]
  /repos/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/microsoft.build/16.10.0/lib/net5.0/Microsoft.Build.cs(2558,49): error CS1056: Unexpected character '$' [/repos/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/microsoft.build/16.10.0/Microsoft.Build.16.10.0.csproj::TargetFramework=net5.0] [/root/.nuget/packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23168.1/tools/Build.proj]

**Comment by MichaelSimons** [comment] 2023-04-06 22:39
cc @ViktorHofer

**Comment by MichaelSimons** [comment] 2023-04-07 14:18
This reproduces in dotnet/source-build-reference-packages which is using the following version of GenAPI

    <Dependency Name="Microsoft.DotNet.GenAPI.Task" Version="8.0.100-preview.4.23203.10">
      <Uri>https://github.com/dotnet/sdk</Uri>
      <Sha>326fa05c36c21a75fec88a28faa555371c9af8c2</Sha>
    </Dependency>

This version of the SDK contains Rosyln 542fea0c2a93aacb3e8c52c2ce43e975d29832f3.  I am not seeing the fix when looking at the Roslyn source.  It looks like the PR was merged into main while the SDK is retrieving updates from release/dev17.6

**Comment by ViktorHofer** [comment] 2023-04-12 14:50
Michael is right. https://github.com/dotnet/roslyn/commit/e625bee16460737f48ba8999755dff91f582c474 which was merged three weeks ago is only part of the main branch right now. @jaredpar do you know when that specific commit will reach dotnet/sdk? I guess it's intentional that roslyn's main branch doesn't flow into dotnet/sdk?

**Comment by ericstj** [comment] 2023-04-17 19:48
@MichaelSimons is this still reproducing?  Any way we can force an update to ensure the issue is fixed?

**Comment by ViktorHofer** [comment] 2023-04-18 15:55
I can help with making sure that GenAPI receives that fix but I was hoping that roslyn's flow into sdk will normalize soon. Let me check again.

**Comment by ViktorHofer** [comment] 2023-04-18 16:02
dotnet/sdk retrieved new roslyn bits which includes the mentioned fix with https://github.com/dotnet/sdk/pull/31838/. The GenAPI bits from today which automatically flow into SBRP should already have the fix. Closing.

**Closed by ViktorHofer** 2023-04-18 16:02 UTC
Labels: untriaged, Area-GenAPI
