### ISSUE TITLE
Unable to install .NET 7 on Ubuntu 22.04.1 on WSL

### ISSUE THREAD

**Issue by VenkateshSrini** [dotnet/sdk#28995] opened 2022-11-10 04:58 UTC
### Describe the bug
I'm unable to install dotnet 7 on ubuntu. The instaruction page [here](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu) gives instruction for installing the .NET 6 only. Hence I downloaded the scripts from [here](https://dotnet.microsoft.com/en-us/download/dotnet/scripts) and again on execution it is installing only .NET 6. Can you please tell me how to install .NET 7 on Ubuntu 22.04.1 on WSL

### To Reproduce

Execute the above script

**Comment by akosijiji** [comment] 2022-11-10 20:37
I also experienced this issue.

**Comment by craigktreasure** [comment] 2022-11-10 21:27
Unfortunately, even the [.NET 7 announcement](https://devblogs.microsoft.com/dotnet/announcing-dotnet-7/) demonstrates how to install .NET 6 and not .NET 7. However, I was able to install the .NET 7 SDK using the [Microsoft Package Feed](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu#2204-microsoft-package-feed) instructions and then running `sudo apt-get install -y dotnet-sdk-7.0`.

**Comment by VenkateshSrini** [comment] 2022-11-11 03:35
@craigktreasure Thank you very much this works now. Can you please add these steps to document install documentation or put it as a blog somewhere? I'm sure many of us are still suffering from this problem. Also, one more point to note is that if the users are in Ubuntu 20.x they need to upgrade to the latest LTS

**Comment by nagilson** [comment] 2022-11-15 23:09
This seems (mostly) like a duplicate of https://github.com/dotnet/sdk/issues/28995, except for the fact that this is questioning how to install it at all, while the other issue more specifically points out you need to use the MSFT feed. 

I'm guessing that the changes to the documentation pages haven't been made because the dotnet 7 packs aren't in Jammy yet and once that happens it will be updated. @baronfel May comment on whether we care to update the documentation for the MSFT feed in the meantime.

**Closed by nagilson** 2022-11-15 23:09 UTC
Labels: untriaged, Area-Linux

**Comment by anirugu** [comment] 2022-11-22 04:56
Hi @craigktreasure I tried to install same in ubuntu 20.04.5 LTS in codespace, still doesn't work for me 
![image](https://user-images.githubusercontent.com/35772421/203224818-4c7a2e54-6408-415f-b2ae-cfc5229a3751.png)

BTW installation goes succesful.
After installation I see only 6.0 is mention in --list-sdks
@nagilson Is this means The default ubuntu (20.04) in codespace will not work with dotnet7. That is weird. Because the default version of codespace is ubuntu 20.04 This means that developer can't use .net 7 unless manually install the release-upgrade and spent 20-30 minutes in codespace
@Chuxel

**Comment by anirugu** [comment] 2022-11-22 05:03
The fix for me is don't use default one and build it with 22.04 by choosing Ubuntu. @Chuxel  Are you planning to bring dotnet 7.0 to default codespace image.

Because Ubuntu 22.04 will not have the good part of codespace that default codespace config have. It will waste of time to do manual work in devcontainer.json even it's support a lot of customization.

**Comment by anirugu** [comment] 2022-11-22 05:40
Thanks,  I got the point already. The problem for me is codespace's default config used ubuntu 20.04 LTS so developer is totally blocked due to that if he choose to stick with default settings.

As I mention in my last reply. Until codespace move to 22.04 developer can't use .net 7 and default settings together. Either they need  to chose ubuntu 22.04

The problem with non-default codespace (like 22.04 in this case) is they are not maintain by codespace team so it's burden to change thing manually.

**Comment by Chuxel** [comment] 2022-11-28 16:04
> The fix for me is don't use default one and build it with 22.04 by choosing Ubuntu. @Chuxel Are you planning to bring dotnet 7.0 to default codespace image.
> 
> Because Ubuntu 22.04 will not have the good part of codespace that default codespace config have. It will waste of time to do manual work in devcontainer.json even it's support a lot of customization.

This was tracked in the images repo https://github.com/devcontainers/images/issues/200
