### ISSUE TITLE
deps.json is not regenerated when .csproj changes

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#2093] opened 2018-03-28 05:04 UTC
**Repro**
1. Create project
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

</Project>
```
2. `dotnet build`
(Look at `test.deps.json`.. Should contain this)
```js
{
  //...
  "compilationOptions": {
    // ...
    "debugType": "embedded"
  },
```
3. Change project to ` <DebugType>portable</DebugType>` and run `dotnet build`

**Expected**
.deps.json changes to `"debugType": "portable"`

**Actual**
.deps.json file is not regenerated. File still contains `"debugType": "embedded"` until you manually clean and rebuild.

[msbuild.binlog.zip](https://github.com/dotnet/sdk/files/1854632/msbuild.binlog.zip)
 
**Details**
Using dotnet 2.1.300-preview1-008174

**Comment by livarcocc** [comment] 2018-03-28 05:06
We may have a bug for this already. I will try to find it tomorrow.

**Comment by nguerrera** [comment] 2018-03-29 16:38
Duplicate of #1942. @dsplaisted is going to fix this.

**Closed by nguerrera** 2018-03-29 16:38 UTC
