### ISSUE TITLE
Same issue for my web app in .net core 3.1 app

### ISSUE THREAD

**Issue by QishengRan** [dotnet/sdk#15107] opened 2020-12-29 10:55 UTC
Same issue for my web app in .net core 3.1 app

_Originally posted by @SrushtiPasari-GEP in https://github.com/dotnet/sdk/issues/3935#issuecomment-662375076_

**Comment by sfoslund** [comment] 2021-02-19 19:53
Closing this issue as the problem is being tracked in #3935

**Closed** 2021-02-19 19:54 UTC
Labels: untriaged
