### ISSUE TITLE
ParseContainerProperties of Microsoft.NET.Build.Containers deadlocks if ContainerImageName ends with '.'

### ISSUE THREAD

**Issue by Falco20019** [dotnet/sdk#33499] opened 2023-06-22 14:05 UTC
### Describe the bug
I had a sequentially generated name, that was somehow like the following. The property at the end was undefined and therefore lead to a name that ended with a dot.
`<ContainerImageName>my_test_image.$(UndefinedProp)</ContainerImageName>`

The build will deadlock on the `ParseContainerProperties` task in that case without further output.

### To Reproduce
1. Create new console application
2. Add PackageReference to Microsoft.NET.Build.Containers v7.0.304 (latest stable)
3. Add `<ContainerImageName>my_test_image.$(UndefinedProp)</ContainerImageName>` to PropertyGroup
4. Run `dotnet publish --os linux --arch x64 -c Release /t:PublishContainer /v:diag`

### Exceptions (if any)
No exceptions, only deadlocking. In my case, those were the last lines:
```
Die ParseContainerProperties-Aufgabe aus der C:\Users\dejhbk0l\.nuget\packages\microsoft.net.build.containers\7.0.304\build\..\tasks\net7.0\Microsoft.NET.Build.Containers.dll-Assembly wird verwendet.
ParseContainerProperties-Aufgabe (Aufgaben-ID: 102)
 Aufgabenparameter:ContainerImageTag=1.0.0 (Aufgaben-ID: 102)
 Aufgabenparameter:ContainerImageName=my_test_image. (Aufgaben-ID: 102)
 Aufgabenparameter:FullyQualifiedBaseImageName=mcr.microsoft.com/dotnet/runtime:6.0 (Aufgaben-ID: 102)
 Aufgabenparameter:
     ContainerEnvironmentVariables=
         GRPC_XDS_BOOTSTRAP
                 Value=/app/xds_bootstrap.json (Aufgaben-ID: 102)
```

### Further technical details
```
dotnet --info
.NET SDK:
 Version:   7.0.304
 Commit:    7e794e2806

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.304\

Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9

.NET SDKs installed:
  6.0.402 [C:\Program Files\dotnet\sdk]
  6.0.410 [C:\Program Files\dotnet\sdk]
  7.0.304 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by baronfel** [comment] 2023-06-22 14:10
Thanks for the report - I believe this is a duplicate of https://github.com/dotnet/sdk-container-builds/issues/387, so I will close this issue in favor of that one..

**Closed by baronfel** 2023-06-22 14:10 UTC
Labels: untriaged, Area-NuGet
