### ISSUE TITLE
zsh: command not found: dotnet on Mac m1

### ISSUE THREAD

**Issue by orrloshka** [dotnet/sdk#22910] opened 2021-11-21 20:41 UTC
I have macOS 12.0.1 
When I open a project on visual studios, the message says that I need to install .net core 3.1. But when I download it, nothing changes and I still cannot run the the command dotnet
I would appreciate, if someone helped me

Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by eiriktsarpalis** [comment] 2021-12-06 10:37
Getting many customer reports on this error:

https://github.com/dotnet/core/issues/6979
https://github.com/dotnet/core/issues/6972
https://github.com/dotnet/core/issues/6957
https://github.com/dotnet/core/issues/6924
https://github.com/dotnet/core/issues/6951
https://github.com/dotnet/core/issues/6933

Could we please prioritize this?

**Comment by dsplaisted** [comment] 2021-12-06 20:07
Hi folks,

This issue should describe how the .NET SDK works on M1 machines and what we recommend: https://github.com/dotnet/sdk/issues/22380

In general, you should only install the ARM64 versions of the SDK and not any of the x86 ones (uninstall them if you already did), and things will work a lot better.

**Comment by BeauNouvelle** [comment] 2021-12-10 00:24
@dsplaisted This answer has been posted a few times, but it won't solve the entire issue.

It seems as though the file path has changed, and so it's not getting linked correctly.
I deleted and re-installed the arm version the other day and had to manually symlink myself to get it working.

**Comment by tjpegram** [comment] 2022-01-13 03:42
> Hi folks,
> 
> This issue should describe how the .NET SDK works on M1 machines and what we recommend: #22380
> 
> In general, you should only install the ARM64 versions of the SDK and not any of the x86 ones (uninstall them if you already did), and things will work a lot better.

This is not a valid solution to this issue. There are several frameworks that only support .net core 3.1 rather than the SDK which does not solve the issue of the command not working, thus microsoft should find a fix for this.

**Comment by techcolin** [comment] 2022-01-24 16:31
For what it's worth, I only got this issue after upgrading to Monterey.  It was fine on my M1 on Big Sur.  Not sure what the upgrade did, but I verified the path had changed and created the symlink as above.

**Comment by greenEkatherine** [comment] 2022-02-09 18:15
Here is that issue again https://github.com/dotnet/core/issues/7170

**Comment by BeauNouvelle** [comment] 2022-02-09 21:51
Lol this is seriously still a thing?

**Comment by INGCRENGIFO** [comment] 2022-02-10 01:52
With the version v6.0.102 the same error.

I needed `sudo ln -s /usr/local/share/dotnet/dotnet /usr/local/bin` to fix it

**Comment by marcpopMSFT** [comment] 2022-02-11 00:04
CC @richlander

**Comment by wpMcDonnell** [comment] 2022-03-04 05:00
I use bash but still... I have a new m1 mac aka arm64 architecture

Arm64 .Net 6 for mac os installs to `usr/local/share/dotnet/`

x64 .Net 5 (I need this for a project that was started perviously) installs to `usr/local/share/x64`

if you download both, you are going to have a nightmare of a time uninstalling correct versions and getting paths for dotnet correct, like I did. If you download .Net 5 x64 after .Net 6 arm64, it will look something like this usr/local/share/dotnet/x64 with runtimes and sdks duplicated and scattered about between dotnet and x64

So what did I do? 

1.) I removed the `usr/local/share/dotnet` folder to completely start from the beginning - i saw this wasn't recommended but after struggling with the uninstall core tool and recommended commands for version deletions, I went for it. Always be careful when deleting folders from your system, this will probably break VS code for .NET and you will have to repair it

2.) then i download .Net5 x64 for mac os even tho I have an arm64 chip.

3.) I installed rosetta via CLI which lets intel apps run on arm64

4.) Dotnet command still doesnt work cause arm64 chip is expecting a different path, so I use command from above 
`sudo ln -s /usr/local/share/dotnet/x64/dotnet /usr/local/bin`

5.) I exit terminal, Ctrl+q my terminal

6.) restart terminal

7) run `dotnet --version` and you should have your desired .Net x64 version running on your new M1 macbook, in my case .Net 5

**Comment by NuclearFishin** [comment] 2022-03-10 02:10
Hi all, I've just encountered the `command not found: dotnet` issue setting up a new M1 Mac to develop my .NET 5 project. Specifically the steps I took were, from first power-on:

1. Update MacOS software updates
    - Monterey 12.2.1 (21D62)

2. Install .NET 5 SDK via the MacOS x64 installer
    - https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-5.0.406-macos-x64-installer

At this point I received the `zsh: command not found: dotnet` error. Hopefully this is a simple enough case for reproduction!

3. I then tried installing the .NET 6 SDK via the MacOS ARM64 installer
    - https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.201-macos-arm64-installer

Unfortunately I still received the error `zsh: command not found: dotnet`. I was really expecting this one to work.

Like several commenters above, adding a symbolic link to `/usr/local/bin/dotnet` **does** work, linking to `/usr/local/share/dotnet/x64/dotnet` for .NET 5, or `/usr/local/share/dotnet/dotnet` for .NET 6.

Is this the "official" solution for now? I.e., is the symlink the only part of the installation that failed?

(Happy to provide installation logs if they exist)

**Comment by BeauNouvelle** [comment] 2022-03-10 02:23
@NuclearFishin

Not official until they acknowledge the issue. 
The maintainers are still "maintaining" that the solution is to install the ARM64 version.

**Comment by AlbertoLeon** [comment] 2022-03-29 08:03
I installed the ARM64 version and I have the same issue.
As mentioned before, executing `sudo ln -s /usr/local/share/dotnet/dotnet /usr/local/bin` fixed it.

**Comment by victorcappa** [comment] 2022-04-08 01:20
MacOs 12.3.1, tried the above solutions but none seems to work

**Comment by ATANG09** [comment] 2022-04-15 07:50
> 

cool man

**Comment by ATANG09** [comment] 2022-04-15 07:51
> EDIT: ignore, see next comment.
> 
> After installation the symlink is missing, which is likely due to SIP (System Integrity Protection). I tried to do this manually by disabling SIP and running the following command.
> 
> ```
> ln -s /usr/local/share/dotnet/dotnet /usr/local/bin/
> ```
> 
> It creates the file just fine, however terminal still can't see it. Even adding it to the PATH for .zshrc doesn't work.
> 
> It looks like dotnet is installed correctly, but just can't be accessed...
> 
> This is about as far as I have got.

cool

**Comment by Filliny** [comment] 2022-11-21 11:27
> MacOs 12.3.1, tried the above solutions but none seems to work
cos even all here says that  dotnet sits in /usr/local/share/dotnet/dotnet   its installs in /usr/local/share/dotnet/dotnet /Users/<YourUserName>/.dotnet/dotnet

**Comment by DenisDolmatov2020** [comment] 2022-11-23 17:35
brew install dotnet

**Comment by init-center** [comment] 2022-12-30 09:51
This problem still exists, need to manually create a link after install

**Comment by Bhaney44** [comment] 2023-01-14 06:10
The pathing problem is very difficult to solve because the there is no way to know where the installation happens without doing a lot of digging.  

IN:
`dotnet`

OUT:
`zsh: command not found: dotnet`

I need to find a way to install `dotnet` locally, such that I can actually use the software. Any advice or suggestions would be appreciated. Thanks!

**Comment by Bhaney44** [comment] 2023-01-14 06:20
IN:

`ln -s /usr/local/share/dotnet/dotnet /usr/local/bin/`

OUT:

`ln: /usr/local/bin//dotnet: Permission denied`

I am not sure why Apple developed such a terrible chip in the M1. But, it is very difficult to navigate the terminal when the system denies the admin. Any advice would be appreciated. Thanks.

**Comment by EHampton252** [comment] 2023-01-19 15:42
I managed to install dotnet by using Homebrew:

`brew install dotnet`

**Comment by philnord** [comment] 2023-01-22 20:31
chiming in here, Mac M1 as well and had this problem too. Symlink fix above worked for me.

**Comment by PabloLION** [comment] 2023-03-07 10:49
for Mac M1, you need to `sudo ln -s /usr/local/share/dotnet/dotnet /usr/local/bin/` without `sudo` it wont work. @Bhaney44

**Comment by Fhwang0926** [comment] 2023-03-14 08:04
i using intel imac, my case erase all and reinstall dodtnet 6.0.x, refer it https://stackoverflow.com/questions/44089518/how-can-i-uninstall-dotnet-core-from-macos-sierra

**Comment by pms1969** [comment] 2023-03-14 11:13
M1 Mac and the install location for dotnet is `~/.dotnet/dotnet`.
globab tools just don't work, and linking `/usr/local/bin/dotnet` to the installed version does not work either. Anything I can do?

**Comment by SittenSpynne** [comment] 2023-04-09 02:47
I've tried pretty much everything in this and get:

> /usr/local/bin : no such file or directory.

**Comment by NathanielOctaviano** [comment] 2023-04-26 07:07
I am so stuck in this problem "dotnet not found" until I installed the **.NET SDK Arm64** in this link
https://dotnet.microsoft.com/en-us/download
Just click the arrow down button and it will show the **.NET SDK Arm64** option, download it and try the command **dotnet** in your terminal. Mine's working already

**Comment by ch3ck3r3d** [comment] 2023-05-07 21:44
> With the version v6.0.102 the same error.
> 
> I needed `sudo ln -s /usr/local/share/dotnet/dotnet /usr/local/bin` to fix it

M2 Pro and had the same issue for v7.0.203, this fixed the problem for me. Although v7 is in STS I am waiting for v8 to get out of preview.

**Comment by navid-kianfar** [comment] 2023-05-14 16:16
in Mac M1 you also **need to create the bin folder in "/usr/local" if it does not exists**

sudo mkdir /usr/local/bin

then you may run:

sudo ln -s /usr/local/share/dotnet/x64/dotnet /usr/local/bin/

**Comment by LanguageXange** [comment] 2023-07-22 12:10
I had the same issue on Mac M1 as well 
( I downloaded the .NET 7.0 SDK (v7.0.306) - macOS Arm64 )

and this command works for me 
`sudo ln -s /usr/local/share/dotnet/dotnet /usr/local/bin`

Kudos to all the people sharing the solution above

**Comment by GuySerg** [comment] 2023-08-31 11:42
Had the same issue on MacBook Pro M1.

Got dotnet bundled with Rider. Didn't have `/usr/local/share`, `/usr/local/bin` folders on my machine, symlink didn't work.
Managed the issue by updating my environment variables for the zsh shell. I added this line to the `.zprofile`:

`export PATH="$PATH:$HOME/.dotnet"`

You might need also to reload your profile to pick up changes. Also, be aware that on some systems these changes could be rewritten by other zsh shell-related configs.

**Comment by kedzior-io** [comment] 2023-09-02 09:15
> Had the same issue on MacBook Pro M1.
> 
> Got dotnet bundled with Rider. Didn't have `/usr/local/share`, `/usr/local/bin` folders on my machine, symlink didn't work. Managed the issue by updating my environment variables for the zsh shell. I added this line to the `.zprofile`:
> 
> `export PATH="$PATH:$HOME/.dotnet"`
> 
> You might need also to reload your profile to pick up changes. Also, be aware that on some systems these changes could be rewritten by other zsh shell-related configs.

@GuySerg that worked for M2 as well.

**Comment by Pamavoc** [comment] 2023-12-05 09:49
> [NuclearFishin](/NuclearFishin)

Thanks, worked for me with a M1 config, SDK 8 :

`sudo ln -s /usr/local/share/dotnet/x64/dotnet /usr/local/share/dotnet/dotnet`

**Comment by vmaryanne82** [comment] 2023-12-29 18:25
> I use bash but still... I have a new m1 mac aka arm64 architecture
> 
> * Aam64 `.Net 6` for mac os installs to `usr/local/share/dotnet/`
> * x64 `.Net 5` installs to `usr/local/share/dotnet/x64`
> 
> If you download both, you are going to have a nightmare of a time uninstalling correct versions and getting paths for dotnet correct, like I did. If you download `.NET 5` x64 after `.NET 6` arm64, it will look like this `usr/local/share/dotnet/x64` with runtimes and sdks duplicated and scattered about between dotnet and x64
> 
> So what did I do?
> 
> 1.) I removed the `usr/local/share/dotnet` folder to completely start from the beginning - i saw this wasn't recommended but after struggling with the uninstall core tool and recommended commands for version deletions, I went for it. Always be careful when deleting folders from your system, this will probably break VS code for `.NET` and you will have to repair it
> 
> 2.) then i download `.NET 5` x64 for mac os even tho I have an arm64 chip.
> 
> 3.) I installed rosetta via CLI which lets intel apps run on arm64
> 
> 4.) Dotnet command still doesnt work cause arm64 chip is expecting a different path, so I use command from above `sudo ln -s /usr/local/share/dotnet/x64/dotnet /usr/local/bin`
> 
> 5.) I `exit `terminal,` Ctrl+q` my terminal
> 
> 6.) re-open terminal
> 
> 7.) run `dotnet --version` and you should have your desired `.Net` x64 version running on your new M1 macbook, in my case `.NET 5`

This is the perfect reply

**Comment by BhargavaVidiyala** [comment] 2024-07-04 23:51
"sudo ln -s /usr/local/share/dotnet/dotnet /usr/local/bin " Enter this in terminal and then asks for password, then this issue gets solved . (My device is M1 Mac)
Kudos to all the people sharing the solution above

**Comment by linv2** [comment] 2024-07-20 09:38
> "sudo ln -s /usr/local/share/dotnet/dotnet /usr/local/bin " Enter this in terminal and then asks for password, then this issue gets solved . (My device is M1 Mac) Kudos to all the people sharing the solution above

After i exec 
```
sudo ln -s /home/ubuntu/.dotnet/dotnet /usr/local/bin/
```
the extension is working.

**Closed** 2024-07-22 11:49 UTC
Labels: Area-Install
