### ISSUE TITLE
Support for crossgen on build/publish

### ISSUE THREAD

**Issue by dasMulli** [dotnet/sdk#593] opened 2017-01-05 23:32 UTC
Feature Request:
Support crossgen-ing output assemblies for runtime-specific builds (=> e.g. self-contained apps).

This would be nice to have when publishing assemblies but may also be of (limited?) use for building.

Also, it would be great to be able to crossgen third party dlls pulled in via NuGet to further improve startup times.

**Comment by livarcocc** [comment] 2018-01-29 18:25
Closing this as a duplicate of the CLI one. It will be better to track this issue there and this repo will merge with the CLI repo in the medium time frame.

**Closed by livarcocc** 2018-01-29 18:25 UTC
Labels: Feature Request
