### ISSUE TITLE
SDK doesnt publish exes correctly when used as a project reference

### ISSUE THREAD

**Issue by jaredpar** [dotnet/sdk#1675] opened 2017-10-20 16:24 UTC
Often a group of exes need to be built and deployed together. This is common in applications like Roslyn where we ship several exes as a single unit: csc, vbc and VBCSCompiler. 

Rather than building each project separately and then copying the outputs together we create deployment projects. Essentially dummy exes projects that just reference all of the exes that we need via project reference elements

``` xml
<ProjectReference Include="..\..\src\Compilers\CSharp\csc\csc.csproj" />
<ProjectReference Include="..\..\src\Compilers\VisualBasic\vbc\vbc.csproj" />
<ProjectReference Include="..\..\src\Compilers\Server\VBCSCompiler\VBCSCompiler.csproj" />
``` 

This approach works fine in desktop MSBuild as it will correctly deploy all of the runtime assets. The same approach does not work on SDK projects though as the publish step fails to include critical files like deps.json and runtimeconfig.json. That completely breaks this approach.

If this isn't meant to be supported by SDK that would be unfortunate but understandable. I would expect an error though positively asserting that this case is not supported. Today everything builds and publishes without error but the output is completely unusable. 

Repo:

Clone https://github.com/jaredpar/roslyn and checkout the branch repro/group-exe. Then run the following commands:

``` cmd
> dotnet restore build/ToolsetPackages/BaseToolset.csproj
> dotnet restore build/ToolsetPackages/CoreToolset.csproj
> dotnet restore build/Toolset/CoreToolset.csproj
> dotnet publish -o ${HOME}/temp/test --framework netcoreapp2.0 build/Toolset/CoreToolset.csproj
```

The directory `${HOME}/temp/test` should contain the deps.json / runtimeconfig.json for csc, vbc and VBCSCompiler but it does not. That means the output of publish is unusable. 

CC @khyperia

**Comment by livarcocc** [comment] 2017-10-20 17:09
So, if I understand this correct, you have a project that references three other self-contained netcoreapp projects as project references and you expect that publish this aggregator project will also publish all its references as an app?

If that's the case, you are right, we do not support that. P2P references are treated as libraries and not applications. In order to accomplish this I think you could change your aggregator project to have a list of projects that it needs to publish and for you to invoke publish in each of them separately.

**Comment by jaredpar** [comment] 2017-10-20 18:13
> . In order to accomplish this I think you could change your aggregator project to have a list of projects that it needs to publish and for you to invoke publish in each of them separately.

That doesn't quite get the behavior we want though. Part of the advantage to using the `<ProjectReference>` route is that MSBuild hepls ensure we have consistent dependencies across the projects. If any dependencies are wrong the standard warnings around conflicts will come into play.

This is important because the versions need to be consistent in order to ensure the exes will run correctly when all their dependencies are dumped into a single directory. 

> If that's the case, you are right, we do not support that. P2P references are treated as libraries and not applications

In that case why do the app.config files get deployed at all? Thats only relevant when running the application. I would assume, possibly wrong, that app.config, runtimeconfig.json and deps.json would all be deployed or none.

**Comment by dsplaisted** [comment] 2017-10-20 18:55
I would also like some way to publish multiple apps to the same folder (and correctly handle the dependencies).

However, it's not as simple as copying the additional files when an app project is referenced.  The deps.json and runtimeconfig.json will have been generated within the context of the app's dependencies.  If the "publish" project ends up resolving different versions of those dependencies, then the versions deployed won't match what the app is expecting, which I think could lead to failures.

**Comment by jaredpar** [comment] 2017-10-20 19:04
> If the "publish" project ends up resolving different versions of those dependencies, then the versions deployed won't match what the app is expecting, which I think could lead to failures.

Exactly. We want these failures. It tells us that we screwed up our dependencies :smile:

**Comment by dsplaisted** [comment] 2017-11-21 19:30
Here's a potential workaround that includes the deps.json and runtimeconfig.json in the files that referenced projects will copy.

```xml
  <!-- Include MSBuild.deps.json and MSBuild.runtimeconfig.json in ContentWithTargetPath so they will be copied to the output folder of projects
       that reference this one. -->
  <Target Name="AddRuntimeDependenciesToContent" Condition=" '$(TargetFrameworkIdentifier)' == '.NETCoreApp'" BeforeTargets="GetCopyToOutputDirectoryItems">
    <ItemGroup>
      <ContentWithTargetPath Include="$(ProjectDepsFilePath)" CopyToOutputDirectory="PreserveNewest" TargetPath="$(ProjectDepsFileName)" />

      <ContentWithTargetPath Include="$(ProjectRuntimeConfigFilePath)" CopyToOutputDirectory="PreserveNewest" TargetPath="$(ProjectRuntimeConfigFileName)" />
    </ItemGroup>
  </Target>
```

**Comment by jaredpar** [comment] 2017-12-05 05:14
@dsplaisted 

How supported is that work around? This is a feature we sorely miss since switching to the new SDK / Exes (lots of duplication + missed errors). If this is fairly supported we'd consider switching to use it.

**Comment by dsplaisted** [comment] 2018-03-28 19:53
@jaredpar I wouldn't call it supported.  The problem is going to be if the different Exes have different versions of shared dependencies.  If that's not the case, then I *think* everything should work well.

**Comment by jaredpar** [comment] 2018-03-28 20:41
If it's not supported I'm rather hesitant to move to it. Depending on unsupported features is equally painful to both our teams when they eventually get broken

**Comment by ViktorHofer** [comment] 2020-04-22 07:15
@dsplaisted can we please adjust the milestone? We have a tracking issue against this in dotnet/runtime: https://github.com/dotnet/runtime/blob/ec9d33daf4f1922b2f36f548752ac4539f370c91/eng/testing/runtimeConfiguration.targets#L19

**Comment by MartyIX** [comment] 2020-07-08 09:03
This helped me https://github.com/dotnet/runtime/blob/ec9d33daf4f1922b2f36f548752ac4539f370c91/eng/testing/runtimeConfiguration.targets#L19 for my .NET Core 3.1 application:

```csharp
  <ItemGroup Condition="'$(GenerateRuntimeConfigurationFiles)' == 'true'">
    <None Include="$(TestRuntimeConfigurationFile)"
          Condition="Exists('$(TestRuntimeConfigurationFile)')"
          Link="$(TargetName).exe.config"
          CopyToOutputDirectory="PreserveNewest"
          Visible="false" />
    <!--
      Include deps.json and runtimeconfig.json in ContentWithTargetPath so they will
      be copied to the output folder of projects that reference this one.
      Tracking issue: https://github.com/dotnet/sdk/issues/1675
    -->
    <ContentWithTargetPath Include="$(ProjectDepsFilePath)"
                           Condition="'$(TargetsNetCoreApp)' == 'true' and '$(GenerateDependencyFile)' == 'true'"
                           CopyToOutputDirectory="PreserveNewest"
                           TargetPath="$(ProjectDepsFileName)" />
    <ContentWithTargetPath Include="$(ProjectRuntimeConfigFilePath)"
                           Condition="'$(TargetsNetCoreApp)' == 'true'"
                           CopyToOutputDirectory="PreserveNewest"
                           TargetPath="$(ProjectRuntimeConfigFileName)" />
  </ItemGroup>
```

**Comment by ViktorHofer** [comment] 2020-07-08 09:10
That's me implementing (mostly copying) what @dsplaisted suggested [above](https://github.com/dotnet/sdk/issues/1675#issuecomment-346135772) 😄

**Comment by MartyIX** [comment] 2020-07-08 09:15
@ViktorHofer I've just spent an hour trying to fix the original issue, so I posted your version because it's not obvious that one needs to use the latest master version in git to get to a working solution. 

Thank you for your work!

**Comment by ViktorHofer** [comment] 2020-07-08 09:22
Sure, np.

> because it's not obvious that one needs to use the latest master version in git to get to a working solution.

what do you mean by that?

**Comment by MartyIX** [comment] 2020-07-08 09:24
> @dsplaisted can we please adjust the milestone? We have a tracking issue against this in dotnet/runtime: https://github.com/dotnet/runtime/blob/ec9d33daf4f1922b2f36f548752ac4539f370c91/eng/testing/runtimeConfiguration.targets#L19

@ViktorHofer This refers to some commit from 2019. This one is newer: https://github.com/dotnet/runtime/blob/ec9d33daf4f1922b2f36f548752ac4539f370c91/eng/testing/runtimeConfiguration.targets#L19 and that code works for me.

**Comment by ViktorHofer** [comment] 2020-07-08 09:25
Got it, thanks for clarifying.

**Comment by kirsan31** [comment] 2020-07-15 08:57
`The same approach does not work on SDK projects though as the publish step fails to include critical files like deps.json and runtimeconfig.json.`

Just to note, that the problem appear not only on publish step, but on simple build too, see #11207.

**Comment by urosjovanovic** [comment] 2020-07-15 12:00
Yes, it is also not copied on build action.

I have tried the workaround proposed [above](https://github.com/dotnet/sdk/issues/1675#issuecomment-346135772) but had no luck. It throws a build error that it cannot copy *.deps.json and *.runtimeconfig.json because they do not exist.

I've added the target at the end of referenced .csproj (.net console app).

**Comment by ViktorHofer** [comment] 2020-07-15 12:58
@urosjovanovic do you have a repro that you can share? The workaround above should work.

**Comment by urosjovanovic** [comment] 2020-07-15 13:11
@ViktorHofer here is a minimal repro case, it's an asp.net core web app referencing net core console app. Thanks in advance.

[ReferencedConsoleApp.zip](https://github.com/dotnet/sdk/files/4925387/ReferencedConsoleApp.zip)

**Comment by ViktorHofer** [comment] 2020-07-15 13:50
OK the reason why the proposed workaround doesn't work in your repro is because you don't have any other content items in the lib that are copied over. Please try this one:

```
  <Target Name="AddRuntimeDependenciesToContent"
          Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp'"
          BeforeTargets="GetCopyToOutputDirectoryItems"
          DependsOnTargets="GenerateBuildDependencyFile;
                            GenerateBuildRuntimeConfigurationFiles">
    <ItemGroup>
      <ContentWithTargetPath Include="$(ProjectDepsFilePath)"
                            Condition="'$(GenerateDependencyFile)' == 'true'"
                            CopyToOutputDirectory="PreserveNewest"
                            TargetPath="$(ProjectDepsFileName)" />
      <ContentWithTargetPath Include="$(ProjectRuntimeConfigFilePath)"
                            Condition="'$(GenerateRuntimeConfigurationFiles)' == 'true'"
                            CopyToOutputDirectory="PreserveNewest"
                            TargetPath="$(ProjectRuntimeConfigFileName)" />
    </ItemGroup>
  </Target>
```

**Comment by urosjovanovic** [comment] 2020-07-15 15:26
@ViktorHofer Thank you, this works!

However, I also noticed that some dependencies are not copied for the referenced project as well.

For example, I have a reference to System.Security.Permissions package in the console app.
The System.Security.Permissions.dll is present in the output folder of the console app but is not copied over to the output of the project referencing the console app project which causes a runtime error when trying to run the console app.

Is the same workaround considered OK for this use-case, for example if I add the line:

`<ContentWithTargetPath Include="$(OutDir)System.Security.Permissions.dll" CopyToOutputDirectory="PreserveNewest" TargetPath="System.Security.Permissions.dll" />`

it works, but at which point this becomes too much of a hack?

What is also weird, is that for example Newtonsoft.Json package gets copied OK, both in console app outdir and the referencing project's outdir.

Don't know if these issues are related at all but I couldn't find any similar cases reported.

**Comment by ViktorHofer** [comment] 2020-07-15 16:15
I guess that would be a question for @dsplaisted and @ericstj. I would say if the hack works for you, use it but beware of the risk that it might break in the future.

**Comment by ericstj** [comment] 2020-07-15 17:29
> However, I also noticed that some dependencies are not copied for the referenced project as well.

Dependencies shouldn't be copied.  Dependencies should be allowed to flow transitively into the referenced project.  That's what @jaredpar was specifically calling out as something he wanted to accomplish with this strategy here https://github.com/dotnet/sdk/issues/1675#issuecomment-338283234.

In this case System.Security.Permissions wasn't copied because your referencing project is an ASPNetCore project and AspNetCore's shared framework *includes* System.Security.Permissions.dll.  You'd run into the same problem when referencing any package which is in the AspNetCore.App shared framework and not NetCore.App shared framework.

**Comment by ltrzesniewski** [comment] 2020-08-18 16:44
Note that the workaround doesn't handle a self-contained publish correctly: the dependency won't be published in self-contained mode.

To reproduce:

```
dotnet new console -n ConsoleAppA
dotnet new console -n ConsoleAppB
dotnet add ConsoleAppA reference ConsoleAppB
```

Paste the workaround to ConsoleAppB, then:

```
dotnet publish ConsoleAppA -r win-x64
```

Now diff the two `.deps.json` files in `ConsoleAppA\bin\Debug\netcoreapp3.1\win-x64\publish`:
 - The `runtimeTarget` of `ConsoleAppA` is `.NETCoreApp,Version=v3.1/win-x64` and it has all the runtime dependencies included
 - The `runtimeTarget` of `ConsoleAppB` is `.NETCoreApp,Version=v3.1` and the runtime dependencies are not listed

This can be fixed by setting the `RuntimeIdentifier` or `RuntimeIdentifiers` property in `ConsoleAppB`.

---

I'm currently using a... less subtle workaround though as I haven't seen this issue before, and I don't really want to set the `RuntimeIdentifier` property in the project. I'm posting it here in case it may help someone else:

In `ConsoleAppA`, add this:

```xml
<Target Name="AddExeDependencyForBuild" BeforeTargets="CopyFilesToOutputDirectory">
  <MSBuild Projects="..\ConsoleAppB\ConsoleAppB.csproj"
           Targets="Publish"
           Properties="PublishDir=$([System.IO.Path]::GetFullPath($(OutDir)));PublishReadyToRun=false"
           BuildInParallel="$(BuildInParallel)" />
</Target>

<Target Name="AddExeDependencyForPublish" BeforeTargets="CopyFilesToPublishDirectory">
  <MSBuild Projects="..\ConsoleAppB\ConsoleAppB.csproj"
           Targets="Publish"
           Properties="PublishDir=$([System.IO.Path]::GetFullPath($(PublishDir)))"
           BuildInParallel="$(BuildInParallel)" />
</Target>
```

The drawback of this approach is that the project gets built twice.

I suppose you can combine both workarounds this way:

 - Set `Condition="'$(RuntimeIdentifier)' == ''"` on the `AddRuntimeDependenciesToContent` target
 - Delete the `AddExeDependencyForBuild` target (only keep `AddExeDependencyForPublish`)

---

Here's yet another fix I tried, it's to be used with the original one. Add this to `ConsoleAppA`:

```xml
<Target Name="ForceRidAgnosticToFalse" AfterTargets="_GetProjectReferenceTargetFrameworkProperties">
  <ItemGroup>
    <_MSBuildProjectReferenceExistent Update="@(_MSBuildProjectReferenceExistent)"
                                      UndefineProperties="$([MSBuild]::ValueOrDefault('%(UndefineProperties)', '').Replace(';RuntimeIdentifier', ''))" />
  </ItemGroup>
</Target>
```

This is not great either, as it depends on and modifies "internal" data (targets and items whose names start with an underscore).

---

Anyway, nothing I posted here is particularly pleasant... I'd be grateful if the SDK was fixed to be able to handle exe references correctly. 😉

**Comment by AaronRobinsonMSFT** [comment] 2020-09-25 04:25
Fixing this would be helpful for testing the `DllImport` source generation with [DNNE](https://github.com/AaronRobinsonMSFT/DNNE).

See https://github.com/dotnet/runtimelab/pull/124.

**Comment by TonyValenti** [comment] 2020-10-08 14:29
We're running into challenges because of this too.  It would be really nice if this could get resolved.

**Comment by MartyIX** [comment] 2020-10-27 08:14
How can I use https://github.com/dotnet/sdk/issues/1675#issuecomment-658779827 in .NET 5? 

I believe that `'$(TargetFrameworkIdentifier)' == '.NETCoreApp'` needs to be modified but I'm not sure what the new identifier is.

**Comment by ltrzesniewski** [comment] 2020-10-27 08:52
@MartyIX `$(TargetFrameworkIdentifier)` is still `.NETCoreApp` in .NET 5.

**Comment by ChrisUnityArto** [comment] 2020-11-04 11:33
I would like to add my vote to the resolution of this issue and also add my vote to the opinion that it is a regression from dot net framework.

**Comment by ViktorHofer** [comment] 2021-02-23 19:49
Fixed by https://github.com/dotnet/sdk/pull/14488

**Closed by ViktorHofer** 2021-02-23 19:49 UTC

**Comment by kirsan31** [comment] 2021-02-23 20:21
@ViktorHofer In What VS version it will be included?

**Comment by dsplaisted** [comment] 2021-02-23 20:28
It should be in .NET SDK 5.0.200, which will ship with VS 16.9

**Comment by RandomEngy** [comment] 2021-03-03 04:20
VS 16.9.0 is out and it works! Thanks for the fix.

**Comment by jeremy-visionaid** [comment] 2024-07-14 23:12
Looks like this is still a problem for Managed C++ dependencies, but the workarounds suggested here for adding it to ContentWithTargetPath manually work for those too. I'll open a new issue if I get the chance.
