### ISSUE TITLE
With .NET 6.0 installed, publish .NET Framework 2.1 fails to error "HTTP Error 502.5 - Process Failure".

### ISSUE THREAD

**Issue by v-elenafeng** [dotnet/sdk#18642] opened 2021-06-18 09:29 UTC
**Testcases Affected**
Publish ASP.NET Core 2.1 (.NET Framework)

**Repro Steps**
1. With .NET 6.0 Preview 6 installed, open VS and sign in with account
2. File > New project > ASP.NET Core Empty > .NET Core 2.1 > Check "Run on .NET Framework"
3. Right-click on the project > Publish to App service (Windows)

It shows "HTTP Error 502.5 - Process Failure" on the published website.

**Actual Result**
![image](https://user-images.githubusercontent.com/78580199/122534458-1d75f780-d055-11eb-8f51-1496a0b890a0.png)

**Comment by BrennanConroy** [comment] 2021-06-30 17:23
This can be reproed locally, no need to publish to app service. I used sdk 6.0.100-preview.7.21324.2 to repro the issue, but OP was using a preview6 SDK. Looking at the difference between the published output with a 5,0 SDK vs 6.0 SDK, there is 164 items vs. 68 items, so there is definitely a big difference between the SDKs.

Output from running the .exe from the 6.0 SDK:
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

Adding the missing dll will then move on to complain about the next missing dll, and I assume it will keep doing so until the ~100 missing files are added.

**Comment by dougbu** [comment] 2021-07-01 23:37
From dotnet/aspnetcore$30419, it seems this issue started w/ the 6.0-preview1 SDK. Did that preview release make important changes in how apps are published @wli3 @dsplaisted @marcpopMSFT❔

> @BrennanConroy I assume this is not a blocker for preview6?

I'd say it's not a preview6 blocker given our release timeline (shrug). Let's treat this as important and urgent but not s ship-stopper for our preview releases. That said, we should fix this before the next 6.0 release because it's a regression since 5.0 of a scenario important enough for CTI to test.

**Comment by Pilchie** [comment] 2021-07-01 23:40
:eyes:

**Comment by shirhatti** [comment] 2021-07-02 20:17
I've root caused this issue to this change in the SDK- https://github.com/dotnet/sdk/pull/14020/files

Impacted customers can work around this by adding this to their project file

```xml
  <PropertyGroup>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>
```

**Comment by dougbu** [comment] 2021-07-02 21:14
@shirhatti are you saying #14020 has a bug causing removal of files _required_ in scenarios like this one❔

@sfoslund @AntonLapounov @dsplaisted is there a fix planned for this regression from 5.0.x❔ The workaround sounds simple enough but the connection to having too _few_ files in the published output seems unlikely for customers to grok i.e. the workaround doesn't seem discoverable.

**Comment by shirhatti** [comment] 2021-07-02 21:55
> @shirhatti are you saying #14020 has a bug causing removal of files required in scenarios like this one❔

Looks like it to me. I have a before/after binlog handy if someone wants to take a look.

FWIW, I noticed we've disabled this in the aspnetcore repo as well https://github.com/dotnet/aspnetcore/blob/main/eng/Workarounds.props#L37

**Comment by dougbu** [comment] 2021-07-02 22:05
> FWIW, I noticed we've disabled this in the aspnetcore repo as well https://github.com/dotnet/aspnetcore/blob/main/eng/Workarounds.props#L37

That's worth a lot @shirhatti❕ I forgot about that workaround and dislike the idea of requiring it of many customers upgrading from 5.0.x to 6.0.x.

**Comment by dsplaisted** [comment] 2021-07-04 03:25
It looks like this is the same thing as #18101

@marcpopMSFT Another hit on this regression

**Comment by dsplaisted** [comment] 2021-08-20 00:24
This should be fixed in .NET SDK RC1 with #19731

**Closed** 2021-08-20 00:41 UTC
Labels: untriaged

**Comment by v-elenafeng** [comment] 2021-08-23 09:36
Not repro with 17.0.0 Preview 4.0 [31622.41.main] + 6.0.100-rc.1.21422.7.
