### ISSUE TITLE
Mistyped command gives stack dump

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/sdk#15142] opened 2020-12-31 23:47 UTC
```
C:\repro>dotnet -d tool install
Telemetry is: Enabled
Microsoft.DotNet.Cli.CommandLine.CommandParsingException: Specify one tool Package Id to install.
   at Microsoft.DotNet.Cli.ParseResultExtensions.ShowHelpOrErrorIfAppropriate(ParseResult parseResult)
   at Microsoft.DotNet.Cli.CommandBase.ShowHelpOrErrorIfAppropriate(ParseResult parseResult)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallCommand..ctor(AppliedOption appliedCommand, ParseResult parseResult, ToolInstallGlobalOrToolPathCommand toolInstallGlobalOrToolPathCommand, ToolInstallLocalCommand toolInstallLocalCommand)
   at Microsoft.DotNet.Tools.Tool.ToolCommand.<get_SubCommands>b__9_0(AppliedOption appliedOption)
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
   at Microsoft.DotNet.Tools.Tool.ToolCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Usage: dotnet tool install [options] <PACKAGE_ID>
```
```
:\Users\danmose>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.200-preview.20614.14
 Commit:    863605c8c3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200-preview.20614.14\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  2.1.811 [C:\Program Files\dotnet\sdk]
  3.1.404 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.20614.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

**Comment by wli3** [comment] 2021-02-02 01:21
@sfoslund I see "-d" means "verbose" for the reporter. Is that intentional to add stack trace when "-d" is added?

**Comment by sfoslund** [comment] 2021-02-02 18:29
Yes, this is intentional. Without `-d` we don't see the stack trace, this behavior is consistent across 5.0 and 6.0.

**Comment by danmosemsft** [comment] 2021-02-02 20:37
Ah, I didn't realize that. The flag meaning changes, depending on position. Got it, seems useful flag.

**Comment by sfoslund** [comment] 2021-02-02 20:44
Closing this as not a bug

**Closed by sfoslund** 2021-02-02 20:44 UTC
