### ISSUE TITLE
dotnet build with ResXFileRef doesn't work

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#1568] opened 2017-09-07 16:15 UTC
See https://github.com/Microsoft/vsts-tasks/issues/5205

Build [TaskRepro.zip](https://github.com/dotnet/sdk/files/1285348/TaskRepro.zip) using `dotnet build` and using `msbuild.exe`.  You will notice the resources embedded in the output assembly are different:

Using `dotnet build`:
![image](https://user-images.githubusercontent.com/8291187/30173507-8221348e-93bd-11e7-8e6e-3b9817856fd7.png)
You'll see it is just a string value.

Using `msbuild.exe`:
![image](https://user-images.githubusercontent.com/8291187/30173532-9b389d4a-93bd-11e7-8120-0685af3ab1ba.png)
You'll see it is actually a byte[].

This causes the resources.Designer.cs file's code gen to error at runtime:

```
2017-09-01T20:07:41.9560273Z Initialization method Ommited.TestInitialize threw exception. System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Byte[]'..
2017-09-01T20:07:41.9600087Z Stack Trace:
2017-09-01T20:07:41.9649846Z at Ommited.ExtensionsResources.get_TestFile() in d:\a\1\s\src\Tests\Ommited\Resources\ExtensionsResources.Designer.cs:line 564
```

```C#
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TestFile {
            get {
                object obj = ResourceManager.GetObject("TestFile", resourceCulture);
                return ((byte[])(obj));
            }
        }
```

**Comment by dasMulli** [comment] 2017-09-07 16:43
Related to / dupe of ?:
https://github.com/Microsoft/msbuild/issues/2272
https://github.com/Microsoft/msbuild/issues/2221

**Comment by eerhardt** [comment] 2017-09-07 16:46
It may be a dupe of https://github.com/Microsoft/msbuild/issues/2221.  Not sure since the `dotnet/sdk` has its own code path to generate resources when running on .NET Core:

https://github.com/dotnet/sdk/blob/e83933917a2f3e3d10c6d18180ba6fab514117c8/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.targets#L405-L447

**Comment by dasMulli** [comment] 2017-09-07 17:07
As far as I can tell, the `@(_SatelliteAssemblyResourceInputs)` here are already generated by the `GenerateResource` task which only does [naive xml reading on .net core](https://github.com/Microsoft/msbuild/blob/8a08831d9975cadcee4820247b6605eb2eac3124/src/Tasks/GenerateResource.cs#L2908-L2914).

The interesting thing here is where the logic that generates the `.designer.cs` file in VS lives

**Comment by dasMulli** [comment] 2017-09-07 17:17
Okay that one is in msbuild as well.. can be called form `GenerateRsource` as well (https://github.com/Microsoft/msbuild/blob/8a08831d9975cadcee4820247b6605eb2eac3124/src/Tasks/GenerateResource.cs#L3199-L3264) and the implementation is here: https://github.com/Microsoft/msbuild/blob/8a08831d9975cadcee4820247b6605eb2eac3124/src/Tasks/StronglyTypedResourceBuilder.cs

**Comment by dasMulli** [comment] 2017-09-07 17:24
However this is kind of.. 💩 
So VS calls the netfx msbuild and it will happily embed a binary file. Then the file generator hooked up in VS uses netfx msbuild logic to generate the strongly typed code file (for which there isn't a .net core implementation) and that works. When built on .NET Core, msbuild will only emit string resources and the previously generated code file crashes on decoding.
Best thing is probably to emit a warning / error in msbuild when the resx entry has the `type="…"` attribute defined to indicate that this project should be built using the netfx msbuild or implement the embedding logic (by implementing the winforms embedding type via convention).

**Comment by nguerrera** [comment] 2017-09-12 20:19
This is a duplicate of https://github.com/Microsoft/msbuild/issues/2221

We generate satellite assemblies with our own code, but not the .resources files inside them. That is still handled by msbuild, and there is a bug in their handling on .NET Core.

**Closed by nguerrera** 2017-09-12 20:19 UTC
