### ISSUE TITLE
Publishing self-contained solution yields wrong system binaries in some environments

### ISSUE THREAD

**Issue by genriquez** [dotnet/sdk#20450] opened 2021-09-01 11:44 UTC
### Summary:
We are facing an issue where our projects are published with wrong System.* binaries from our builders, causing the program to crash due to wrong file versions. Problem seems to stem from netstandard1.6 dependencies (that cannot be changed since they come from nuget packages in our actual solution).

### Repro test project:
[ContainedPublishFail.zip](https://github.com/dotnet/sdk/files/7090652/ContainedPublishFail.zip)
Attached projects is most basic scenario found. Both app and netstandard1.6 lib use System.Text.RegularExpressions. 
* All our dev machines yield proper binaries and can run the app (System.Text.RegularExpressions.dll 5.0.421.11614 - 497KB). 
* Our builders and non-dev machines (which might or might not have VS 2017/2019 installed, but without license so they are not in use), yield wrong binaries (System.Text.RegularExpressions.dll 4.6.24705.1 - 112KB).

Updating the library to netstandard2.0 seemed to fix the issue in our tests machines. In our actual solution all netstandard libraries are 2.0, but some nuget dependencies seem to be netstandard1.6, so it is not possible to fix it this way.

### Repro steps:
1. Unzip test solution into new folder and open a terminal at the folder
2. Run `dotnet restore ContainedPublishFail.sln --runtime win-x64`
3. Run `dotnet publish ContainedPublishFail.sln --output output --runtime win-x64 --self-contained true --no-restore`
4. Run `output\ContainedPublishFail.exe some123string`

#### Expected output (same output in dev machines):
```
Number: 123
```
#### Actual output (in failing builders and non-dev machines):
```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Text.RegularExpressions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Text.RegularExpressions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at ContainedPublishFail.Program.Main(String[] args)
```

### Additional information:
We ran the restore and publish steps with _detailed_ verbosity level (tried _diagnostic_ but there is just too much data that needs to be redacted). [logs.zip](https://github.com/dotnet/sdk/files/7090729/logs.zip)

They contain logs for both restore and publish steps. The main reason to have a restore step separately is that we use a local nuget repository, using the `--source` param for restore.

@vijayrkn Although this is not a web project, we do reproduce the same issue with web project publishing. Apologies if you are not the right person to ping.

**Comment by genriquez** [comment] 2021-09-21 15:02
@vijayrkn Any idea about this? or have anyone else I could ping for some help?

**Comment by vijayrkn** [comment] 2021-09-21 15:18
@genriquez - Thank you for the sharing the sample solution and detailed steps. Sorry for the late response on this since I missed the initial ping. 

I just tried the solution that you shared and with the same exact steps, I can get the application to run successfully. 

`
C:\Users\vramak\Downloads\ContainedPublishFail>dotnet publish ContainedPublishFail.sln --output output --runtime win-x64 --self-contained true --no-restore
Microsoft (R) Build Engine version 17.0.0-preview-21458-01+2c5510013 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  netstdlib -> C:\Users\vramak\Downloads\ContainedPublishFail\lib\bin\Debug\netstandard1.6\netstdlib.dll
  netstdlib -> C:\Users\vramak\Downloads\ContainedPublishFail\lib\bin\Debug\netstandard1.6\win-x64\netstdlib.dll
  netstdlib -> C:\Users\vramak\Downloads\ContainedPublishFail\output\
  ContainedPublishFail -> C:\Users\vramak\Downloads\ContainedPublishFail\app\bin\Debug\net5.0\win-x64\ContainedPublishFail.dll
  ContainedPublishFail -> C:\Users\vramak\Downloads\ContainedPublishFail\output\

C:\Users\vramak\Downloads\ContainedPublishFail>output\ContainedPublishFail.exe some123string
Number: 123
`

I am using the latest 6.0 rc1 sdk. Can you also share the `dotnet info` details? Does the issue reproduce with the latest rc1 SDK?

**Comment by genriquez** [comment] 2021-09-21 15:41
@vijayrkn - Please find attached dotnet info output of my local environment (which yields correct assemblies). I'll try and get the same info from our builder machines tomorrow. [dotnetinfo.works.txt](https://github.com/dotnet/sdk/files/7204392/dotnetinfo.works.txt)

About using rc1, we are currently tied to sdk 5.0.201 by internal policy, so even if it works I am not sure we can implement it yet. I'll see if I can test this on a non-critical machine (so no builders). One curious difference I forgot to mention is that the publish logs on failing machines seem to make use of assemblies under `C:\Program Files\dotnet\packs\`, while working machines don't.

**Comment by dsplaisted** [comment] 2021-09-21 19:38
I'm not sure what would have changed, but there have been various fixes that have gone into 6.0, so one of them may have changed something here.

Instead of looking at verbose logs, it's way better to look at [binlogs](https://msbuildlog.com/).  There isn't currently a way to redact information from them, but they are also [way more useful](https://aka.ms/binlog) than text logs for us to investigate an issue if you can provide them.  You can also create a text log at whatever verbosity you want from a binlog.

You provided a repro here so we probably don't need a binlog, what I think we need now is confirmation of what version of the SDK you are using when this fails.

**Comment by genriquez** [comment] 2021-09-22 11:19
Here is the dotnet info from the machine where it fails. [dotnetinfo.fails.txt](https://github.com/dotnet/sdk/files/7210145/dotnetinfo.fails.txt)

Do you absolutely need testing this with rc1? I would rather not touch much the environments where we can reproduce the issue since I don't have direct control over them.

**Comment by marcpopMSFT** [comment] 2023-11-14 21:41
Old bug triage: Closing for now as a lot has changed in this code. Please ping us if it's still an issue. Sorry for the delay.

**Closed by marcpopMSFT** 2023-11-14 21:41 UTC
Labels: untriaged, Area-NetSDK
