### ISSUE TITLE
Sources under a folder named "Packages"  are ignored on build

### ISSUE THREAD

**Issue by ridomin** [dotnet/sdk#1708] opened 2017-11-01 15:06 UTC
.NET Command Line Tools (15.5.0-preview-007044)

All source files and folders are included in the build, however, a folder named "Packages" is excluded. I've verified this behavior in CLI and VS 15.5 Preview.

Looks like a regression from previous versions (checked in 15.4).

Repro Steps.
```
dotnet new classlib
mkdir Packages
echo 'bad c# file' > Packages/Class1.cs
dotnet build
```

Expected. Build failed because Class1.cs is not a valid C# file
Observed. Build succeed because Packages/Class1 is excluded from the build

**Comment by livarcocc** [comment] 2017-11-01 18:56
Your Packages folder below is upper case.
 
We remove (always have) packages (lower case) from sources since 1.0.0. We did this to maintain compatibility with project.json when we moved from it to csproj and msbuild.
 
The fact that this used to work for you and now fails is likely a path normalization fix that happened in MSBuild. Adding @Andy Gerlicher here so that he can comment on path normalization fixes that might have gone into MSBuild to cause this to happen.
 
Once we get confirmation that this was a path normalization change in MSBuild, I will go ahead and close this issue.

cc @cdmihai @AndyGerlicher

**Comment by onovotny** [comment] 2017-11-01 18:58
This is bad and projects have valid folders called `Packages` in them with code.

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/tree/master/Core/Packages

Please do not put this on the default items list if it's *inside* the project folder. If it's outside the project folder, which I believe was the intent, that's ok as that was to target the packages.config folder.

**Comment by dsplaisted** [comment] 2017-11-01 19:40
Yeah, I'm the one who wrote that TODO.  The problem is now that we've shipped, that removing that glob could also break projects.

However, I've confirmed that this is a break even on case-insensitive file systems.  In the 2.0 SDK, code from a `Packages` folder would be included.  With 15.5 Preview, code from a `Packages` folder won't be included.

So assuming that we keep the current behavior of MSBuild in the 15.5 preview (which I believe was a bug fix), then we would need to weigh the risk of breaking projects by newly excluding code from `Packages` against the risk of breaking projects by newly including code from `packages`.  I'd vote for getting rid of the glob exclusion for `packages`.

**Closed** 2017-11-07 14:29 UTC
