### ISSUE TITLE
When publishing the nuget dll is not updated if the nuget version is downgraded

### ISSUE THREAD

**Issue by IlyaGrigorievWeb** [dotnet/sdk#24595] opened 2022-03-28 21:26 UTC
**Steps to reproduce:**
1. Create simple console project
2. Add some nuget package, for example Newtonsoft.Json version 13.0.1
3. Execute the "dotnet publish" command from the terminal
4. Downgrade the package version for example to 12.0.3
5. Execute the "dotnet publish" command again

**Expected result:** The version of the nuget package dll is 12.0.3
**Observed result:** The version of the nuget package dll is 13.0.1

This is similar to https://github.com/dotnet/sdk/issues/10754#issuecomment-897294843

**Comment by KalleOlaviNiemitalo** [comment] 2022-03-28 23:08
May be a duplicate of <https://github.com/dotnet/sdk/issues/10754>.

**Closed** 2022-04-21 23:01 UTC
Labels: untriaged, Area-NuGet
