### ISSUE TITLE
_HandlePackageFileConflicts reports conflicts for satellite assemblies

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#1529] opened 2017-08-23 03:54 UTC
```
git clone https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VSIDEConEx.IdentityService
cd VSIDEConEx.IdentityService
git co 67aa3553c0741f8f44195a6b71ab87b5fadf953f
.\init
cd src\IdentityService
msbuild /v:normal
```

**Expected**
Few or no build warnings

**Actual**
Hundreds of warnings about copy local conflicts from the `_HandlePackageFileConflicts` target, such as:

> Encountered conflict between 'CopyLocal:C:\Users\andarno\.nuget\packages\microsoft.visualstudio.threading\15.3.20\lib\net45\cs\Microsoft.VisualStudio.Threading.resources.dll' and 'CopyLocal:C:\Users\andarno\.nuget\packages\microsoft.visualstudio.threading\15.3.20\lib\net45\ru\Microsoft.VisualStudio.Threading.resources.dll'.  Could not determine winner due to equal file and assembly versions.

Note the warnings are regarding two *satellite* assemblies with different cultures. There should be no conflict here, since they should be copied locally to their own culture-specific subfolders.

**Comment by nguerrera** [comment] 2017-08-31 03:37
Duplicate of #1465. These are high importance messages, not warnings right?

**Closed by nguerrera** 2017-08-31 03:37 UTC

**Comment by AArnott** [comment] 2017-08-31 04:38
Yes, I suppose so. Thanks.
