### ISSUE TITLE
Support wildcard versions in baseline package validation

### ISSUE THREAD

**Issue by iedeny** [dotnet/sdk#23772] opened 2022-02-05 07:03 UTC
### Is your feature request related to a problem? Please describe.
 [Basline package validator](https://docs.microsoft.com/en-us/dotnet/fundamentals/package-validation/baseline-version-validator) requires to specify exact version as baseline like below:
`<PackageValidationBaselineVersion>1.0.0</PackageValidationBaselineVersion>` 

### Describe the solution you'd like
Support wildcards is baseline version. Example:
`<PackageValidationBaselineVersion>1.0.*</PackageValidationBaselineVersion>`

### Additional context
This is useful when hotfixes for version 1.0 are released frequently and updating baseline every time creates an overhead for engineering systems. I understand the downside of non-deterministic builds but in our case it is an acceptable compromise.

**Comment by RehanSaeed** [comment] 2022-02-28 10:09
Could tha package validator also get the latest version from NuGet to validate against when the following is set? I believe this would be what 90% of develoers want:

`<PackageValidationBaselineVersion>latest</PackageValidationBaselineVersion>`

**Comment by 0xced** [comment] 2022-04-07 20:04
> `<PackageValidationBaselineVersion>latest</PackageValidationBaselineVersion>`

What would this mean? Latest _stable_ or latest _prerelease_ version? Maybe both should be supported? Maybe what we actually want is latest stable _major_ version?

In case there are version `2.0.0` `2.1.2` and `3.0.0-alpha1` published on NuGet, which one should be picked to be compared against?

Those are honest questions, I haven't actually put too much thought into it but indeed having to update `PackageValidationBaselineVersion` after publishing a NuGet package is cumbersome. This could be improved by supporting some kind of wildcard and/or `latest` special versions.

**Comment by ViktorHofer** [comment] 2022-06-03 09:43
Closing https://github.com/dotnet/sdk/issues/25268 as a duplicate of https://github.com/dotnet/sdk/issues/25268 which has more information and possible implementations.

**Closed by ViktorHofer** 2022-06-03 09:43 UTC
Labels: Area-Compatibility
