### ISSUE TITLE
With .Net 6 Preview7, failed to retarget .net 6.0 project to other TFM(net 5.0 or net48)

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#19144] opened 2021-07-22 07:31 UTC
Environmnet:
Install net6 preview 7 SDK(6.0.100-preview.7.21369.19) + 17.0 preview 3
Repro steps:
1. dotnet new console -o myconsole In CLI, and the default tfm is net6.0
2. Modify the project's framework to net5.0 or net48 in  *csproj file.
3. dotnet build

Expected 
Step3: build succeed

Actual
If retarget to net5.0: build with below error in CLI
![image](https://user-images.githubusercontent.com/65637796/126601152-657dc15c-43d1-4552-a7bc-a0722e6980ef.png)

If retarget to net48 build with below error in CLI
![image](https://user-images.githubusercontent.com/65637796/126603005-b3b08904-ac2e-400a-8e34-83f2c608a869.png)

Note: 
1. In VS, If retarget to net5.0: build with below error
![image](https://user-images.githubusercontent.com/65637796/126606098-ef3c3ba3-775e-4eb3-b743-f5e5a2fa08ef.png)

This issue may because .net 6 template changes starting with the .NET 6 Preview 7 SDK, and not repro with old template

2. In VS, If retarget to net48 build with below error
![image](https://user-images.githubusercontent.com/65637796/126603215-66b665b7-da03-4f18-96db-f17388ba1a57.png)
We changed it to old template and add code `<LangVersion>8.0</LangVersion>` or delete the code     `<Nullable>enable</Nullable>`, build succeed

**Comment by JoeRobich** [comment] 2021-07-22 16:36
The dotnet templates are now using newer C# language features that are not officially supported on .NET Framework. I feel like the templates are correct here for two reasons. 1) seasoned .NET developers would expect the template to use these new features 2) we would want new .NET developers to learn this style of .NET development

**Comment by KathleenDollard** [comment] 2021-07-22 23:01
If you select the framework you want from the Visual Studio New Project Dialog, or via the --framework switch on `dotnet new` you should get a working template. If you do not, that would be an issue.

If you target .NET 6 and then downgrade, that will not work because we are using features that are supported only in .NET 6.

Is there a scenario where creating an app and then downgrading the framework is important. I expect it to be a trend that we will pair template features with the corresponding framework features.

**Comment by KathleenDollard** [comment] 2021-07-23 18:12
Closing this as by design.

**Closed by KathleenDollard** 2021-07-23 18:12 UTC
Labels: untriaged
