### ISSUE TITLE
Nuget error NU3028 and NU3037 From 27/01/2021

### ISSUE THREAD

**Issue by aneeff** [dotnet/sdk#15511] opened 2021-01-27 14:55 UTC
Hi,

We are facing a series of NU3028 and NU3037 when doing docker build..

... docker build: from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain ... docker build: : error NU3037: Package 'Microsoft.Extensions.Configuration.Abstractions 2.1.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired. ... docker build: : error NU3028: Package 'Microsoft.Extensions.Configuration.Abstractions 2.1.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain

**Comment by dasMulli** [comment] 2021-01-27 15:11
Duplicate of https://github.com/NuGet/Home/issues/10491

**Comment by marcpopMSFT** [comment] 2021-01-27 21:27
Please track in the NuGet issue.

**Closed by marcpopMSFT** 2021-01-27 21:27 UTC
Labels: Area-NuGet
