### ISSUE TITLE
cannot build and run project from macos template on .NET 6 (NETSDK1102)

### ISSUE THREAD

**Issue by dlech** [dotnet/sdk#18395] opened 2021-06-19 17:10 UTC
Here is what I did:
1. Install .NET 6 preview 5
2. `sudo dotnet workload install microsoft-macos-sdk-full`
3. `dotnet new macos -o TestMacOS`
4. `cd TestMacOS`
5. `dotnet run` or `dotnet build`

Building fails with:

```
Build FAILED.

/usr/local/share/dotnet/sdk/6.0.100-preview.5.21302.13/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(181,5): error NETSDK1102: Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app. [/Users/david/work/junk/TestMacOS/TestMacOS.csproj]
    0 Warning(s)
    1 Error(s)
```

**Comment by dlech** [comment] 2021-06-19 17:57
Related: https://github.com/xamarin/xamarin-macios/issues/11094#issuecomment-822601406

**Comment by eerhardt** [comment] 2021-06-30 16:25
@sbomer @agocke @LakshanF - is this a linker issue or an issue with the macos-sdk? Note @AaronRobinsonMSFT also opened https://github.com/xamarin/xamarin-macios/issues/12046.

If this is a macos-sdk issue, maybe this issue can be closed as a duplicate of https://github.com/xamarin/xamarin-macios/issues/12046.

**Comment by agocke** [comment] 2021-06-30 18:18
Looked through and I think this is a dup of https://github.com/xamarin/xamarin-macios/issues/12046

**Closed by agocke** 2021-06-30 18:18 UTC
Labels: Area-ILLink, untriaged
