### ISSUE TITLE
Improve error message for singular TF element

### ISSUE THREAD

**Issue by GuardRex** [dotnet/sdk#697] opened 2017-01-20 06:10 UTC
cross-reference: https://github.com/dotnet/cli/issues/4996

Providing a TF element like this ...
```xml
<TargetFramework>net451;netcoreapp1.1</TargetFramework>
```
... generates an exception message like this ...
```
C:\Program Files\dotnet\sdk\1.0.0-rc4-004530\Microsoft.Common.CurrentVersion.targets(123,17): 
error MSB4115: The "HasTrailingSlash" function only accepts a scalar value, but its argument 
"$(OutputPath)" evaluates to "bin\Debug\net451;netcoreapp1.1\" which is not a scalar value. 
[PATH\KeyVaultConfigProviderSample\KeyVaultConfigProviderSample.csproj]
```
Although the phrase "only accepts a scalar value" makes perfect sense now, it wasn't easy to grok the problem from the exception when I first laid eyes on it.

Can the exception plainly say that `<TargetFramework>` should be `<TargetFrameworks>` when there are more than one?

**Comment by srivatsn** [comment] 2017-01-20 06:14
Dupe of https://github.com/dotnet/sdk/issues/385

**Closed by srivatsn** 2017-01-20 06:14 UTC
