### ISSUE TITLE
[CreateAppHost] fails on building with the .NET 6 preview1 SDK (21108.2) 

### ISSUE THREAD

**Issue by AraHaan** [dotnet/sdk#15823] opened 2021-02-11 23:10 UTC
outputs from ``dotnet build`` on my winforms project (targets net472 and .NET 5.0 and uses the .NET 5 SDK to fix an issue with nuget resolve what will be in the 16.10 VS Preview I think). This same output also happens when building with Visual Studio as well.
```
1>C:\Program Files\dotnet\sdk\6.0.100-preview.1.21108.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018: The "CreateAppHost" task failed unexpectedly.
1>C:\Program Files\dotnet\sdk\6.0.100-preview.1.21108.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
1>C:\Program Files\dotnet\sdk\6.0.100-preview.1.21108.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018: File name: 'System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
1>C:\Program Files\dotnet\sdk\6.0.100-preview.1.21108.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018: The Zone of the assembly that failed was:
1>C:\Program Files\dotnet\sdk\6.0.100-preview.1.21108.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018: MyComputer
1>C:\Program Files\dotnet\sdk\6.0.100-preview.1.21108.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.MachOUtils.RemoveSignature(String filePath)
1>C:\Program Files\dotnet\sdk\6.0.100-preview.1.21108.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.<>c__DisplayClass2_0.<CreateAppHost>g__RemoveSignatureIfMachO|2()
1>C:\Program Files\dotnet\sdk\6.0.100-preview.1.21108.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018:    at Microsoft.NET.HostModel.RetryUtil.RetryOnIOError(Action func)
1>C:\Program Files\dotnet\sdk\6.0.100-preview.1.21108.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.CreateAppHost(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String assemblyToCopyResorcesFrom)
1>C:\Program Files\dotnet\sdk\6.0.100-preview.1.21108.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018:    at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore()
1>C:\Program Files\dotnet\sdk\6.0.100-preview.1.21108.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
1>C:\Program Files\dotnet\sdk\6.0.100-preview.1.21108.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Program Files\dotnet\sdk\6.0.100-preview.1.21108.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1>C:\Program Files\dotnet\sdk\6.0.100-preview.1.21108.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018: 
1>C:\Program Files\dotnet\sdk\6.0.100-preview.1.21108.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(512,5): error MSB4018:
```

**Comment by AraHaan** [comment] 2021-02-12 17:29
6.0.100-preview.1.21107.2 works, however it broke after that version.

**Comment by AraHaan** [comment] 2021-02-13 19:57
cc: @dsplaisted

**Comment by dsplaisted** [comment] 2021-02-16 01:05
This looks like a dupe of #15225.  See that issue for details as well as a workaround.

**Closed by dsplaisted** 2021-02-16 01:05 UTC
Labels: needs team triage
