### ISSUE TITLE
IDE shows missing netstandard.dll while build succeeds

### ISSUE THREAD

**Issue by terrajobst** [dotnet/sdk#1403] opened 2017-07-11 21:51 UTC
I’m using the latest (public) version of VS with the latest .NET Core tooling. I’m consuming a .NET Standard 2.0 library from a .NET Framework 4.6.1 project. The project builds and runs just fine, but shows errors in the IDE:

![Errors in IDEs](https://user-images.githubusercontent.com/5169960/28092473-584c1fb8-6648-11e7-928e-5c3b78fa764f.jpg)

## Repro steps

1. Create a .NET Standard 2.0 class library
2. Change the code of `Class1` as follows:
    ```C#
    using System;

    public class Class1
    {
        public (string key, int value) GetData()
        {
            return ("Meaning of Life", 42);
        }
    }
    ```
3. Create a .NET Framework 4.6.1 console app
4. Add a reference to the class library you created earlier
4. Change the code of `Program` as follows:
    ```C#
    using System;

    class Program
    {
        static void Main(string[] args)
        {
            var c = new Class1();
            var data = c.GetData();
            Console.WriteLine(data);
        }
    }
    ```

## Expected Behavior

No squiggles and no items in the error list.

## Actual Behavior

The error list shows the following errors:

* CS0012: The type `ValueTuple<,>` is defined in an assembly that is not referenced. You must add a reference to assembly `netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51`.
* CS1503: Argument 1: cannot convert from `(string key, int value)` to `bool`

However, the project compiles & runs fine.

## Findings

From @davkean

> It’s very likely the compiler isn’t being given the netstandard.dll via the design-time build. No idea how this gets added to a .NET Framework 4.6.1 project – but whomever adds that dll should investigate. They can get the results of a design-time build: https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md#getting-visual-studio-to-output-the-results-of-a-design-time-build.

From @nguerrera 

> Please file a bug on dotnet/sdk as that’s where the component that adds the netstandard ref to netframework projects [now lives](https://github.com/dotnet/sdk/blob/release/2.0.0/src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.NETFramework.targets#L23-L25).

**Comment by nguerrera** [comment] 2017-07-11 21:56
@livarcocc

**Comment by dsplaisted** [comment] 2017-07-12 21:03
I’ve figured out what the problem is here.  The issue is that we detect whether any references depend on .NET Standard [using a task](https://github.com/dotnet/sdk/blob/cd6019ffadf8dd3173aef3525c642940e0485cc4/src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.NETFramework.targets#L38-L41) that looks at the metadata of the assembly to see if it has a reference to netstandard.dll.  However, in this scenario, the project has not been built yet, so there is no assembly on disk for the task to examine.

Building the solution and then closing and re-opening it makes the issue go away.

A similar issue existed with the System.Runtime facades, and was resolved by adding [metadata for the target platform](https://github.com/microsoft/msbuild/blob/5030bb3a21f2b0235a5bd0c99b4b0e09546a1013/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1835-L1836) to the item returned by the `GetTargetPath` target, which was then [consumed](https://github.com/Microsoft/msbuild/blob/5030bb3a21f2b0235a5bd0c99b4b0e09546a1013/src/Tasks/Microsoft.NETFramework.CurrentVersion.targets#L95) in the `ImplicitlyExpandDesignTimeFacades` target.

So I'd propose we fix this bug in a similar fashion:

- For projects targeting .NET Standard 1.5 or higher, add `DependsOnNETStandard` metadata to the `_ResolvedProjectReferencePaths` item returned by `GetTargetPath`
- In `Microsoft.NET.Build.Extensions.NETFramework.targets`, check for that metadata as an alternate way of determining whether the project depends on .NET Standard

@rainersigwald @AndyGerlicher Ideally we'd add the `DependsOnNETStandard` metadata in the .NET SDK.  The way the metadata is handled changed recently in https://github.com/Microsoft/msbuild/pull/2197.  Is there a safe way for the SDK to add a target which runs after `GetTargetPathWithTargetPlatformMoniker` but before `GetTargetPath` which could add additional metadata to the `TargetPathWithTargetPlatformMoniker` item?

**Comment by rainersigwald** [comment] 2017-07-12 21:17
The relevant parts of the target definitions you're talking about are:

```xml
<Target Name="GetTargetPathWithTargetPlatformMoniker"
        BeforeTargets="GetTargetPath" ... />

<Target Name="GetTargetPath" DependsOnTargets="$(GetTargetPathDependsOn)" ... />
```

I think it'd be fine to add

```xml
<Target Name="InjectNetStandardMetadata"
        BeforeTargets="GetTargetPath"
        DependsOnTargets="GetTargetPathWithTargetPlatformMoniker" />
```

There's no (understandable) ordering between targets that `BeforeTargets` the same target, but there are only two possible orders here:
1. The new target runs second, its DependsOn is satisified, it runs, and `GetTargetPath` runs.
2. The new target tries to run first, the engine sees that its DependsOn isn't satisified, pushes that onto the stack, resolves it, and continues.

**Comment by dsplaisted** [comment] 2017-07-12 21:23
@rainersigwald Thanks.  Do you think that's a stable enough extension point?  An alternative would be for the SDK to set a property and modify the MSBuild `GetTargetPathWithTargetPlatformMoniker` to also set an additional piece of metadata, like:

```xml
<DependsOnNETStandard>$(DependsOnNETStandard)</DependsOnNETStandard>
```

Do you have any preference between the two options?

**Comment by rainersigwald** [comment] 2017-07-12 21:36
I think it's a fairly stable extension point (but of course the evidence is against me since it changed in this release).

I slightly prefer this approach, especially at this point in the cycle.

Is the value for the metadatum known at project eval time, or is it only computed at build time? If it's known at eval time, you could use an ItemDefinitionGroup for `TargetPathWithTargetPlatformMoniker` in the SDK defining your metadatum.

**Comment by rainersigwald** [comment] 2017-07-12 21:37
Also, this is a duplicate of #1393, right @mhutch? This is basically the "invent a new platform" design we were thinking about.

**Comment by dsplaisted** [comment] 2017-07-12 21:41
It looks to me like #1393 is related to this, but different.

**Comment by mhutch** [comment] 2017-07-12 22:11
Yes, #1393 is a bit different, it's for pre-2.0 netstandards.

**Comment by livarcocc** [comment] 2017-07-19 20:50
This has been inserted into VS. Please, re-activate if this still reproes in the latest VS build.

**Closed by livarcocc** 2017-07-19 20:50 UTC
Labels: Impacts VS, Urgency-Soon

**Comment by terrajobst** [comment] 2017-07-24 21:03
No longer repros for me. Thanks!
