### ISSUE TITLE
.NET SDK 5.0.202 fails to compile netcoreapp3.1 projects

### ISSUE THREAD

**Issue by martincostello** [dotnet/sdk#16758] opened 2021-04-06 17:21 UTC
Using the .NET 5.0.202 SDK to compile a project targeting `netcoreapp3.1` fails with the following errors:

```
error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.win-x64 with version (= 3.1.14)
error NU1102: Unable to find package Microsoft.WindowsDesktop.App.Runtime.win-x64 with version (= 3.1.14)
error NU1102: Unable to find package Microsoft.AspNetCore.App.Runtime.win-x64 with version (= 3.1.14)
```

It looks like with .NET 5.0.5 being released a week earlier than usual, it has dependencies on the 3.1 release for next Tuesday that haven't been published to NuGet.org yet.

**Comment by martincostello** [comment] 2021-04-06 18:53
Possibly related, also having a different package restore issue on Windows builds in GitHub Actions where it fails without a `NuGet.config` file being present in the repo. See the following two PRs for examples.

  * https://github.com/justeat/JustSaying/pull/893 ([error](https://github.com/justeat/JustSaying/runs/2281054922#step:4:15))
  * https://github.com/justeat/JustEat.StatsD/pull/328 ([error](https://github.com/justeat/JustEat.StatsD/runs/2281003705#step:6:31))

**Comment by marcpopMSFT** [comment] 2021-04-06 20:18
@jamshedd @rbhanda

**Comment by rbhanda** [comment] 2021-04-06 21:21
Hello @martincostello , we have published 3.1.14 nugets. Please let us know if this issue is resolved after this.

**Comment by martincostello** [comment] 2021-04-06 21:43
Yep - compilation succeeds now. Thanks!

**Comment by marcpopMSFT** [comment] 2021-04-06 23:22
We'll close this in the morning if we hear no more reports.  Thanks for reaching out.

**Comment by Shane32** [comment] 2021-04-07 05:52
> Possibly related, also having a different package restore issue on Windows builds in GitHub Actions where it fails without a `NuGet.config` file being present in the repo. See the following two PRs for examples.
> 
> * [justeat/JustSaying#893](https://github.com/justeat/JustSaying/pull/893) ([error](https://github.com/justeat/JustSaying/runs/2281054922#step:4:15))
> * [justeat/JustEat.StatsD#328](https://github.com/justeat/JustEat.StatsD/pull/328) ([error](https://github.com/justeat/JustEat.StatsD/runs/2281003705#step:6:31))

I am still getting what appears to be the same nuget restore error message with GitHub Action workflows on Windows platforms.  Linux platforms (same code, same workflow, same everything) runs fine.

* https://github.com/graphql-dotnet/graphql-dotnet/runs/2284168775 ( https://github.com/graphql-dotnet/graphql-dotnet/pull/2427 )
* https://github.com/graphql-dotnet/parser/runs/2282962195 ( https://github.com/graphql-dotnet/parser/pull/126 )

Reverting to SDK 5.0.201 corrects the error and builds properly on both platforms; you can see in the latter PR that changing the SDK version was all that was required to make it build successfully.  You can also see that nuget package restore was completed successfully on Linux even though the run was canceled due to the failure on the Windows run.

**Comment by marcpopMSFT** [comment] 2021-04-15 17:48
GitHub Actions has confirmed that they've rolled out a fix to remove an empty Nuget.config file that was still causing issues for some customers (as NuGet also made a change to not automatically include NuGet.org when an empty NuGet.config file is found). We believe this should be resolved now thought they warn that any users for the choco package manager may still be broken because that manager also creates an empty Nuget.config.  Closing this issue.  Please reactivate if you still see issues.

**Closed by marcpopMSFT** 2021-04-15 17:48 UTC
Labels: Area-Install
