### ISSUE TITLE
interactive restore failing in latest net7 sdks

### ISSUE THREAD

**Issue by lewing** [dotnet/sdk#27597] opened 2022-08-31 16:17 UTC
### Describe the bug
`dotnet restore --interactive` fails to run the interactive tasks required to authenticate internal feeds
`msbuild /t:restore /p:nugetInteractive=true` does seem to work as a workaround

### To Reproduce

Add an internal feed to your nuget.config and try to get it to authenticate using `dotnet restore --interactive`

**Comment by lewing** [comment] 2022-08-31 16:18
cc @danroth27

**Comment by marcpopMSFT** [comment] 2022-09-07 23:50
@rokonec @AR-May @MichalPavlik this appears to be caused by msbuild server. I had it succeed once for me after trying a bunch of times and on a hunch, I disabled msbuild server (using DOTNET_CLI_DO_NOT_USE_MSBUILD_SERVER) and it started working. Once I turned msbuild server back on, it worked the first time but every time after that failed.

Note that --interactive just passes -property:NuGetInteractive=true through to msbuild. Is one of you available to take a look?  Thanks.

**Comment by marcpopMSFT** [comment] 2022-09-08 16:25
I was reproducing it with the following steps

1. Installing the 6.0.401 candidate build from the [artifacts tab](https://dev.azure.com/dnceng/internal/_build/results?buildId=1967044&view=results)
2. Running installcredprovider per [these instructions](https://microsoft.sharepoint.com/teams/netfx/CLR/ProjectK/_layouts/15/Doc.aspx?sourcedoc={10065841-2fa5-4c26-b91a-7d4b66b69a3c}&action=edit&wd=target%28net-core-validation.one%7C640f23bd-16f2-3442-a65f-b5eaf735912b%2FPrivate%20feeds%20for%20.NET%20Core%20and%20.NET%20releases%7C27551197-6789-470c-bc74-c35d8501897a%2F%29&wdorigin=703) 
3. Adding the private feed to a nuget config file (dotnet new nugetconfig, dotnet nuget add source https://pkgs.dev.azure.com/dnceng/internal/_packaging/6.0.401-servicing.22421.13-shipping/nuget/v3/index.json)
4. Then dotnet new console
5. Then dotnet build -r win-x64 --interactive

Step 5 without the nuget config file should give an error NU1102 not able to find 6.0.9 versions of various runtime packages.  Step 5 will give error NU1301 if --interactive is not working along with `C:\Program Files\dotnet\sdk\7.0.100-rc.1.22431.12\NuGet.targets(132,5): warning : The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`
, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet` [C:\Users\WDAGUtilityAccount\test\bug.csproj]`

Success will give you the following and an ask to log in the web browser.
`[NuGet Manager]     [CredentialProvider]DeviceFlow: https://pkgs.dev.azure.com/dnceng/internal/_packaging/6.0.401-servicing.22421.13-shipping/nuget/v3/index.json
[NuGet Manager]     [CredentialProvider]ATTENTION: User interaction required.`

**Comment by marcpopMSFT** [comment] 2022-09-09 22:18
@MichalPavlik were you able to reproduce the problem?

**Comment by MichalPavlik** [comment] 2022-09-12 11:54
Not yet. I see this output:

```
PS C:\TestProjects\NugetIssue> dotnet build -r win-x64 --interactive
MSBuild version 17.4.0-dev-22459-01+2db11c256 for .NET
  Determining projects to restore...
[NuGet Manager] [Warning] The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`
      [CredentialProvider]DeviceFlow: https://pkgs.dev.azure.com/dnceng/internal/_packaging/6.0.401-servicing.22421.13-shipping/nuget/v3/index.json
      [CredentialProvider]ATTENTION: User interaction required.

      **********************************************************************

      To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ... to authenticate.

      **********************************************************************```

Based on your description, this looks like successful path. I have few questions
 - Step 1 is there because 6.0.401 will be the first stable release with MSBuild Server? 
 - After the first successful build, nuget doesn't print the message about authentication anymore. Is there a cache I should clear?

**Comment by marcpopMSFT** [comment] 2022-09-12 16:15
Apologies, the bug I was reproing was in the .net 7 SDKs. I got confused in writing up the instructions as I was using a 6.0.401 feed for testing but with the net7 SDK (as it's a signed feed).

Let's try this rc1 build [here](https://dev.azure.com/dnceng/internal/_build/results?buildId=1981363&view=results) and this feed: https://pkgs.dev.azure.com/dnceng/internal/_packaging/7.0.100-rc.1.22429.3-shipping/nuget/v3/index.json

Note that the files from that feed should be released this week (pending final signoff).

**Comment by dsplaisted** [comment] 2022-09-21 21:21
Looks like this should be fixed in RC2

**Closed by dsplaisted** 2022-09-21 21:21 UTC
Labels: untriaged, Area-NetSDK

**Comment by rokonec** [comment] 2023-04-12 15:00
We have created workaround in MSBuild to not run server when interactive restore is ON.
If we need to enable performance of MSBuild server for such use cases we can do so after related NuGET bug is fixed:
https://github.com/NuGet/Home/issues/12540
