### ISSUE TITLE
Incorrect parsing of msbuild parameters

### ISSUE THREAD

**Issue by firerain-fd** [dotnet/sdk#27526] opened 2022-08-29 13:44 UTC
Since version 6.0.303 the utility does not correctly parse msbuild parameters when several parameters with a ; (semicolon) separator are specified in the -p parameter.

![image](https://user-images.githubusercontent.com/29374803/187215404-dd51e46d-6cb6-422b-93f0-61c119525380.png)
![image](https://user-images.githubusercontent.com/29374803/187215416-f4242d5d-f7ae-4f49-85b4-31e59292f5f5.png)

**Comment by baronfel** [comment] 2022-08-29 13:45
Thanks for reporting, this is a duplicate of https://aka.ms/dotnet/containers/customization and so I'll close it in favor of that one.

**Closed by baronfel** 2022-08-29 13:45 UTC
Labels: untriaged, Area-NetSDK

**Comment by firerain-fd** [comment] 2022-08-29 13:51
How is this related?

**Comment by baronfel** [comment] 2022-08-29 13:56
Apologies, I was smoking too fast and had the wrong link in my clipboard. Updated, hopefully that's more clear.

**Comment by firerain-fd** [comment] 2022-08-29 13:58
Ahh, okay )
