### ISSUE TITLE
SDK resolver does not work with snap installations of SDK on Linux

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#10403] opened 2019-08-01 15:09 UTC
See https://github.com/OmniSharp/omnisharp-vscode/issues/3160

When installed via snap:

```
sudo snap install dotnet-sdk --beta --classic
sudo snap alias dotnet-sdk.dotnet dotnet
```

Then `dotnet` on PATH resolves to a realpath of /usr/bin/snap and not to a dotnet executable next to the sdk foler.

This breaks an assumption of the resolver that we can use realpath on dotnet on PATH to find the SDK.

We could maybe implement something like the much slower option of shelling out to dotnet --info as msbuildlocator and legacy omnisharp do. Or we would need a way to resolve to the real directory somehow. I am not sure if snap gives us this ability. Is there a way to query snap to know if there is a dotnet-sdk installed and where can we find it's real directory. Can we do this without forking processes and parsing stdout?

The slow path could be a fallback. If there is a dotnet on PATH, but it does not resolve to a realpath with an sdk directory, try running it with --info. This would fix other hypothetical deployments like a dotnet that is a shell script that execs dotnet with custom args or whatever.  It may make sense to keep this as an ultimate fallback even if we find a more efficient way to handle the snap case.

**Comment by mattiaswerner** [comment] 2020-04-29 21:04
I was struggling with omnisharp not resolving the dotnet-sdk snap on 20.04 until I discovered that a simple

`ln -s /snap/dotnet-sdk/current/dotnet /usr/local/bin/dotnet`

did the trick. No need for msbuild path exports or an omnisharp json legacy resolver.

**Comment by programatta** [comment] 2020-04-30 09:28
> I was struggling with omnisharp not resolving the dotnet-sdk snap on 20.04 until I discovered that a simple
> 
> `ln -s /snap/dotnet-sdk/current/dotnet /usr/local/bin/dotnet`
> 
> did the trick. No need for msbuild path exports or an omnisharp json legacy resolver.

Thanks! It's works as a charm!

Only, I found other problem, for example, if you want execute your project from command line:
`
dotnet run <your.dll>
`
or 
`
dotnet run bin/Debug/netcoreapp3.1/<your.dll>
`
threw an exception.
I solved this problem here:
https://github.com/dotnet/core/issues/2186#issuecomment-472629489

p.d: My apologies, but my English is not very good.

**Comment by leolopez89** [comment] 2020-08-12 01:22
@jeffkhull I solve the problem only exporting the variable 
```bash
export MSBuildSDKsPath="/usr/share/dotnet/sdk/$(dotnet --version)/Sdks"```
Thanks a lot!!!

**Comment by gp200918** [comment] 2020-09-18 10:13
The problem is the snap alias. Do not install it.

Instead do this:
1)
sudo snap install dotnet-sdk --channel=5.0/beta –classic

DO NOT install the alias because it makes VSCode not find the SDK.
sudo snap alias dotnet-sdk.dotnet dotnet

2)
Start VSCode with a script file with this content:
export PATH=$PATH:/snap/dotnet-sdk/current/
/home/XXX/Downloads/VSCode/code-insiders

You have to adapt the second line, that starts VSCode insiders, to your case.

**Comment by noah1510** [comment] 2021-02-01 11:59
Would it be possible to look for the SDK in the DOTNET_ROOT environment variable?
DOTNET_ROOT is already an intended environment variable by the sdk when you try to directly run a binary produced by the dotnet sdk.
All the extention has to do is check if that variable exists and then look for the sdk in that path.

Adding the SDK to the path causes a lot of problems (at least the snap installation) but having it in a separate variable should be a good 'workaraound'.

**Comment by Krishnadas-KP** [comment] 2021-11-26 16:44
> I was struggling with omnisharp not resolving the dotnet-sdk snap on 20.04 until I discovered that a simple
> 
> `ln -s /snap/dotnet-sdk/current/dotnet /usr/local/bin/dotnet`
> 
> did the trick. No need for msbuild path exports or an omnisharp json legacy resolver.

Fantastic. This solved for me too. Thank you

**Comment by tazuddinleton** [comment] 2022-08-24 19:54
Getting following error when  running `dotnet run` :

```
relocation error: /usr/lib/libc.so.6: symbol _dl_fatal_printf version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
```

**Comment by wheelerlaw** [comment] 2022-09-09 15:15
> Getting following error when running `dotnet run` :
> 
> ```
> relocation error: /usr/lib/libc.so.6: symbol _dl_fatal_printf version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
> ```

Open a new issue. This doesn't seem at all related to the topic of this issue.

**Comment by alexcohn** [comment] 2023-02-22 10:37
Similar problem on arm64 Mac, with vscode Insiders. Running `dotnet --info` produces this:
````
.NET SDK (reflecting any global.json):
 Version:
 Commit:    N/A

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.1
 OS Platform: Darwin
 RID:
 Base Path:   /Users/alex/UnrealEngine/Engine/Binaries/ThirdParty/DotNet/6.0.302/mac-arm64/sdk/6.0.302/

global.json file:
  /Users/alex/UnrealEngine/global.json

Host:
  Version:      6.0.7
  Architecture: arm64
  Commit:       0ec02c8c96

.NET SDKs installed:
  6.0.302 [/Users/alex.cohn/github/UnrealEngine/Engine/Binaries/ThirdParty/DotNet/6.0.302/mac-arm64/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.7 [/Users/alex/UnrealEngine/Engine/Binaries/ThirdParty/DotNet/6.0.302/mac-arm64/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.7 [/Users/alex/UnrealEngine/Engine/Binaries/ThirdParty/DotNet/6.0.302/mac-arm64/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
  ````
My *dotnet* was installed by UnrealEngine. Is this an incompatible version? Why is `.NET SDK (reflecting any global.json)` empty? Should something special be addd to **global.json**?
````
{
  "sdk": {
    "version": "6.0.302"
  }
}
````

**Comment by Exagram** [comment] 2024-02-14 03:57
> `ln -s /snap/dotnet-sdk/current/dotnet /usr/local/bin/dotnet`

You are a genius!

I hope the MS wizards find a way to update their document here with your solution: https://github.com/dotnet/vscode-csharp/wiki/Troubleshooting:-'The-.NET-Core-SDK-cannot-be-located.'-errors#linux-snap-instructions

**Comment by nagilson** [comment] 2024-05-07 20:27
Snap installs are managed by canonical, so we created a new issue here https://github.com/canonical/dotnet-snap/issues/13 and also updated the documentation.

**Closed by nagilson** 2024-05-07 20:27 UTC
Labels: needs team triage, Area-SdkResolvers
