### ISSUE TITLE
VB.NET "My" not working as expected?

### ISSUE THREAD

**Issue by DualBrain** [dotnet/sdk#3387] opened 2019-05-30 19:40 UTC
@cston and @KathleenDollard,

Here is an isolated example running on the most recent bits as far as I can tell (at least with regards to the Microsoft.VisualBasic side of things).

Module Program
  Sub Main(args As String())
    Console.WriteLine(My.Computer.Name)
    Console.WriteLine((New Microsoft.VisualBasic.Devices.ServerComputer).Name)
    Console.WriteLine(System.Environment.MachineName)
  End Sub
End Module

The first line doesn’t work in .NET Core 3.0; however, the second and third lines do.  Playing with the same code in the full .NET Framework, all three lines work and when you jump to the reference for My.Computer.Name, it goes to Microsoft.VisualBasic.Devices.ServerComputer.Name.  I then jumped back over to the .NET Core source tree and that property simply returns System.Environment.MachineName.  One thing I find interesting about this is it’s not a 1:1 map… how does My.Computer.Name map to a property inside of an instantiated instance of Microsoft.VisualBasic.Devices.ServerComputer?  Some “magic” black-box stuff there?

So am I just missing something as far as how to "light up" the My side of things when working with a .NET Core 3.0 console project?  Or is there some additional work that still has to be done beyond the work that has taken place within the Microsoft.VisualBasic namespace?

(BTW, @cston great work thus far!)

Thanks.

Cory Smith

**Comment by cston** [comment] 2019-07-02 17:17
Related issue: https://github.com/dotnet/sdk/issues/3379

**Comment by nguerrera** [comment] 2019-07-10 20:01
Duplicate of https://github.com/dotnet/sdk/issues/2793

**Comment by nguerrera** [comment] 2019-07-11 02:02
Reopening for second half of this: `define:_MyType=\"Console\"`, the VB runtime part is tracked by #2793

**Comment by nguerrera** [comment] 2019-07-11 02:31
So the define comes from this in the classic .csproj template

```
<MyType>Console</MyType>
```

And Window Forms projects have MyType=WindowsForms, and then WPF has MyType=Custom with a generated MyWpfExtension.vb added to the project.


@KathleenDollard I'll need your help here. Do we want to change the templates to match the framework templates on this or are we expecting the SDKs to do some magic here? Not sure how to magically do the WPF one where there is a generated file added to the project, though. 

I think a default of MyType=Console in the SDK and then the WindowsDesktop SDK can override to MyType=WindowsForms for UseWindowsForms=true.

But how do we handle WPF. I see MyType=Windows as a possible value here, but not sure if that is sufficient for WPF?
https://github.com/dotnet/roslyn/blob/fab7134296816fc80019c60b0f5bef7400cf23ea/src/Compilers/VisualBasic/Portable/Symbols/EmbeddedSymbols/VbMyTemplateText.vb

Possibly this might be the best path forward:

1. Microsoft.NET.Sdk defaults to MyType=Console.
2. Close this issue and open a new one on Microsoft.NET.Sdk.WindowsDesktop to override defaults appropriately, work with Roslyn if any changes are needed there.

**Comment by nguerrera** [comment] 2019-07-11 02:35
Combining with the workaround for #2793  the following is enough to get the program in this issue to build and run:

``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <MyType>Console</MyType>
  </PropertyGroup>
  <Target Name="SetVBRuntimePath" AfterTargets="ResolveAssemblyReferences">
    <PropertyGroup>
      <VBRuntime Condition="'%(ReferencePath.FileName)' == 'Microsoft.VisualBasic'">%(ReferencePath.Identity)</VBRuntime>
    </PropertyGroup>
  </Target>
</Project>
```

**Comment by nguerrera** [comment] 2019-07-11 22:33
Discussed with @KathleenDollard and @cston. For the time being, we will assume that MyType remains unset by default and it is up to templates, project system, user to set it. So I will close this once the following works with the code in this isssue:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <MyType>Console</MyType>
</Project>
```

And file an issue for the templates to include MyType.

**Comment by nguerrera** [comment] 2019-07-11 22:50
Filed these issues for the templates:

* Console and Clas library: https://github.com/dotnet/templating/issues/2006
* WPF: https://github.com/dotnet/wpf/issues/1230
* Windows Forms: https://github.com/dotnet/winforms/issues/1346

**Comment by DualBrain** [comment] 2019-07-12 02:11
I'm assuming this still requires something else to be done; meaning that it's expected that this doesn't currently work in Preview6.  If I'm correct on this, would you be able to guess as to when it (which preview for example) that this might be available?

**Comment by nguerrera** [comment] 2019-07-12 15:17
I'm doing the equivalent of that target in the SDK "automagically". That will be in preview 8.  Only MyType will be needed in the project once that's in, and the issues above track adding MyType to various VB templates.

**Closed** 2019-07-16 20:43 UTC

**Comment by nguerrera** [comment] 2019-08-07 20:07
Unfortunately VB "My" will not work in 3.0 after all. Some types like "Computer" are being removed from corefx in order to be able to find an appropriate higher level where they can finish their implementation with dependencies that are higher than the base shared framework (winforms).

This means that we have to default MyType to Empty and the build will fail if you try to set it to something else. 

@KathleenDollard @cston Do we have a tracking issue for that elsewhere? I'd like to leave this closed as the work remaining would still be in the VB runtime library and project templates, and nothing remains in SDK.

**Comment by cston** [comment] 2019-08-14 14:45
@nguerrera, see https://github.com/dotnet/winforms/issues/1632.
