### ISSUE TITLE
`dotnet build` CLI issue with `-v:n -bl` in .NET 7 RC 1 builds

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/sdk#26965] opened 2022-08-03 15:11 UTC
### Describe the bug

Let me begin by saying this is weird. Not sure if it is a `dotnet` CLI issue or MSBuild.

This started happening here: https://github.com/xamarin/xamarin-android/pull/7217

I found if you do:

```bash
$ dotnet build -v:n -bl Xamarin.Android.sln -t:Restore || echo "Exit code: $?"
...
Determining projects to restore...
Exit code: 1
```

This seems to work fine if I remove the `-v:n` argument. Such as: https://github.com/xamarin/xamarin-android/pull/7217/commits/17bc8657d0bae5e488637aeda6cee312a53b7034

If I try .NET 7 Preview 6 (just tried latest public build):

```bash
Time Elapsed 00:00:02.31
```
The exit code isn't printed because it was a success (was 0).

### To Reproduce

Install .NET 7.0.100-rc.1.22402.10, and run `-t:Restore -bl -v:n` on a `.sln` file? I don't think there is anything special about our `.sln`. I also think it might happen for any target? Nothing special about `Restore`.

### Exceptions (if any)

None? `.binlog` does not have errors either?

### Further technical details

```
.NET SDK:
 Version:   7.0.100-rc.1.22402.10
 Commit:    3faa96e7bf

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.4
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /Users/jopepper/src/xamarin-android/bin/Debug/dotnet/sdk/7.0.100-rc.1.22402.10/

Host:
  Version:      7.0.0-rc.1.22381.5
  Architecture: arm64
  Commit:       508fef51e8

.NET SDKs installed:
  7.0.100-rc.1.22402.10 [/Users/jopepper/src/xamarin-android/bin/Debug/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0-rc.1.22401.10 [/Users/jopepper/src/xamarin-android/bin/Debug/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0-rc.1.22381.5 [/Users/jopepper/src/xamarin-android/bin/Debug/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]

Environment variables:
  Not set

global.json file:
  /Users/jopepper/src/xamarin-android/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by baronfel** [comment] 2022-08-03 15:29
I just quickly tried this on Windows with 7.0.100-rc.1.22043.4 (the latest available to me from the installer repo table links) and couldn't reproduce the exit code error on my system. Not saying that you're not seeing a real problem, just that I couldn't quickly repro it.

**Comment by jonathanpeppers** [comment] 2022-08-03 15:35
Ok, if I prepend my command with `DOTNET_CLI_DO_NOT_USE_MSBUILD_SERVER=true` it also seems to fix this.

**Comment by baronfel** [comment] 2022-08-03 15:36
@rokonec something for the team to check out

**Comment by rokonec** [comment] 2022-08-04 16:46
@jonathanpeppers That you for great bug report. Thanks to it we have found and fixed yet another elusive bug.
We plant to merge it into msbuild tomorrow day and it will flow into SDK soon.

**Comment by rokonec** [comment] 2022-08-05 12:04
We believe it has been just fixed by [related PR](https://github.com/dotnet/msbuild/pull/7860)

**Closed by rokonec** 2022-08-05 12:04 UTC
Labels: build, Area-CLI
