### ISSUE TITLE
PDB files are not copied from package lib folder to the consumer bin folder

### ISSUE THREAD

**Issue by wasker** [dotnet/sdk#1383] opened 2017-07-04 17:07 UTC
Sample code:
1. PackagedLibrary - library, which is packaged as NuGet, includes PDB file along with DLL; currently published as PackagedLibrary-1.0.0-beta.
2. LibraryConsumer - ASP.NET Core 1.1 project, consumes library from NuGet.

Repro:
1. Unzip, restore packages, rebuild all.
2. Open LibraryConsumer\bin\Debug\net452\win7-x86. Observe that there's only PackagedLibrary.dll, but not PackagedLibrary.pdb

Expectation: PDB is also copied to consumer project output.

In fact, if you create a new ASP.NET Web Application (.NET Framework) project and add same package there (`Install-Package -Id PackagedLibrary -Version 1.0.0-beta`), you'll see PDB being copied to output.

Why is this important? The project I'm working on is a complex web application with a lot of dependencies on internal libraries. All libraries are indexing their source code in PDB and packaging PDBs along with DLLs. If problem occurs and library user needs to debug, they can simply step into the library call. If PDBs are not automatically copied, it's impossible to do (unless you know about this issue and copy PDBs manually).

[PackagePdbAspNetCore.zip](https://github.com/dotnet/sdk/files/1122688/PackagePdbAspNetCore.zip)

**Comment by livarcocc** [comment] 2018-02-12 23:54
@nguerrera is this the issue you were referring to last week?

**Comment by nguerrera** [comment] 2018-02-13 00:11
Yes. Duplicate of https://github.com/dotnet/sdk/issues/1458 

We will be fixing this in 2.1.300.

**Closed by nguerrera** 2018-02-13 00:11 UTC

**Comment by guogangj** [comment] 2019-10-11 09:20
Unfortunately, this issue reappears in dotnet core 3.0.100, I described it there: [https://github.com/dotnet/core/issues/3587](dotnet core 3.0 doesn't copy symbol files(*.pdb) and xml document files from nuget package to bin/publish folder.)
