### ISSUE TITLE
The executable generated from `dotnet publish -r linux-x64` doesn't have "x" permission 

### ISSUE THREAD

**Issue by kichalla** [dotnet/sdk#1331] opened 2017-06-09 22:16 UTC
Related issues:
- https://github.com/NuGet/Home/issues/4424#issuecomment-307479450
- https://github.com/dotnet/cli/issues/6286

Repro steps:
- Install this CLI on a Linux VM(mine was Ubuntu 16.04 LTS): https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview2-006391/dotnet-sdk-2.0.0-preview2-006391-linux-x64.tar.gz
- mkdir testconsole
- cd testconsole
- Add a `NuGet.config` with the following content:
 ```xml
 <?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="DotNetCore" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```
- dotnet new console
- Open the testconsole.csproj file and add the property `<RuntimeIdentifier>linux-x64</RuntimeIdentifier>` and save the file
- dotnet restore
- dotnet publish -r linux-x64
- cd to the published directory
- Run `./testconsole`

**Expected:**
`Hello World!`

**Actual**:
bash: ./testconsole: Permission denied

cc @steveharter @gkhanna79

**Comment by gkhanna79** [comment] 2017-06-12 02:10
@kichalla This issue was present in Preview1 - do you know why it was not surfaced then and is surfacing only now? Is this because it was masked by the Nuget bug?

@livarcocc We should consider taking this for Preview2 SDK. What is the timeline for it?

**Comment by kichalla** [comment] 2017-06-12 11:52
> @kichalla This issue was present in Preview1 - do you know why it was not surfaced then and is surfacing only now? Is this because it was masked by the Nuget bug?

Yes, this issue was masked by the Nuget bug. Also I couldn't report this earlier because I was waiting for a CLI which [had ](https://github.com/NuGet/Home/issues/4424#issuecomment-301510977)this Nuget fix.

**Comment by steveharter** [comment] 2017-06-12 15:15
I can confirm the repro steps (Ubuntu 14)

The workarounds for now:
- Manually perform a `chmod +x testconsole`
or
- Run via `dotnet testconsole.dll` instead of testconsole directly

I'll start working on the fix.

**Comment by gkhanna79** [comment] 2017-06-12 15:17
> Run via dotnet testconsole.dll instead of testconsole directly

For standalone app, which is where this is a bug, this workaround is not correct. I think we should strive to get a fix in today so that we can have the potential to take in the SDK.

@livarcocc which branch should @steveharter prepare the fix in?

**Comment by gkhanna79** [comment] 2017-06-12 22:58
@steveharter Do you have an ETA on the PR?

**Comment by steveharter** [comment] 2017-06-12 23:54
Soon (EOD); verifying fix. Planning on targeting master branch first.

There are two approaches to the implementation: use File.Copy(apphost, testconsole) to copy the permissions from apphost to the testconsole and then replace the contents, or do a raw chmod +x on testconsole. I'm taking the File.Copy approach as a raw chmod will introduce calls into unix interop assemblies which is riskier.

**Comment by steveharter** [comment] 2017-06-13 03:39
See referenced PR; Tests are failing locally because the apphost being restored does not have the execute bit set. Need a newer version of NuGet?

Note: I must need permissions to the sdk repo as I can't modify any properties, including adding a reviewer.

**Comment by gkhanna79** [comment] 2017-06-13 03:42
@livarcocc @nguerrera Can you please help @steveharter with the issues above and also help answer the question around Nuget version as we should be taking this fix for Preview2.

CC @leecow as well.

**Comment by nguerrera** [comment] 2017-06-13 04:23
It's possible that NuGet version in master is too old. We haven't RIed in a while. PR should target 2.0 branch

**Comment by gkhanna79** [comment] 2017-06-13 21:14
Closing since the PR is now merged.

**Closed by gkhanna79** 2017-06-13 21:14 UTC
Labels: Bug

**Comment by sayhicoelho** [comment] 2018-12-14 16:41
> * Manually perform a `chmod +x testconsole`
@steveharter fixed my issue! thank you!
