### ISSUE TITLE
--runtime or --use-current-runtime  with --sc or --selfcontained gives warning warning NETSDK1179: One of '--self-contained' or '--no-self -contained' options are required when '--runtime' is used.

### ISSUE THREAD

**Issue by JeepNL** [dotnet/sdk#25300] opened 2022-05-07 09:27 UTC
.NET 7 prev. 3
Microsoft (R) Build Engine version 17.2.0-preview-22175-02+058a0262c for .NET

**UPDATE: maybe I should use `--no-self-contained` with these projects. I don't know.**

Building a project on Windows or L:inux with `--runtime <runtime identifier>` or `--use-current-runtime`  and with `--sc` or `--selfcontained` gives warning:

- warning `NETSDK1179: One of '--self-contained' or '--no-self -contained' options are required when '--runtime' is used.`

*Sample command line*
`dotnet build FluentUI.Demo.Shared.csproj --use-current-runtime --sc -o test`

*Full error:*
`C:\Program Files\dotnet\sdk\7.0.100-preview.3.22179.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(1113,5): warning NETSDK1179: One of '--self-contained' or '--no-self
-contained' options are required when '--runtime' is used. [C:\Users\jdkra\Downloads\fast-blazor-main\examples\FluentUI.Demo.Shared\FluentUI.Demo.Shared.csproj]`

Using `--no-selfcontained` works as it should.

**Comment by eduherminio** [comment] 2022-05-14 21:44
I've experienced this regression warning in 6.0.300 as well, both locally in Ubuntu and in GH Actions agents (see [this run](https://github.com/lynx-chess/Lynx/actions/runs/2325222305), for example).

I can confirm it was working properly for me in 6.0.100 (Ubuntu).

**Comment by baronfel** [comment] 2022-05-14 21:48
This will be fixed in the 6.0.301 release because of [this merged PR](https://github.com/dotnet/sdk/pull/25367).

**Comment by eduherminio** [comment] 2022-05-14 21:51
Thanks @baronfel 😃

**Comment by marcpopMSFT** [comment] 2022-05-20 22:45
Closing since the PR is merged.

**Closed by marcpopMSFT** 2022-05-20 22:45 UTC
Labels: Bug, untriaged, Area-CLI, needs-triage

**Comment by redwyre** [comment] 2022-09-15 16:40
I'm getting this issue in 6.0.400, but perhaps not in a situation that was expected: 
```
dotnet publish ".\Tools\Eco.BugReports\Server\Eco.BugReports.Server.csproj" --output $PublishDir --configuration $Config --self-contained true --runtime linux-x64 -fl1 -flp1:errorsonly
MSBuild version 17.3.0+92e077650 for .NET
...
C:\Program Files\dotnet\sdk\6.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(1114,5): error NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [D:\jenkins_agent\workspace\Eco Services\Eco Services BugReports PR\Tools\Eco.VersionStampGit\Eco.VersionStampGit.csproj]
```
You will notice that it's building a dependent project here which is an exe (a tool used as part of the build process), and it seems it doesn't get the flag (but I don't care because it's not used in the output)
