### ISSUE TITLE
System.TypeLoadException when running a simple specific code

### ISSUE THREAD

**Issue by coreuo** [dotnet/sdk#29819] opened 2023-01-08 13:28 UTC
### Describe the bug
After running a console application with the code below `System.TypeLoadException` is thrown without any additional info.

(InnerException is null)
### To Reproduce
```
var a = new A();

public struct A
{
    public B<A> B;
}

public struct B<T>
{
}
```

### Exceptions (if any)

`System.TypeLoadException: Could not load type 'A' from assembly 'Launcher, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.`

### Further technical details
- Include the output of `dotnet --info`
```
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
```
Microsoft Visual Studio Community 2022
Version 17.4.1
VisualStudio.17.Release/17.4.1+33110.190
```

**Comment by vitek-karas** [comment] 2023-01-09 17:14
Closing as duplicate of https://github.com/dotnet/runtime/issues/6924

**Closed by vitek-karas** 2023-01-09 17:14 UTC
Labels: untriaged
