### ISSUE TITLE
dotnet pack wrong path on DotNetCoreCLI@2 [Azure DevOps]

### ISSUE THREAD

**Issue by 0xAndre** [dotnet/sdk#27080] opened 2022-08-10 13:53 UTC
### Describe the bug
The buildProperties property on DotNetCoreCLI@2 task (Azure DevOps) is generating the wrong path to csproj, when the latest version of the sdk is used (6.0.400).

![image](https://user-images.githubusercontent.com/17546189/183917218-2b8e629b-2850-4c70-b458-242c384d4b6f.png)

There is no problem when using sdk version 6.0.302:

![image](https://user-images.githubusercontent.com/17546189/183918842-c93c89f2-443b-4c94-b768-5b47a58c7f48.png)

### To Reproduce
- Add DotNetCoreCLI@2 task and fill the buildProperties property.
- Self-hosted agent with UseDotNet@2 (6.0.*)

DotNetCoreCLI@2 version: 2.202.0

**Comment by baronfel** [comment] 2022-08-10 14:02
Duplicate of https://github.com/dotnet/sdk/issues/27059, please see that issue for workarounds.

**Closed by baronfel** 2022-08-10 14:02 UTC
Labels: untriaged, Area-CLI
