### ISSUE TITLE
Error when running Blazor app before running any other .NET Core 3.0 app: Unable to generate deps.json, it may have been already generated

### ISSUE THREAD

**Issue by danroth27** [dotnet/sdk#2948] opened 2019-02-15 18:45 UTC
If you create a Blazor app after installing the .NET Core 3.0 Preview 2 SDK and you have a clean NuGet package cache you get an error when running the app: "Unable to generate deps.json, it may have been already generated". 

Blazor apps rely on a `DotNetCliToolReference` to run, but they also target .NET Standard:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RunCommand>dotnet</RunCommand>
    <RunArguments>blazor serve</RunArguments> 
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="0.8.0-preview-19104-04" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="0.8.0-preview-19104-04" PrivateAssets="all" />

    <DotNetCliToolReference Include="Microsoft.AspNetCore.Blazor.Cli" Version="0.8.0-preview-19104-04" />
  </ItemGroup>

</Project>
```

It appears that the problem is that the Microsoft.NetCore.App package doesn't get restored, which then causes the Blazor app to fail at runtime. If you create any other .NET Core app before trying to run the Blazor app, the Microsoft.NetCore.App package is then already restored and the app runs fine. At the very least the error message doesn't really help you understand what is going on here.

Repro steps:
- Install .NET Core 3.0 Preview 2
- `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.8.0-preview-19104-04`
- `dotnet nuget locals all -c`
- `dotnet new blazor -o BlazorApp1`
- `cd BlazorApp1`
- `dotnet run`

Expected result:
- Blazor app runs successfully

Actual result:
- Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": C:\Program Files\dotnet\sdk\3.0.100-preview-010184\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj

To workaround the issue you can create any .NET Core app, which will result in the missing Microsoft.AspNetCore.App package to get successfully restored.

Workaround:
- `cd ..`
- `dotnet new console -o ConsoleApp1`
- `cd BlazorApp1`
- `dotnet run`

**Comment by danroth27** [comment] 2019-02-15 18:45
@SteveSandersonMS

**Comment by livarcocc** [comment] 2019-02-15 21:37
@dsplaisted can you take a look?

**Comment by jasonds** [comment] 2019-02-17 21:15
Thank you for posting this @danroth27. This workaround temporarily solves it.

**Comment by ottwell** [comment] 2019-02-18 10:28
genius! worked for me as well

**Comment by wbhyde** [comment] 2019-02-19 15:29
The workaround by @danroth27 worked for me (Thanks!).  I was running a new install of .Net Core 3.0, preview 3 that I downloaded just to try Blazor.  Looks like there needs to be a set of test cases to cover each type of project starting with a clean install each time.

**Comment by dsplaisted** [comment] 2019-02-21 19:16
I took a look at this yesterday with @wli3, and we think this will be fixed when the targeting packs are bundled in the .NET Core SDK.  This will be in Preview 3 for Windows.

**Comment by wli3** [comment] 2019-02-21 19:30
I just checked. It stops reproducing

**Comment by alierdogan70** [comment] 2019-02-26 22:45
This worked for me. Thank you.


> To workaround the issue you can create any .NET Core app, which will result in the missing Microsoft.AspNetCore.App package to get successfully restored.
> 
> Workaround:
> 
> * `cd ..`
> * `dotnet new console -o ConsoleApp1`
> * `cd BlazorApp1`
> * `dotnet run`

**Comment by arivoir** [comment] 2019-02-27 18:03
The workaround worked for me too. Thanks

**Comment by nguerrera** [comment] 2019-05-23 21:07
>> I took a look at this yesterday with @wli3, and we think this will be fixed when the targeting packs are bundled in the .NET Core SDK. This will be in Preview 3 for Windows.

> I just checked. It stops reproducing

Closing as fixed.

**Closed by nguerrera** 2019-05-23 21:07 UTC
